### PR TITLE
[offline-plugin] Add support for SW caching of prefetched resources

### LINKED ISSUE #6081: [v2] gatsby-plugin-offline non index roots don't load when offline
## Description

When I return to a page offline that I have previously loaded whilst online the page does not load and shows the browser standard no internet connection page. When I do this on the index page the page loads fine and I can navigate to the pages that don't work. All the pages that don't work are built from markdown dynamically as they are blog articles.

### Steps to reproduce

1. navigate to a blog article
2. take device offline
3. reload the page
4. notice standard no internet page

1. navigate to index page
2. take device offline
3. reload the page
4. notice the site loads fine

### Expected result

The site should load as if offline

### Actual result

The site failed to load

### Environment

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  Binaries:
    npm: 5.6.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: next => 2.0.0-beta.4
    gatsby-cli: next => 2.0.0-beta.2
    gatsby-image: next => 2.0.0-beta.2
    gatsby-plugin-canonical-urls: next => 2.0.0-beta.2
    gatsby-plugin-favicon: ^2.1.1 => 2.1.1
    gatsby-plugin-google-tagmanager: next => 2.0.0-beta.2
    gatsby-plugin-manifest: next => 2.0.2-beta.2
    gatsby-plugin-offline: next => 2.0.0-beta.2
    gatsby-plugin-react-helmet: next => 3.0.0-beta.2
    gatsby-plugin-sass: next => 2.0.0-beta.2
    gatsby-plugin-sharp: next => 2.0.0-beta.2
    gatsby-plugin-sitemap: next => 2.0.0-beta.2
    gatsby-plugin-typescript: next => 2.0.0-beta.2
    gatsby-remark-copy-linked-files: next => 2.0.0-beta.2
    gatsby-remark-images: next => 2.0.1-beta.3
    gatsby-remark-prismjs: next => 3.0.0-beta.2
    gatsby-source-filesystem: next => 2.0.1-beta.2
    gatsby-transformer-remark: next => 2.1.1-beta.2
    gatsby-transformer-sharp: next => 2.1.1-beta.2

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

### File contents (if changed)

`gatsby-config.js`: N/A 
```typescript
import * as path from "path";

interface GatsbyConfig {
  siteMetadata: {
    siteUrl: string;
    title: string;
  };
  plugins: Array<string | { resolve: string; options?: object }>;
}

const SITE_NAME = "James Adarich";
const SITE_URL = `https://${process.env.SITE_DOMAIN}`;

const GATSBY_CONFIG: GatsbyConfig = {
  siteMetadata: {
    siteUrl: SITE_URL,
    title: SITE_NAME
  },
  plugins: [
    // core templates
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-typescript",
    "gatsby-plugin-sass",
    "gatsby-transformer-sharp",
    "gatsby-plugin-sharp",
    "gatsby-plugin-offline",

    {
      resolve: "gatsby-plugin-favicon",
      options: {
        logo: "./src/images/favicon.png",
        injectHTML: true,
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          firefox: true,
          twitter: false,
          yandex: false,
          windows: false
        }
      }
    },

    {
      resolve: "gatsby-plugin-manifest",
      options: {
        name: SITE_NAME,
        short_name: SITE_NAME,
        start_url: "/",
        background_color: "#eee",
        theme_color: "#eee",
        display: "minimal-ui",
        icons: [
          {
            src: "/favicons/apple-touch-icon-72x72.png",
            sizes: "72x72",
            type: "image/png"
          },
          {
            src: "/favicons/apple-touch-icon-114x144.png",
            sizes: "144x144",
            type: "image/png"
          },
          {
            src: "/favicons/apple-touch-icon-180x180.png",
            sizes: "180x180",
            type: "image/png"
          }
        ]
      }
    },

    // markdown plugins
    {
      resolve: "gatsby-source-filesystem",
      options: {
        path: path.resolve("./src"),
        name: "markdown-pages"
      }
    },
    {
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: [
          "gatsby-plugin-sharp",
          "gatsby-remark-copy-linked-files",
          {
            resolve: "gatsby-remark-prismjs",
            options: {
              // Class prefix for <pre> tags containing syntax highlighting;
              // defaults to 'language-' (eg <pre class="language-js">).
              // If your site loads Prism into the browser at runtime,
              // (eg for use with libraries like react-live),
              // you may use this to prevent Prism from re-processing syntax.
              // This is an uncommon use-case though;
              // If you're unsure, it's best to use the default value.
              classPrefix: "line-numbers language-"
            }
          },
          {
            resolve: "gatsby-remark-images",
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 1000
            }
          }
        ]
      }
    },

    // SEO plugins
    {
      resolve: "gatsby-plugin-canonical-urls",
      options: {
        siteUrl: SITE_URL
      }
    },
    {
      resolve: "gatsby-plugin-sitemap",
      options: {
        query: `
        {
          site {
            siteMetadata {
              siteUrl
            }
          }
          allSitePage(
            filter: {
              path: {
                regex: "${/^(?!\/(dev-404-page|404|offline-plugin-app-shell-fallback|500)).*$/}"
              }
            }
          ) {
            edges {
              node {
                path
              }
            }
          }
        }`
      }
    }
  ]
};

if (process.env.GOOGLE_TAG_MANAGER_ID) {
  GATSBY_CONFIG.plugins.push({
    resolve: "gatsby-plugin-google-tagmanager",
    options: {
      id: process.env.GOOGLE_TAG_MANAGER_ID,
      includeInDevelopment: false
    }
  });
}

export = GATSBY_CONFIG;
```
`package.json`: N/A 
```json
{
  "license": "MIT",
  "scripts": {
    "build": "npm run build:server && npm run build:gatsby",
    "build:server": "tsc server/startup.ts --module commonjs --target esnext",
    "build:gatsby": "tsc gatsby-browser.ts gatsby-config.ts gatsby-node.ts gatsby-ssr.ts --module commonjs --target esnext && gatsby build",
    "develop": "npm run build && gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "lint": "npm run lint:sass && npm run lint:typescript",
    "lint:fix": "npm run lint:sass:fix && npm run lint:typescript:fix",
    "lint:sass": "sass-lint \"**/*.scss\" --ignore \"node_modules/**/*.*\"",
    "lint:sass:fix": "sass-lint \"**/*.scss\" --ignore \"node_modules/**/*.*\" --fix ",
    "lint:typescript": "tslint \"**/*.ts\" \"**/*.tsx\" --exclude \"node_modules/**/*.*\"",
    "lint:typescript:fix": "tslint --fix \"**/*.ts\" \"**/*.tsx\" --exclude \"node_modules/**/*.*\"",
    "start": "node ./server/startup.js",
    "test": "npm run lint"
  },
  "dependencies": {
    "express": "^4.16.2"
  },
  "devDependencies": {
    "@types/express": "^4.11.1",
    "@types/glob": "^5.0.35",
    "@types/node": "^8.10.10",
    "@types/prop-types": "^15.5.2",
    "@types/react-helmet": "^5.0.4",
    "core-js": "^2.5.7",
    "eslint": "^4.19.1",
    "gatsby": "next",
    "gatsby-cli": "next",
    "gatsby-image": "next",
    "gatsby-plugin-canonical-urls": "next",
    "gatsby-plugin-favicon": "^2.1.1",
    "gatsby-plugin-google-tagmanager": "next",
    "gatsby-plugin-manifest": "next",
    "gatsby-plugin-offline": "next",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-sass": "next",
    "gatsby-plugin-sharp": "next",
    "gatsby-plugin-sitemap": "next",
    "gatsby-plugin-typescript": "next",
    "gatsby-remark-copy-linked-files": "next",
    "gatsby-remark-images": "next",
    "gatsby-remark-prismjs": "next",
    "gatsby-source-filesystem": "next",
    "gatsby-transformer-remark": "next",
    "gatsby-transformer-sharp": "next",
    "glob": "^7.1.2",
    "graphql": "^0.13.2",
    "node-sass": "^4.9.0",
    "prettier": "^1.10.2",
    "prismjs": "^1.15.0",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-helmet": "^5.2.0",
    "sass-lint": "^1.12.1",
    "tslint": "^5.9.1",
    "tslint-plugin-prettier": "^1.3.0",
    "typescript": "^2.7.2",
    "webpack": "^4.12.0"
  }
}

```
`gatsby-node.js`: N/A 
```typescript
/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 */

// You can delete this file if you're not using it

// blog stuff
import * as path from "path";
import * as fs from "fs";
import * as zlib from "zlib";
import * as glob from "glob";

exports.createPages = ({ boundActionCreators, graphql }: any) => {
  const { createPage } = boundActionCreators;

  const blogPostTemplate = path.resolve(`src/components/blog-post.tsx`);

  return graphql(`
    {
      allMarkdownRemark(
        sort: { order: DESC, fields: [frontmatter___date] }
        limit: 1000
      ) {
        edges {
          node {
            frontmatter {
              path
            }
          }
        }
      }
    }
  `).then((result: any) => {
    if (result.errors) {
      return Promise.reject(result.errors);
    }

    result.data.allMarkdownRemark.edges.forEach(({ node }: any) => {
      createPage({
        path: node.frontmatter.path,
        component: blogPostTemplate,
        context: {} // additional data can be passed via context
      });
    });
  });
};

exports.onPostBuild = (pages: any) => {
  const publicPath = path.join(__dirname, "public");
  const gzippable = glob.sync(`${publicPath}/**/?(*.html|*.js|*.css)`);
  gzippable.forEach((file: any) => {
    const content = fs.readFileSync(file);
    const zipped = zlib.gzipSync(content);
    fs.writeFileSync(`${file}`, zipped);
  });
};
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### LINKED ISSUE #6378: Investigate capturing what pages are prefetched before the service worker loads and then ensuring those page resources are cached in SW
@kkemple's recent gatsby-plugin-offline PR dramatically improved its reliability on loading a site from a SW for the index page. One potential source of errors however is that when a user first visits a site, the sw doesn't load immediately. During that time, Gatsby will prefetch resources. If the user revisits the site offline and try to click on a link to a page that was prefetched before the sw loaded, the site will error because the page resources aren't in the sw cache.

One possible fix is that gatsby-plugin-offline includes a gatsby-browser.js that listens for prefetching of resources and records them and then once the sw loads, instructs it to fetch those items into its cache.

### LINKED ISSUE #6652: When adding resources to the service worker, don't cache rss/xml files
Noticed that the rss.xml file is being added on next.gatsbyjs.org which it shouldn't.

### PR DESCRIPTION
**Pull request by kkemple**
This PR includes:
- [x] a fix for non-cached preset assets
	- _Current strategy for catching prefetched assets is to record prefetches until SW is installed, then simply fetch them in the background so they are added to runtime cache by SW._
- [x] new API hooks for service worker events
- [ ] ~~migration to [`workbox`](https://developers.google.com/web/tools/workbox/)~~
	- [ ] ~~set custom cache names so plugins can tie in easily~~
- [x] document new APIs
- [x] update docs for onPrefetchPathname callback arguments
- [x] prevent caching of .xml files

Closes #6378
Closes #6081
Closes #6652

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 95fccb8b54db99cc0feb0b12bd2be90e56aa6862

https://app.netlify.com/sites/using-postcss-sass/deploys/5b50a9eab31274383c4ae63c

File: packages/gatsby-plugin-offline/src/gatsby-browser.js [hunk 1]
```diff
@@ -1 +1,10 @@
 exports.registerServiceWorker = () => true
+
+exports.onPrefetchPathname = pathData => {
+  if (`serviceWorker` in navigator) {
+    navigator.serviceWorker.controller.postMessage({
+      type: `prefetch`,
+      ...pathData,
```
Comment (kkemple) [inline packages/gatsby-plugin-offline/src/gatsby-browser.js]: what needs to be done to this data before we can pass on to SW?

File: packages/gatsby-plugin-offline/src/prefetch-catcher.js [hunk 2]
```diff
@@ -0,0 +1,6 @@
+self.addEventListener(`message`, async ({ data }) => {
+  if (data.type === `prefetch`) {
+    const cache = await caches.open(`runtimecache`)
```
Comment (kkemple) [inline packages/gatsby-plugin-offline/src/prefetch-catcher.js]: need to figure out the proper name of cache

File: packages/gatsby-plugin-offline/src/gatsby-browser.js (hunk 1 above)
Comment (kkemple) [reply packages/gatsby-plugin-offline/src/gatsby-browser.js]: docs look unclear on what is actually passed, an issue could be opened to fix as well, let me know if we want that!

https://next.gatsbyjs.org/docs/browser-apis/#onPrefetchPathname

File: packages/gatsby-plugin-offline/src/prefetch-catcher.js (hunk 2 above)
Comment (KyleAMathews) [reply packages/gatsby-plugin-offline/src/prefetch-catcher.js]: You can look in the Chrome "application" tab for the name of the cache. Also probably worth looking through the sw-precache docs to see if they talk about this use case of explicitly caching resources from the client.

File: packages/gatsby-plugin-offline/src/gatsby-browser.js (hunk 1 above)
Comment (KyleAMathews) [reply packages/gatsby-plugin-offline/src/gatsby-browser.js]: What needs cached is the code/data files for each path that's prefetched. I can't remember off-hand what is passed to `onPrefetchPathname`. If the actual URLs are passed, there's an internal API on `loader.js` I believe for getting those resource paths.

Importantly though we only need to record prefetching _until_ the SW is loaded as then it'll start caching itself. SW's have lifecycle events which we track here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/register-service-worker.js

What I think we should do is send those events out via `api-runner-browser` so that then plugins like this one could listen to them. Then you just have a boolean like `swNotLoaded` which defaults to false and while it's false, it queues up page resources and then once the sw loads, it stops listening to prefetching (as the SW is now) and sends all the page resources to the SW to cache them there.

Comment (KyleAMathews) [reply packages/gatsby-plugin-offline/src/gatsby-browser.js]: >docs look unclear on what is actually passed, an issue could be opened to fix as well, let me know if we want that!

That'd be great too!

File: packages/gatsby-plugin-offline/src/prefetch-catcher.js (hunk 2 above)
Comment (kkemple) [reply packages/gatsby-plugin-offline/src/prefetch-catcher.js]: i checked and couldn't find anything, workbox docs have it and wonder if it's the same, at worst case i can dig through source code or look at application tag

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 4fe78a02c48b279d1af7124cf68e715c05cbaa3e

https://app.netlify.com/sites/gatsbyjs/deploys/5b57704267610c461f99845b

File: packages/gatsby-plugin-offline/src/gatsby-browser.js [hunk 3]
```diff
@@ -1 +1,40 @@
 exports.registerServiceWorker = () => true
+
+let swNotInstalled = true
+const pathnameResources = []
+
+exports.onPrefetchPathname = ({ pathname, getResourcesForPathname }) => {
```
Comment (KyleAMathews) [inline packages/gatsby-plugin-offline/src/gatsby-browser.js]: This could use a comment to explain that here we record resources that are prefetched before the sw has been installed and can cache things directly.

File: packages/gatsby-plugin-offline/src/gatsby-browser.js [hunk 4]
```diff
@@ -1 +1,40 @@
...
+exports.onServiceWorkerInstalled = () => {
+  swNotInstalled = false
+
+  // grab nodes from head of document
+  const nodes = document.querySelectorAll(
+    `head > script[src], head > link[as=script]`
+  )
+
+  // get all script URLs
+  const scripts = [].slice
```
Comment (KyleAMathews) [inline packages/gatsby-plugin-offline/src/gatsby-browser.js]: ol' skool dom hacking

File: packages/gatsby/cache-dir/register-service-worker.js [hunk 5]
```diff
@@ -1,10 +1,11 @@
-import emitter from "./emitter"
+import { apiRunner } from "./api-runner-browser"
 
 if (`serviceWorker` in navigator) {
   navigator.serviceWorker
     .register(`${__PATH_PREFIX__}/sw.js`)
     .then(function(reg) {
       reg.addEventListener(`updatefound`, () => {
+        apiRunner(`onServiceWorkerUpdateFound`)
```
Comment (KyleAMathews) [inline packages/gatsby/cache-dir/register-service-worker.js]: let's pass in `reg` as an option (though maybe call it just `serviceWorker` to all the API calls in case plugins want access to it.

File: packages/gatsby-plugin-offline/src/gatsby-browser.js (hunk 4 above)
Comment (kkemple) [reply packages/gatsby-plugin-offline/src/gatsby-browser.js]: 😎
