### PR TITLE
chore: Upgrade minimatch to fix RegEx DoS security issue

### LINKED ISSUE #10282: [Security] Upgrade minimatch to fix RegEx DoS security issue
See #10198 for context.

## Description

One of the dependencies of the `gatsby-remark-code-repls` package relies on an outdated version of `minimatch` that allows for a Regular Expression Denial of Service (see [npm report](https://nodesecurity.io/advisories/118) on the matter)

### Steps to reproduce

Run `yarn audit` and see the high severity security issue.

### PR DESCRIPTION
**Pull request by phacks**
Fixes #10282

TODO:

- [x] Switch to `recursive-readdir` library
- [x] Implement async readdir behavior
- [x] Fix existing tests
- [x] Test error handling
- [x] Test on a `gatsby-starter-blog` with few examples of REPLs
- [x] Try and implement the `Promise.all` refactor

### CODE REVIEW

**Comment by DSchau** [comment]
@phacks applied the `do not merge` and `WIP` labels while you're still working on this and validating.

Please remove when it's ready for another set of 👀!

**Comment by phacks** [comment]
@DSchau Should be ready for a review!

I created a sample repo with lots of code REPLs to test it out, it’s available here: https://github.com/phacks/gatsby-code-repl-samples

I managed to implement the `Promise.all()` refactor, although in my benchmark (~10 000 code REPLs), I found virtually no differences in the `createPages` duration. I’m not sure whether that’s normal or not 🤔

**Comment by phacks** [comment]
I forgot to mention that for some (as yet unknown) reason, the `/redirect-to-codepen` links do not work in my example repo. However, they do not work with the current `gatsby-remark-code-repls` plugin, so I don’t think my PR has something to do with that. I may take some time to investigate the issue after this PR!

File: packages/gatsby-remark-code-repls/src/gatsby-node.js [hunk 1]
```diff
@@ -36,45 +36,48 @@ exports.createPages = (
...
+      return
+    }
 
-  files.forEach(file => {
-    if (extname(file) === `.js` || extname(file) === `.jsx`) {
-      const slug = file
-        .substring(0, file.length - extname(file).length)
-        .replace(new RegExp(`^${directory}`), `redirect-to-codepen/`)
-      const code = fs.readFileSync(file, `utf8`)
+    Promise.all(
```
Comment (DSchau) [inline packages/gatsby-remark-code-repls/src/gatsby-node.js]: This is still synchronous right? Why the change?

**Comment by LekoArts** [comment]
@phacks Hi. Do you have time to answer @DSchau question? :)

**Comment by phacks** [comment]
@LekoArts @DSchau Oops! This one went under my radar. I will have a look at it by this weekend (probably today though), thanks!

File: packages/gatsby-remark-code-repls/src/gatsby-node.js (hunk 1 above)
Comment (phacks) [reply packages/gatsby-remark-code-repls/src/gatsby-node.js]: @DSchau it was an attempt at this refactoring:

https://github.com/gatsbyjs/gatsby/blob/9bd0a276d4de922541651d7111b55be7d52f5e4d/packages/gatsby-remark-code-repls/src/gatsby-node.js#L39-L42

However, as you pointed at it’s still synchronous, because `recursive-readdir` returns all the files at once, instead of one by one. Updated the PR to drop the refactoring part, what do you think?

File: packages/gatsby-remark-code-repls/src/gatsby-node.js [hunk 2]
```diff
@@ -36,45 +36,46 @@ exports.createPages = (
     )
   }
 
-  // TODO We could refactor this to use 'recursive-readdir' instead,
-  // And wrap with Promise.all() to execute createPage() in parallel.
-  // I'd need to find a way to reliably test error handling though.
-  const files = recursiveReaddir(directory)
+  try {
```
Comment (wardpeet) [inline packages/gatsby-remark-code-repls/src/gatsby-node.js]: just wondering why do a try catch if you're going to rethrow anyway?

Comment (phacks) [reply packages/gatsby-remark-code-repls/src/gatsby-node.js]: That’s true, thanks. I’m wondering what is better between omitting the `try / catch` altogether or adding a simple `console.error` in the `catch` with a (hopefully) helpful error message, e.g. 

> Error in gatsby-remark-code-repls plugin: cannot read directory ${directory}

What do you think @wardpeet

Comment (wardpeet) [reply packages/gatsby-remark-code-repls/src/gatsby-node.js]: I missed this one 🤦‍♂️ reporter.panic is probably a great way! Especially if you can give a good error message like.

> Oh this went wrong, please check ...

Comment (phacks) [reply packages/gatsby-remark-code-repls/src/gatsby-node.js]: @wardpeet Didn’t know about `reporter.panic`, neat! I updated the PR to use it and enhance the error handling. Thanks!

File: packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js [hunk 3]
```diff
@@ -53,80 +58,95 @@ describe(`gatsby-remark-code-repls`, () => {
...
 
-    it(`should error if provided an invalid examples directory`, () => {
+    it(`should error if provided an invalid examples directory`, async () => {
       fs.existsSync.mockReturnValue(false)
 
-      expect(() => createPages(createPagesParams)).toThrow(
-        `Invalid REPL directory specified: "REPL/"`
-      )
+      try {
+        await createPages(createPagesParams)
```
Comment (wardpeet) [inline packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js]:
```suggestion
        expect(() => createPages(createPagesParams)).toThrow()
```
https://jestjs.io/docs/en/expect#tothrowerror

File: packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js [hunk 4]
```diff
@@ -53,80 +58,95 @@ describe(`gatsby-remark-code-repls`, () => {
...
 
-    it(`should error if an invalid redirect template is specified`, () => {
+    it(`should error if an invalid redirect template is specified`, async () => {
       fs.existsSync.mockImplementation(path => path !== `foo/bar.js`)
 
-      expect(() =>
-        createPages(createPagesParams, { redirectTemplate: `foo/bar.js` })
-      ).toThrow(`Invalid REPL redirectTemplate specified`)
+      try {
+        await createPages(createPagesParams, { redirectTemplate: `foo/bar.js` })
```
Comment (wardpeet) [inline packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js]: use expect toThrow from jest like mentioned above

File: packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js [hunk 5]
```diff
@@ -53,80 +58,95 @@ describe(`gatsby-remark-code-repls`, () => {
...
+      }
+    })
+
+    it(`should propagate any Error from recursive-readdir`, async () => {
+      const error = TypeError(`glob pattern string required`)
+
+      readdir.mockRejectedValue(error)
+
+      try {
+        await createPages(createPagesParams)
```
Comment (wardpeet) [inline packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js]: use expect toThrow from jest like mentioned above

**Comment by wardpeet** [comment]
@phacks almost there! sorry about this!

**Comment by phacks** [comment]
@wardpeet No worries! It looks like the syntax you suggested isn’t available for `async` functions — I suggested a few alternatives (including mine) in the first comment.

**Comment by phacks** [comment]
@wardpeet Hi! Do you think you may have some time to have a (hopefully) last look at this PR? Thanks!

File: packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js (hunk 3 above)
Comment (wardpeet) [reply packages/gatsby-remark-code-repls/src/__tests__/gatsby-node.js]: yours is great! 👍
