### PR TITLE
fix(gatsby): leak less in chokidar listeners

### LINKED ISSUE #25868: Gatsby develop refresh endpoint memory leak
## Description

Each time the refresh endpoint is hit, memory increases a little bit and it doesn't go down, eventually leading to a heap out of memory after multiple refreshes.

develop process memory previous to a refresh:
image

develop process memory after a refresh:
image

and hitting more times refresh it just goes higher.

adding **--max_old_space_size** to a high value just delays the out of memory.

### Steps to reproduce

gatsby develop
hit refresh endpoint
wait until refresh finishes
hit refresh endpoint
...

### Expected result

Memory should not increase without getting back to normal over time.

### Actual result

Eventually there is a memory leak

### Environment

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
  Binaries:
    Yarn: 1.21.0 - C:\Users\apa\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3 - /c/Python38/python
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: 2.24.2 => 2.24.2 
    gatsby-graphiql-explorer: ^0.2.31 => 0.2.31 
    gatsby-plugin-react-decorators: 0.0.4 => 0.0.4 
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18 
    gatsby-plugin-sass: ^2.1.26 => 2.1.26 
    gatsby-plugin-sharp: ^2.3.9 => 2.3.9 
    gatsby-plugin-typescript: ^2.1.23 => 2.1.23 
    gatsby-source-contentful: ^2.3.15 => 2.3.15 
    gatsby-source-filesystem: ^2.1.42 => 2.1.42 
    gatsby-transformer-json: ^2.2.22 => 2.2.22 
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9

### PR DESCRIPTION
**Pull request by vladar**
## Description

This PR addresses one of our memory leaks in `develop` with refresh endpoint (in this case in internal plugin `internal-data-bridge`).

Refresh endpoint always re-runs `sourceNodes` and we keep re-creating chokidar listeners that retain current redux state at the moment of the `sourceNodes` call. So we basically retain as many state "snapshots" as there were `sourceNode` API calls (i.e. refreshes).

To confirm I've run the https://github.com/reactjs/reactjs.org website with a 200MB node memory limit and kept hitting the `__refresh` endpoint. Before this PR it was OOMing on the 14-16th refresh, after this PR somewhere after 30th (so other memory leaks in play)

To clarify: this is not the only leak 😢 We have others. It is possible that chokidar listeners in `gatsby-source-filesystem` are also leaking. But this warrants a separate investigation.

Also, originally we were hoping that sourceNodesStatefully (#19663) would be a proper fix for those kinds of leaks but it has it's own issues and breaking changes, so need to fix those individually.

## Related Issues
Partially addresses #25868

### CODE REVIEW

File: packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js [hunk 1]
```diff
@@ -87,8 +85,8 @@ exports.sourceNodes = ({ createContentDigest, actions, store }) => {
       siteMetadata: {
         ...configCopy.siteMetadata,
       },
-      port: state.program.proxyPort,
-      host: state.program.host,
```
Comment (vladar) [inline packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js:91]: Here we retain the state

Comment (pieh) [reply packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js:91]: Yup, we could call `store.getState()` here, but because `program` can't change this is fine (`program` does get retained in memory either way)

**Review by pieh — APPROVED** [review]
LGTM, let's ship it!

**Comment by vladar** [comment]
Published in `gatsby@2.24.89`
