### PR TITLE
fix(gatsby-cli): don't fail when using `--log-pages` and/or `--write-to-file`

### LINKED ISSUE #23941: There is no flag --log-pages in my gatsby build command
## Summary

at https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/#reporting-what-has-been-built it is writting I can use a `--log-pages` flag. But my cli says that flag does not exist. I tried different recent versions of gatsby.

### PR DESCRIPTION
**Pull request by albertlincoln**
## Description

Resolves #23941 there is no log-pages cli arg option

### Documentation

https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/

## Related Issues

#23941

### CODE REVIEW

File: packages/gatsby-cli/src/create-cli.js [hunk 1]
```diff
@@ -182,6 +182,16 @@ function buildLocalCommands(cli, isLocalSite) {
...
+        .option(`log-pages`, {
+          type: `boolean`,
+          default: false,
+          describe: `Log the pages that changes since last build (for optimization).`,
+        })
+        .option(`write-to-file`, {
+          type: `boolean`,
+          default: false,
+          describe: `Save the log of changed pages for future comparison (for optimization).`,
+        })
```
Comment (pieh) [inline packages/gatsby-cli/src/create-cli.js:194]: Those switches should be available only when `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES` is used or description should mention that. Those don't do anything in default builds

Comment (pieh) [reply packages/gatsby-cli/src/create-cli.js:194]: Let's just use `hidden: true` on them for hot fix - this should ensure same behaviour as before they broke with `yargs` upgrade. We can later discuss if this is or isn't best idea

**Comment by pieh** [comment]
Published `gatsby-cli@2.12.16` / `gatsby@2.21.22`. Once again - thanks for the fix!
