### PR TITLE
Compat fix for gatsby-cli v2 with gatsby v1

### LINKED ISSUE #8575: Unknown browser query `dead` - WTF
I have a project using a Gatsby theme starter and last week I was building my project with no problems what so ever, this morning I tried to run a new build without having done any prior changes at all I get some intimidating error. I need to fix this this project is due to go live soon..

**Error Generating CSS failed
BrowserslistError: Unknown browser query `dead`**

FYI - Also getting this on some NEW starter Gatsby repos.

gatsby@2.4.1
node@10.11.0
npm@6.4.1

OS - Ubuntu 16.04.5 LTS

### PR DESCRIPTION
**Pull request by m-allanson**
Gatsby v1 includes postcss-next which uses an older version of browserslist. This means the default browserslist query `["> 0.25%", "not dead"]` won't work in Gatsby v1. This causes an error when you have `gatsby-cli` v2 installed and you're working on a Gatsby v1 site.

Fixes #8575 
Refs #8560

### CODE REVIEW

File: packages/gatsby-cli/src/create-cli.js [hunk 1]
```diff
@@ -26,6 +31,21 @@ function buildLocalCommands(cli, isLocalSite) {
     siteInfo.browserslist = json.browserslist || siteInfo.browserslist
   }
 
+  function installedGatsbyVersion() {
+    let majorVersion
+    try {
+      let packagePath = require.resolve(
+        path.join(process.cwd(), `node_modules`, `gatsby`, `package.json`)
```
Comment (m-allanson) [inline packages/gatsby-cli/src/create-cli.js]: Not sure how reliable this is...

File: packages/gatsby-cli/src/create-cli.js [hunk 2]
```diff
@@ -18,6 +17,12 @@ function buildLocalCommands(cli, isLocalSite) {
   const defaultHost = `localhost`
   const directory = path.resolve(`.`)
 
+  // 'not dead' query not available in browserslist used in Gatsby v1
+  const DEFAULT_BROWSERS =
+    installedGatsbyVersion() === 1
+      ? [`> 1%`, `last 2 versions`, `IE >= 9`]
+      : [`>0.25%`, `not dead`]
```
Comment (m-allanson) [inline packages/gatsby-cli/src/create-cli.js]: This defaults to the v2 query unless we definitely know this is a v1 site.

File: packages/gatsby-cli/src/create-cli.js [hunk 3]
```diff
@@ -26,6 +31,21 @@ function buildLocalCommands(cli, isLocalSite) {
     siteInfo.browserslist = json.browserslist || siteInfo.browserslist
   }
 
+  function installedGatsbyVersion() {
+    let majorVersion
+    try {
+      let packagePath = require.resolve(
+        path.join(process.cwd(), `node_modules`, `gatsby`, `package.json`)
+      )
+      const packageInfo = JSON.parse(fs.readFileSync(packagePath))
```
Comment (pieh) [inline packages/gatsby-cli/src/create-cli.js]: You can do ``require(`gatsby/package.json`)`` like in here I think:
https://github.com/gatsbyjs/gatsby/blob/bc1a79de577ac9f2c77eaac3bcaa4a8368e3ad35/packages/gatsby/cache-dir/static-entry.js#L11

Comment (m-allanson) [reply packages/gatsby-cli/src/create-cli.js]: Oh yeah, straight up require. Thanks 😅 

I _think_ this still needs to use `process.cwd()` to provide an absolute path - otherwise the require doesn't resolve the local `node_modules` directory from a globally installed `gatsby-cli`. Maybe there's a neater way?
