### PR TITLE
Use a WeakMap to store parent of subobjects in nodes

### LINKED ISSUE #2772: CSS additionalProperties issue
Hi there!
Recently I started to get error running gatsby develop.
```
info bootstrap finished - 4.564 s

[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  Error: Module build failed: Error: /Users/vitaliizhukov/work/sh-site/website/.cache/develop-stati  c-entry.js: Invalid configuration
  
  - index.js:204 PluginPass.Program
    [website]/[babel-plugin-react-css-modules]/dist/index.js:204:17 
```
Running 'gatsby build' leads to next error:
```
info bootstrap finished - 4.339 s

⡀ Building CSS[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]
success Building CSS — 1.661 s
⠄ Building production JavaScript bundles[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]
success Building production JavaScript bundles — 0.344 s
⠁ [ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]

error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module build failed: Error: /Users/vitaliizhukov/work/sh-site/website/.cache/static-entry.  js: Invalid configuration
  
  - index.js:204 PluginPass.Program
    [website]/[babel-plugin-react-css-modules]/dist/index.js:204:17
```

I found out that last gatsby version that builds website successfully is 1.9.81. (But for that version I had another issue with multiple graphql entries)
What do I miss here?
Thanks.

### PR DESCRIPTION
**Pull request by pieh**
this prevents mutating plugin data that is deeper in object properites
fixes #2772

For context check #2772 and my comment there

### CODE REVIEW

**Comment by jquense** [comment]
thanks for the PR! I think the better option to fix this is probably to have createNode not mutate the input in the first place...or whereever the mutation is happening. We don't necessarily want to work around that behavior when it probably isn't intentional in the first place

**Comment by pieh** [comment]
Updated PR with suggested change.

Previous version of "fix" just in case for reference - https://github.com/pieh/gatsby/commit/f4e52bda36ca054858407fb2eecdb2736931168e

File: packages/gatsby/src/redux/actions.js [hunk 1]
```diff
@@ -366,6 +366,11 @@ actions.createNode = (node: any, plugin?: Plugin, traceId?: string) => {
     )
   }
 
+  // Make deep copy of node before mutating it, this makes sure original object
+  // will not fail validation due to unexpected fields.
+  // (reference: https://github.com/gatsbyjs/gatsby/issues/2772 )
+  node = _.cloneDeep(node)
```
Comment (jquense) [inline packages/gatsby/src/redux/actions.js]: Sorry! this isn't what I meant. I'd like to avoid a deep clone entirely because it can very expensive, and we have no idea what content or structure nodes will have. Instead I'd like to find the places where mutation is happening and remove them, rather then make mutation safe.

Comment (pieh) [reply packages/gatsby/src/redux/actions.js]: oh, right, I had brain lag or something - now i read your comment again and think to myself how did I understand it the way I did before ...

So if gatsby shouldn't mutate then you would have revert this - https://github.com/gatsbyjs/gatsby/commit/656299d2244ecbda35458cc262aea1cf146fca78

Comment (KyleAMathews) [reply packages/gatsby/src/redux/actions.js]: Hmmmm yeah we could move that code into a library that then is used in source/transformer plugins that need it.

Comment (jquense) [reply packages/gatsby/src/redux/actions.js]: yeah this is a bit tough, since we sort of need to hope consumers play nice and don't mutate...the problem tho is that enforcing generally it is pretty costly especially here where nodes may be/are complex data structures.

Comment (pieh) [reply packages/gatsby/src/redux/actions.js]: Could you elaborate a little what problem https://github.com/gatsbyjs/gatsby/commit/656299d2244ecbda35458cc262aea1cf146fca78 fixed? Is it needed in all nodes or is just for source/transformers plugins? Maybe I could just change createNode and add argument to opt-out of adding `_PARENT` fields and just opt-out of it for plugin data? This would avoid any cloning at all (obviously prefered solution).

Comment (KyleAMathews) [reply packages/gatsby/src/redux/actions.js]: See this comment https://github.com/gatsbyjs/gatsby/issues/2567#issuecomment-340068410 It's basically a workaround for GraphQL as it doesn't let you know what the parent of a sub-object is which breaks Gatsby in subtle ways.

Avoiding mutating plugins would be a great start. So yeah, question is should we opt-in to adding _PARENT or opt-out.

I think it's a generally useful/needed pattern which is why I added it to actions.js so I'm leaning towards opt-out. Thoughts?

Comment (jquense) [reply packages/gatsby/src/redux/actions.js]: maybe instead of tagging each sub object we could use a WeakMap hashing objects to parent id? e.g. something like:

```
map = new WeakMap()

eachChildObject(node, obj => { 
  map.set(obj, node.id)
})
```

then expose a getParent api perhaps?

Comment (KyleAMathews) [reply packages/gatsby/src/redux/actions.js]: Ooo that's good! Yeah, that sounds much nicer. @pieh you have time to work on this by chance? I'm pretty strapped for time over next few days / week.

**Comment by pieh** [comment]
updated PR

tested against repository linked in https://github.com/gatsbyjs/gatsby/issues/2567#issuecomment-339885576 to check if "parent fix" still works

**Comment by KyleAMathews** [comment]
🙇  this is awesome!

**Comment by jlengstorf** [comment]
Hiya @pieh! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs
