### PR TITLE
feat(gatsby-remark-images): support markdownCaptions in mdx + fix for remark

### LINKED ISSUE #14474: [gatsby-remark-images] When using `showCaption`, parse the caption as markdown
## Summary

When using `showCaptions: true` as an option for the `gatsby-remark-images`, it inserts the title of the image as raw html.
How about considering the caption as markdown and parsing it before inserting it?

### Motivation

https://github.com/mathieudutour/medium-to-own-blog/issues/5

Happy to work on it if that's something that you find interesting

### LINKED ISSUE #20000: gatsby-remark-images error if using markdownCaptions: true
## Description

There seems to have been a regression and an error similar to the one reported in #16703 and fixed in #19288 is effected if `markdownCaptions: true` is specified in the `gatsby-remark-images` configuration within `gatsby-config.js`

The error is the same, but the reported call stack is a little different.

### Steps to reproduce

1. Create a new Gatsby site using `gatsby-starter-blog`:

        gatsby new markdown-caption-repro https://github.com/gatsbyjs/gatsby-starter-blog

2. Run `yarn upgrade`
3. Specify `markdownCaptions` in the `gatsby-remark-images` block

        resolve: `gatsby-remark-images`,
        options: {
          markdownCaptions: true,
          maxWidth: 590,
          showCaptions: true,
        },

4. Run `yarn develop`

### Expected result

The page content should be generated and the development site should be available.

### Actual result

```
 ERROR

UNHANDLED REJECTION Cannot read property 'contentDigest' of undefined



  TypeError: Cannot read property 'contentDigest' of undefined

  - extend-node-type.js:59 htmlAstCacheKey
    [narkdown-caption-repro]/[gatsby-transformer-remark]/extend-node-type.js:59:87

  - extend-node-type.js:318 getHTMLAst
    [narkdown-caption-repro]/[gatsby-transformer-remark]/extend-node-type.js:318:41

  - extend-node-type.js:343 Object.getHTML [as generateHTML]
    [narkdown-caption-repro]/[gatsby-transformer-remark]/extend-node-type.js:343:27

  - index.js:150 getImageCaption
    [narkdown-caption-repro]/[gatsby-remark-images]/index.js:150:21

  - index.js:301 generateImagesAndUpdateNode$
    [narkdown-caption-repro]/[gatsby-remark-images]/index.js:301:52


not finished run queries - 1.251s
not finished Generating image thumbnails - 1.383s
```

### Environment

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Celeron(R) N4100 CPU @ 1.10GHz
  Binaries:
    Node: 12.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Programs/Python27/python
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.18.4 => 2.18.7 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-feed: ^2.3.22 => 2.3.23 
    gatsby-plugin-google-analytics: ^2.1.29 => 2.1.29 
    gatsby-plugin-manifest: ^2.2.30 => 2.2.31 
    gatsby-plugin-offline: ^3.0.24 => 3.0.27 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sharp: ^2.3.4 => 2.3.5 
    gatsby-plugin-typography: ^2.3.18 => 2.3.18 
    gatsby-remark-copy-linked-files: ^2.1.31 => 2.1.31 
    gatsby-remark-images: ^3.1.34 => 3.1.35 
    gatsby-remark-prismjs: ^3.3.25 => 3.3.25 
    gatsby-remark-responsive-iframe: ^2.2.28 => 2.2.28 
    gatsby-remark-smartypants: ^2.1.17 => 2.1.17 
    gatsby-source-filesystem: ^2.1.39 => 2.1.40 
    gatsby-transformer-remark: ^2.6.38 => 2.6.39 
    gatsby-transformer-sharp: ^2.3.6 => 2.3.7 
```

### PR DESCRIPTION
**Pull request by mathieudutour**
## Description

Second part of #16574. In the previous PR, we pass down a compiler (in the `gatsby-transformer-remark` package) so that gatsby-remark plugins can use it to recursively parse a piece of content (in that case, the caption of an image). But when used in the `gatsby-plugin-mdx`, the remark plugins didn't get the compiler.
This PR fixes it.

## Related Issues

Second part of #16574.
Fixes #14474 for the MDX case
Fixes #20000

### CODE REVIEW

**Comment by mathieudutour** [comment]
can't seem to be able to see why the build service failed

File: packages/gatsby-plugin-mdx/utils/gen-mdx.js [hunk 1]
```diff
@@ -116,6 +116,10 @@ export const _frontmatter = ${JSON.stringify(data)}`
       reporter,
       cache,
       pathPrefix,
+      compiler: {
+        parseString: compiler.parse.bind(compiler),
+        generateHTML: ast => mdx.sync(ast, options),
```
Comment (vladar) [inline packages/gatsby-plugin-mdx/utils/gen-mdx.js:121]: I don't have enough context on this but it looks like `generateHTML` here is `sync` while in `gatsby-transformer-remark` it is `async`:

https://github.com/gatsbyjs/gatsby/blob/ca19076f2964c0f6101d28b3a68a117b33d8cc70/packages/gatsby-transformer-remark/src/extend-node-type.js#L184-L187

(note the `getHTML` function is async)

It probably caused #20000 here:

https://github.com/gatsbyjs/gatsby/blob/ca19076f2964c0f6101d28b3a68a117b33d8cc70/packages/gatsby-remark-images/src/index.js#L118

(as return value is expected to be sync, but we have a Promise here in case of `gatsby-transformer-remark`)

Comment (mathieudutour) [reply packages/gatsby-plugin-mdx/utils/gen-mdx.js:121]: good catch

**Comment by mathieudutour** [comment]
we really should move this to TS. Happy to take on that if nobody started those packages yet

**Comment by vladar** [comment]
Unfortunately, it didn't fix the #20000 issue. There is more about it:

https://github.com/gatsbyjs/gatsby/blob/ca19076f2964c0f6101d28b3a68a117b33d8cc70/packages/gatsby-transformer-remark/src/extend-node-type.js#L343-L346

As you see `getHTML` accepts Gatsby node, not markdown AST. So when you feed it with the result of `parseString` from here:

https://github.com/gatsbyjs/gatsby/blob/ca19076f2964c0f6101d28b3a68a117b33d8cc70/packages/gatsby-transformer-remark/src/extend-node-type.js#L184-L187

It still fails with the same error:

```
UNHANDLED REJECTION Cannot read property 'contentDigest' of undefined
```

Because `remark.parse` returns AST and `getHTML` expects gatsby node. I think you actually need to change compiler in `gatsby-transformer-remark` to:

```js
compiler: { 
  parseString: remark.parse.bind(remark), 
  generateHTML: ast => hastToHTML(toHAST(ast)), 
}
```

(then it all can stay sync?). But I didn't test it.

**Comment by mathieudutour** [comment]
Oh you're right.

The issue with `hastToHTML(toHAST(...))` is that you bypass all the remark plugins and the caches. So I'd be more tempted to change `remark.parse.bind(remark)` to something like
```js
// returns a node-like object
(string) => ({
  internal: {
    contentDigest: digest(string),
    content: remark.parse(string)
  }
})
```

**Comment by vladar** [comment]
This looks like a hack that will one day shoot us in the foot (this happens more often than not).

Also how much benefit do we get from cache here? I doubt that it will be a significant boost (as far as I understand we don't have cache in MDX version anyway?)

If we still want cache we can just add a separate function similar to `getHTML` which will cache this (it should be simple enough to write).

**Comment by mathieudutour** [comment]
It's mostly about the plugins and options for the users that would be ignored (might be really confusing if some part of the MD is parsed with some plugins while others aren't). I'm actually not too worried about the caches because the captions will always be small.

But I had it all wrong, not sure what I did last time. The issue is not about `generateHTML` but about `parseString`. Could you check my latest commit?

File: packages/gatsby-transformer-remark/src/extend-node-type.js [hunk 2]
```diff
@@ -165,10 +168,22 @@ module.exports = (
...
+    async function getMarkdownAST(content, markdownNode) {
       if (process.env.NODE_ENV !== `production` || !fileNodes) {
         fileNodes = getNodesByType(`File`)
       }
+
+      // compiler to inject in the remark plugins
+      // so that they can use our parser/generator
+      // with all the options and plugins from the user
+      const compiler = {
+        parseString: string => getMarkdownAST(string, markdownNode),
```
Comment (vladar) [inline packages/gatsby-transformer-remark/src/extend-node-type.js:180]: Multiple calls of `getMarkdownAST` with the same `markdownNode` may potentially cause problems because of `mutateSource`. Other plugins literally mutate `markdownNode` inside this function. For example:

https://github.com/Rulikkk/gatsby-remark-emoji/blob/8dd4f880b54e0a83ab2dba924fee58550a570a87/index.js#L9-L22

After this change, they will apply mutation to the same `markdownNode` (not `string`) multiple times. There may be idempotent plugins (maybe even the example above) but in general, idempotency is not guaranteed in `mutateSource`.

File: packages/gatsby-transformer-remark/src/extend-node-type.js [hunk 3]
```diff
@@ -193,7 +205,7 @@ module.exports = (
           return Promise.resolve()
         }
       })
-      const markdownAST = remark.parse(markdownNode.internal.content)
+      const markdownAST = remark.parse(content)
```
Comment (vladar) [inline packages/gatsby-transformer-remark/src/extend-node-type.js:208]: Related to the previous comment. This will ignore changes applied by `mutateSource` above (as they are applied to `markdownNode.internal.content` not to `content`)

**Comment by vladar** [comment]
My best suggestion so far would be to exclude `mutateSource` part from parsing.

In other words, maybe worth extracting method `parseString(string, markdownNode)` from this piece:

https://github.com/gatsbyjs/gatsby/blob/4043129519dd466e4468527656175465cf3f916b/packages/gatsby-transformer-remark/src/extend-node-type.js#L196-L248

And use this new method in both `getMarkdownAST` and in your `compiler.parseString`. Then `mutateSource` will be applied for the whole node once (in `getMarkdownAST`) and remark plugins will still work for captions parsing.

File: packages/gatsby-transformer-remark/src/extend-node-type.js (hunk 2 above)
Comment (mathieudutour) [reply packages/gatsby-transformer-remark/src/extend-node-type.js:180]: Ah interesting, I didn't consider that

**Comment by pvdz** [comment]
(You can ignore gatsby

**Comment by pvdz** [comment]
Sorry. I was going to say that you can ignore the "Gatsby Build Service" failures as they are unrelated to this PR and they are non-blocking. Then mid-way I managed to activate the close button :/ So anyways. Ignore those failures.

File: packages/gatsby-transformer-remark/src/extend-node-type.js [hunk 4]
```diff
@@ -165,35 +165,21 @@ module.exports = (
...
+    // Parse a markdown string and its AST representation,
+    // applying the remark plugins if necesserary
+    async function parseString(string, markdownNode) {
+      // compiler to inject in the remark plugins
+      // so that they can use our parser/generator
+      // with all the options and plugins from the user
+      const compiler = {
+        parseString: string => parseString(string, markdownNode),
+        generateHTML: ast =>
+          hastToHTML(ast, {
```
Comment (vladar) [inline packages/gatsby-transformer-remark/src/extend-node-type.js:177]: I think this still has to be converted to HAST first (as we basically get remark AST here):

```suggestion
          hastToHTML(toHAST(ast), {
```

Comment (mathieudutour) [reply packages/gatsby-transformer-remark/src/extend-node-type.js]: you're right, and there are actually a couple of options we pass to that function so I extracted it to use it everywhere

**Comment by vladar** [comment]
Published in:

 - `gatsby-plugin-mdx@1.1.10`
 - `gatsby-remark-images@3.2.5`
 - `gatsby-transformer-remark@2.7.4`

**Comment by afc163** [comment]
This breaks https://github.com/rstacruz/gatsby-remark-component

@rstacruz

**Comment by mathieudutour** [comment]
how so?

**Comment by chris-erickson** [comment]
Now when I enable `markdownCaptions: true` I'm getting an unhandled promise rejection.  The `showCaptions: ['title']` option does work if `markdownCaptions: false` (but the MD is unprocessed!).  How can I debug this particular issue?

**Comment by mathieudutour** [comment]
1. What the error of the rejected promise?
1. What's your config?
2. Do you have a repro somewhere?

**Comment by chris-erickson** [comment]
So sorry, I forgot to include the error: `UNHANDLED REJECTION Expected node, not '[object Promise]'`

`gatsby-config.json` snippet.
```js
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        commonmark: true,
        footnotes: true,
        pedantic: true,
        gfm: true,
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 960,
              quality: 90
              showCaptions: ['title', 'alt'],
              markdownCaptions: true,
              linkImagesToOriginal: false,
            },
          },
        ],
      },
    },
```

I don't have a reproduction at the moment, our site is quite expansive so it would take me a bit to do that.  If this doesn't provide any useful leads, I can do that.  FWIW, this seems to fail regardless of whether I have a "title" attribute in a MD image link, in other words, it seems like it's not a parsing issue at first glance.

**Comment by mathieudutour** [comment]
found it: #23427
