### PR TITLE
fix(gatsby): fix `$in` operator to return unique elements

### LINKED ISSUE #26382: GraphQL "in" filter on array fields returns duplicates
## Description

I'm trying to filter records (blog articles in my case) by the `tags` field, which is an **array of strings**. I am looking to search for all articles which **contain** any tags from some array. Example query is below:

```gql
query MyQuery {
  allContentfulArticle(filter: {tags: {in: ["environment","food"]}}) {
    nodes {
      id
      title
      tags
    }
  }
}
```

This should return any articles with *either* the `environment` tag or `food` tag. This does work, but for some reason this is returning duplicates for me, but only for cases when the article contains **both the tags** in the search array, with the exact same ID (the actual response I get back is below):

```json
{
  "data": {
    "allContentfulArticle": {
      "nodes": [
        {
          "id": "89fd7eba-ccaf-5e43-aa4f-9455692f6940",
          "title": "Hello world",
          "tags": [
            "environment",
            "science"
          ]
        },
        {
          "id": "7985f52d-048e-5f5d-8b18-52cf02624bb9",
          "title": "Static sites are great",
          "tags": [
            "environment",
            "food"
          ]
        },
        {
          "id": "7985f52d-048e-5f5d-8b18-52cf02624bb9",
          "title": "Static sites are great",
          "tags": [
            "environment",
            "food"
          ]
        }
      ]
    }
  }
}
```

It's also worth noting that this is also the case for the `glob` operator (e.g. `environment|food`) or the regex operator.

### Steps to reproduce

This should be reproducible in the default [Contentful Starter](https://github.com/contentful-userland/gatsby-contentful-starter) example as I am still using mostly the same model and data from this example.

Then just try the query I listed above and make sure one of the blog posts has both of the tags in the tag search array.

### Expected result

No duplicate records should be returned

### Actual result

Duplicates are returned.

### PR DESCRIPTION
**Pull request by pvdz**
Make sure that the `$in` operator for graphql queries only returns unique elements. It was possible to get the same element multiple times if the list of elements matched multiple elements in the same node.

I've also added the same check to all other test cases.

This should fix #26382

### CODE REVIEW

File: packages/gatsby/src/redux/nodes.ts [hunk 1]
```diff
@@ -695,15 +695,16 @@ export const getNodesFromCacheByValue = (
...
 
     // TODO: we can also mergeSort for every step. this may perform worse because of how memory in js works.
     // For every value in the needle array, find the bucket of nodes for
     // that value, add this bucket of nodes to one list, return the list.
     filterValueArr.forEach((v: FilterValueNullable) =>
-      filterCache.byValue.get(v)?.forEach(v => arr.push(v))
+      filterCache.byValue.get(v)?.forEach(v => set.add(v))
     )
 
+    const arr = [...set] // this is bad for perf but will guarantee us a unique set :(
```
Comment (wardpeet) [inline packages/gatsby/src/redux/nodes.ts:707]: would it help to have 1 set and 1 array? Memory will grow but maybe it's not a big deal? The set could contain only identifiers if that makes things smaller.

Comment (vladar) [reply packages/gatsby/src/redux/nodes.ts:707]: I think V8 has a fast-path for cases like this, so shouldn't be that bad: https://v8.dev/blog/spread-elements#spreading-strings%2C-sets%2C-and-maps

File: packages/gatsby/src/schema/__tests__/run-query.js [hunk 2]
```diff
@@ -360,6 +360,7 @@ describe(`Filter fields`, () => {
         hair: { eq: needle },
       })
 
+      expect(result?.length ?? 0).toEqual(new Set(result ?? []).size) // result should contain unique elements
```
Comment (vladar) [inline packages/gatsby/src/schema/__tests__/run-query.js:363]: Maybe have `runFilter` to always return an array to avoid excessive optional chaining?

**Review by vladar — APPROVED** [review]
Looks good to me 👍 Left an inline comment but nothing blocking this PR, up to you.

File: packages/gatsby/src/redux/nodes.ts (hunk 1 above)
Comment (pvdz) [reply packages/gatsby/src/redux/nodes.ts:707]: Beyond whether it can/should or not, concrete changes to the fast filter caching mechanism will take up more time than we currently have available. Either this is a band-aid that works for an operator that is already assumed to be slower than `$eq`, or it's the best fix and `$in` is still going to be slower. I would keep it like this for now.

I think there's still perf left ot be squeezed out of fast filters but that'll have to be done in like a focus sprint where I can get back into context of all the things. And after we finish the benchmark project, because then we can more reliably track its perf.

Comment (pvdz) [reply packages/gatsby/src/redux/nodes.ts:707]: (Once we have those graphs and the right benchmarks, we can easily compare different implementations against each other and make a decision with high degree of confidence based on numbers)

File: packages/gatsby/src/schema/__tests__/run-query.js (hunk 2 above)
Comment (pvdz) [reply packages/gatsby/src/schema/__tests__/run-query.js:363]: I definitely want to do that once we can break majors. As it stands, we'll have to live with this empty array vs null result.

Comment (vladar) [reply packages/gatsby/src/schema/__tests__/run-query.js:363]: I meant `runFilter` wrapper in tests here (not in the code itself): https://github.com/gatsbyjs/gatsby/blob/aa9e0be0938dd5a0bc9cc936ea664f5df3073172/packages/gatsby/src/schema/__tests__/run-query.js#L337-L344
