### PR TITLE
fix: constrain height of www search results based on viewport height

### LINKED ISSUE #6221: v2 docs search modal cut off on smaller screens
## Description

When viewing the v2 docs site at https://next.gatsbyjs.org/docs, while using the the search field, the pop-up window appears to be cutoff on smaller screens (A 13" Macbook Pro for example), or in smaller browser windows, when there is a large amount of search result content.

screen shot 2018-06-28 at 6 01 23 pm

### Steps to reproduce

- Visit https://next.gatsbyjs.org/docs on a device with a small screen (ex: 13" Macbook Pro), or resize the browser window viewport to a small height (Below 760px in this case)
- Enter a query/term into the search field (ex: `styling`) that might result in a large amount of returned results
- View that the bottom of the modal appears to be cutoff

### Expected result

I would expect the search modal to have a vertical scrollbar or some other way to reduce the overall height of the modal at smaller screen/browser window sizes.

### Actual result

Content underneath the **Reference** heading appears to be cutoff, and I was unable to see what that additional content/search results might be.

### Environment

13" Macbook Pro
macOS Sierra v10.12.6
1280x800 resolution
Google Chrome v67.0.3396.99

### PR DESCRIPTION
**Pull request by Wattenberger**
Fixes #6221

The existing max-height rule was on a container div that didn't specify scroll/auto on overflow and it was too tall. I moved the rule to a child div that already specified `overflow: auto` and bumped up the space allotted for the fixed nav.

This is my first gatsby pull request - please let me know if I'm missing anything. Thanks!

### CODE REVIEW

File: www/src/components/search-form.js [hunk 1]
```diff
@@ -78,6 +77,7 @@ css.insert(`
   }
 
   .algolia-autocomplete .ds-dropdown-menu [class^="ds-dataset-"] {
+    max-height: calc(100vh - 7rem) !important;
```
Comment (DSchau) [inline www/src/components/search-form.js]: we're pretty guilty of this, but is `7rem` the header height? Is it possible to do something like this, just so it's obvious?

```js
const HEADER_HEIGHT = `7rem`

// later
max-height: calc(100vh - ${HEADER_HEIGHT}) !important;

```

Comment (fk) [reply www/src/components/search-form.js]: @DSchau Good call! We have constants for header and banner heights in https://github.com/gatsbyjs/gatsby/blob/57b57e1116157e66be66235ccf5e0004edda8302/www/src/utils/presets.js#L37-L38

search dropdown

☝️ We position the dropdown slightly above the header – which I personally like and would keep - and want some whitespace at the bottom (which @Wattenberger's PR already takes care of), so maybe something along the lines of

```js
const dropdownOffsetTop = ...
const dropdownOffsetBottom = ... 

max-height: calc(100vh - ${presets.headerHeight} - ${presets.bannerHeight} - ${presets.dropdownOffsetTop} - ${dropdownOffsetBottom}) !important;
```

to get rid of the magic number for `max-height`? We could then also replace https://github.com/gatsbyjs/gatsby/blob/57b57e1116157e66be66235ccf5e0004edda8302/www/src/components/search-form.js#L21 with a `calc` that considers `dropdownOffsetTop`.

Comment (DSchau) [reply www/src/components/search-form.js]: @fk seems manageable to me! Thanks for the leg work digging into it!

Comment (fk) [reply www/src/components/search-form.js]: 💯 @Wattenberger Let us know if you want to help us getting rid of those magic numbers! 😅

Comment (Wattenberger) [reply www/src/components/search-form.js]: I do! Down with magic numbers!
I added a constant right above the styles since the `searchDropdownOffsetTop` is scoped to that one component.
I also noticed that the search dialog was too high on the homepage and scooched that down.

**Comment by fk** [comment]
Thank you @Wattenberger for following up! 🙏

I jumped in to set `debug` back to `false` and resolve a merge conflict that stemmed from switching from glamor to emotion in the meantime.
