### PR TITLE
[www] Fix header background for paginated "Blog" pages

### LINKED ISSUE #8041: [www] Fix header background for paginated "Blog" pages
Unlike all other .org pages, `/blog/` sports a header and content with a non-white background:

image

We set the background color for the header in 
https://github.com/gatsbyjs/gatsby/blob/446856b8de282945ac9153edc77f684a9824d91b/www/src/components/navigation.js#L99-L102 based on
https://github.com/gatsbyjs/gatsby/blob/446856b8de282945ac9153edc77f684a9824d91b/www/src/components/navigation.js#L33

We recently introduced pagination to the blog, splitting up blogs posts across pages like `/blog/2`, `/blog/3`, etc. These pages are not caught by the current condition for `isBlog`, resulting in the header background to be white:

image

It'd be nice to have a grey-ish header background for e.g. https://next.gatsbyjs.org/blog/2, too!

### PR DESCRIPTION
**Pull request by fk**
Resolves #8041 by changing the URLs for "paginated blog index pages" from e.g. `/blog/2` to `/blog/page/2`, and updating the condition defining wether to render the header with a grey or white background accordingly.

I chose to change the URLs for "paginated blog index pages" instead of fiddling around with a more complex condition/regex. That condition would have had to differentiate among e.g. `/blog/2` (a paginated page, w/ gray header bg) and e.g. `/blog/2018-07-17-announcing-gatsby-preview/` (a blog article, w/ white header bg) — while this certainly would have been possible, it still felt a little fragile.

The URL change comes with the side effect of making the "paginated blog index page" URLs a little more meaningful.

### CODE REVIEW

File: www/src/components/pagination/index.js [hunk 1]
```diff
@@ -17,8 +17,8 @@ class Pagination extends React.Component {
     const prevPageNum =
       currentPage - 1 === 1 ? `` : (currentPage - 1).toString()
     const nextPageNum = (currentPage + 1).toString()
-    const prevPageLink = isFirst ? null : `/blog/${prevPageNum}`
-    const nextPageLink = isLast ? null : `/blog/${nextPageNum}`
+    const prevPageLink = isFirst ? null : `/blog/page/${prevPageNum}`
```
Comment (pieh) [inline www/src/components/pagination/index.js]: on page "2" this link would be to `/blog/page/` (which doesn't exist - we have `/blog`). I think we probably should adjust  `prevPageNum` assignment:
```diff
const prevPageNum =
-      currentPage - 1 === 1 ? `` : (currentPage - 1).toString()
+      currentPage - 1 === 1 ? `` : `page/${(currentPage - 1).toString()}`
```
and drop changes to `prevPageLink`? (Potentialy do the same for `nextPageLink` for consistency

File: www/src/components/pagination/index.js [hunk 2]
```diff
@@ -8,7 +8,7 @@ import { options, rhythm } from "../../utils/typography"
 
 class Pagination extends React.Component {
   changePage = e => {
-    navigate(`/blog/${e.target.value}`)
+    navigate(`/blog/page/${e.target.value}`)
```
Comment (pieh) [inline www/src/components/pagination/index.js]: I'm not sure - this might not work for first page as well? (special case of it being just `/blog` with page number)?

**Comment by fk** [comment]
Argh! Clearly wasn't thinking there… 🤦‍♂️

images-1

Thanks @pieh and @NickyMeuleman (and @DSchau)!

File: www/src/components/pagination/index.js (hunk 2 above)
Comment (NickyMeuleman) [reply www/src/components/pagination/index.js]: Since the value for the first page is an empty string (which is falsy)
```diff
- navigate(`/blog/${e.target.value}`)
+ navigate(e.target.value ? `/blog/${e.target.value}` : `/blog`)
```

**Comment by fk** [comment]
@pieh @calcsam Wanna take another look at this? I fixed the stupid things I did and would love to get this in!

**Comment by fk** [comment]
^ NVM actually, will pretend to be a big boy and merge this in now! ;-)

**Comment by calcsam** [comment]
Nice @fk !
