### PR TITLE
fix(gatsby-cli): convert hooks into class component

### LINKED ISSUE #14911: gatsby-cli 2.6.12 error: RangeError: Maximum call stack size exceeded
## Description

After using `yarn upgrade` and then `yarn start`, I now get an error `RangeError: Maximum call stack size exceeded`

I've seen a related issue with React Helmet, from my tests doesn't seem to be related to this.

### Steps to reproduce

```
yarn upgrade
yarn start
```

### Expected result

No errors!

### Actual result

```
/mnt/d/ee/hello-world/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at Object.console.error (/mnt/d/ee/hello-world/node_modules/gatsby-cli/lib/reporter/index.js:216:50)
    at warningWithoutStack (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:100:32)
    at warnAboutUpdateOnUnmounted (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:10458:5)
    at scheduleWork (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:11868:11)
    at Object.enqueueSetState (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:3152:5)
    at GatsbyReporter.Component.setState (/mnt/d/ee/hello-world/node_modules/react/cjs/react.development.js:335:16)
    at GatsbyReporter._addMessage (/mnt/d/ee/hello-world/node_modules/gatsby-cli/lib/reporter/reporters/ink/reporter.js:132:10)
    at Object.error (/mnt/d/ee/hello-world/node_modules/gatsby-cli/lib/reporter/index.js:82:22)
    at Object.console.error (/mnt/d/ee/hello-world/node_modules/gatsby-cli/lib/reporter/index.js:216:39)
    at warningWithoutStack (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:100:32)
    at warnAboutUpdateOnUnmounted (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:10458:5)
    at scheduleWork (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:11868:11)
    at Object.enqueueSetState (/mnt/d/ee/hello-world/node_modules/react-reconciler/cjs/react-reconciler.development.js:3152:5)
    at GatsbyReporter.Component.setState (/mnt/d/ee/hello-world/node_modules/react/cjs/react.development.js:335:16)
    at GatsbyReporter._addMessage (/mnt/d/ee/hello-world/node_modules/gatsby-cli/lib/reporter/reporters/ink/reporter.js:132:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! pedrolamas.com@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the pedrolamas.com@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pedro/.npm/_logs/2019-06-19T13_19_45_344Z-debug.log
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Environment

Running on Windows 10 latest version via WSL!

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver) -> Windows WSL
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.9.4 => 2.9.9
    gatsby-cli: ^2.6.12 => 2.6.12
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-mdx: ^0.6.3 => 0.6.3
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.1.3
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sass: ^2.0.13 => 2.0.13
    gatsby-plugin-sharp: ^2.1.9 => 2.1.9
    gatsby-plugin-typescript: ^2.0.15 => 2.0.15
    gatsby-remark-images: ^3.0.16 => 3.0.16
    gatsby-source-filesystem: ^2.0.43 => 2.0.43
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
    gatsby-transformer-yaml: ^2.1.12 => 2.1.12
  npmGlobalPackages:
    gatsby-cli: 2.6.12
```

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
- Converted Develop component from hooks to class component.
- Add error logging to ink when our react component goes south.
image
- I also added telemetry to make sure we track it.

## Related Issues
Fixes #14911

### CODE REVIEW

File: packages/gatsby-cli/src/reporter/reporters/ink/reporter.js [hunk 1]
```diff
@@ -126,8 +127,39 @@ export default class GatsbyReporter extends React.Component {
     this._addMessage(`verbose`, str)
   }
 
+  static getDerivedStateFromError(error) {
+    return { hasError: true, error: error.name }
+  }
+
+  componentDidCatch(error, info) {
+    trackBuildError(`INK`, {
```
Comment (wardpeet) [inline packages/gatsby-cli/src/reporter/reporters/ink/reporter.js]: @jamo how do I track this error properly?

Comment (sidharthachatterjee) [reply packages/gatsby-cli/src/reporter/reporters/ink/reporter.js]: Yup, this looks correct

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-cli@2.7.16`
