### PR TITLE
[v2] [gatsby-plugin-offline] [cache-dir] Fix bugs with mismatching actual/canonical paths

### LINKED ISSUE #7261: [v2] Refreshing a page then hitting back (browser back button) leads to 404
## Description

I have a local project that is using the v2 of Gatsby. Eevrything works great except for the fact that a page refresh and a back button on the browser always leads to a 404. On that 404 page Gatsby displays a list of routes and the actual route (the one that responded with 404) is in that list.

```
http://localhost:8000/categories/release/
-----
Gatsby.js development 404 page
There's not a page yet at /categories/release/

Create a React.js component in your site directory at src/pages/categories/release.js and this page will automatically refresh to show the new page component you created.

If you were trying to reach another page, perhaps you can find it below.

Pages (7)
/tags/cards/
/tags/example/
/tags/release/
/categories/release/
/404/
/
/404.html
```

### Environment

```
gatsby info --clipboard

  System:
    OS: Linux 4.17 Fedora 28 (Workstation Edition) 28 (Workstation Edition)
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 4.4.23 - /bin/bash
  Binaries:
    Node: 10.7.0 - /usr/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.1.0 - /usr/bin/npm
  Browsers:
    Chrome: 68.0.3440.75
    Firefox: 61.0.1
  npmPackages:
    gatsby: next => 2.0.0-beta.97 
    gatsby-1-config-css-modules: next => 1.0.10-13 
    gatsby-image: next => 2.0.0-beta.7 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-mailchimp: 2.2.3 => 2.2.3 
    gatsby-plugin-netlify: ^2.0.0-beta.6 => 2.0.0-beta.6 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-sass: next => 2.0.0-beta.10 
    gatsby-plugin-sharp: next => 2.0.0-beta.7 
    gatsby-plugin-styled-components: next => 3.0.0-beta.3 
    gatsby-plugin-typescript: next => 2.0.0-beta.9 
    gatsby-source-contentful: next => 2.0.1-beta.15 
    gatsby-source-filesystem: next => 2.0.1-beta.10 
    gatsby-transformer-sharp: next => 2.1.1-beta.6 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby: 2.0.0-beta.54

```

### File contents (if changed)

`gatsby-config.js`: 

```
let contentfulConfig, mailchimpConfig;

try {
	contentfulConfig = require('./config/contentful.json');
} catch (_) {
	contentfulConfig = {
		spaceId: process.env.CONTENTFUL_SPACE_ID,
		accessToken: process.env.CONTENTFUL_DELIVERY_TOKEN,
	}
}

try {
	mailchimpConfig = require('./config/mailchimp.json')
} catch (_) {
	mailchimpConfig = {
		endpoint: process.env.MAILCHIMP_ENDPOINT
	}
}

module.exports = {
	plugins: [
		'gatsby-plugin-react-helmet',
		`gatsby-plugin-typescript`,
		`gatsby-transformer-sharp`,
		`gatsby-plugin-sharp`,
		`gatsby-plugin-sass`,
		`gatsby-plugin-styled-components`,
		{
			resolve: `gatsby-plugin-google-fonts`,
			options: {
				fonts: [
					`Roboto:300,300i,400,400i,500,500i,600,600i`,
				],
			},
		},
		{
			resolve: `gatsby-source-contentful`,
			options: contentfulConfig,
		},
		{
			resolve: 'gatsby-plugin-mailchimp',
			options: mailchimpConfig,
		},
		`gatsby-plugin-netlify`, // make sure to keep it last in the array
	],
};

```

`package.json`: 

```
{
  "name": "",
  "description": "",
  "version": "1.0.0",
  "author": "",
  "dependencies": {
    "@blueprintjs/core": "^3.0.1",
    "autoprefixer": "^9.0.1",
    "babel-plugin-styled-components": "^1.5.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "gatsby": "next",
    "gatsby-1-config-css-modules": "next",
    "gatsby-image": "next",
    "gatsby-plugin-google-fonts": "0.0.4",
    "gatsby-plugin-mailchimp": "2.2.3",
    "gatsby-plugin-netlify": "^2.0.0-beta.6",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-sass": "next",
    "gatsby-plugin-sharp": "next",
    "gatsby-plugin-styled-components": "next",
    "gatsby-plugin-typescript": "next",
    "gatsby-source-contentful": "next",
    "gatsby-source-filesystem": "next",
    "gatsby-transformer-sharp": "next",
    "grid-styled": "^5.0.2",
    "install": "^0.12.1",
    "lodash": "^4.17.10",
    "lodash.debounce": "^4.0.8",
    "moment": "^2.22.2",
    "node-sass": "^4.9.2",
    "npm": "^6.3.0",
    "prismjs": "^1.15.0",
    "react": "^16.4.1",
    "react-accessible-accordion": "^2.4.4",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.4.1",
    "react-helmet": "^5.2.0",
    "react-player": "^1.6.4",
    "react-prism": "^4.3.2",
    "react-redux": "^5.0.7",
    "react-share": "^2.2.0",
    "react-slick": "^0.23.1",
    "remark": "^9.0.0",
    "remark-react": "^4.0.3",
    "slick-carousel": "^1.8.1",
    "styled-components": "^3.3.3",
    "tinycolor2": "^1.4.1"
  },
  "keywords": [
    "static site",
    "cards",
    "smart cards",
    "blog"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@types/grid-styled": "^4.2.0",
    "@types/lodash": "^4.14.115",
    "@types/moment": "^2.13.0",
    "@types/node": "^10.5.5",
    "@types/prismjs": "^1.9.0",
    "@types/prop-types": "^15.5.4",
    "@types/reach__router": "^1.0.0",
    "@types/react": "^16.4.7",
    "@types/react-dom": "^16.0.6",
    "@types/react-helmet": "^5.0.6",
    "@types/react-redux": "^6.0.5",
    "@types/react-share": "^2.1.1",
    "@types/react-transition-group": "^2.0.13",
    "@types/tinycolor2": "^1.4.1",
    "prettier": "^1.13.7",
    "redux-devtools-extension": "^2.13.5"
  },
  "repository": {
    "type": "git",
    "url": ""
  }
}

```

`gatsby-node.js`: 

```
const _ = require('lodash');
const Promise = require('bluebird');
const path = require('path');
const {createFilePath} = require(`gatsby-source-filesystem`);
const {createRemoteFileNode} = require(`gatsby-source-filesystem`);

const getTags = (edges) => {
	const tags = [];

	_.each(edges, edge => {
		if (_.get(edge, "node.tags")) {
			for (let i = 0; i < edge.node.tags.length; i++) {
				tags.push(edge.node.tags[i]);
			}
		}
	});

	return tags;
};

const getCategories = (edges) => {
	const categories = [];

	_.each(edges, edge => {
		if (_.get(edge, "node.categories")) {
			for (let i = 0; i < edge.node.categories.length; i++) {
				categories.push(edge.node.categories[i]);
			}
		}
	});

	return categories;
};

exports.createPages = ({graphql, actions}) => {
	const {createPage} = actions;

	return new Promise((resolve, reject) => {
		const postTemplate = path.resolve('./src/templates/post/index.tsx');
		const tagTemplate = path.resolve("./src/templates/tag/index.tsx");
		const categoryTemplate = path.resolve("./src/templates/category/index.tsx");

		resolve(graphql(`
				{
					allContentfulPost(sort: {fields: [createdAt], order: DESC}) {
						edges {
							node {
								id
								slug
								
								tags {
									id
									slug
									title
								}

								categories {
									id
									slug
									title
								}

								createdAt
								updatedAt
							}
						}
					}
				}
			`).then(result => {
			if (result.errors) {
				console.error(result.errors);
				reject(result.errors);
			}

			const edges = result.data.allContentfulPost.edges;

			const tags = getTags(edges);
			const categories = getCategories(edges);

			// Create posts and pages.
			_.each(edges, (edge, index) => {
				const slug = edge.node.slug;

				const previous = index === edges.length - 1 ? null : edges[index + 1].node;
				const next = index === 0 ? null : edges[index - 1].node;

				//	create posts pages
				createPage({
					path: `/posts/${slug}/`,
					component: postTemplate,
					context: {
						slug: slug,
						previous,
						next,
					},
				});
			});

			// Make tag pages
			_.uniq(tags).forEach(tag => {
				createPage({
					path: `/tags/${tag.slug}/`,
					component: tagTemplate,
					context: {
						slug: tag.slug
					},
				})
			});

			// Make category pages
			_.uniqBy(categories, 'id').forEach(category => {
				createPage({
					path: `/categories/${category.slug}/`,
					component: categoryTemplate,
					context: {
						slug: category.slug
					},
				})
			});
		}));
	});
};
```

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

NO console errors shown.

### LINKED ISSUE #7760: [v2] Gatsby attempts to reload a page infinitely if the canonical path doesn't match window.location.pathname
This is mainly a problem when the hosting rewrites uppercase URLs as lowercase, and would also occur e.g. if an external link points to a page on a Gatsby site with different casing. To test locally, after running `gatsby build` and before `gatsby serve`, copy a page folder to another location (e.g. `cp -r public/about public/about-test`).

Analysis so far: replacing `window.location.pathname` with `window.page.path` in `production-app.js` (around lines 85) prevents the `A page wasn't found for...` warning displaying in the console, and `loader.getPage(window.page.path)` returns `true`:

image

(In the future I'll also perform checks to make sure it still uses `window.location.pathname` if the canonical path points to the offline app shell, otherwise it would just render a blank page without `no-cache=1`.)

However, the RouteHandler element's `props.location` still use the actual window's location, and these props are used to determine which page to actually load. I believe they get passed to `PageRenderer` which then checks if the `pageResources` exist, and this check fails due to the actual pathname for which Gatsby doesn't have resources. Thus we have the infinite reload, where `&no-cache=1` keeps getting added to the URL: (while testing I returned null before this happens to make things easier, but normally that line wouldn't exist so it would keep reloading)

image

So what we need to do is set change the RouteHandler's `props.location.pathname` to match the canonical path, to allow Gatsby to find the resources. This is what I'm currently stuck on, I'll just copy my last commend from #7355 over here

### PR DESCRIPTION
**Pull request by davidbailey00**
Changelog:

- Add back the check in `load-directly-or-404.js` - @KyleAMathews was correct that this should be unnecessary, however a lot of the recent bugs were due to behaviour surrounding the new `no-cache=1` so it might help if others are discovered later.
- Set the correct pathname without loading from the server if it mismatches the canonical path - this allows Gatsby to find the resources for the page, even if the server is serving it at a different location (e.g. lowercase when it should be uppercase)
- Replace the URL if `loadDirectlyOr404` succeeds upon initially trying to load the page, for correct history.
  - Not sure yet if this fixes #7261 since my manual tests didn't include reloading before pressing back etc, but it works correctly for all the tests I've performed.

<details>
<summary>Click to see manual tests</summary>

```
configurations:

- 1) online without gatsby-plugin-offline
- 2) online with gatsby-plugin-offline
- 3) offline with gatsby-plugin-offline
- 4) online in develop

- x.1) with a custom 404 page
- x.2) without a custom 404 page


tests:

- 1) 404s are handled correctly from internal links - custom 404 or server 404
  if custom is unavailable, or offline error, but no blank pages

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 2) 404s are handled correctly when entering a URL directly - as above, and
  the URL fetched contains the original query parameters (not just no-cache=1)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 3A) back button works properly after internal link 404 (navigates to the
  expected page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 3B) back button works properly after external link 404 (navigates to the
  expected page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 4) pages which fail to load display a native offline error (no blank pages)

  requires: [3.1, 3.2]
  passed:   [3.1, 3.2]

- 5) the service worker remains installed after a 404/offline error

  requires: [3.1, 3.2]
  passed:   [3.1, 3.2]

- 6) Netlify CMS /admin/ loads or displays an offline error (no 404/blank page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 7) going to a page by entering the URL directly works

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 8) clicking the "mismatching canonical URL" link works with JS, and goes
  backwards and forwards correctly (or shows offline)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]

- 9) directly entering the mismatching canonical URL works with JS, and goes
  backwards and forwards correctly (or shows offline)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2]

- 10) going to a page with a mismatching canonical URL always shows a 404 in
  development

  requires: [4.1, 4.2]
  passed:   [4.1, 4.2]
```
</details>

Fixes #7760

### CODE REVIEW

**Comment by davidbailey00** [comment]
AppVeyor appears to be stuck on queued... again

**Comment by jlengstorf** [comment]
UI tests failed; retrying because it looked like a timeout.

**Comment by davidbailey00** [comment]
@jlengstorf Kyle changed the behaviour in #7763 although unfortunately it doesn't seem to have worked

**Comment by KyleAMathews** [comment]
@davidbailey00 yeah, been looking into it. Should have a PR up fixing it sooner than later.

File: packages/gatsby/cache-dir/production-app.js [hunk 1]
```diff
@@ -80,14 +80,30 @@ apiRunnerAsync(`onClientEntry`).then(() => {
...
   }
 
+  if (
+    window.page.path &&
+    window.page.path !== window.location.pathname &&
+    window.page.path !== `/offline-plugin-app-shell-fallback/`
+  ) {
+    const url = new URL(window.location)
+    url.pathname = window.page.path
+    navigate(url, { replace: true })
```
Comment (KyleAMathews) [inline packages/gatsby/cache-dir/production-app.js]: `navigate` only takes a string https://github.com/reach/router/blob/master/website/src/markdown/api/navigate.md#to

Comment (davidbailey00) [reply packages/gatsby/cache-dir/production-app.js]: Thanks for pointing this out, just fixed it!
