### PR TITLE
Moves responsive image CSS back into attribute

### LINKED ISSUE #17593: [gatsby-remark-images] Large blank spaces / blurs in RSS feeds
## Description

The `gatsby-remark-images` plugin causes large blank space above images in RSS readers that apply the page’s inline styles.

This seems to be due to #14816, which moved the `` tag’s positioning out of the `style` attribute and into a `<style>` tag that is not seen by RSS readers.

Because of this, the `` is not absolutely positioned over the background element, which causes either a large white space or a blurry background, depending on the HTML support in the reader. Additionally, the image is not correctly sized.

### Steps to reproduce

1. Include `gatsby-remark-images` in a site and put an image in a blog post.
1. View the site in Reeder or NetNewsWire

### Expected result

Images naturally fit in with the content of the post.

### Actual result

The background element is not covered up, leaving either white space or a blurry image.

Here are shots of the Gatsby blog post [Creating a purpose-driven media platform](https://www.gatsbyjs.org/blog/2019-08-23-creating-a-purpose-driven-media-platform/)

NetNewsWire 5.0 on OS X:

Screen Shot 2019-09-12 at 1 49 56 PM

Reeder on iOS:

IMG_4160

In some cases, such as FeedBin for the web, the RSS reader throws out enough of the CSS and HTML that it strips the background padding element, so things look fine:

Screen Shot 2019-09-12 at 1 55 33 PM

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.68 => 2.15.5

### PR DESCRIPTION
**Pull request by fionawhim**
## Description

This PR reverts a part of #14816 that moved the image styles into a <style>
tag in the head. Per this comment from @JoshuaWalsh, putting the styles
in the <head> was just a cleanliness improvement, and did not affect the
functionality that #14816 was addressing:

https://github.com/gatsbyjs/gatsby/pull/14816#issuecomment-531076102

Reverting this PR allows the responsive images to display correctly when
the Remark HTML is displayed outside of the Gatsby layout, such as in
an RSS feed.

## Related Issues

Fixes #17593

### CODE REVIEW

**Comment by pvdz** [comment]
Ah sounds like a good fix :)

One semantic change is that before it was creating a css class that could apply to multiple elements. Afterwards this code is duplicated if multiple elements want to use it.

I understand if this image is never intended to be re-used by multiple elements, it's just not clear in this PR. Can you confirm please?

File: packages/gatsby-remark-images/src/index.js [hunk 1]
```diff
@@ -190,6 +190,15 @@ module.exports = (
...
     }
 
+    const imageStyle = `
+      width: 100%;
+      height: 100%;
+      margin: 0;
+      vertical-align: middle;
+      position: absolute;
+      top: 0;
+      left: 0;`.replace(/\s*(\S+:)\s*/g, `$1`)
```
Comment (pvdz) [inline packages/gatsby-remark-images/src/index.js]: Isn't this just `.replace(/\s*/g, '')` ? Or are we defensive about future updates where certain rules may be whitespace sensitive.

Comment (pvdz) [reply packages/gatsby-remark-images/src/index.js]: (Also, if you're stripping whitespace anyways, it's probably nice to have the closing backtick on the next line, aligned with the `const`.)

**Comment by vladar** [comment]
Looks good to me. But tests are failing. You will have to re-run them with `--updateSnapshot`.

File: packages/gatsby-remark-images/src/index.js (hunk 1 above)
Comment (fionawhim) [reply packages/gatsby-remark-images/src/index.js]: Thanks for the review!

Not sure about the regexp. I copied it in from the [older version of the file](https://github.com/gatsbyjs/gatsby/blob/9fb78f8634d42e0f5547e320aafed9ae5b489223/packages/gatsby-remark-images/src/index.js#L177). I think being defensive here is a good move, though.

Since the regexp only strips before the CSS property name and between the colon and the value, it doesn’t strip the newline after the last line, so leaving backtick as-is.

**Comment by fionawhim** [comment]
@pvdz I can’t say if anyone has started to put `gatsby-resp-image-image` as a class on other elements not generated by this plugin between July when the `<style>` tag was first added and now. This would be a breaking change for those people, I suppose.

@vladar Thanks for the review! I updated the snapshots and pushed to this branch.
