### PR TITLE
fix(gatsby): Fix stack overflow on queries with circular fragments

### LINKED ISSUE #20826: Fragments referencing each other causes a stack overflow
## Description

If you have two fragments and they reference each other 

`determineUsedFragmentsForDefinition` hits a infinite loop

### Steps to reproduce

```graphql
  fragment b on TypedocType {
      declaration {
        ...a
      }
    }

    fragment a on TypedocNode {
      type {
        ...b
      }
    }

    query {
      typedocNode {
        ...a
      }
    }
```

### PR DESCRIPTION
**Pull request by vladar**
## Description

This PR fixes stack overflow caused by circular fragments. Stack overflow was first introduced here: https://github.com/gatsbyjs/gatsby/pull/19665 

## Related Issues
Fixes #20826

### CODE REVIEW

File: packages/gatsby/src/query/query-compiler.js [hunk 1]
```diff
@@ -443,6 +444,10 @@ const determineUsedFragmentsForDefinition = (
       [Kind.FRAGMENT_SPREAD]: node => {
         const name = node.name.value
         const fragmentDefinition = definitionsByName.get(name)
+        if (visitedFragmentDefinitions.has(fragmentDefinition)) {
+          return
+        }
+        visitedFragmentDefinitions.add(fragmentDefinition)
         if (fragmentDefinition) {
```
Comment (pvdz) [inline packages/gatsby/src/query/query-compiler.js]: This implies that you may be adding primitives to the `visitedFragmentDefinitions` set.

If nothing else, I would bet that we could move the 447-450 to be inside the falsy check to prevent falsy values being added to the queue. Or if the value is never falsy, drop the check.

Also, if `name` is a unique descriptor of these objects then maybe that would be as good a value to use for this purpose.

Comment (vladar) [reply packages/gatsby/src/query/query-compiler.js]: Right, `fragmentDefinition` can be `undefined` in an edge case. Will move the check inside `if (fragmentDefinition) { }`
