### PR TITLE
fix(gatsby-source-wordpress): Remove search and replace regex literal recommendation

### LINKED ISSUE #31411: gatsby-source-wordpress searchAndReplace[0].search must be a string
## Description

In gatsby source WordPress, the newly created feature "searchAndReplace" does not allow to write a `regular expression literal`, the options schema validation does not accept it.

@TylerBarnes Before we merged this feature I added a comment in the docs to use `regular expression literal`, I guess we should fix this before public release.

I didn't find a way to make Joi happy with a regular expression literal, I need to dig more into this.

### Steps to reproduce

Add the following config a gatsby WordPress setup:
```
    {
      resolve: "gatsby-source-wordpress",
      options: {
        url: metadata.wordpressUrl + "/graphql",
        searchAndReplace: [
          {
            search: /https:\/\/some.url-to-replace.org/,
            replace: "https://some-other.url",
          },
        ],
      },
    },
```

### Expected result

The run the feature properly

### Actual result

The gatsby options schema validation reject the setting since `search` is not a string.
```
Invalid plugin options for "gatsby-source-wordpress":

- "searchAndReplace[0].search" must be a string

not finished load plugins - 1.965s

error Command failed with exit code 1.

```

### Environment

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.12 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 78.10.0esr
  npmPackages:
    gatsby: ^3.5.0 => 3.5.0
    gatsby-plugin-catch-links: ^3.5.0 => 3.5.0
    gatsby-plugin-image: ^1.5.0 => 1.5.0
    gatsby-plugin-local-search: ^2.0.1 => 2.0.1
    gatsby-plugin-manifest: ^3.5.0 => 3.5.0
    gatsby-plugin-react-helmet: ^4.5.0 => 4.5.0
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2
    gatsby-plugin-sass: ^4.5.0 => 4.5.0
    gatsby-plugin-sharp: ^3.5.0 => 3.5.0
    gatsby-plugin-sitemap: ^4.1.0 => 4.1.0
    gatsby-source-filesystem: ^3.5.0 => 3.5.0
    gatsby-source-wordpress: ^5.6.0-next.1 => 5.6.0-next.1
    gatsby-transformer-sharp: ^3.5.0 => 3.5.0
```

### PR DESCRIPTION
**Pull request by jooola**
~~A regular expression literal generate a RegExp object at compile time. We need to allow string or object in the option schema.~~

EDIT: I decided to remove the documentation entry recommending a Regex literal, instead of the above solution.

Improvements can be made in the future.

cc @TylerBarnes

## Related Issues

Fix #31411
Related to #31091

### CODE REVIEW

**Comment by jooola** [comment]
@TylerBarnes Using `Joi.alternatives()` does not play well with the documentation, what should we do ?

I could add some extra code in the docs generation script, or force somehow the type to be a String, but using `trueType` in the meta did not work.

Any ideas ? Thoughts ?

Maybe this should be a blocker, before the `searchAndReplace` feature is released to the public as stable.

**Comment by jooola** [comment]
Does gatsby generate a graphql schema for the plugin options, and make it accessible from graphql ? If yes this means we cannot use `Joi.alternatives` ?

Should we simply remove the sentence saying we recommend regex expression literal ?

**Comment by jooola** [comment]
I finally simply removed the documentation string saying a regular expression literal was recommended.

File: packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.ts [hunk 1]
```diff
@@ -538,9 +538,7 @@ When using this option, be sure to gitignore the wordpress-cache directory in th
       .items(
         Joi.object({
           search: Joi.string()
-            .description(
-              `The regex rule used to search a terme. Using a 'regular expression literal' is recommended over a simple regex string.`
-            )
+            .description(`The regex rule used to search a terme.`)
```
Comment (TylerBarnes) [inline packages/gatsby-source-wordpress/src/steps/declare-plugin-options-schema.ts:541]:
```suggestion
            .description(`The regex rule used to search when replacing strings in node data. It will search stringified JSON of node to capture strings at any nested depth.`)
```

**Review by TylerBarnes — CHANGES_REQUESTED** [review]

**Comment by jooola** [comment]
Commited your change, rebased, should be good to go.

**Review by TylerBarnes — APPROVED** [review]

**Comment by TylerBarnes** [comment]
Thanks @jooola !

**Comment by jooola** [comment]
My pleasure
