### PR TITLE
fix(gatsby-remark-prismjs): fix line highlighting with multiline tokens

### LINKED ISSUE #26079: [gatsby-remark-prismJs] line highlighting does not work properly with 'triple-quoted-string'
## Description

Line hightlighting does not work for language python when line is inside span 'triple-quoted-string'.

### Steps to reproduce
project: https://github.com/Skurrr/prismJsBug
run gatsby serve
go to: http://localhost:8000/test/
inspect html dom:
obraz
### Expected result
markdown structure shouldn't be altered. 
lines 2 and 3 should be highlighted

### Actual result
Span 'triple-quoted-string' seems to be messy, as result first string line is moved to the same line as """. Whole triple-quoted-string span is marked for highlighting, i would expect that below lines are highligted(see /src/markdow-pages/test.md)

-  opening docString: `"""`

- first text line:     This is a one line description of the bbue CDA Module.

### Environment

 System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.1 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
    gatsby-remark-prismjs: ^3.5.10 => 3.5.10
    gatsby-source-filesystem: ^2.3.23 => 2.3.23
    gatsby-transformer-remark: ^2.8.27 => 2.8.27
  npmGlobalPackages:
    gatsby-cli: 2.12.67

### PR DESCRIPTION
**Pull request by pieh**
## Description

This fixes line highlighting with other multiline token spans other than just `plain-text` (so for example various form of multiline comments, like triple quotes in python or `/*`, `*/` in js).

I added test case for it.

## Related Issues

Fixes #26079

### CODE REVIEW

File: packages/gatsby-remark-prismjs/src/directives.js [hunk 1]
```diff
@@ -109,8 +109,8 @@ module.exports = function highlightLineRange(code, highlights = []) {
   if (highlights.length > 0 || HIGHLIGHT_DIRECTIVE.test(code)) {
     // HACK split plain-text spans with line separators inside into multiple plain-text spans
     // separated by line separator - this fixes line highlighting behaviour for jsx
```
Comment (laurieontech) [inline packages/gatsby-remark-prismjs/src/directives.js:111]: Is this comment still accurate?

Comment (pieh) [reply packages/gatsby-remark-prismjs/src/directives.js:111]: Other than mentioning just `plain-text`, it is accurate, I will update it to mentioned "for example plain-text" and list couple of others token types.

Great catch! Thanks!

**Comment by wardpeet** [comment]
Successfully published:
 - gatsby-remark-prismjs@3.5.11
