### PR TITLE
Temp fix for scroll behavior problems

### LINKED ISSUE #7454: [v2] Navigating to previously visited pages with <Link> retains scroll position
## Description

Clicking on a `<Link>` in v2 (111) appears to scroll you to a previous scroll position (if it exists) rather than scroll you to the top.

### Steps to reproduce

I've been able to recreate this in `gatsby-starter-default`:
https://gatsby-v2-beta-111-scroll.netlify.com/

(The only change is artificial padding added to the first page above the `/page-2` `<Link>`)

- Visit https://gatsby-v2-beta-111-scroll.netlify.com/
- On the home page, scroll down to the `page-2` link and click it 
- On `page-2`, now click 'Go back to the homepage'

### Expected result

You are taken back to the top of the home page

### Actual result

You are taken back to the home page but scrolled down the page (at the exact same position you were when you linked the `page-2` link)

### Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v8.11.1/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.111
    gatsby-plugin-manifest: next => 2.0.2-beta.6
    gatsby-plugin-offline: next => 2.0.0-beta.9
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### Other notes

- This behaviour doesn't occur on the v1 starter. 
- I understand that there was a switch to `reach-router`, could this be linked?
- Manually adding `window.scrollTo(0, 0) / window.scroll({top: 0})` in page `componentDidMount` had no effect, though it would work after wrapping it in an arbitrary `setTimeout` - though this yields an initial flash of content in the wrong scroll position.

By default, I imagine the desired behaviour would be for all clicked `<Link>` elements to scroll you to the top of that target page and that only using the browser back / forward buttons would retain scroll position state in this manner.

### PR DESCRIPTION
**Pull request by KyleAMathews**
Closes #7454

### CODE REVIEW

File: packages/gatsby-link/src/index.js [hunk 1]
```diff
@@ -151,6 +156,9 @@ class GatsbyLink extends React.Component {
               }
             }
 
+            // Temp hack while awaiting https://github.com/reach/router/issues/119
+            window.__navigatingToLink = true
```
Comment (pieh) [inline packages/gatsby-link/src/index.js]: I think this should be in https://github.com/gatsbyjs/gatsby/blob/5f09cc377d06e51df5b39abc2fb5300853907c6b/packages/gatsby/cache-dir/navigation.js#L50 rather than `Link` component to cover programmatic navigation

File: packages/gatsby-link/src/index.js [hunk 2]
```diff
@@ -4,6 +4,11 @@ import React from "react"
 import { Link, Location } from "@reach/router"
 import { parsePath } from "gatsby"
 
+// Temp hack while awaiting https://github.com/reach/router/issues/119
+if (typeof window !== `undefined`) {
+  window.__navigatingToLink = false
+}
+
```
Comment (pieh) [inline packages/gatsby-link/src/index.js]: I would move this to https://github.com/gatsbyjs/gatsby/blob/5f09cc377d06e51df5b39abc2fb5300853907c6b/packages/gatsby/cache-dir/navigation.js#L113

File: packages/gatsby-link/src/index.js (hunk 1 above)
Comment (KyleAMathews) [reply packages/gatsby-link/src/index.js]: and yeah, replacing shouldn't update the scroll
