### PR TITLE
fix(gatsby): do not fail on 3rd-party schemas with relay-classic support

### LINKED ISSUE #30199: Error: Schema must contain uniquely named types but contains multiple types named "GRVSCStylesheet"
## Description

Just migrated to Gatsby 3 (3.0.4) and getting the following error after every save in development mode. The error appears in the terminal and Gatsby gets stuck on 'building schema' without ever progressing. 

```zsh
Missing onError handler for invocation 'building-schema', error was 'Error: Schema must contain
 uniquely named types but contains multiple types named "GRVSCStylesheet".'. Stacktrace was
'Error: Schema must contain uniquely named types but contains multiple types named
"GRVSCStylesheet".
    at new GraphQLSchema (/Users/Admin/Documents/website/node_modules/graphql/type/schema.js:194:15)
    at SchemaComposer.buildSchema (/Users/Admin/Documents/website/node_modules/graphql-compose/lib/SchemaComposer.js:179:12)
    at buildSchema (/Users/Admin/Documents/website/node_modules/gatsby/src/schema/schema.js:77:33)
    at build (/Users/Admin/Documents/website/node_modules/gatsby/src/schema/index.js:105:18)
    at buildSchema (/Users/Admin/Documents/website/node_modules/gatsby/src/services/build-schema.ts:19:3)'
```

### Steps to reproduce

Run Gatsby in development mode, make a change to a file and save.

### Expected result

Pages should be re-compiled with the reflected changes.

### Actual result

Error message displayed as above.

### Environment

System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    npm: 7.6.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.82
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4
    gatsby-plugin-feed: ^3.0.0 => 3.0.0
    gatsby-plugin-image: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^3.0.1 => 3.0.1
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^4.0.0 => 4.0.0
    gatsby-remark-vscode: ^3.2.0 => 3.2.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-graphql: ^3.0.0 => 3.0.0
    gatsby-transformer-remark: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0

### PR DESCRIPTION
**Pull request by vladar**
## Description

Workaround for an edge case typical for Relay Classic-compatible schemas. It is easier to explain with an example.

For example, GitHub API fed to `gatsby-source-graphql` contains this piece:

```graphql
type Query {
  github: GitHub
}
type GitHub {
  relay: Query
}
```

During the initial schema building, we replace the third-party `Query` type with our own `Query` type. `graphql-compose` does that by mutating the original `GraphQLSchema` instance of the third-party schema.

**The problem:**
When we rebuild the schema our own instance of `Query` type from the previous build leaks into the new schema (via mutated third-party `GraphQLSchema` instance) and produces the dreaded error:

```
Schema must contain uniquely named types but contains multiple types named "Foo"
```

In theory, it should not happen because we mutate third-party schema again when rebuilding and replace the old `Query` type with the new one here:
https://github.com/gatsbyjs/gatsby/blob/33aa3570ecb38ee2df09f1ad6de1be5fed13c156/packages/gatsby/src/schema/schema.js#L842-L846

But behavior change in `graphql-compose@7` introduced a new codepath which made it possible. It happens indirectly when creating a composer for type `GitHub` here:

https://github.com/gatsbyjs/gatsby/blob/33aa3570ecb38ee2df09f1ad6de1be5fed13c156/packages/gatsby/src/schema/schema.js#L788-L794

`processThirdPartyTypeFields` would have replaced the old `Query` type with the new one but `createTC` kicks in first and recursively creates type composers for all nested types, including the old `Query` via `relay` field.

To prevent this we must make sure that fields of the `GitHub` type are initialized lazily. Then `graphql-compose` won't traverse everything recursively when creating type composer and `processThirdPartyTypeFields` will have a chance to replace the old `Query` type with the new one before bad type composer for the old `Query` type is created.

This is a mess and was extremely hard to debug. So I've decided to document it better here for a paper trail in case we hit related problems in the future 😒

Fixes #30199

### CODE REVIEW

File: packages/gatsby/src/schema/schema.js [hunk 1]
```diff
@@ -830,21 +856,24 @@ const resetOverriddenThirdPartyTypeFields = ({ typeComposer }) => {
...
+}) => {
   // Fix for types that refer to Query. Thanks Relay Classic!
-  typeComposer.getFieldNames().forEach(fieldName => {
+  const fields = type.getFields()
+  Object.keys(fields).forEach(fieldName => {
     // Remove customization that we could have added via `createResolvers`
     // to make it work with schema rebuilding
-    const field = typeComposer.getField(fieldName)
-    const fieldType = field.type.getTypeName()
+    const fieldType = String(fields[fieldName].type)
```
Comment (wardpeet) [inline packages/gatsby/src/schema/schema.js:869]: Is this not always a string?

Comment (vladar) [reply packages/gatsby/src/schema/schema.js:869]: No, it's actually an instance of GraphQL type (possibly with `nonNull` and `listOf` wrappers). But those have toString method that gets printed to something like `[GitHub!]`

File: packages/gatsby/src/schema/__tests__/rebuild-schema.js [hunk 2]
```diff
@@ -77,24 +79,36 @@ const deleteNodeAndRebuild = async node => {
...
-    fields: {
-      external: {
-        type: new GraphQLObjectType({
-          name: `ExternalType`,
-          fields: {
-            externalFoo: {
-              type: GraphQLString,
-              resolve: parentValue =>
-                `${parentValue}.ExternalType.externalFoo.defaultResolver`,
+    fields: () => {
```
Comment (pieh) [inline packages/gatsby/src/schema/__tests__/rebuild-schema.js:82]: Is this to simulate the what the actual workaround is doing (using thunk/lazy fields)? Shouldn't we actually have "un-thunked" fields here (as before the PR) to actually test that workaround works?

Comment (vladar) [reply packages/gatsby/src/schema/__tests__/rebuild-schema.js:82]: It doesn't matter actually because of `assertValidSchema(schema)` below that will resolve all thunks effectively anyway (it traverses the full schema).

And the funny part is that it was a missing piece when I was trying to reproduce the issue in tests. Tests were just refusing to fail. And then I had to do another pass of debugging just to figure out that in the real-world situation we have `extracting queries` step between schema builds.

And this step calls this `assertValidSchema` under the hood and that's how the stage gets set for the actual bug. It is not reproducible without it.

File: packages/gatsby/src/schema/schema.js [hunk 3]
```diff
@@ -785,12 +789,34 @@ const addThirdPartySchemas = ({
         type.name !== `Date` &&
         type.name !== `JSON`
       ) {
+        const isCompositeType =
+          type instanceof GraphQLObjectType ||
+          type instanceof GraphQLInterfaceType
```
Comment (pieh) [inline packages/gatsby/src/schema/schema.js:794]: Do we need to handle `GraphQLInputObjectType`? Was just checking https://github.com/graphql/graphql-js/blob/00ef21739731d1ea7fc61e4294b5bec5a2e535f2/src/type/definition.js#L1471 for type ... types that make use of `fields` but I lack context wether same (or similar) problem might apply to input type

File: packages/gatsby/src/schema/schema.js [hunk 4]
```diff
@@ -785,12 +789,34 @@ const addThirdPartySchemas = ({
         type.name !== `Date` &&
         type.name !== `JSON`
       ) {
+        const isCompositeType =
```
Comment (pieh) [inline packages/gatsby/src/schema/schema.js:792]: NIT: can we rename it to 
```suggestion
        const typeHasFields =
```
or something like that?

There is `GraphQLCompositeType` and some utils for it, which means something else so I'd like to avoid using "composite" description here that differs from what `graphql-js` means by it ( ref https://github.com/graphql/graphql-js/blob/00ef21739731d1ea7fc61e4294b5bec5a2e535f2/src/type/definition.js#L289-L308 )

File: packages/gatsby/src/schema/schema.js (hunk 3 above)
Comment (vladar) [reply packages/gatsby/src/schema/schema.js:794]: We need this fix only for types that may carry `Query` type in one of their fields (that's the only offender). Inputs cannot contain this type.

File: packages/gatsby/src/schema/schema.js (hunk 4 above)
Comment (vladar) [reply packages/gatsby/src/schema/schema.js:792]: Oh, yeah. I forgot that union is also considered to be a `composite` type.

**Review by pieh — APPROVED** [review]
🙏
