### PR TITLE
fix(gatsby): Panic when root config is a function

### LINKED ISSUE #16265: Warn if function is used in root site config
## Description

If you write a gatsby-config.js in the root of your site with the function style, it will fail in weird ways because plugins aren't added when you think they are.

(I'm on my phone and accidentally deleted the rest of the template I'm sorry 😭)

# Solution 

In bootstrap/index.js we should add a typeof config === function check on the root config before it is passed in to loadThemes and reporter.panic with a nice error message if it is a function

### PR DESCRIPTION
**Pull request by cephalization**
Not 100% sure if or where tests for this should be written, I could not find any other tests for bootstrap's index. I did use gatsby-dev to test that this change works however and it appears to do so.

Additionally, not sure if we want this panic to occur on configs that are still using experimental configs _AND_ non experimental configs so it does it before loading either config.

## Description

When bootstrap loads the root config, throw a panic if the config is of type `Function`.

## Related Issues

Fixes #16265

### CODE REVIEW

File: packages/gatsby/src/bootstrap/index.js [hunk 1]
```diff
@@ -75,6 +75,12 @@ module.exports = async (args: BootstrapArgs) => {
     getConfigFile(program.directory, `gatsby-config`)
   )
 
+  if (typeof config === `function`) {
+    report.panic(
+      `Custom gatsby-config as a Function is not supported in site root.`
+    )
+  }
+
   // theme gatsby configs can be functions or objects
```
Comment (cephalization) [inline packages/gatsby/src/bootstrap/index.js]: Should we update this comment as well?

File: packages/gatsby/src/bootstrap/index.js [hunk 2]
```diff
@@ -75,6 +75,12 @@ module.exports = async (args: BootstrapArgs) => {
     getConfigFile(program.directory, `gatsby-config`)
   )
 
+  if (typeof config === `function`) {
+    report.panic(
+      `Custom gatsby-config as a Function is not supported in site root.`
```
Comment (ChristopherBiscardi) [inline packages/gatsby/src/bootstrap/index.js]:
```suggestion
      `A gatsby-config that exports a function can only be used as a theme and not run directly.
If you are trying to run a theme directly, use the theme in an example site or starter instead and run that site to test.
If you are in the root gatsby-config.js for your site, change the export to be an object and not a function as functions are not supported in the root gatsby-config.`
```

File: packages/gatsby/src/bootstrap/index.js (hunk 1 above)
Comment (ChristopherBiscardi) [reply packages/gatsby/src/bootstrap/index.js]: This seems fine. What would you want to update it to?

Comment (cephalization) [reply packages/gatsby/src/bootstrap/index.js]: We now panic and crash if the `gatsby-config` is a function, this seems to be the opposite of what the comment says. Unless the root config is not considered a theme config in which case I misunderstood

File: packages/gatsby/src/bootstrap/index.js (hunk 2 above)
Comment (cephalization) [reply packages/gatsby/src/bootstrap/index.js]: This is a much more helpful message haha, thanks!

**Comment by KyleAMathews** [comment]
Could you convert the error to be a structured error? E.g. https://github.com/gatsbyjs/gatsby/pull/15619

We're switching all errors over and we shouldn't add new non-structured errors.

To convert it, you need to add an error entry to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/structured-errors/error-map.js and then reference that in the error object you pass into `report.panic`.

Thanks! Can answer any questions you have. We need to create a doc page for this as well.

**Comment by cephalization** [comment]
> Could you convert the error to be a structured error? E.g. #15619
> 
> We're switching all errors over and we shouldn't add new non-structured errors.
> 
> To convert it, you need to add an error entry to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/structured-errors/error-map.js and then reference that in the error object you pass into `report.panic`.
> 
> Thanks! Can answer any questions you have. We need to create a doc page for this as well.

I can give it a shot 👍

**Comment by KyleAMathews** [comment]
Thanks!

--
Kyle Mathews

Blog: http://bricolage.io
Twitter: http://twitter.com/kylemathews

**Comment by cephalization** [comment]
Does the id of the structured error just iterate off of the last error id?

**Comment by KyleAMathews** [comment]
The errors are pretty random actually :-D

Part of the goal of structured errors is that people can google the numbers and find something specific to the error. So it doesn't really matter what you pick as long as it isn't the same as another error and it isn't a "common" number e.g. 123456.

Incremented IDs tend to come up when someone is doing a PR converted unstructured errors and converts several together. There's no meaning otherwise.

**Comment by cephalization** [comment]
2019-07-31 20_12_59-gatsby-config js - gatsby-test - Visual Studio Code

File: packages/gatsby-cli/src/structured-errors/error-map.js [hunk 3]
```diff
@@ -81,6 +81,15 @@ const errorMap = {
     type: `CONFIG`,
     level: `ERROR`,
   },
+  "10126": {
+    text: context =>
+      `A ${
+        context.configName
+      } that exports a function can only be used as a theme and not run directly.\nIf you are trying to run a theme directly, use the theme in an example site or starter instead and run that site to test.\nIf you are in the root gatsby-config.js for your site, change the export to be an object and not a function as functions are not supported in the root gatsby-config.`,
```
Comment (cephalization) [inline packages/gatsby-cli/src/structured-errors/error-map.js]: This is a huge giant line with newline characters because if I just move them to the next line manually I get indentation. I could not use `report.stripIndent` while using structured errors as far as I could tell

**Comment by cephalization** [comment]
Not sure why circle is choking, will look into it tomorrow

File: packages/gatsby/src/bootstrap/index.js [hunk 4]
```diff
@@ -75,6 +75,16 @@ module.exports = async (args: BootstrapArgs) => {
     getConfigFile(program.directory, `gatsby-config`)
   )
 
+  // The root config cannot be exported as a function, only theme configs
+  if (typeof config === `function`) {
+    report.panic({
+      id: `10126`,
+      context: {
+        configName: `gatsby-config`,
```
Comment (KyleAMathews) [inline packages/gatsby/src/bootstrap/index.js]: This should pass in the path to the config file as well so it's clear which one to use.

**Comment by cephalization** [comment]
Screen Shot 2019-08-01 at 6 42 48 AM
