### PR TITLE
fix(gatsby): Fix OOM from telemetry storing too much

### LINKED ISSUE #22717: JavaScript heap out of memory with gatsby +2.20.6, not with 2.20.5
Just updated all dependencies I have, since I had them halted due to https://github.com/gatsbyjs/gatsby/issues/6291 that now should be solved

Done in 2 sites
- one is building well
- the other (much lower number of images) is crashing with an out-of-memory error

If I get back to the previous gatsby version `2.20.9 => 2.15.15` (the other packages left updated) I can build as usual

EDIT: with gatsby `2.19.5` it also builds well
EDIT: with gatsby `2.20.0` it also builds well
EDIT: with gatsby `2.20.5` it also builds well
EDIT: with gatsby `2.20.6` it fails

Features added in 2.20.6:
gatsby-telemetry: Make build collect GraphQL/Sift query data for telemetry (#22540) (1bec140)
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#2206-2020-03-25

EDIT2: It also fails when building it on a desktop computer (more powerful, but not at all hugely more powerful)

```
  System (laptop):
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

The output
```
gatsby clean
info Deleting .cache, public
info Successfully deleted directories
gatsby build
success open and validate gatsby-configs - 0.065s
warn Plugin gatsby-theme-kuworking-core is not compatible with your gatsby version 2.20.7 - It requires gatsby@2.20.9
success load plugins - 1.482s
success onPreInit - 0.010s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.038s
success copy gatsby files - 0.058s
success onPreBootstrap - 0.012s
success createSchemaCustomization - 0.007s
success source and transform nodes - 10.253s
success building schema - 0.268s
success createPages - 17.776s
success createPagesStatefully - 0.164s
success onPreExtractQueries - 0.004s
success update schema - 0.291s
success extract queries from components - 0.290s
success write out requires - 0.012s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.353s
success onPostBootstrap - 0.363s
⠀
info bootstrap finished - 34.030 s
⠀
success Building production JavaScript and CSS bundles - 19.220s
success Rewriting compilation hashes - 0.004s
[============================]   50.715 s 51/51 100% Generating image thumbnails
[=====================       ]   31.952 s 223/287 78% run queries

<--- Last few GCs --->

[16528:00000148B6F71A50]    66340 ms: Scavenge 1352.0 (1421.4) -> 1352.0 (1422.4) MB, 1.1 / 0.0 ms  (average mu = 0.202, current mu = 0.137) allocation failure
[16528:00000148B6F71A50]    66342 ms: Scavenge 1352.6 (1422.4) -> 1352.6 (1422.9) MB, 0.8 / 0.0 ms  (average mu = 0.202, current mu = 0.137) allocation failure
[16528:00000148B6F71A50]    66344 ms: Scavenge 1353.0 (1422.9) -> 1352.9 (1423.9) MB, 0.9 / 0.0 ms  (average mu = 0.202, current mu = 0.137) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x03ee07a1e6e9 <JSObject>
    0: builtin exit frame: stringify(this=0x03ee07a11a21 <Object map = 000002B5265042A9>,0x03d95c0826f1 <undefined>,0x03d95c0826f1 <undefined>,0x030d24fa6a69 <Object map = 000001DF654E3681>,0x03ee07a11a21 <Object map = 000002B5265042A9>)

    1: arguments adaptor frame: 1->3
    2: query [000003BA81EE21E1] [C:\CODING\kuworking\node_modules\gatsby\dist\query\graphql-runner.js:~116] [pc=000000D04D...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF61204C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF612027416 node::MakeCallback+4534
 3: 00007FF612027D90 node_module_register+2032
 4: 00007FF61234189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6123417CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF612527F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF61251EF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF61251D5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF612526317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF612526396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6126502BB v8::internal::Factory::AllocateRawWithImmortalMap+59
12: 00007FF612652D6D v8::internal::Factory::NewRawTwoByteString+77
13: 00007FF612697F5B v8::internal::interpreter::BytecodeArrayIterator::done+5579
14: 00007FF6124EA8EF v8::internal::interpreter::operator<<+55551
15: 00007FF6124E8852 v8::internal::interpreter::operator<<+47202
16: 00007FF6124E5DF9 v8::internal::interpreter::operator<<+36361
17: 00007FF6124E8F6D v8::internal::interpreter::operator<<+49021
18: 00007FF6124E5DF9 v8::internal::interpreter::operator<<+36361
19: 00007FF6124E8F6D v8::internal::interpreter::operator<<+49021
20: 00007FF6124E5DF9 v8::internal::interpreter::operator<<+36361
21: 00007FF6124E6E8A v8::internal::interpreter::operator<<+40602
22: 00007FF6124E976E v8::internal::interpreter::operator<<+51070
23: 00007FF6124E6C8D v8::internal::interpreter::operator<<+40093
24: 00007FF6124E3CC8 v8::internal::interpreter::operator<<+27864
25: 00007FF612712256 v8::internal::WasmJs::Install+231750
26: 00007FF61271214B v8::internal::WasmJs::Install+231483
27: 000000D04BFDC721
```

And the package.json

```
{
  "dependencies": {
    "@openfonts/kulim-park_latin": "^0.0.1",
    "@stripe/stripe-js": "1.3.0",
    "gatsby": "2.20.9",
    "gatsby-theme-kuworking-core": "0.1.67",
    "react": "16.13.1",
    "react-beautiful-dnd": "13.0.0",
    "react-dom": "16.13.1",
    "webfontloader": "1.6.28"
  },
  "devDependencies": {
    "babel-eslint": "10.1.0",
    "eslint": "6.8.0",
    "eslint-config-prettier": "6.10.1",
    "eslint-config-standard": "14.1.1",
    "eslint-plugin-import": "2.20.2",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-prettier": "3.1.2",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-react": "7.19.0",
    "eslint-plugin-standard": "4.0.1",
    "prettier": "2.0.2"
  },
  "resolutions": {
    "**/@emotion/core": "10.0.28",
    "**/@emotion/styled": "10.0.27",
    "**/@mdx-js/mdx": "1.5.8",
    "**/@mdx-js/react": "1.5.8",
    "theme-ui": "0.3.1"
  },
}
```

I presume it will be difficult to create a repo that reproduces this, since the other site has very similar dependencies and doesn't fail

But while I'm trying to figure it out, perhaps someone can give me some directions of where to go

### PR DESCRIPTION
**Pull request by freiksenet**
## Description

Fixes #22717, #22691

### CODE REVIEW

File: packages/gatsby/src/query/graphql-runner.ts [hunk 1]
```diff
@@ -164,9 +165,20 @@ export default class GraphQLRunner {
...
         statsQuery = statsQuery.body
       }
-      this.stats.uniqueOperations.add(`${statsQuery}${JSON.stringify(context)}`)
-
-      this.stats.uniqueQueries.add(statsQuery)
+      this.stats.uniqueOperations.add(
+        crypto
+          .createHash(`sha1`)
+          .update(statsQuery)
+          .update(JSON.stringify(context))
```
Comment (sidharthachatterjee) [inline packages/gatsby/src/query/graphql-runner.ts:172]: We might not need the JSON.stringify anymore since

Comment (pvdz) [reply packages/gatsby/src/query/graphql-runner.ts:172]: This would also break on circular references (for the sake of creating a hash).

Can we either apply Sid's suggestion or at least use `v8.serialize()` for this? (That does support circular references, and a larger payload, although I certainly hope that's never an issue in this step)
