### PR TITLE
fix(gatsby-source-contentful): Add contentful_id field recursively

### LINKED ISSUE #15426: gatsby-source-contentful not adding contentful_id to all nodes
## Description

The `gatsby-source-contentful` [fixIds](https://github.com/gatsbyjs/gatsby/blob/c4a7c40d63538704f8964cdeb1df8a04285e9b21/packages/gatsby-source-contentful/src/normalize.js#L57-L67) method is recursively "fixing" contentful node ids, but only adding a `contentful_id` field one level deep.

### Steps to reproduce

Create a new gatsby site with `gatsby-source-contentful`. In Contentful, create a new content type with a Rich Text field, then create a new entry with an embedded asset.

### Expected result

When querying the rich text json in gatsby, the embedded asset should have a `contentful_id` field.

### Actual result

The embedded asset does not have a `contentful_id` field, but the id has been prefixed with a `c` (see the screenshot below).

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 5.0.7 - /usr/local/bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 62.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.3 => 2.13.3 
    gatsby-image: ^2.2.4 => 2.2.4 
    gatsby-plugin-sharp: ^2.2.2 => 2.2.2 
    gatsby-source-contentful: ^2.1.6 => 2.1.6 
    gatsby-transformer-remark: ^2.6.0 => 2.6.0 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1 

image

### PR DESCRIPTION
**Pull request by TuckerWhitehouse**
## Description

The gatsby-source-contentful [fixIds](https://github.com/gatsbyjs/gatsby/blob/c4a7c40d63538704f8964cdeb1df8a04285e9b21/packages/gatsby-source-contentful/src/normalize.js#L57-L67) method is recursively "fixing" contentful node ids, but only adding a contentful_id field one level deep.

## Related Issues

Fixes #15426

### CODE REVIEW

**Comment by vladar** [comment]
Published in `gatsby-source-contentful@2.1.73`

File: packages/gatsby-source-contentful/src/normalize.js [hunk 1]
```diff
@@ -54,17 +53,25 @@ const fixId = id => {
...
-      contentful_id: object.sys.id,
-    },
-  }
-}
+    if (_.isArray(val)) {
+      return _.toArray(fixIds(val))
+    }
+    if (_.isPlainObject(val)) {
+      return fixIds(val)
+    }
```
Comment (vladar) [inline packages/gatsby-source-contentful/src/normalize.js]: This should account for circular references otherwise we'll get stack overflow errors. Probably also need a test with circular references.

**Comment by dial3x** [comment]
This fix broke my code. We use some circular references. Perhaps it should be an option instead of the default?
```
"gatsby-source-contentful" threw an error while running the sourceNodes lifecycle:
Maximum call stack size exceeded
```

**Comment by bsgreenb** [comment]
Correct, I've been able to repro that upgrading to this version causes Maxmimum Callstack issue.

**Comment by pvdz** [comment]
--> #20313
