### PR TITLE
fix(gatsby-dev-cli): chmod gatsby bin on copy

### LINKED ISSUE #18809: Mark gatsby binary as an executable in gatsby-dev-cli
When `gatsby-dev-cli` copies over files in a local project, it doesn't mark the `gatsby` binary in `node_modules/.bin` as an executable which causes running `yarn gatsby develop` to fail. 

We fix this by running `chmod +x node_modules/.bin/gatsby` but it would be nice to get to the root of this issue and fix it in `gatsby-dev-cli`

### PR DESCRIPTION
**Pull request by blainekasten**
## Description

The issue is that yarn and npm will chmod a bin file on install. when gatsby-dev copies files over, the copied file needs to be chmod'd again.

Also in here, I noticed that gatsby-dev was copying over `__mocks__` files, so those were added to the ignore list.

## Related Issues

Fixes #18809

### CODE REVIEW

File: packages/gatsby-dev-cli/src/watch.js [hunk 1]
```diff
@@ -147,6 +156,7 @@ async function watch(
     /\.git/i,
     /\.DS_Store/,
     /[/\\]__tests__[/\\]/i,
+    /[/\\]__mocks__[/\\]/i,
```
Comment (pieh) [inline packages/gatsby-dev-cli/src/watch.js]: Nice!

**Comment by sidharthachatterjee** [comment]
I can't express just _how_ happy I am to see this fixed! Thank you so much @blainekasten ❤️
