### PR TITLE
fix(gatsby): Fix SSL for develop

### LINKED ISSUE #24272: SSL errors when using `gatsby develop --https`
##  Description

When running `gatsby develop --https` both with without `--cert-file`/`--key-file` SSL does not work in Firefox, Chrome or Safari (screenshots below).

### Steps to reproduce

1. I've created a minimal reproduction in https://github.com/patrickarlt/gatsby-ssl-issue-reproduction. This is based off the default starter with the latest version of Gatsby.
2. `npm install`
3. `npm run start:devcert` this starts the local dev server and automatically creates SSL certs.
4. Observe failures.
5. Install [`mkcert`](https://github.com/FiloSottile/mkcert), for Mac this means:
   * `brew install mkcert`
   * `brew install nss`
   * `mkcert install`
   * `mkcert localhost`
6. `npm run start:local-certs` this starts the dev server with the local certs from `mkcert`
7. Observe failures.

In order to check that the certs are valid you can use [`http-server`](https://www.npmjs.com/package/http-server):

* `npm i -g http-server`
* `http-server . -C localhost.pem -K localhost-key.pem -S -a localhost`

This displays the directory structure of our project tin the browser over `https://...` note the lock icon in Chrome:

### Expected result

The server should successfully serve pages over `https://...`.

### Actual result

Browsers produce SSL errors.

### Environment

**Gatsby**

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 77.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.3 => 2.22.3
```

**OpenSSL**

```
$ openssl version
LibreSSL 2.6.5
```

**mkcert**

```
$ brew info mkcert 
mkcert: stable 1.4.1 (bottled)
Simple tool to make locally trusted development certificates
https://github.com/FiloSottile/mkcert
/usr/local/Cellar/mkcert/1.4.1 (6 files, 5.3MB) *
  Poured from bottle on 2020-04-08 at 18:45:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mkcert.rb
==> Dependencies
Build: go ✘
==> Analytics
install: 3,827 (30 days), 11,641 (90 days), 47,679 (365 days)
install-on-request: 3,351 (30 days), 10,186 (90 days), 40,390 (365 days)
build-error: 0 (30 days)
```

**nss**

```
$ brew info nss
nss: stable 3.52 (bottled)
Libraries for security-enabled client and server applications
https://developer.mozilla.org/docs/NSS
/usr/local/Cellar/nss/3.52 (225 files, 34.1MB) *
  Poured from bottle on 2020-05-19 at 16:52:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nss.rb
==> Dependencies
Required: nspr ✔
==> Analytics
install: 38,963 (30 days), 105,774 (90 days), 394,028 (365 days)
install-on-request: 8,110 (30 days), 19,022 (90 days), 62,334 (365 days)
build-error: 0 (30 days)
```

### PR DESCRIPTION
**Pull request by mxstbr**
Should fix #24272 again!

### CODE REVIEW

File: packages/gatsby/src/commands/develop.ts [hunk 1]
```diff
@@ -168,6 +150,26 @@ module.exports = async (program: IProgram): Promise<void> => {
...
+  })
+
+  const developProcess = new ControllableScript(`
+    const cmd = require(${JSON.stringify(developProcessPath)});
+    const args = ${JSON.stringify({
+      ...program,
+      port: developPort,
+      proxyPort,
+      // Don't pass SSL options down to the develop process, it should always use HTTP
+      ssl: null,
```
Comment (blainekasten) [inline packages/gatsby/src/commands/develop.ts:168]: can you explain how this fixes ssl? haha, it _looks_ like it does the opposite 😆

Comment (sidharthachatterjee) [reply packages/gatsby/src/commands/develop.ts:168]: I think the child process needs to be HTTP regardless whereas the parent one (proxy) is SSL
