### PR TITLE
fix(gatsby): print childOf directive for implicit child fields

### LINKED ISSUE #19674: gatsby-plugin-schema-snapshot Issue with Contentful LongText fields
## Description

I recently tried using `gatsby-plugin-schema-snapshot` to create an explicit snapshot of the schema for a project that uses `gatsby-source-contentful`. This works as expected with the exception of LongText fields in Contentful. Per the [documentation](https://www.gatsbyjs.org/packages/gatsby-source-contentful/?=contentful#a-note-about-longtext-fields) LongText fields should actually be an object rather than a string. 

Generated type using `gatsby-plugin-schema-snapshot` for a field named `body` which is a LongText field in Contentful. 

```
type contentfulPostBodyTextNode implements Node @dontInfer {
  body: String
}
```
This causes the following part of the query to fail if the actual content doesn't exist: 

```
 body {
  childMarkdownRemark {
    timeToRead
    html
    excerpt(pruneLength: 320)
  }
}
```

### Steps to reproduce
1. Select a project that uses at least one LongText field in Contentful
2. Install `gatsby-plugin-schema-snapshot` and add it to the `gatsby-config.js`
3. Run `gatsby build` and view the snapshot file created
4. See how the LongText field is defined as a string rather than an object

### PR DESCRIPTION
**Pull request by vladar**
## Description

Fixes a bug with schema printing of inferred `childOf` directive. Before this PR if we print a schema with infered child fields (e.g. `File.childImageSharp`) it won't include `childOf` directive:

```graphql
type ImageSharp implements Node @dontInfer {
  id: ID!
}
```

After this PR it correctly prints this:
```graphql
type ImageSharp implements Node @dontInfer @childOf(types: ["File"]) {
  id: ID!
}
```

This fixed variant will correctly wotk in Gatsby v3. The variant before this PR will fail to work in Gatsby v3 (the printed schema snapshot won't add the `File.childImageSharp` field).

### ~Potentially a breaking change :/~

Worked around breaking change via #28656

<details>
<summary>
See details (no longer actual)
</summary>
Requires a bit of investigation. To illustrate a possible break. With this change, we automatically apply the `childOf` extension (instead of inferring child fields):

```graphql
type Foo implements Node @childOf(types: ["Bar", "Baz"], many: true) {
  id: ID!
}
```

The `many` argument here is what is problematic. Before this change (with simple inference) we could get these two types (at least theoretically):

```graphql
type Bar {
  childFoo: Foo
}
type Baz {
  childrenFoo: [Foo]
}
```

so in one case - singular `Bar.childFoo` in the other case - array `Baz.childrenFoo`. After this change, we will always have both singular or both arrays. Mixing is not allowed with this directive.

The `many` argument applies to all parent types. Not sure if it is intentional or an oversight.

## Ways to fix this

1. Suggested by @pieh : Always add both `child{Field}` and `children{Field}` to the schema and deprecate `many` option altogether. Wih this change `child{Field}` will always return the first child (as listed in node `children` array)

2. Support the new syntax in `childOf` directive where we can define `many` per type. Something like:

```graphql
type Foo implements Node @childOf(parents: [{name: "Bar", many: false}, { name: "Baz", many: true }]) {
  id: ID!
}
```
</details>

## Related issues 

Fixes #19674

### CODE REVIEW

File: packages/gatsby/src/schema/schema.js [hunk 1]
```diff
@@ -1046,9 +1055,15 @@ const addImplicitConvenienceChildrenFields = ({
...
-    typeComposer.addFields(createChildField(typeName))
+    // Set `@childOf` extension automatically
+    // This will cause convenience children fields like `childImageSharp`
+    // to be added in `addConvenienceChildrenFields` method.
+    // Also required for proper printing of the `@childOf` directive in the snapshot plugin
+    if (!childOfExtension?.types) {
+      childOfExtension = { types: [] }
+    }
+    childOfExtension.types.push(parentTypeName)
+    childTypeComposer.setExtension(`childOf`, childOfExtension)
```
Comment (vladar) [inline packages/gatsby/src/schema/schema.js:1066]: The essence of this PR: instead of adding fields directly we add the `childOf` directive here. And fields are always added in a single place now - where this directive is processed (in `addConvenienceChildrenFields`):

https://github.com/gatsbyjs/gatsby/blob/76a3b57455704f72778b41e01f00ed1b61cc6622/packages/gatsby/src/schema/schema.js#L972-L975

File: packages/gatsby/src/schema/schema.js [hunk 2]
```diff
@@ -1046,9 +1055,15 @@ const addImplicitConvenienceChildrenFields = ({
...
-
-    typeComposer.addFields(createChildrenField(typeName))
-    typeComposer.addFields(createChildField(typeName))
+    // Set `@childOf` extension automatically
+    // This will cause convenience children fields like `childImageSharp`
+    // to be added in `addConvenienceChildrenFields` method.
+    // Also required for proper printing of the `@childOf` directive in the snapshot plugin
+    if (!childOfExtension?.types) {
+      childOfExtension = { types: [] }
+    }
```
Comment (pieh) [inline packages/gatsby/src/schema/schema.js:1064]: Question - `@childOf` can have either `types` or `mimeTypes` set - https://github.com/gatsbyjs/gatsby/blob/8ff6245f44882d891bc6f291363019047cbdb55f/packages/gatsby/src/schema/extensions/index.js#L58-L85

It has defaultValue set to empty array - but what happens when extension is set programmatically with `schema.buildObjectType` - does this also use that `defaultValue`?

I just wonder if this check might ovverride some extension that omit to define `types`, but do use `mimeTypes`

Comment (pieh) [reply packages/gatsby/src/schema/schema.js:1064]: Alternatively - should newly `childExtension` created here set `mimeTypes` to empty array? too :)

Comment (vladar) [reply packages/gatsby/src/schema/schema.js]: Good catch 👍 Added `mimeTypes` there.

Comment (vladar) [reply packages/gatsby/src/schema/schema.js]: Actually, this causes printer snapshot failures because now `mimeTypes: []` is printed anytime `childOf` is used. I've updated the code. The new version won't add `mimeTypes` by default but will preserve it if it was set for this extension somewhere else.

**Review by pieh — APPROVED** [review]
Looks great! That was quite a journey to get to this point (including other PR(s) on the way heh and possibly some ahead (weird behaviour of `update` option on schema snapshot plugin ;) ).

Let's get this in!
