### PR TITLE
fix(gatsby-transformer-remark): fix plugin conflict causing escaped HTML in headings

### LINKED ISSUE #13608: [gatsby-transformer-remark] Section titles with code in ``s creates escaped HTML <code> tags
## Description

When using the automatic TOC generation from `gatsby-transformer-remark` with markdown section titles that contain code in backticks, the generated TOC heading contains escaped HTML `<code>` tags that show up in the document.  Instead of actually emitting the `<code>` tag in the HTML string, it's escaped and the HTML is rendered as text.

### Steps to reproduce

Create a markdown remark with a heading like this:

```md
## Generating TOCs with `gatsby-transformer-remark`
```

This will generate the following HTML string for the TOC:

`<ul>\n<li><a href=\"/demo/#generating-tocs-with-code-classlanguage-textgatsby-transformer-remarkcode\">Generating TOCs with &#x3C;code class=\"language-text\">gatsby-transformer-remark&#x3C;/code></a></li>\n</ul>`

### Expected result

The `<code>` tag shouldn't be escaped and should be emitted directly

### Actual result

The `<code>` tag is escaped, causing it to be rendered as text rather than as HTML.

### Environment

```

  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.17 => 2.1.17 
    gatsby-cli: ^2.4.8 => 2.4.11 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-feed: ^2.0.14 => 2.0.14 
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.14 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.19 
    gatsby-plugin-offline: ^2.0.11 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.15 => 2.0.22 
    gatsby-plugin-typescript: ^2.0.1 => 2.0.9 
    gatsby-plugin-typography: ^2.2.1 => 2.2.7 
    gatsby-remark-images: ^3.0.1 => 3.0.5 
    gatsby-remark-prismjs: ^3.1.4 => 3.2.4 
    gatsby-source-filesystem: ^2.0.4 => 2.0.22 
    gatsby-source-spotify: ^1.0.1 => 1.0.1 
    gatsby-transformer-csv: ^2.0.4 => 2.0.7 
    gatsby-transformer-json: ^2.1.5 => 2.1.8 
    gatsby-transformer-remark: ^2.1.15 => 2.2.6 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.14 
```

### PR DESCRIPTION
**Pull request by Ameobea**
## Description

 * The `gatsby-remark-prismjs` plugin was causing HTML code to be escaped and rendered as text in TOC entries generated by `gatsby-transformer-remark`.  It generated HTML nodes which the `mdast-util-toc` module flattened into text.  This was fixed upstream in a major version bump.
 * Update the version of `mdast-util-toc` used in `gatsby-transformer-remark` to the latest version in order to fix the issue
   * Set `{ allowDangerousHTML: true }` on calls to `hastToHTML()` and `toHAST()` when building the TOC.  This is required in order to properly render the embedded HTML nodes.
 * Bump `mdast-util-to-hast` to its latest version as well
   * Update one snapshot test that was very slightly broken as a result of this
 * Slight refactor of code in `on-node-create.js` to reduce nesting and clean up control flow
 * Add two snapshot tests to verify that the fix was successful

## Related Issues

Fixes #13608

## Additional Info

This does not address updating the generated anchor link as mentioned here: https://github.com/gatsbyjs/gatsby/issues/13608#issuecomment-495352143

Ideally, another change would be applied to remove the HTML artifacts from the anchor link.

### CODE REVIEW

File: packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap [hunk 1]
```diff
@@ -583,7 +583,9 @@ Object {
 <li><a href=\\"/my%20little%20pony/#second-title\\">second title</a></li>
 </ul>
 </li>
-<li><a href=\\"/my%20little%20pony/#third-title\\">third title</a></li>
+<li>
```
Comment (Ameobea) [inline packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap]: Bumping `mdast-util-to-hast` to its latest version caused this small change in the generated HTML. If this is an unacceptable regression, we can avoid bumping that dependency at this time and just bump `mdast-util-toc` which doesn't regress any existing tests.

Comment (pieh) [reply packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap]: This is tough question - the change in this PR seems like more sane markup than what currently is generated, but it can cause issues to users potentially.

If possible, let's try to keep current markup for now, so we can merge bugfix, without long discussions about this?

File: packages/gatsby-transformer-remark/src/extend-node-type.js [hunk 2]
```diff
@@ -268,48 +268,49 @@ module.exports = (
...
-          toc = hastToHTML(toHAST(tocAst.map))
-        } else {
-          toc = ``
+          return node
         }
-        cache.set(tableOfContentsCacheKey(markdownNode, appliedTocOptions), toc)
-        return toc
+        tocAst.map = addSlugToUrl(tocAst.map)
+
+        toc = hastToHTML(toHAST(tocAst.map, { allowDangerousHTML: true }), {
```
Comment (pvdz) [inline packages/gatsby-transformer-remark/src/extend-node-type.js]: My two cents on this PR...

These two lines are the actual change of this commit. It makes reviewing much easier if either the refactorings (which are good, don't get me wrong) were part of a separate commit, or even PR, and this PR would only contain the actual fix (and relevant test changes). When reviewing this PR, the other changes are literally noise...

No need to change it now. More like a suggestion for a future PR :)

**Comment by pieh** [comment]
I just merged few other remark PRs that cause merge conflicts here - happy to resolve them if you want me to (don't want to push to your branch without asking first :) )

File: packages/gatsby-transformer-remark/src/extend-node-type.js (hunk 2 above)
Comment (Ameobea) [reply packages/gatsby-transformer-remark/src/extend-node-type.js]: I went ahead and got rid of the refactoring changes since I was rebasing anyway.

File: packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap (hunk 1 above)
Comment (Ameobea) [reply packages/gatsby-transformer-remark/src/__tests__/__snapshots__/extend-node.js.snap]: That's understandable.  I've reverted the version bump and reverted these test changes as part of the most recent commit.

**Comment by Ameobea** [comment]
I've taken feedback into account and rebased to the latest master.  Feel free to squash these two commits when merging to produce a cleaner history.

**Comment by Ameobea** [comment]
Hey - just wanted to bump this since it's close to getting off the first page of PRs and I know this is an incredibly active repo.

I've made all requested changes as per code review and reduced the size of the diff.  It's been freshly rebased to the latest master.
