### PR TITLE
[v2] [scripts] feat: create build-examples script and fix some examples

### LINKED ISSUE #7718: Redirect breaks server rendering
## Description

Gatsby does not handle @reach/router's `<Redirect>` component when server rendering, [resulting in a build error on sites that use `<Redirect>`](https://github.com/gatsbyjs/store.gatsbyjs.org/pull/111#issuecomment-413354477). The current workaround is to use the [`noThrow` prop](https://reach.tech/router/api/Redirect) on the redirect.

The fix is to use @reach/router's `isRedirect` method to check errors in `static-entry.js`.

Importing `isRedirect` and replacing [this block](https://github.com/gatsbyjs/gatsby/blob/e2f2ea1eeeaaf1b2fe5ccc95bcbd0f35a0374722/packages/gatsby/cache-dir/static-entry.js#L187-L190) with something like:

```js
  // If no one stepped up, we'll handle it.
  if (!bodyHtml) {
    try {
      bodyHtml = renderToString(bodyComponent)
    } catch (error) {
      // ignore @reach/router redirect errors
      if (!isRedirect(error)) throw error
    }
  }
```

Should fix the issue.

### Steps to reproduce

- Check out the Gatsby Store at this commit https://github.com/gatsbyjs/store.gatsbyjs.org/pull/111/commits/28e69834197efb3d860bb15fe9493b3b66eccc7f
- Run `yarn`
- Run `yarn run build`
- See the build fail with an error

See related PR for workaround: https://github.com/gatsbyjs/store.gatsbyjs.org/pull/111

### Expected result

The site should build

### Actual result

The site build fails with errors.

### Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-beta.7 => 2.0.0-rc.0
    gatsby-image: ^2.0.0-beta.2 => 2.0.0-rc.0
    gatsby-plugin-emotion: ^2.0.0-beta.2 => 2.0.0-rc.0
    gatsby-plugin-react-helmet: ^3.0.0-beta.2 => 3.0.0-rc.0
    gatsby-plugin-sharp: ^2.0.0-beta.2 => 2.0.0-rc.0
    gatsby-source-filesystem: ^2.0.1-beta.3 => 2.0.1-rc.0
    gatsby-transformer-sharp: ^2.1.1-beta.3 => 2.1.1-rc.0
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby-dev-cli: 2.0.0-alpha.80a21f04
```

### PR DESCRIPTION
**Pull request by davidbailey00**
This allows us to test all examples with a single command. Currently failing examples:

- ~~hn (help wanted)~~ no issue? works now
- ~~styleguide~~ fixed
- ~~using-asciidoc~~ fixed (same fix as styleguide)
- ~~using-jss~~ fixed

Fixes #7718

### CODE REVIEW

**Comment by m-allanson** [comment]
Nice, thanks! Want to run the script through https://www.shellcheck.net?

File: scripts/build-examples.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#!/bin/bash
+
+status=""
+
+yarn boostrap &&
```
Comment (DSchau) [inline scripts/build-examples.sh]: 😱 I'll fix this.

Comment (davidbailey00) [reply scripts/build-examples.sh]: ah, whoops...
