### PR TITLE
fix(gatsby): don't show error for proper redirects

### LINKED ISSUE #18665: What is the good method to configure redirection from `/` page to another page ?
How can I redirect `/` to `/page-2/` ?

I have tryed 2 solutions:

# First solution

https://github.com/harobed/gatsby-redirect-on-root-index in `master` branch.

When I execute `npm run develop`, I have this error in Browser console:

```
The route "/" matches both a page and a redirect; this is probably not intentional.
```

but no error after `npm build; npm serve`

# Second solution

https://github.com/harobed/gatsby-redirect-on-root-index in `page-resources-is-undefined` branch.

When I execute `npm run develop`, I have this error in Browser console:

```
TypeError: locationAndPageResources.pageResources is undefined
```

When I execute `npm build; npm serve`, I have this error:

```
NOT FOUND
```

this is not found page, redirection don't work.

# Question

What is the good method to configure redirection on `/` page?

### PR DESCRIPTION
**Pull request by mnurik**
## Description

Changed If statement for showing error message in Development mode, that if there is no such page redirect was intentional.
## Related Issues
Fixes #18665

### CODE REVIEW

File: packages/gatsby/cache-dir/navigation.js [hunk 1]
```diff
@@ -18,9 +18,8 @@ function maybeRedirect(pathname) {
 
   if (redirect != null) {
     if (process.env.NODE_ENV !== `production`) {
-      const pageResources = loader.loadPageSync(pathname)
-
-      if (pageResources != null) {
```
Comment (pvdz) [inline packages/gatsby/cache-dir/navigation.js]: Seems to me like these cases are not identical.

`isPageNotFound` will return `this.pageDb.get(pagePath) && this.pageDb.get(pagePath).notFound === true`
`loadPageSync` will return `this.pageDb.has(pagePath) ? this.pageDb.get(pagePath).payload : undefined`

The `isPageNotFound` is, it seems, referring to an existing page that represents a `404` page (or whatever). Whereas the check here is trying to assert whether we have anything to show for the requested path at all (whether it be content or a 404 page or anything else).

It's not clear to me that it was your intention to change that semantic.

**Comment by pieh** [comment]
I think adding test case for redirects (one that overlap with existing page, and one that tries to redirect from non-existing page) in https://github.com/gatsbyjs/gatsby/tree/master/e2e-tests/development-runtime would help:
 - with establishing how this work
 - making sure we don't introduce regressions

File: packages/gatsby/cache-dir/navigation.js (hunk 1 above)
Comment (mnurik) [reply packages/gatsby/cache-dir/navigation.js]: The thing is here: `loadPageSync` never returned undefined whether you have this file inside pages directory or not. So that means condition always was true and it showed error message.

I ll go with example: lets say I want to have redirect  from `path-1` to `path-2`, and I only have `path-2.js` file under pages folder. It redirected as expected but with error message saying: The route path-2 matches a page and a redirect but I don't have `path-1.js` file under pages. Somehow 
 `loadPageSync('path-1')` returned object which is true for if condition on line 22.

**Comment by pvdz** [comment]
@mnurik (Github says you requested a review but I don't see new commits and @pieh's suggestion seems a good way forward. The tests will show us the way. And if you're correct then the current system is broken anyways so it'll be an improvement where a test would be really good to have anyways. Let me know if I missed anything?)

**Comment by mnurik** [comment]
@pieh @pvdz I have added e2e tests for redirect one that overlap with existing page, and one that tries to redirect from non-existing page. I couldn't find a way to write tests to check what console errors we have with Cypress.

**Comment by pvdz** [comment]
(Triggered a rebase to get the tests passed a breaking commit)

File: e2e-tests/development-runtime/cypress/integration/redirect/redirect.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+  it(`should redirect page to index page when there is no such page`, () => {
+    cy.visit(`/redirect-without-page`).waitForRouteChange()
+
+    cy.location(`pathname`).should(`equal`, `/`)
+  })
+
+  it(`should redirect page to index page even there is a such page`, () => {
+    cy.visit(`/redirect`).waitForRouteChange()
+
+    cy.location(`pathname`).should(`equal`, `/`)
```
Comment (pieh) [inline e2e-tests/development-runtime/cypress/integration/redirect/redirect.js]: I assume in this case we will get `The route "${pathname}" matches both a page and a redirect; this is probably not intentional.` error in browser console? Wonder if we can assert that console entry

Comment (pieh) [reply e2e-tests/development-runtime/cypress/integration/redirect/redirect.js]: added this in hacky way, resolving the comment

File: packages/gatsby/cache-dir/navigation.js [hunk 3]
```diff
@@ -18,9 +18,8 @@ function maybeRedirect(pathname) {
...
+      // If such page exist show the error. If not it was intentional.
+      if (!loader.isPageNotFound(pathname)) {
```
Comment (pieh) [inline packages/gatsby/cache-dir/navigation.js]: I did run few tests with this and started to think that replacing one with the other might not actually be the way to go and we might need both checks.

`loader.isPageNotFound` will be false if user doesn't have 404 page and there is a page for given pathname. So this means that now users without 404 page will get those error messages. This also makes it tricky to test, as we would have to do another build for no-404 case

Doing a little matrix for this:

|                       | Path exists + have 404 | Path exists + doesn't have 404 | Path doesn't exist + have 404 | Path doesn't exist + doesn't have 404 |
|-----------------------|------------------------|--------------------------------|-------------------------------|---------------------------------------|
| loader.isPageNotFound | false                  | false                          | true                          | false                                 |
| loader.loadPageSync   | { ...data }            | { ...data }                    | { ... data } (for 404 page)   | undefined                             |

We want to show error (probably should have been warning) message when both `loader.isPageNotFound(X) === false && loader.loadPageSync(X) !== null`?

Comment (pieh) [reply packages/gatsby/cache-dir/navigation.js]: Maybe some other method in loader - like `pageExists(pathname)` would be better, as our navigation code shouldn't really need to know that much about loader stuff

Comment (mnurik) [reply packages/gatsby/cache-dir/navigation.js]: @pieh I am totally agree with you to show warning message instead of error. pageExisits method sounds amazing. Will work on creating that method.

Comment (blainekasten) [reply packages/gatsby/cache-dir/navigation.js]: @mnurik any update on this from your? 😃

Comment (n-mirzayev) [reply packages/gatsby/cache-dir/navigation.js]: @blainekasten sorry, long vacation :D Working on solution

Comment (mnurik) [reply packages/gatsby/cache-dir/navigation.js]: @blainekasten sorry, long vacation :D Working on solution

File: packages/gatsby/cache-dir/loader.js [hunk 4]
```diff
@@ -315,6 +315,16 @@ export class BaseLoader {
...
+  isPageExist(rawPath) {
+    const pagePath = findPath(rawPath)
+    const page = this.pageDb.get(pagePath)
+    return (
+      page &&
+      stripSurroundingSlashes(page.payload.page.path) ===
+        stripSurroundingSlashes(rawPath)
+    )
+  }
+
```
Comment (pieh) [inline packages/gatsby/cache-dir/loader.js]: Only thing here is that this method is used only in development, but it does get included in production bundles - we want to avoid cases like that. I'll go ahead and make some adjustments to minimize that

File: packages/gatsby/cache-dir/loader.js [hunk 5]
```diff
@@ -315,6 +315,16 @@ export class BaseLoader {
     return page && page.notFound === true
   }
 
+  isPageExist(rawPath) {
+    const pagePath = findPath(rawPath)
+    const page = this.pageDb.get(pagePath)
+    return (
+      page &&
+      stripSurroundingSlashes(page.payload.page.path) ===
+        stripSurroundingSlashes(rawPath)
```
Comment (pieh) [inline packages/gatsby/cache-dir/loader.js]: also question about usage of those `stripSurroundingSlashes` - this shouldn't be needed I think? We don't really use that in actual navigation code elsewhere (from my check) so it's bit of red flag that this is here

File: packages/gatsby/cache-dir/loader.js (hunk 4 above)
Comment (pieh) [reply packages/gatsby/cache-dir/loader.js]: handled

File: packages/gatsby/cache-dir/loader.js (hunk 5 above)
Comment (pieh) [reply packages/gatsby/cache-dir/loader.js]: handled

File: packages/gatsby/cache-dir/dev-loader.js [hunk 6]
```diff
@@ -34,6 +34,12 @@ class DevLoader extends BaseLoader {
   doPrefetch(pagePath) {
     return Promise.resolve(require(`./socketIo`).getPageData(pagePath))
   }
+
+  __internal__doesPageExist(rawPath) {
+    const pagePath = findPath(rawPath)
+    const page = this.pageDb.get(pagePath)
+    return !!page && page.notFound !== true
```
Comment (mnurik) [inline packages/gatsby/cache-dir/dev-loader.js]: @pieh I think you will get true from this function if there is no 404 page. As it checks `undefined !== true`

Comment (pieh) [reply packages/gatsby/cache-dir/dev-loader.js]: I've done some checks for various variants - not most readable - but check:

Screenshot 2020-02-12 at 23 49 46

Comment (mnurik) [reply packages/gatsby/cache-dir/dev-loader.js]: Ok, I just checked with dev tools debugger. Thanks

Comment (pieh) [reply packages/gatsby/cache-dir/dev-loader.js]: last one in the screenshot is I think case you mentioned - it will bail early because `page` will be falsy (being undefined)

Comment (pieh) [reply packages/gatsby/cache-dir/dev-loader.js]: I can add some unit tests for that

Comment (pieh) [reply packages/gatsby/cache-dir/dev-loader.js]: > Ok, I just checked with dev tools debugger. Thanks

Just for clarification - is the code ok? Or I need to get back to drawing board? :)

Comment (mnurik) [reply packages/gatsby/cache-dir/dev-loader.js]: @pieh for me code is ok, just want to be sure that you are aware of, page.notFound is undefined in cases when there is no 404.js

Comment (pieh) [reply packages/gatsby/cache-dir/dev-loader.js]: Ok, I was writing some unit tests and see what you mean - I think I will also need to update some runtime code to properly mark `page.notFound` as `true` if 404.html doesn't exist

Comment (pieh) [reply packages/gatsby/cache-dir/dev-loader.js]: Tho it is bit confusing because the code "as-is" seemed to be working for me, but maybe I messed things up in manual testing

**Comment by pvdz** [comment]
@mnurik Hi :) Can you please let us know if you're still working on this? I know there's been a lot of back-and-forth but it has been open for a while and no update for over a month so would like to know. Perhaps we should put this PR in Draft mode? (Click "convert to draft" under the reviewers block at the top)

**Comment by mnurik** [comment]
@pvdz Hi, unfortunately I am not, as @pieh started take care of it, and he changed all the stuff, so I am less familiar with changes than him. So feel free to close it, either @pieh can create separate PR or fix this one.

**Comment by pieh** [comment]
I'll put this into draft mode for now, because I don't remember status of it - the e2e tests for redirects we added seems to be passing, but also need to keep in mind the tests I added look pretty weird when I look at them right now (and also noted in the comments around them) and I'm not 100% confident they are actually correctly asseting things or not

File: packages/gatsby/cache-dir/navigation.js (hunk 3 above)
Comment (pieh) [reply packages/gatsby/cache-dir/navigation.js:23]: ok, we got back here after other fixes that happened not in this PR, and right now this is actually working as intended
