### PR TITLE
fix(gatsby): handle case of changing page path casing on case-insensitive fs

### LINKED ISSUE #31055: Gatsby V3 does not create page in onCreatePage function after deletePage
## Description

Recently I migrated my project from gatsby V2 to V3 and after migration, some of the code does not work as it supposed to. 

A scenario which I was using and which I need to achieve right now:

 1. I have different subfolders under the `/pages` folder, every
    subfolder has `index.js` files and is named uppercase
 2. In `gatsby-node.js` file in `onCreatePage` function I delete page with `deletePage` function and create a new one with a different slug with `createPage` function. 
 
my `gatsby-node.js` code:

  ```
  export const onCreatePage = ({ page, actions }) => {
      const { deletePage, createPage } = actions;
    
      const page_path = toLower(page.path);
    
      deletePage(page);
    
      if (page.componentPath === `${__dirname}/src/pages/HomePage/index.js`) {
        // create a new page but with '/' as path
        createPage({ ...page, path: '/' });
      } else if (page_path.match(/^\/account/)) {
        page.matchPath = '/account/*';
    
        // Create the new page.
        createPage({ ...page, path: page_path });
      } else if (
        page_path.match(/^\/kitchensink/) &&
        process.env.NODE_ENV === `production`
      ) {
        //pass
      } else {
        // create a new page but make slug all lowercase as page subfolders are named uppercase
        createPage({ ...page, path: page_path });
      }
    };
```

After migration, this method deletes the page but does not create a new one, seems that `createPage` function does not work anymore or it has some issues. As a result, I do not get any pages as it was deleted, it does not appear in the `public` folder structure either. 

Maybe I do not spot my mistake, tried many different things to solve the issue but did not work.

Is there any way to force gatsby URLs to be JUST lowercase? 

Thanks for any help  

### Steps to reproduce

-

### Expected result

The expected result is to have each page created with a lower case slug when pages folder sub-directories are named uppercase

### Actual result

Pages are getting deleted with `deletePage` but not created with `createPage` function as it used to be in gatsby V2

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    npm: 7.9.0 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /Users/baivaras/.pyenv/shims/python
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.3.1 => 3.3.1 
    gatsby-codemods: ^2.3.0 => 2.3.0 
    gatsby-image: ^3.3.0 => 3.3.0 
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1 
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0 
    gatsby-plugin-facebook-pixel: ^1.0.5 => 1.0.5 
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.5 
    gatsby-plugin-google-analytics: ^3.3.0 => 3.3.0 
    gatsby-plugin-google-tagmanager: ^3.3.0 => 3.3.0 
    gatsby-plugin-hotjar: ^1.1.1 => 1.1.1 
    gatsby-plugin-image: ^1.3.1 => 1.3.1 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^3.3.0 => 3.3.0 
    gatsby-plugin-offline: ^4.3.0 => 4.3.0 
    gatsby-plugin-page-creator: ^3.3.0 => 3.3.0 
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0 
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1 
    gatsby-plugin-remove-console: 0.0.2 => 0.0.2 
    gatsby-plugin-remove-trailing-slashes: ^3.3.0 => 3.3.0 
    gatsby-plugin-robots-txt: ^1.5.6 => 1.5.6 
    gatsby-plugin-s3: ^0.3.8 => 0.3.8 
    gatsby-plugin-sass: ^4.3.0 => 4.3.0 
    gatsby-plugin-sharp: ^3.3.1 => 3.3.1 
    gatsby-plugin-sitemap: ^3.3.0 => 3.3.0 
    gatsby-plugin-styled-components: ^4.3.0 => 4.3.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
    gatsby-plugin-zopfli: ^2.0.0 => 2.0.0 
    gatsby-source-airtable: ^2.1.1 => 2.1.1 
    gatsby-source-filesystem: ^3.3.0 => 3.3.0 
    gatsby-source-wordpress: ^5.3.1 => 5.3.1 
    gatsby-transformer-remark: ^4.0.0 => 4.0.0 
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0 
  npmGlobalPackages:
    gatsby-cli: 3.3.0

### PR DESCRIPTION
**Pull request by pieh**
## Description

On Windows and MacOs if you change casing of page path it results in page being generated and then deleted. 

Consider scenario of creating `/TEST/` page and then in `onCreatePage` adjust page path to lower case which results in `/test/` page. What currently happen is that `/test/` is generated and `/TEST/` is scheduled for deletion. In case insensitive filesystems it means we will delete same files we just created.

## Related Issues

fixes #31055

### CODE REVIEW

File: packages/gatsby/src/commands/build-utils.ts [hunk 1]
```diff
@@ -70,6 +70,11 @@ function normalizePagePath(path: string): string {
   if (path === `/`) {
     return `/`
   }
+
+  if (platform() === `win32` || platform() === `darwin`) {
```
Comment (vladar) [inline packages/gatsby/src/commands/build-utils.ts:74]: Maybe move the check outside of this function? Platforms likely won't change 😅

Comment (pieh) [reply packages/gatsby/src/commands/build-utils.ts]: Done in https://github.com/gatsbyjs/gatsby/pull/31071/commits/495e64330b583dde72f3a390eb75721ebae4e27a

File: packages/gatsby/src/commands/__tests__/build-utils.ts [hunk 2]
```diff
@@ -4,14 +4,21 @@ import {
...
 interface IMinimalStateSliceForTest {
   html: IGatsbyState["html"]
   pages: IGatsbyState["pages"]
 }
 
 describe(`calcDirtyHtmlFiles`, () => {
+  let calcDirtyHtmlFiles
+  beforeEach(() => {
+    jest.isolateModules(() => {
+      calcDirtyHtmlFiles = require(`../build-utils`).calcDirtyHtmlFiles
```
Comment (vladar) [inline packages/gatsby/src/commands/__tests__/build-utils.ts:18]: Why do we need to isolate the module here (and also in the test)? I never used `isolateModules` before so just curious.

**Review by vladar — APPROVED** [review]
Thank you! 👍

File: packages/gatsby/src/commands/__tests__/build-utils.ts (hunk 2 above)
Comment (pieh) [reply packages/gatsby/src/commands/__tests__/build-utils.ts:18]: I do need to isolate because of `os.platform()` calls (that I _need_ to mock) execute at import time (that's why I do have them isolated in casing specific tests). 

In here (swiching import that is already there to this) it just seemed that if I import regularly before I import in `isolateModules` just for casing tests - I still get cached module which means my mocking of `os.platform()` has no effect
