### PR TITLE
fix(gatsby): Handle missing match-paths.json in serve

### LINKED ISSUE #16092: gatsby serve - Hint: "Did you mean this? serve" - confused🥴
# Summary

I am cloning the repo, running `npm install` and copying the public folder from a previous pipeline step. 

If run `gatsby serve`, it returns an exit code 1.

If I run gatsby build again, it works.

## Relevant information

I am running gatsby serve in my CI/CD pipeline. The "error" that is coming back is very confusing.

Screenshot 2019-07-25 at 22 13 40

Any ideas what the problem is?

### Environment (if relevant)

gatsby info --clipboard

  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (1) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.13.31 => 2.13.31 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.8 => 2.2.8 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.7.20

### PR DESCRIPTION
**Pull request by m-allanson**
## Description

`gatsby serve` uses the `match-paths.json` file from Gatsby's `.cache` directory to configure client side routing. It assumes that file always exists. If that file _doesn't_ exist, the error bubbles up to [the cli's generic fail handling code](https://github.com/gatsbyjs/gatsby/blob/742b818ab176c3953e21d6e5d05a66cb6bd55254/packages/gatsby-cli/src/create-cli.js#L437-L448). 

This results in a confusing error as seen in #16092.

This PR adds a warning if `match-paths.json` doesn't exist:

Screenshot of updated warning message

## Related Issues

Fixes #16092

### CODE REVIEW

File: packages/gatsby/src/commands/serve.js [hunk 1]
```diff
@@ -31,7 +31,22 @@ onExit(() => {
...
+      `${chalk.yellow(
+        `warn`
+      )} Could not read "match-paths.json" from the .cache directory`
+    )
+    console.log(
+      `${chalk.yellow(
+        `warn`
+      )} Client-side routing will not work correctly. Maybe you need to re-run "gatsby build"?`
+    )
+  }
```
Comment (pieh) [inline packages/gatsby/src/commands/serve.js]: We should be able to use `reporter.warn` here I think?

Comment (sidharthachatterjee) [reply packages/gatsby/src/commands/serve.js]: Done
