### PR TITLE
fix(gatsby): support file inference for any field name (not just [a-zA-Z0-9_])

### LINKED ISSUE #20151: Gatsby image hyphen bug with GraphQL
## Description

I have been working on a project using Gatsby in conjunction with Netlify CMS and repeatedly ran into the GraphQL error 'Field "image" must not have a selection since type "String" has no subfields' when querying my page markdown files. It turned out that this occurred only when the name of the image's parent node contained a hyphen. This issue has previously been raised (https://github.com/gatsbyjs/gatsby/issues/14644) but was never resolved as it was closed by gatsbot.

### Steps to reproduce

A minimal reproduction is available here: https://github.com/MatthewWilson24/gatsby-hyphen-bug-reproduction.

In src/pages/index.md I have the following markdown page data:
```
---
templateKey: index-page
image-with-text:
  image: /img/test.jpg
  text: Subfield of hyphenated field
imageWithText:
  image: /img/test.jpg
  text: Subfield of camelcase field
---
```

Which is queried in src/templates/index-page.js as follows:
```
export const pageQuery = graphql`
  query IndexPageTemplate {
    markdownRemark(frontmatter: { templateKey: { eq: "index-page" } }) {
      frontmatter {
        image_with_text {
          image {
            childImageSharp {
              fluid {
                ...GatsbyImageSharpFluid
              }
            }
          }
          text
        }
        imageWithText {
          image {
            childImageSharp {
              fluid {
                ...GatsbyImageSharpFluid
              }
            }
          }
          text
        }
      }
    }
  }
```

### Expected result

Gatsby should convert both image file paths to file nodes and the queries should succeed.

### Actual result

The query for "imageWithText" succeeds but the query for "image_with_text" causes the GraphQL error 'Field "image" must not have a selection since type "String" has no subfields'.

### Environment
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.13.31 => 2.18.12
    gatsby-image: ^2.0.23 => 2.2.36
    gatsby-plugin-netlify: ^2.0.6 => 2.1.30
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.1.33
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.18
    gatsby-plugin-sass: ^2.0.7 => 2.1.26
    gatsby-plugin-sharp: ^2.2.9 => 2.3.8
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.1.33
    gatsby-remark-images: ^3.1.6 => 3.1.38
    gatsby-remark-relative-images: ^0.2.1 => 0.2.3
    gatsby-source-filesystem: ^2.0.26 => 2.1.42
    gatsby-transformer-remark: ^2.6.9 => 2.6.42
    gatsby-transformer-sharp: ^2.1.9 => 2.3.9

### PR DESCRIPTION
**Pull request by vladar**
## Description

This PR fixes file inference on fields other than `[a-zA-Z0-9_]` which was broken before. Take an example:

```js
  createNode({
    id: `1`,
    "file-here": `./file_1.jpg`,
    parent: null,
    children: [],
    internal: { type: `Test` },
  })
```

Before this PR, `file-here` was always inferred as `String` not `File`. But if you were to change the field name to `file_here` it correctly inferred it as `File`.

After this PR both `file-here` and `file_here` are inferred as `File` (and any field with special characters in general).

### Documentation
N/A

## Related Issues
Fixes #20151

### CODE REVIEW

File: packages/gatsby/src/schema/infer/__tests__/infer.js [hunk 1]
```diff
@@ -1053,6 +1053,39 @@ Object {
...
+        },
+      ].concat(getFileNodes())
+
+      const result = await getQueryResult(
+        nodes,
+        `
+          file_dashed {
+            absolutePath
+          }
+          file___________________________ {
```
Comment (TylerBarnes) [inline packages/gatsby/src/schema/infer/__tests__/infer.js]: I think this PR should be reviewed by someone else; but out of curiosity, what's with the underscores?

Comment (vladar) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: We replace special chars found in node fields with underscores in GraphQL schema. So this is basically this line converted to GraphQL-compatible name:

https://github.com/gatsbyjs/gatsby/blob/67aa4baf9c8e4713c38a08cd0f4aa2241949ccc4/packages/gatsby/src/schema/infer/__tests__/infer.js#L1058

This is expected behavior (works the same before this PR). The issue is that before this PR the reverse link from GraphQL field to Gatsby node field was lost.

Comment (TylerBarnes) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: Ahhh, makes sense. Thanks for the explanation!

Comment (sidharthachatterjee) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: This is hilarious 😆

Comment (muescha) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: but is this replacement not a problem with 2 similar fields like:

- `file-Nüsse` -> `file_N_sse`
- `file-Nässe` -> `file_N_sse`

which both results in same `file_N_sse`?

maybe it makes sense to encode the names with [Punycode](https://en.wikipedia.org/wiki/Punycode) which results in:

- `file-Nüsse` -> `xn--file-nsse-v9a`
- `file-Nässe` -> `xn--file-nsse-02a`

and also works for normal code:

- `file-Nasse` -> `file-Nasse`

Comment (sidharthachatterjee) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: @muescha That is a good point! 

@vladar Thoughts?

Comment (muescha) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: one drawback: 

it is not anymore nice readable 
- but maybe it is possible to add an field `original_field_name` where the name can shown in the query result
- or an comment at the schema doc with the original name can be somehow generated?

Comment (muescha) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: ok - one more drawback: 
- punycode results in `[a-z0-9-]` but then a replacement from `-` to `_` is possible...

Comment (vladar) [reply packages/gatsby/src/schema/infer/__tests__/infer.js]: I agree that we could do better here but this is out of the scope of this PR. Also changing this behavior would be breaking.

Anyways, I tried finding any open issue for something like this but it looks like there are none, which means it is not that big of a problem. Of course, we can open a separate issue to handle this but I feel that it would be much better to have an issue from a person who really suffers from this problem vs. us doing this.

As for the technical part - we could use slugify as we already do to generate query name from the file path:

https://github.com/gatsbyjs/gatsby/blob/21d6a874d506f253767cfbef4deb0eb3618ef743/packages/gatsby/src/query/file-parser.js#L28-L40
