### PR TITLE
[gatsby-plugin-manifest] Generate a 32x32 favicon instead of generating from first manifest icon

### LINKED ISSUE #19899: [gatsby-plugin-manifest] Default favicon set doesn't render well (Firefox, retina display)
## Description

When using the default favicon set produced by `gatsby-plugin-manifest`, the icon used by Firefox looks low-res (on my retina Macbook).

**Firefox**

Screenshot 2019-12-01 at 10 41 38
Screenshot 2019-12-01 at 10 41 38

**Chrome**

Screenshot 2019-12-01 at 14 14 30
Screenshot 2019-12-01 at 14 14 30

### Steps to reproduce

This affects any site using `gatsby-plugin-manifest`'s automatic icon generation, including [Gatsby's own](https://github.com/gatsbyjs/gatsby/tree/master/www). You could build that project to reproduce this.

### Expected result

Favicon looks sharp in both browsers.

### Actual result

Favicon looks low-res in Firefox.

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - /var/folders/hp/53td47vs5bq5pcx9j918qsfc0000gn/T/yarn--1575197307021-0.11396977243068873/node
    Yarn: 1.19.2 - /var/folders/hp/53td47vs5bq5pcx9j918qsfc0000gn/T/yarn--1575197307021-0.11396977243068873/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  Languages:
    Python: 3.7.3 - /Users/owen/.pyenv/shims/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: 2.15.36 => 2.15.36
    gatsby-image: 2.2.27 => 2.2.27
    gatsby-plugin-manifest: 2.2.21 => 2.2.21
    gatsby-plugin-offline: 3.0.14 => 3.0.14
    gatsby-plugin-react-helmet: 3.1.11 => 3.1.11
    gatsby-plugin-sharp: 2.2.29 => 2.2.29
    gatsby-plugin-styled-components: 3.1.9 => 3.1.9
    gatsby-plugin-typography: 2.3.12 => 2.3.12
    gatsby-source-filesystem: 2.1.31 => 2.1.31
    gatsby-transformer-remark: 2.6.32 => 2.6.32
    gatsby-transformer-sharp: 2.2.21 => 2.2.21
```

## Proposed fix

Adding the 32x32px version to the [default icons config](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-manifest/src/common.js#L5) fixes this, and looks good in other browsers I tested too (Chrome, Safari, iOS Safari).

Happy to submit a PR with this change, unless there's a known reason to avoid including the 32x32 resolution.

### PR DESCRIPTION
**Pull request by cycleseven**
## Description

`gatsby-plugin-manifest` [uses the first of the configured manifest `icons`](https://github.com/gatsbyjs/gatsby/issues/19899#issuecomment-560939742) to generate a favicon. This isn't necessarily intuitive, and means a 48x48 favicon is used by default, [which is probably not the ideal size](https://github.com/gatsbyjs/gatsby/issues/19899#issuecomment-560849602).

This PR decouples the favicon size from the configured manifest icons, and generates a 32x32 icon instead.

### Some caveats

- This would technically introduce a breaking change: in "hybrid" mode, users can currently control the generated favicon size using the first element of `icons`. This change takes that control away.
- This PR introduces an edge case: a user could configure a path in their `icons` config that clashes with the fixed favicon path. As it stands, the favicon generation would overwrite the one from `icons` in that edge case. It's a slim chance this would have any impact imo: someone would have to want a non-32x32 icon called `favicon-32x32.png`, which would be a bit weird 😄 
- A 32x32 PNG alone is probably still not the most widely compatible favicon setup. But it should be an improvement over 48x48. Users who want deeper control over favicons can still opt-out of `gatsby-plugin-manifest`'s favicon generation as before.

See the related issue for more info and discussion.

### Documentation

The `README.md` for `gatsby-plugin-manifest` is slightly tweaked to give more details about the generated favicon format.

## Related Issues

Fixes #19899

### CODE REVIEW

File: packages/gatsby-plugin-manifest/src/common.js [hunk 1]
```diff
@@ -1,6 +1,14 @@
...
 import sysPath from "path"
 
+exports.favicons = [
+  {
+    src: `favicon-32x32.png`,
+    sizes: `32x32`,
+    type: `image/png`,
+  },
+]
+
```
Comment (cycleseven) [inline packages/gatsby-plugin-manifest/src/common.js:11]: Although there's currently just one favicon being generated, I thought it would make sense to define this as an array to mirror `icons`. Means adding more sizes is easy as a bonus, possibly a case of YAGNI though 🤷‍♂️

File: packages/gatsby-plugin-manifest/README.md [hunk 2]
```diff
@@ -238,7 +238,9 @@ module.exports = {
 
 #### Disable favicon
 
-Excludes `<link rel="icon" href="/favicon.png" />` link tag to html output. You can set `include_favicon` plugin option to `false` to opt-out of this behavior.
+A favicon is generated by default in automatic and hybrid modes (a 32x32 PNG, included via a `<link rel="icon" />` tag in the document head).
+
+You can set `include_favicon` plugin option to `false` to opt-out of this behavior.
```
Comment (laurieontech) [inline packages/gatsby-plugin-manifest/README.md:243]:
```suggestion
You can set the `include_favicon` plugin option to `false` to opt-out of this behavior.
```

File: packages/gatsby-plugin-manifest/src/gatsby-node.js [hunk 3]
```diff
@@ -126,6 +131,11 @@ const makeManifest = async ({
   const suffix =
     shouldLocalize && pluginOptions.lang ? `_${pluginOptions.lang}` : ``
 
+  const faviconIsEnabled =
+    typeof pluginOptions.include_favicon !== `undefined`
+      ? pluginOptions.include_favicon
+      : true
```
[the remark this answers is not in the document]
Comment (cycleseven) [reply packages/gatsby-plugin-manifest/src/gatsby-node.js]: Yeah absolutely, that's better

**Comment by cycleseven** [comment]
@moonmeister

> The only thing I'm curious about is if there is a test for disabling the favicon, and confirming it doesn't get written..this should have already existed. Can you please check if it exists and and if not, please add that test (if you need help or just want me to do so just let me know)

Let me get back to you on this part. 

There are already tests to ensure `gatsby-ssr` correctly includes/excludes the `<link>` [here](https://github.com/gatsbyjs/gatsby/blob/746b7220bc722745b0b962461c2d1a1cefd87baa/packages/gatsby-plugin-manifest/src/__tests__/gatsby-ssr.js#L286)... but the plugin could use something similar on the `gatsby-node` side now, to show we don't generate an unnecessary PNG when `include_favicon` is false.

My first idea on how to test that was to assert that `sharp` is called the correct number of times with the expected parameters (ie. that sharp call exists by default, and doesn't exist when `include_favicon` is false). 

But then I saw there was already at least one test that should cover the positive case, like [this one](https://github.com/gatsbyjs/gatsby/blob/746b7220bc722745b0b962461c2d1a1cefd87baa/packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js#L158). Which raises the question of why that didn't fail so far. In theory, I'd expect my code changes to modify the number of calls to sharp under that plugin config.

[Since the content digest function is mocked to return a constant](https://github.com/gatsbyjs/gatsby/blob/746b7220bc722745b0b962461c2d1a1cefd87baa/packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js#L46), and the icon generation is [skipped if the content digest is already cached](https://github.com/gatsbyjs/gatsby/blob/835f2cfc5f896edcbdab26ebd87c51d173d9c12c/packages/gatsby-plugin-manifest/src/gatsby-node.js#L40), then it actually seems like some existing tests will be asserting `expect(sharp).toHaveBeenCalledTimes(n)` for some n that doesn't actually match the real number of sharp calls outside the test environment 🤔 could be misunderstanding so far though.

Will try to take a closer look at this later in the week and figure out what's going on here and how best to add those tests 🤞

File: packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js [hunk 4]
```diff
@@ -43,7 +43,7 @@ jest.mock(`gatsby-core-utils`, () => {
   return {
     slash: originalCoreUtils.slash,
     cpuCoreCount: jest.fn(() => `1`),
-    createContentDigest: jest.fn(() => `contentDigest`),
+    createContentDigest: originalCoreUtils.createContentDigest,
```
Comment (cycleseven) [inline packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js:46]: Seems better to me to use the real `createContentDigest` function. Although the snapshots look more random now, it's still [a deterministic value](https://github.com/gatsbyjs/gatsby/blob/58e28ac14b9247f335651cfc2125396ff6d7a13c/packages/gatsby-core-utils/src/__tests__/create-content-digest.ts#L10).

The benefit is that the `expect(sharp).toHaveBeenCalledTimes(n)` assertions match reality now: have updated those throughout the file. Now the existing assertions properly cover the favicon generation, and I've added a new test case to show the favicon is skipped when `include_favicon` is false.

**Comment by moonmeister** [comment]
Really good work on tests and everything. Thanks!

File: packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js (hunk 4 above)
Comment (moonmeister) [reply packages/gatsby-plugin-manifest/src/__tests__/gatsby-node.js:46]: Thanks for fixing this.

**Comment by cycleseven** [comment]
Failing CI check, guess that change to the tests wasn't as safe as I thought...? 😞 can't see what the error in the Cloud Tests is from my end though. @moonmeister if you can let me know what exactly failed, I'm happy to finish this off from my end. Might be getting into poor feedback loop territory here though: also happy to hand this last part over to you if you're up for it?

**Comment by moonmeister** [comment]
That page isn't loading for me so not sure I can help. We may have to wait for a Gatsby Core team member to give us the details. Given everything passed on circle it might just be fluke. But, some hash algorithms are hardware dependent. Meaning it's possible whatever hardware is running in the cloud build is creating a different hash.

**Comment by cycleseven** [comment]
> But, some hash algorithms are hardware dependent. Meaning it's possible whatever hardware is running in the cloud build is creating a different hash.

I guess I'd expect [other tests that call the real createContentDigest](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/__tests__/create-content-digest.ts) to suffer from the same problem if that was it 🤔 but that does make sense in theory yeah, I guess there was a good reason to mock the function in the first place.

If that's the issue, it should work equally well to mock `createContentDigest` with an identity/stringify function instead.

```
jest.mock(`gatsby-core-utils`, () => {
  return {
    createContentDigest: jest.fn(x => `${x}`),
  }
})
```

Still outputs a unique value for each unique input, without depending on the real hash algo... so would tick the requirements for these tests, I think.

I'll wait on a Gatsby Core member to see what's up with that CI failure before moving forward though, might be counterproductive to try and fix this blind. Will keep my eye out for updates here 🤞 thanks for all the help so far.

**Comment by pvdz** [comment]
(Fwiw; The Cloud tests failure was unrelated to this PR, caused to npm noise in the CLI which triggered a non-zero exit by Gatsby. The noise is unrelated to the test. All tests passed.)

**Comment by moonmeister** [comment]
Awesome! well, then I think we're just waiting for @gatsbyjs/core team member to review and we should be good.

**Comment by pvdz** [comment]
Where do we find one of those?

**Comment by pvdz** [comment]
(Kidding. I'll make a superficial pass but I have zero insight into this plugin so somebody else will have to do the semantics)

**Comment by moonmeister** [comment]
> (Kidding. I'll make a superficial pass but I have zero insight into this plugin so somebody else will have to do the semantics)

Well hopefully that was what my review was good for. I haven't actually tested the new plugin manually, but if tests are passing and @cycleseven has seen it work irl then we should be good.

**Comment by pvdz** [comment]
Ok, fair enough and well met :)

Code looks good. One question remaining for me is whether this is backwards compat breaking. Before it was taking the first image of the set. What happens to people that bump the package without changing their config?

**Comment by cycleseven** [comment]
@pvdz thanks for taking a look at this.

> One question remaining for me is whether this is backwards compat breaking. Before it was taking the first image of the set. What happens to people that bump the package without changing their config?

So first it's worth making it clear the only possible breaking change here would be that the generated favicon _resolution_ changes: when we say "first image of the set", that set configures the generated sizes, but it's from a single input image. Nobody can end up with the wrong favicon after this. Probably these changes will be completely unnoticeable for most eg. Chrome seems really good at handling different sizes identically. 

But yeah as mentioned in the original description above, there's technically a breaking change for what I assume would be a small minority of users who might be taking advantage of an undocumented side effect of the config to generate a non-standard favicon size intentionally. To break this down:

## [Automatic mode](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/#automatic-mode-configuration)

These users completely leave it up to the plugin to generate appropriate sizes for both manifest icons + favicon. For those users, this should just be a transparent browser compat improvement.

I assume this is the majority of users.

## [Manual mode](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/#manual-mode-configuration)

The plugin doesn't generate a favicon for these users, and it never did. No change here.

## [Hybrid mode](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/#hybrid-mode-configuration)

These users manually define the sizes they want for the manifest. Favicon is just an opt-in or opt-out, the docs make no promise about what size the favicon is or where that size comes from. But it's possible that some users a) have understood that the plugin uses the first manifest icon size for the favicon by experimenting or reading the source, b) intentionally want to control that size and c) want that size to be something other than 32x32.

From my (non-exhaustive) research, 32 really does look like the best supported size if you can only pick one, so it's hard to imagine this being a noticeable or bad change even for this group of users. But it's true that they will lose control that they technically had before, so that's a breaking change for sure.

I think we'd want to eventually make that breaking change in any case. But I'm also happy to submit a non-breaking version of this that only affects "automatic" mode to tide us over until a major version...? Up to you guys, let me know 👍 

@moonmeister 

> @cycleseven has seen it work irl then we should be good

Yeah, I've tested this out with my real Gatsby project using [gatsby-dev-cli](https://www.npmjs.com/package/gatsby-dev-cli), with both my original config, as well as just leaning on automatic mode. I assume this is enough? Give me a shout if you have something more in mind though.

**Comment by moonmeister** [comment]
Thanks for the details on the dev experience change. I'm comfortable pushing this as a bug fix. It doesn't require any config change and doesn't really add any features. If someone out there was hacking private implementation details rather than just opening an issue, is doubtful, and not supported. 

That testing should be plenty.

**Comment by moonmeister** [comment]
@cycleseven  Thanks again for the work and the PR!

**Comment by cycleseven** [comment]
@moonmeister @laurieontech @pvdz thank you all for giving your time to help get this in 🎉

**Comment by pieh** [comment]
Published `gatsby-plugin-manifest@2.3.6`
