### PR TITLE
fix(gatsby): fix filtering by sub-fields of the field with custom resolver

### LINKED ISSUE #26056: runQuery filter in custom resolver breaks other queries (race condition?)
I define a custom relationship from neighbourhoods to stores using `createSchemaCustomization`:

`gatsby-node.js`

```js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions
  const { buildObjectType } = schema

  createTypes([
    buildObjectType({
      name: "SanityNeighbourhood",
      interfaces: ["Node"],
      fields: {
        stores: {
          type: "[SanityStore]",
          resolve: async ({ id }, args, { nodeModel }) =>
            await nodeModel.runQuery({
              query: {
                filter: { neighbourhoods: { elemMatch: { id: { eq: id } } } },
              },
              type: "SanityStore",
              firstOnly: false,
            }),
        },
      },
    }),
  ])
}
```

Then I create a page for each neighbourhood:

`gatsby-node.js`

```js
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const { data, errors } = await graphql(`
    query CreatePages {
      neighbourhoods: allSanityNeighbourhood {
        nodes {
          slug {
            current
          }
        }
      }
    }
  `)

  if (errors) {
    throw errors
  }

  data.neighbourhoods.nodes.forEach(({ slug: { current: slug } }) => {
    createPage({
      path: slug,
      component: require.resolve(`./src/templates/neighbourhood.js`),
      context: { slug },
    })
  })
}
```

My neighbourhood template calls my custom resolver to retrieve a list of stores for each neighbourhood:

`src/templates/neighbourhood.js`

```js
export const query = graphql`
  query NeighbourhoodTemplate($slug: String!) {
    sanityNeighbourhood(slug: { current: { eq: $slug } }) {
      stores {
        id
      }
    }
  }
`
```

So far, everything works.

Now, on my home page, if I try to grab a list of stores in a particular neighbourhood:

`src/pages/index.js`

```js
export const query = graphql`
  query IndexPage {
    allSanityStore(
      filter: {
        neighbourhoods: {
          elemMatch: { slug: { current: { eq: "harbourfront" } } }
        }
      }
    ) {
      nodes {
        id
      }
    }
  }
`
```

`allSanityStore.nodes` comes back empty. If I make the exact same query at runtime using GraphiQL, I get the expected list of nodes.

For some reason, my custom resolver has affected the result of a seemingly unrelated query.

This is just one example. It seems that any custom resolver that calls `nodeModel.runQuery` with a filter seems to have unpredictable, far-reaching impacts on query results across the entire site.

### Steps to reproduce

See https://github.com/gatsbyjs/gatsby/issues/26056#issuecomment-675508616

### Expected result

Defining a custom resolver should not affect the results of unrelated queries.

### Actual result

My custom resolver affects the results of unrelated queries.

### Environment

```txt
  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47
    gatsby-source-sanity: ^6.0.3 => 6.0.3
```

### PR DESCRIPTION
**Pull request by vladar**
## Description

This PR fixes an edge case in Gatsby materialization. The bug shows up when filtering by nested fields of a field with a custom resolver.

See #26056 for full details and my investigation on this bug. Also, the test case in this PR demonstrates a situation when this error occurs.

## Related Issues
Fixes #26056
Maybe also #23549

### CODE REVIEW

**Review by pvdz — APPROVED** [review]
lgtm

File: packages/gatsby/src/schema/node-model.js [hunk 1]
```diff
@@ -785,6 +787,11 @@ const determineResolvableFields = (
     if (!fieldsToResolve[fieldName] && needsResolve) {
       fieldsToResolve[fieldName] = true
     }
+    if (!fieldsToResolve[fieldName] && isNestedType) {
+      // If parent field needs to be resolved - all nested fields should be added as well
+      // See https://github.com/gatsbyjs/gatsby/issues/26056
+      fieldsToResolve[fieldName] = true
+    }
```
Comment (wardpeet) [inline packages/gatsby/src/schema/node-model.js:794]: Small nit
```suggestion
    if (!fieldsToResolve[fieldName] && (needsResolve || isNestedType)) {
      // If parent field needs to be resolved - all nested fields should be added as well
      // See https://github.com/gatsbyjs/gatsby/issues/26056
      fieldsToResolve[fieldName] = true
    }
```

**Review by wardpeet — COMMENTED** [review]
Code looks good to me, I don't have much knowledge on what fieldsToResolve does in the bigger picture.

File: packages/gatsby/src/schema/node-model.js (hunk 1 above)
Comment (vladar) [reply packages/gatsby/src/schema/node-model.js:794]: I thought about this but then the comment looks like it also relates to the `needsResolve` part which is not the case.

Comment (wardpeet) [reply packages/gatsby/src/schema/node-model.js:794]: true, let's keep it as is

**Comment by vladar** [comment]
Published in `gatsby@2.24.51`
