### PR TITLE
Fixes theme extension bug

### LINKED ISSUE #23697: Themes: Shadowing algorithm for page templates doesn't allow other extensions
## Description

The PR https://github.com/gatsbyjs/gatsby/pull/17681 added the ability to shadow queries that e.g. are used in createPage calls. But this [comment](https://github.com/gatsbyjs/gatsby/pull/17681#issuecomment-588442955) (and I was able to reproduce it) showed a flaw:

> I hit an edge case. Create a site from `@lekoarts/gatsby-theme-minimal-blog` and attempt to shadow the `template/homepage-query.tsx` with a local `src/@lekoarts/gatsby-theme-minimal-blog-core/templates/homepage-query.js`. It won't shadow over the in-theme file. Rename it with the same extension...it works.

> the documents for `createPage` tells you to use an absolute path to the component. So, the theme author didn't do anything wrong. (per docs) The component will always have an extension, so the algorithm resolving the shadowed component will not allow extension overriding. :(

It also shows a false warning:

```shell
warn The GraphQL query in the non-page component "/mnt/c/Users/Lennart/Development/Playground/minimal-blog-additional-field/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/page-query.tsx" will Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.
```

### Steps to reproduce

Clone https://github.com/LekoArts/minimal-blog-additional-field and change the file extensions of the shadowed files to `.jsx`. On `localhost:8000/about` you shouldn't see the the `subtitle` line.

### Expected result

Users should be able to use .js, .jsx or .tsx

### Actual result

Users need to use .tsx

### Environment

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  npmPackages:
    gatsby: ^2.20.36 => 2.21.9
    gatsby-plugin-google-analytics: ^2.1.4 => 2.3.0
    gatsby-plugin-manifest: ^2.2.3 => 2.4.1
    gatsby-plugin-netlify: ^2.1.3 => 2.3.0
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.4.1
  npmGlobalPackages:
    gatsby-cli: 2.12.1
    gatsby-dev-cli: 2.7.0
```

### PR DESCRIPTION
**Pull request by laurieontech**
Fixes #23697 

It appears that this only worked for Webpack situations because it was able to resolve files in a greedy manner without a fully qualified path. It should now work in all cases.

### CODE REVIEW

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js [hunk 1]
```diff
@@ -130,23 +130,23 @@ module.exports = class GatsbyThemeComponentShadowingResolverPlugin {
...
-        return exists
+          ) // find extension
+          return matchingExtension
+            ? possibleComponentPath + matchingExtension
+            : false // if extension matches, create path
+        } else {
+          return possibleComponentPath
+        }
       })
+      .find(path => path != false) // if full path matched, return it
```
Comment (johno) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:149]: We can make this filter more succinct if all values are falsey or a matched path, a suggestion to consider:

```suggestion
      .find(Boolean) // if full path matched, return it
```

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/create-page.js [hunk 2]
```diff
@@ -3,6 +3,11 @@ const path = require(`path`)
 const GatsbyThemeComponentShadowingResolverPlugin = require(`.`)
 const { store } = require(`../../redux`)
 
+const pathWithoutExtension = fullPath => {
```
Comment (johno) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/create-page.js:6]: 😎

File: e2e-tests/themes/development-runtime/src/gatsby-theme-about/templates/bio.jsx [hunk 3]
```diff
@@ -0,0 +1,7 @@
+import React from "react"
+
+export default () => (
+  <>
+    <p data-testid="bio">A bio all about me.</p>
+  </>
+)
```
Comment (pvdz) [inline e2e-tests/themes/development-runtime/src/gatsby-theme-about/templates/bio.jsx:7]: Prettier?

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js [hunk 4]
```diff
@@ -119,7 +119,7 @@ module.exports = class GatsbyThemeComponentShadowingResolverPlugin {
           .map(({ themeDir }) => path.join(themeDir, `src`, theme))
       )
       .map(dir => path.join(dir, component))
-      .find(possibleComponentPath => {
+      .map(possibleComponentPath => {
```
Comment (pvdz) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:122]: My two cents: this was already kind of confusing and this change did not help. 
- the change from `.find` to `.map` is a red flag
- the back-to-back `.map` calls look a little redundant 
- .find(Boolean) is a new one for me

I think this whole return statement-concat-map-map-find chunk ought to be rewritten to be a regular loop.

Up to you.

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/create-page.js [hunk 5]
```diff
@@ -25,7 +30,11 @@ module.exports = function (pageComponent) {
 
   if (matchingThemes.length == 1) {
     const [theme] = matchingThemes
-    const [, component] = pageComponent.split(path.join(theme.themeDir, `src`))
+
+    const pageComponentWithoutExtension = pathWithoutExtension(pageComponent)
+    const [, component] = pageComponentWithoutExtension.split(
+      path.join(theme.themeDir, `src`)
+    )
```
Comment (pvdz) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/create-page.js:37]: Did this work in Windows before? It does now because both parts are normalized through `path.join`. I guess that's good but implicit and easy to break.

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js [hunk 6]
```diff
@@ -130,23 +130,23 @@ module.exports = class GatsbyThemeComponentShadowingResolverPlugin {
...
-        return exists
+          ) // find extension
+          return matchingExtension
+            ? possibleComponentPath + matchingExtension
+            : false // if extension matches, create path
+        } else {
+          return possibleComponentPath
+        }
       })
+      .find(Boolean) // if full path matched, return it
```
Comment (blainekasten) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:149]: instead of a `map/find(Bool)` could this just be a `some()` call?

File: e2e-tests/themes/development-runtime/src/gatsby-theme-about/templates/bio.jsx (hunk 3 above)
Comment (pvdz) [reply e2e-tests/themes/development-runtime/src/gatsby-theme-about/templates/bio.jsx:7]: How is this not a lint error? :thinking: jsx files ignored?

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js (hunk 6 above)
Comment (blainekasten) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:149]: actually nvm. I see what's happening here ignore this :)

File: e2e-tests/themes/development-runtime/src/gatsby-theme-about/templates/bio.jsx (hunk 3 above)
Comment (pvdz) [reply e2e-tests/themes/development-runtime/src/gatsby-theme-about/templates/bio.jsx:7]: (It doesn't show in the discussion part, but if you look at the actual diff it'll show you that there is no trailing newline)

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js (hunk 4 above)
Comment (laurieontech) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:122]: 100% agree. It's on our radar to rewrite all of this, but didn't want to bundle that with the bug fix.
