### PR TITLE
Fix `gatsby-remark-prismjs` highlight bug

### LINKED ISSUE #1917: gatsby-remark-prismjs failed to highlight cpp code
### Problem

`gatsby-remark-prismjs` failed to highlight the following [markdown with cpp code](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/master/src/pages/test-blog-with-cpp-code/index.md):

````plain
## A Sample Cpp Code

```cpp
int sum(int a, int b) {
    return a + b;
}
```
````
> I made a repo([VincentBel/gatsby-prism-cpp-highlight-bug](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug)) to reproduce the issue.  
> Some quick link:
> - [gatsby-config.js](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/master/gatsby-config.js)
> - [package.json](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/master/package.json)

**The result**:

image

and the [generated js file](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/70ad594a341d7591d8a54e6634e8f30a15da7e40/public/test-cpp-code-highlight/index.html#L12-L14):

```html
      <pre class="language-cpp"><code>int sum(int a, int b) {
    return a + b;
}</code></pre>
```

### Env

- OS: macOS Sierra 10.12.6
- node: v6.9.1
- npm: 5.3.0
- yarn: 0.27.5
- gatsby version:

```js
"gatsby": "^1.9.7",
"gatsby-remark-prismjs": "^1.2.1",
"gatsby-source-filesystem": "^1.4.4",
"gatsby-transformer-remark": "^1.7.2",
```

### PR DESCRIPTION
**Pull request by VincentBel**
Resolves #1917.

I use `gatsby-dev-cli` to test it in the [demo repo](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug), and it works now.

image

> At first I forgot to clear the cache, and it drove me crazy. 😹

### CODE REVIEW

File: packages/gatsby-remark-prismjs/src/__tests__/load-prism-language.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+  it(`throw if language not support`, () => {
+    expect(() => loadPrismLanguage(`imnotalanguage`)).toThrow(
+      `Prism doesn't support language 'imnotalanguage'.`
+    )
+  })
+
+  it(`also load the required language`, () => {
+    const language = `cpp`
+    const requiredLanguage = `c`
+    const Prism = require(`prismjs`)
```
Comment (VincentBel) [inline packages/gatsby-remark-prismjs/src/__tests__/load-prism-language.js]: I'd like to isolate the `prismjs` module for each test so that tests won't affect each other. But it seems no easy way. any ideas? @KyleAMathews

Comment (KyleAMathews) [reply packages/gatsby-remark-prismjs/src/__tests__/load-prism-language.js]: Eh, dunno. Not enough of a Jest expert to know how to do this.

Comment (KyleAMathews) [reply packages/gatsby-remark-prismjs/src/__tests__/load-prism-language.js]: Ooo… but now I am :-) https://facebook.github.io/jest/docs/en/configuration.html#resetmodules-boolean

Comment (KyleAMathews) [reply packages/gatsby-remark-prismjs/src/__tests__/load-prism-language.js]: `jest.resetModules()`

File: packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js [hunk 2]
```diff
@@ -1,5 +1,4 @@
 const parseLineNumberRange = require(`../parse-line-number-range`)
-const highlightCode = require(`../highlight-code`)
 
 describe(`highlight code and lines with PrismJS`, () => {
   it(`parses numeric ranges from the languages variable`, () => {
```
Comment (VincentBel) [inline packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js]: @KyleAMathews Besides, I think these tests are some as, Why duplicate here?

https://github.com/gatsbyjs/gatsby/blob/ca12b4dedefd386943c725561037c0dcac44c4a6/packages/gatsby-remark-prismjs/src/__tests__/parse-line-number-range.js#L4-L43

Comment (VincentBel) [inline packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js]: @KyleAMathews Besides, I think these tests are some as, Why duplicate here?

https://github.com/gatsbyjs/gatsby/blob/ca12b4dedefd386943c725561037c0dcac44c4a6/packages/gatsby-remark-prismjs/src/__tests__/parse-line-number-range.js#L4-L43

File: packages/gatsby-remark-prismjs/src/__tests__/load-prism-language.js (hunk 1 above)
Comment (VincentBel) [reply packages/gatsby-remark-prismjs/src/__tests__/load-prism-language.js]: @KyleAMathews Works great! and it's ready to review now.

File: packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js (hunk 2 above)
Comment (KyleAMathews) [reply packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js]: If there's duplicates, feel free to PR them away!

**Comment by KyleAMathews** [comment]
Thanks! Merging!
