### PR TITLE
fix(gatsby): add app-data to preload list

### LINKED ISSUE #21176: Difference in performance of site after updating Gatsby. (2.15.x - 2.19.x)
## Description

Performance on thirdandgrove.com drops by about 10-15 lighthouse points when upgrading the gatsby package. Network waterfall is shifted. 

### Steps to reproduce

https://www.webpagetest.org/video/compare.php?tests=200204_D4_cf16d7444d81f724a2e69c1e3859a5b9%2C200204_E4_70154384f010a13c3923b0be293255f4&thumbSize=200&ival=100&end=visual#

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
Adding app-data to the `<link preload` list so we make sure to start our js execution as fast as we can.

This fixes a regression introduced by #16686 

Doing this fix introduces us to the next problem: network congestion and bundle bloat. It's hard to explain on these graphs what to see but you should see images coming in faster and execution of js being done faster because app-data is instantly loaded. I also added video's so it makes it more visible what difference it makes

Gatsby before and after, not much difference but the graph shifts a little.
[webpagetest comparison](https://webpagetest.org/video/compare.php?tests=200217_M4_b208606ca45259620b79429c6ffa2c85%2C200217_ZK_22ce1048dbe4c058f0c66dc2816c2d6f&thumbSize=200&ival=100&end=full)
[video](https://webpagetest.org/video/view.php?id=200217_b5eb7992079e591ba6894811219ecbce6794cd5b)

Third and grove is a bitter better too
[webpagetest comparison](https://webpagetest.org/video/compare.php?tests=200217_0Y_c538bba14b70aab54e3849a77baf275b%2C200217_Y9_991abfa07a1e655658edcd95d8c2304f&thumbSize=200&ival=100&end=full)
[video](https://webpagetest.org/video/view.php?id=200217_8bf5fe7aa9146bf2c711d2aacaa82db4dc42adaa)

When there is no network congestion we can see that we're actually faster
[webpagetest comparison](https://webpagetest.org/video/compare.php?tests=200214_P7_655e0681276b32ee078b86f952afb989%2C200217_7E_66d6fae7c8b9407f4caec9ed4f8c0c84&thumbSize=200&ival=100&end=full)
[video](https://webpagetest.org/video/view.php?id=200214_aa3af0f69f18c63df2067452e9d794bc8cd9ec27)

What's next?
Update netlify plugin to have http preload for page-data & app-data, it should make that a few 100ms faster and looks at our bundle sizes.

## Related Issues
Fixes #21176

### CODE REVIEW

File: packages/gatsby/cache-dir/static-entry.js [hunk 1]
```diff
@@ -334,6 +345,17 @@ export default (pagePath, callback) => {
       />
     )
   }
+  if (appData) {
```
Comment (pieh) [inline packages/gatsby/cache-dir/static-entry.js]: Can it ever bu falsy for production builds? (for develop builds we use `develop-static-entry.js`)

Comment (wardpeet) [reply packages/gatsby/cache-dir/static-entry.js]: Technically not but I just copied the code from page data. I was thinking of going through this file in a later stage and rewrite it a bit.

We don't need this in develop :)

Comment (pieh) [reply packages/gatsby/cache-dir/static-entry.js]: For sure we don't need it for develop (was just mentioning this in case the check was to not include it in develop or something)

File: packages/gatsby/cache-dir/static-entry.js [hunk 2]
```diff
@@ -168,8 +174,13 @@ export default (pagePath, callback) => {
   }
 
   const pageDataRaw = fs.readFileSync(getPageDataFile(pagePath))
-  const pageData = JSON.parse(pageDataRaw)
+  const pageData = JSON.parse(pageDataRaw.toString())
   const pageDataUrl = getPageDataUrl(pagePath)
+
+  const appDataRaw = fs.readFileSync(getAppDataFile())
+  const appData = JSON.parse(appDataRaw.toString())
+  const appDataUrl = getAppDataUrl()
```
Comment (pieh) [inline packages/gatsby/cache-dir/static-entry.js]: The app data stuff should is global, so we shouldn't have to re-read same file seperetaly for each html page - so I think we could move this outside of this function and have in module scope? Or alternatively have some memoization for it?

Comment (wardpeet) [reply packages/gatsby/cache-dir/static-entry.js]: That's a good idea

**Comment by blainekasten** [comment]
Does this config option affect this? https://www.gatsbyjs.org/docs/browser-apis/#disableCorePrefetching

**Comment by wardpeet** [comment]
> Does this config option affect this? gatsbyjs.org/docs/browser-apis/#disableCorePrefetching

Thanks for the reminder but no. This is only used when the page is loaded and we preload other pages. For example when you hit a page we prefetch all page-data's for links that are visible on the screen.
