### PR TITLE
fix(gatsby): honor flags disabled via config when deciding wether to add included flags

### LINKED ISSUE #30950: Configuration flag interdependencies (unexpected activation of DEV_SSR)
## Description

Using the following configuration in `v2.32.12` or `v3.2.1` results in `DEV_SSR` being enabled unexpectedly and without a warning that one of the other flags might require DEV_SSR:

```js
module.exports = {
  flags: {
    DEV_SSR: false,
    FAST_DEV: true,
    PARALLEL_SOURCING: true,
  },
}
```

Here's a reproduction using `gatsby new` with no starter and the flags set in `gatsby-config.js`. Running `gatsby develop` in the root of this repo results in the following build output:

> info The following flags are active:
> - FAST_DEV · Enable all experiments aimed at improving develop server start time
> - PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/parallel-sourcing-feedback)) ·
> Run all source plugins at the same time instead of serially. For sites with multiple source plugins,
> this can speedup sourcing and transforming considerably.
> - DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on
> full reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds.
> - PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't
> delete the downloaded files cache when changing gatsby-node.js & gatsby-config.js files.
> - PRESERVE_WEBPACK_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't delete
> webpack's cache when changing gatsby-node.js & gatsby-config.js files.

### Expected result

I'd expect SSR in development to be disabled or for there to be a descriptive error thrown conveying that one of the other flags requires DEV_SSR to be enabled.

### Actual result

DEV_SSR is activated and shown to be active via the `develop` command output as though the flag was not ever configured

### Environment

> gatsby: ^2.32.12 => 2.32.12

or

> gatsby: ^3.2.1 => 3.2.1

### PR DESCRIPTION
**Pull request by pieh**
## Description

1. Allows disabling included flags via gatsby-config (i.e. when `FAST_DEV` is enabled users couldn't disable `DEV_SSR`).

2. This also fixes some issues when printing information about other available flags. Number didn't match, sometimes information was not printed etc (noticed when I was adding tests for 1.)

## Related Issues

Fixes #30950

### CODE REVIEW

File: packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap [hunk 1]
```diff
@@ -247,6 +252,9 @@ flags: {
 The following flags were automatically enabled on your site:
 - PARTIAL_RELEASE · (Umbrella Issue (test)) · test
 - PARTIAL_RELEASE_ONLY_NEW_LODASH · (Umbrella Issue (test)) · test
+
+There is one other flag available that you might be interested in:
+- YET_ANOTHER · (Umbrella Issue (test)) · test
```
Comment (pieh) [inline packages/gatsby/src/utils/__tests__/__snapshots__/handle-flags.ts.snap:257]: example of suggestion not being displayed due to bad condition check we had before

File: packages/gatsby/src/utils/__tests__/handle-flags.ts [hunk 2]
```diff
@@ -261,12 +261,10 @@ describe(`handle flags`, () => {
       - ALWAYS_OPT_IN · (Umbrella Issue (test)) · test
       - DEV_SSR · (Umbrella Issue (https://github.com/gatsbyjs/gatsby/discussions/28138)) · SSR pages on full reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds.
 
-      There are 5 other flags available that you might be interested in:
+      There are 3 other flags available that you might be interested in:
       - FAST_DEV · Enable all experiments aimed at improving develop server start time
       - ALL_COMMANDS · (Umbrella Issue (test)) · test
       - YET_ANOTHER · (Umbrella Issue (test)) · test
-      - PARTIAL_RELEASE · (Umbrella Issue (test)) · test
-      - PARTIAL_RELEASE_ONLY_NEW_LODASH · (Umbrella Issue (test)) · test
```
Comment (pieh) [inline packages/gatsby/src/utils/__tests__/handle-flags.ts:269]: those were specifically disabled, so suggesting those seems hostile to user

File: packages/gatsby/src/utils/handle-flags.ts [hunk 3]
```diff
@@ -122,8 +122,14 @@ const handleFlags = (
...
-          enabledConfigFlags.push(incExp)
-          addIncluded(incExp)
+          const flagIsDisabledByUser =
+            typeof configFlags[includedName] !== `undefined` &&
+            !configFlags[includedName]
+
+          if (!flagIsDisabledByUser) {
+            enabledConfigFlags.push(incExp)
+            addIncluded(incExp)
+          }
```
Comment (pieh) [inline packages/gatsby/src/utils/handle-flags.ts:132]: additional checks to see wether user specifaclly disabled certain flag in config before adding it

File: packages/gatsby/src/utils/__tests__/handle-flags.ts [hunk 4]
```diff
@@ -441,8 +439,120 @@ describe(`handle flags`, () => {
         - FAST_DEV · Enable all experiments aimed at improving develop server start time
         - ALL_COMMANDS · (Umbrella Issue (test)) · test
         - YET_ANOTHER · (Umbrella Issue (test)) · test
-        - PARTIAL_RELEASE · (Umbrella Issue (test)) · test
-        - PARTIAL_RELEASE_ONLY_NEW_LODASH · (Umbrella Issue (test)) · test
```
Comment (pieh) [inline packages/gatsby/src/utils/__tests__/handle-flags.ts:445]: case of number not matching - we were printing `There are 3 other flags` and then list 5 flags

**Review by wardpeet — APPROVED** [review]
LGTM, thanks!
