### PR TITLE
fix(gatsby-remark-copy-linked-files): respect assetPrefix

### LINKED ISSUE #25918: Asset Prefix does not works on SVG
https://www.gatsbyjs.org/docs/asset-prefix/

## Description
The build command for asset prefix does not work with .svg files. 
If you use `img/demo.svg` in markdown then it get's converted to `https://www.your-domain.com/https:/cdn.your-domain.com/{generated-hash-values}/demo.svg`

### Steps to reproduce

Just add path prefix build on a page which load .svg type images.

### Expected result

If you use `img/demo.svg` in markdown then it should get converted to `https:/cdn.your-domain.com/{generated-hash-values}/demo.svg`

### Actual result

If you use `img/demo.svg` in markdown then it get's converted to `https://www.your-domain.com/https:/cdn.your-domain.com/{generated-hash-values}/demo.svg`. This leads to image returning `4xx`

### Environment

`gatsby build --prefix-paths`

### PR DESCRIPTION
**Pull request by pieh**
## Description

Function that generates urls in `gatsby-remark-copy-linked-files` is not compatible with `assetPrefix` - current path joining result in something like `/https:/cdn.your-domain.com/{generated-hash-values}/demo.svg` (note that first character in front of protocol part).

This PR changes to URL generation to match what `gatsby-plugin-sharp` already do (which is just doing string manipulation, because `pathPrefix` is already passing in form that allows for it - it strips trailing slash always, which means that using `${prefix}/some/path` will work correctly): https://github.com/gatsbyjs/gatsby/blob/8ad565f61ddd64f965513ef1d791c595629740d1/packages/gatsby-plugin-sharp/src/index.js#L142-L145

## Related Issues

Fixes #25918

### CODE REVIEW

File: packages/gatsby-remark-copy-linked-files/src/index.js [hunk 1]
```diff
@@ -58,10 +58,7 @@ const newPath = (linkNode, options) => {
 const newLinkURL = (linkNode, options, pathPrefix) => {
   const { destinationDir } = options
   const destination = getDestination(linkNode, destinationDir)
-  const linkPaths = [`/`, pathPrefix, destination].filter(lpath =>
-    lpath ? true : false
-  )
-  return path.posix.join(...linkPaths)
+  return `${pathPrefix ? pathPrefix : ``}/${destination}`
```
Comment (pieh) [inline packages/gatsby-remark-copy-linked-files/src/index.js:61]: Actual fix

File: packages/gatsby-remark-copy-linked-files/src/__tests__/index.js [hunk 2]
```diff
@@ -303,11 +394,12 @@ describe(`gatsby-remark-copy-linked-files`, () => {
     it(`copies file to the destination supplied by destinationDir`, async () => {
       const markdownAST = remark.parse(`![some absolute image](${imagePath})`)
       const validDestinationDir = `path/to/dir`
+      const fileLocationPart = `some-hash/${imageName}.gif`
       const expectedNewPath = path.posix.join(
         process.cwd(),
         `public`,
         validDestinationDir,
-        `/undefined/undefined.gif`
+        fileLocationPart
```
Comment (pieh) [inline packages/gatsby-remark-copy-linked-files/src/__tests__/index.js:402]: this and other adjustments are not necessary for this PR, but as I looked to add cases for assetPrefix I noticed those `undefined` there in expecteted strings and thought that it doesn't inspire a lot of confidence in those tests so I adjusted tests to specify `internal.contentDigest` and `name` fields on File nodes so those are more specific assertions

**Review by pvdz — APPROVED** [review]
lgtm

File: packages/gatsby-remark-copy-linked-files/src/index.js (hunk 1 above)
Comment (vladar) [reply packages/gatsby-remark-copy-linked-files/src/index.js:61]: Is it possible that `pathPrefix` ends with `/`? If so, we may want to keep `path.posix.join`?

Comment (pieh) [reply packages/gatsby-remark-copy-linked-files/src/index.js:61]: When we read config this massages values to strip trailing slash:

https://github.com/gatsbyjs/gatsby/blob/8ad565f61ddd64f965513ef1d791c595629740d1/packages/gatsby/src/joi-schemas/joi.ts#L17-L34

This is done to avoid having to deal with quirks like that in all the plugins

Comment (vladar) [reply packages/gatsby-remark-copy-linked-files/src/index.js:61]: Makes sense, thanks!

**Review by vladar — APPROVED** [review]

**Comment by wardpeet** [comment]
Successfully published:
 - gatsby-remark-copy-linked-files@2.3.16
