### PR TITLE
fix(gatsby): do not cause stack overflow over circular refs

### LINKED ISSUE #11364: gatsby-source-contentful: Maximum call stack size exceeded
Not sure if this is a bug or not. And unfortunately I don't really have much time this week to investigate. But I thought I might as well put this up here.

I'm using the `gatsby-source-contentful` plugin. In my contentful content model I'm having two content types, both with the new Richtext editor. Problems occurs when I have entry links to each other.

To be more clear. Say I have two pages, home and about. If I link from home -> about and from about -> home inside the Richtext editor I get this error.

Like I said before. Not sure if this is a bug.

Here's a callstack https://pastebin.com/fD676e6j

### Environment (if relevant)
```
  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.0 - /var/folders/vh/cx86q1vs2xz5rxlf8b8cny2r0000gn/T/yarn--1548706327929-0.8647198662198463/node
    Yarn: 1.13.0 - /var/folders/vh/cx86q1vs2xz5rxlf8b8cny2r0000gn/T/yarn--1548706327929-0.8647198662198463/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.3
  npmPackages:
    gatsby: 2.0.98 => 2.0.98 
    gatsby-plugin-layout: 1.0.11 => 1.0.11 
    gatsby-plugin-offline: 2.0.21 => 2.0.21 
    gatsby-plugin-react-helmet: 3.0.5 => 3.0.5 
    gatsby-plugin-styled-components: 3.0.4 => 3.0.4 
    gatsby-source-contentful: 2.0.26 => 2.0.26 
    gatsby-transformer-remark: 2.2.0 => 2.2.0 
```

`gatsby-config.js`:
```
plugins: [
        {
            resolve: 'gatsby-plugin-styled-components',
            options: {
                displayName: false
            }
        },
        'gatsby-plugin-react-helmet',
        {
            resolve: 'gatsby-plugin-layout',
            options: {
                component: require.resolve('./src/components/Layout')
            }
        },
        {
            resolve: 'gatsby-source-contentful',
            options: {
                spaceId: '<spaceID>',
                accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
            }
        },
        {
            resolve: '@contentful/gatsby-transformer-contentful-richtext',
            options: contentfulRenderOptions
        },
        'gatsby-plugin-offline'
    ]
```

### PR DESCRIPTION
**Pull request by pvdz**
This allows nodes to have a circular dependency without causing stack overflow exceptions when traversing the graph.

Fixes #11364 (hopefully). Will have to confirm this after publishing an update.

Causes somewhere between 0 and 1% perf regression for our 25k page benchmark site. But it's within variance of benchmarking, not even sure if there's a noticable regression at all. See this table:

The first two columns are on master (at the time of writing), the third and fourth column are after this change. (The `(govbook)` lines are printed from within the benchmark site). Shrug.

```
    master:                |      branch:                  |
------------------------------------------------------------------------------------------------------
     0.025s        0.026s  |       0.026s         0.030s   |   success open and validate gatsby-configs 
     0.365s        0.361s  |       0.333s         0.362s   |   success load plugins 
     0.004s        0.004s  |       0.005s         0.005s   |   success onPreInit 
     0.012s        0.011s  |       0.011s         0.011s   |   success delete html and css files from previous builds 
     0.008s        0.008s  |       0.008s         0.008s   |   success initialize cache 
     0.025s        0.021s  |       0.018s         0.027s   |   success copy gatsby files 
     1.420s        1.530s  |       1.432s         1.655s   |   success onPreBootstrap 
     0.003s        0.004s  |       0.007s         0.006s   |   success createSchemaCustomization 
    11.587s       12.116s  |      12.048s        13.105s   |   success source and transform nodes 
     0.431s        0.491s  |       0.304s         0.332s   |   success building schema 
  560.858ms     591.782ms  |    617.005ms      668.053ms   |   (govbook) initial graphql query
    25.176s       27.344s  |      24.406s        27.665s   |   success govbook/gatsby-node.js 
25198.194ms   27369.563ms  |  24429.250ms    27689.333ms   |   (govbook) created pages
    5.316ms       5.221ms  |      5.142ms        5.059ms   |   (govbook) _wrapGraphql
   35.774ms      32.683ms  |     31.356ms       34.587ms   |   (govbook) _graphql
    2.906ms       3.225ms  |      2.761ms        3.011ms   |   (govbook) _createMarkdownPages
25819.979ms   28018.942ms  |  25102.183ms    28422.466ms   |   (govbook) total exports.createPages
   104.950s      110.702s  |     105.509s       112.224s   |   success createPages 
     0.399s        0.175s  |       0.383s         0.387s   |   success createPagesStatefully 
     0.002s        0.002s  |       0.002s         0.002s   |   success onPreExtractQueries 
     0.316s        0.181s  |       0.356s         0.306s   |   success update schema 
     0.340s        0.146s  |       0.359s         0.319s   |   success extract queries from components 
     0.831s        0.545s  |       0.951s         0.825s   |   success write out requires 
     0.002s        0.002s  |       0.002s         0.002s   |   success write out redirect data 
     0.124s        0.095s  |       0.125s         0.119s   |   success Build manifest and related icons 
     2.233s        1.516s  |       2.303s         2.193s   |   success onPostBootstrap 
   125.512s      130.371s  |     126.555s       134.379s   |   info bootstrap finished 
    13.429s       12.381s  |      14.701s        12.956s   |   success Building production JavaScript and CSS bundles 
     0.005s        0.005s  |       0.008s         0.008s   |   success Rewriting compilation hashes 
    85.845s       95.184s  |         30/s        91.392s   |   success run queries 
    24.421s       27.864s  |      25.243s        25.466s   |   success Building static HTML for pages 
   237.088s      254.554s  |      245.77s       252.497s   |   info Done building 
```

### CODE REVIEW

**Comment by pvdz** [comment]
Thanks @cameron-martin for the inspiration!

File: packages/gatsby/src/schema/infer/inference-metadata.js [hunk 1]
```diff
@@ -113,19 +113,47 @@ const getType = (value, key) => {
...
-const updateValueDescriptor = ({
-  nodeId,
-  key,
-  value,
-  operation = `add`,
-  descriptor = {},
-}) => {
+const updateValueDescriptor = (
+  { nodeId, key, value, operation = `add` /*: add | del*/, descriptor = {} },
+  path = []
```
Comment (pieh) [inline packages/gatsby/src/schema/infer/inference-metadata.js]: other places use `Set` for keeping track if already visited things, was there special reason to use array here?

File: packages/gatsby/src/db/sanitize-node.js [hunk 2]
```diff
@@ -3,19 +3,25 @@ const _ = require(`lodash`)
...
  * Make data serializable
  * @param {(Object|Array)} data to sanitize
+ * @param {boolean} isNode = true
+ * @param {Set<string>} path = new Set
  */
-const sanitizeNode = (data, isNode = true) => {
+const sanitizeNode = (data, isNode = true, path = new Set()) => {
   const isPlainObject = _.isPlainObject(data)
 
+  path.add(data)
```
Comment (pieh) [inline packages/gatsby/src/db/sanitize-node.js]: Should this be inside `if (isPlainObject || _.isArray(data))` block (where we want to traverse things)? If it's not we might add primitives here and wrongly omit some fields as we are traversing because of that?

File: packages/gatsby/src/schema/infer/inference-metadata.js (hunk 1 above)
Comment (pvdz) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: I benchmarked it, this seemed more efficient (although it could be variation). Perhaps because this is an explicit push/pop stack, where the other is arbitrary push.

File: packages/gatsby/src/db/sanitize-node.js (hunk 2 above)
Comment (pvdz) [reply packages/gatsby/src/db/sanitize-node.js]: That's a good point! I'll change that.

**Comment by pvdz** [comment]
Rebased
