### PR TITLE
fix: prevent invalid graphql field names from being created

### LINKED ISSUE #2925: [gatsby-plugin-netlify] error when building schema
`gatsby --version`: 1.1.20
`node --version`: 8.6.0
## Summary

I am trying to set some basic security headers on Netlify, using `gatsby-plugin-netlify` and so far without much success. It appears to run into some conflicts with the GraphQL Schema builder.

My config related to the plugin:
```javascript
{
      resolve: 'gatsby-plugin-netlify',
      options: {
        headers: {
          '/*': [
            `Content-Security-Policy: script-src 'self'`,
            `X-Frame-Options: DENY`,
            `X-Xss-Protection: 1; mode=block`,
            `X-Content-Type-Options: nosniff`,
            `Referrer-Policy: same-origin`,
            `Expect-CT: enforce,max-age=604800`
          ]
       }
    }
}
```

The error I'm getting when running `gatsby develop` or `gatsby build`:

```bash
⠁ Name "__" must not begin with "__", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.
    at assertValidName (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\utilities\assertValidName.js:37:19)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\definition.js:693:44
    at Array.forEach (<anonymous>)
    at GraphQLInputObjectType._defineFieldMap (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\definition.js:692:16)
    at GraphQLInputObjectType.getFields (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\definition.js:681:49)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:223:26)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:226:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:224:28)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:226:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:224:28)
    at Array.reduce (<anonymous>)
    at C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:216:36
    at Array.forEach (<anonymous>)
    at typeMapReducer (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:209:27)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\graphql\type\schema.js:97:34)
    at _callee$ (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\gatsby\dist\schema\index.js:52:20)
    at tryCatch (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\kovacse\.babun\cygwin\home\kovacse\projects\blog\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:117:21)
```

This particular time it was running on a Windows machine but the issue persists on my Linux machine too so I would imagine the Netlify servers wouldn't be able to make use of this either.

I believe the issue is caused by the plugin prefixing some things with "__", thus tripping up GraphQL Builder when it tries to build the schema. I did place the config part as the last plugin, as suggested.

### LINKED ISSUE #3487: "/*" as key leads to GraphQL warning
## Description

If one adds in gatsby-config an option with key `/*` (like: `'/*': "SomeStuff"`) this leads to the following GraphQL warning:
> Name "\__" must not begin with "__", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.

Notice that it does not matter to which plugin I pass this object.

### Environment

Gatsby version: 1.9.153
Node.js version: 9.4.0
Operating System: Linux, Windows

### File contents:

`gatsby-config.js`: 
```
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,    // Just a demo, works for all plugins
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
        '/*': "SomeStuff"         // This leads to warning
      },
    },
  ]
```

### Actual result

The full warning text is in #2925

### Expected behavior

No warning

### Steps to reproduce

1\. add the key `'/*'` to a plugin-option

### PR DESCRIPTION
**Pull request by DSchau**
This PR prevents invalid GraphQL field names from being created, at least in certain circumstances. Field names that were _only_ invalid characters were being translated into `_{STR_LENGTH}`, e.g. `/*` was being translated to `__`, `/*.js` was translated to `___js`, etc.

Note: This will currently transform (for example) `/*` into `_` so I'm not quite sure what the best course of action is to replace that, or what's preferred there.

Fixes #3487; Fixes #2925

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This looks great! My only worry is that it adds a slight risk of duplicate keys being created e.g. `/*js` and `*js` would be the same.

So to tweak the algorithm slightly — how about if there's more than one initial underscore, we replace the ones after the initial with dashes?

File: packages/gatsby/src/schema/__tests__/create-key.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+      [`~/path/to/some/module`, `_-path-to-some-module`],
+      [`/*`, `_-`],
+      [`/*.js`, `_--js`],
+    ].forEach(([input, output]) => {
+      expect(createKey(input)).toBe(output)
+    })
+  })
+
+  it(`does not generate same key for different input`, () => {
+    ;[[`/*.js`, `*js`]].forEach(([one, two]) => {
```
Comment (DSchau) [inline packages/gatsby/src/schema/__tests__/create-key.js]: Could probably _not_ have written this as an array since I'm only testing one sample input. Oh well 🤷‍♂️

**Comment by DSchau** [comment]
@KyleAMathews done!

**Comment by KyleAMathews** [comment]
Looks great! Thanks!

**Comment by DSchau** [comment]
@KyleAMathews so I pulled this down, and I think I should've left it underscores!

I'm seeing the following error:

> error Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "_--html" does not.

Not sure how to fix it beyond reverting back to underscores (which has a possibility of collision!). Is that regular expression valid, or is `-` a valid character in GraphQL?

**Comment by DSchau** [comment]
[Comes direct from GraphQL](https://github.com/graphql/graphql-js/blob/master/src/utilities/assertValidName.js#L14), so definitely that's a valid expression 🙃

**Comment by KyleAMathews** [comment]
oh right... grr GraphQL

Ok, let's just change the subsequent underscores to "x" I guess.
