### PR TITLE
chore: Fix ESLint warnings

### LINKED ISSUE #10943: [gatsby/www]: Fix ESLint warnings
## Problem

When running `yarn lint:code` on Gatsby's repository you'll be greeted with some ESLint warnings. It would be nice to fix those warnings!

```
$ eslint --ignore-path .gitignore --ignore-path .prettierignore --ext .js,.jsx .

/mnt/e/Lennart/Development/GitHub/gatsby/examples/image-processing/src/pages/index.js
  211:68  warning  HTML entities must be escaped  react/no-unescaped-entities
  211:76  warning  HTML entities must be escaped  react/no-unescaped-entities
  250:40  warning  HTML entities must be escaped  react/no-unescaped-entities
  250:44  warning  HTML entities must be escaped  react/no-unescaped-entities
  259:24  warning  HTML entities must be escaped  react/no-unescaped-entities
  259:32  warning  HTML entities must be escaped  react/no-unescaped-entities
  259:43  warning  HTML entities must be escaped  react/no-unescaped-entities
  259:51  warning  HTML entities must be escaped  react/no-unescaped-entities
  270:24  warning  HTML entities must be escaped  react/no-unescaped-entities
  270:32  warning  HTML entities must be escaped  react/no-unescaped-entities
  270:43  warning  HTML entities must be escaped  react/no-unescaped-entities
  270:51  warning  HTML entities must be escaped  react/no-unescaped-entities

/mnt/e/Lennart/Development/GitHub/gatsby/examples/using-contentful/src/pages/image-api.js
   16:21  warning  HTML entities must be escaped  react/no-unescaped-entities
   65:59  warning  HTML entities must be escaped  react/no-unescaped-entities
   68:15  warning  HTML entities must be escaped  react/no-unescaped-entities
   69:28  warning  HTML entities must be escaped  react/no-unescaped-entities
   69:36  warning  HTML entities must be escaped  react/no-unescaped-entities
  228:16  warning  HTML entities must be escaped  react/no-unescaped-entities

/mnt/e/Lennart/Development/GitHub/gatsby/examples/using-contentful/src/pages/index.js
  45:21  warning  HTML entities must be escaped  react/no-unescaped-entities
  53:27  warning  HTML entities must be escaped  react/no-unescaped-entities

/mnt/e/Lennart/Development/GitHub/gatsby/examples/using-css-modules/src/pages/index.js
  12:14  warning  HTML entities must be escaped  react/no-unescaped-entities

/mnt/e/Lennart/Development/GitHub/gatsby/examples/using-drupal/src/pages/index.js
  129:17  warning  Missing "key" prop for element in iterator  react/jsx-key
  150:34  warning  HTML entities must be escaped               react/no-unescaped-entities
  189:17  warning  Missing "key" prop for element in iterator  react/jsx-key

/mnt/e/Lennart/Development/GitHub/gatsby/examples/using-drupal/src/pages/recipes.js
  13:11  warning  Missing "key" prop for element in iterator  react/jsx-key

/mnt/e/Lennart/Development/GitHub/gatsby/examples/using-drupal/src/templates/recipe.js
  56:23  warning  HTML entities must be escaped               react/no-unescaped-entities
  62:55  warning  Missing "key" prop for element in iterator  react/jsx-key
  69:65  warning  Missing "key" prop for element in iterator  react/jsx-key

/mnt/e/Lennart/Development/GitHub/gatsby/examples/using-redirects/src/pages/index.js
  56:22  warning  HTML entities must be escaped  react/no-unescaped-entities
  56:37  warning  HTML entities must be escaped  react/no-unescaped-entities

/mnt/e/Lennart/Development/GitHub/gatsby/packages/gatsby/cache-dir/static-entry.js
  55:5  warning  Missing "key" prop for element in array  react/jsx-key

/mnt/e/Lennart/Development/GitHub/gatsby/www/src/components/evaluation-table.js
   20:9   warning  Missing "key" prop for element in array  react/jsx-key
  117:17  warning  Missing "key" prop for element in array  react/jsx-key
  118:17  warning  Missing "key" prop for element in array  react/jsx-key
  123:23  warning  Missing "key" prop for element in array  react/jsx-key
  127:23  warning  Missing "key" prop for element in array  react/jsx-key
  164:23  warning  Missing "key" prop for element in array  react/jsx-key

/mnt/e/Lennart/Development/GitHub/gatsby/www/src/pages/features.js
  46:5  warning  Missing "key" prop for element in array  react/jsx-key
  49:5  warning  Missing "key" prop for element in array  react/jsx-key
  52:5  warning  Missing "key" prop for element in array  react/jsx-key
  55:5  warning  Missing "key" prop for element in array  react/jsx-key
  58:5  warning  Missing "key" prop for element in array  react/jsx-key
  64:5  warning  Missing "key" prop for element in array  react/jsx-key
  67:5  warning  Missing "key" prop for element in array  react/jsx-key
  68:5  warning  Missing "key" prop for element in array  react/jsx-key
  69:5  warning  Missing "key" prop for element in array  react/jsx-key
  70:5  warning  Missing "key" prop for element in array  react/jsx-key

✖ 47 problems (0 errors, 47 warnings)
```

## Solution

Follow the [How to Contribute](https://www.gatsbyjs.org/docs/how-to-contribute/) guide. If you want to validate the fixes in the browser console you'll also need to run the `www` (gatsbyjs.org) site at some point.

To speed up the `www` developing you can pass an env variable for placeholder images. You'll also need to [add a GitHub token](https://github.com/gatsbyjs/gatsby/tree/master/www#environment-variables). In the end your `.env.development` file should contain:

```
GITHUB_API_TOKEN=your-github-token
GATSBY_SCREENSHOT_PLACEHOLDER=true
```

To validate that you fixed the warnings  run `yarn lint:code` in the root of the repo again.

### PR DESCRIPTION
**Pull request by markusguenther**
## Description

Some packages throw aslant warnings and this PR resolve them.

## Related Issues

Fixes #10943

### CODE REVIEW

File: examples/using-drupal/src/pages/index.js [hunk 1]
```diff
@@ -185,8 +186,12 @@ class IndexPage extends React.Component {
                 flexWrap: `wrap`,
               }}
             >
-              {nextFourPromotedRecipes.map(recipe => (
-                <PromotedCard recipe={recipe} columns={2} />
+              {nextFourPromotedRecipes.map((recipe, index) => (
```
Comment (LekoArts) [inline examples/using-drupal/src/pages/index.js]: Discard the `index` here and use `recipe.fields.slug` for the key.
It's unique: https://github.com/gatsbyjs/gatsby/blob/master/examples/using-drupal/gatsby-node.js#L7

File: examples/using-drupal/src/pages/recipes.js [hunk 2]
```diff
@@ -9,8 +9,8 @@ const AllRecipes = ({ data }) => (
     <Container>
       <h1>Recipes</h1>
       <ul>
-        {data.allRecipes.edges.map(({ node }) => (
-          <li>
+        {data.allRecipes.edges.map(({ node }, index) => (
```
Comment (LekoArts) [inline examples/using-drupal/src/pages/recipes.js]: Use `node.fields.slug` for the key

File: examples/using-drupal/src/pages/index.js (hunk 1 above)
Comment (markusguenther) [reply examples/using-drupal/src/pages/index.js]: Thanks for the advice :)
