### PR TITLE
fix(gatsby-cli): normalize case of windows drive letter

### LINKED ISSUE #19863: After npm update to 2.18.5, ERROR #85910 GRAPHQL  Multiple "root" queries found in file: "IndexPageTemplate" and "IndexPageTemplate".
##  Description

I was seeing the problem described in #19748 , but after npm update picked up 2.18.5 the build failed with a different error (which was repeated for several files):

ERROR #85910 GRAPHQL

Multiple "root" queries found in file: "IndexPageTemplate" and "IndexPageTemplate".
Only the first ("IndexPageTemplate") will be registered.

Instead of:
1 | query IndexPageTemplate {
2 | bar {
3 | #...
4 | }
5 | }
6 |
7 | query IndexPageTemplate {
8 | foo {
9 | #...
10 | }
11 | }

Do:
1 | query indexPageTemplateAndIndexPageTemplate {
2 | bar {
3 | #...
4 | }
5 | foo {
6 | #...
7 | }
8 | }

File: src\templates\index-page.js

### Steps to reproduce

1. clone starter [repo](https://github.com/netlify-templates/gatsby-starter-netlify-cms)
2. npm install
3. npm update
4. npm run build

### Expected result

build should complete

### Actual result

build failed

### Environment

  System:
    OS: Windows 8.1 6.3.9600
    CPU: (4) x64 Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.0
  npmPackages:
    gatsby: ^2.18.5 => 2.18.5 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-netlify: ^2.1.27 => 2.1.27 
    gatsby-plugin-netlify-cms: ^4.1.30 => 4.1.30 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sass: ^2.1.24 => 2.1.24 
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4 
    gatsby-remark-copy-linked-files: ^2.1.31 => 2.1.31 
    gatsby-remark-images: ^3.1.34 => 3.1.34 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.3 
    gatsby-source-filesystem: ^2.1.39 => 2.1.39 
    gatsby-transformer-remark: ^2.6.38 => 2.6.38 
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6

### PR DESCRIPTION
**Pull request by vladar**
## Description

This PR ensures that the current working directory on Windows always has an uppercase drive letter (i.e., C: vs. c:).

### Motivation
Different utils like "true-case-path", "normalize-path", "slash" treat Windows drive letter differently. "true-case-path" will [uppercase](https://github.com/Profiscience/true-case-path/issues/3), others usually don't care. As a result path normalization produces different results depending on current cwd (c: vs. C:) which manifests in weird issues that are very hard to debug (see related issues bellow).

Ad-hoc fixes like the one introduced in #17492 address the part of the problem but anytime you want to compare a path that is normalized this way you must remember about it and normalize the other side of the comparison the same way.

This is not maintainable (and is especially annoying for those who do not use Windows as they cannot even test it). Things get even worse because we can't really control community plugins or site code but everything should still be working even with a different set of libraries.

This PR is meant to be a general solution to this problem and (hopefully) fix it for good.

### Documentation
N/A (as this is a bugfix)

## Related Issues
https://github.com/Profiscience/true-case-path/issues/3
#16721
#17811
Fixes #19863

### CODE REVIEW

**Comment by vladar** [comment]
@wardpeet Mind reviewing? As you are my companion in the misfortune of using Windows 😃

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+    }
+  }
+}
+
+function driveLetterToUpperCase(path) {
+  const segments = path.split(`:\\`)
+  path =
+    segments.length > 1
+      ? segments.shift().toUpperCase() + `:\\` + segments.join(`:\\`)
+      : path
```
Comment (blainekasten) [inline packages/gatsby-cli/src/util/normalize-windows-cwd.js]: somewhat a nit, but it's general a bad practice to reassign arguments. Seems like the easiest thing here is to just make this return here instead of assigning

Comment (vladar) [reply packages/gatsby-cli/src/util/normalize-windows-cwd.js]: Oh, right. Thanks for the suggestion!

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+    }
+
+    if (normalizedCwd !== process.cwd()) {
+      report.warn(
+        report.stripIndent(`
+          Your working directory has a lowercase drive letter:
+            "${cwd}".
+          For stable cross-platform builds we recommend switching it to:
+            "${normalizedCwd}".
+        `)
```
Comment (pieh) [inline packages/gatsby-cli/src/util/normalize-windows-cwd.js]: I wonder about value of this warning: so far our strategy for stable builds is to use relative paths with unix-style slashes in places that would affect build artifacts - for example: https://github.com/gatsbyjs/gatsby/blob/47d2a8d39b96e151036dcb0e01e3cbcf3be8d1b0/packages/gatsby/src/bootstrap/requires-writer.js#L169-L177

which should render drive letter case irrelevant for output?

Is there actual build differences if you use differently cased drive letter with your PR right now?

In case this still matters - can we provide actual commands for user to run to change cwd? (as user might need to switch to tmp dir as in code you have to change dir programatically)

**Comment by wardpeet** [comment]
How do I test this?

**Comment by vladar** [comment]
@wardpeet Switch to lowercase `c:` in cmd/cmder and run default blog starter (without this PR it should produce the error described in #19863)

There is also another repo: https://github.com/murnana/gatsby-bug-repo/tree/feature/gatsbyjs%2319863 which produces webpack warnings on `gatsby develop`

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js (hunk 2 above)
Comment (vladar) [reply packages/gatsby-cli/src/util/normalize-windows-cwd.js]: Oh, right. I guess it only happens in develop here:

https://github.com/gatsbyjs/gatsby/blob/47d2a8d39b96e151036dcb0e01e3cbcf3be8d1b0/packages/gatsby/src/bootstrap/requires-writer.js#L147-L161

But it all started from stable builds issue in https://github.com/gatsbyjs/gatsby/pull/15876 - so that's the initial source of confusion. I will rephrase:

 `For stable cross-platform builds we recommend switching it to` to `For consistent development experience` or do you have other suggestions?

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+      )
+    }
+  }
+}
+
+function driveLetterToUpperCase(path) {
+  const segments = path.split(`:\\`)
+  return segments.length > 1
+    ? segments.shift().toUpperCase() + `:\\` + segments.join(`:\\`)
```
Comment (wardpeet) [inline packages/gatsby-cli/src/util/normalize-windows-cwd.js]: nit, we're using backticks so we can do this ^^
```suggestion
    ? `${segments.shift().toUpperCase()}:\\${segments.join(`:\\`)}`
```

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+ * We can't control community plugins or site code, so everything should be working
+ * even with a different set of libraries.
+ *
+ * Related: https://github.com/Profiscience/true-case-path/issues/3
+ *
+ * 2. Builds save some paths in a cache. If you run the first build from "c:" shell
+ * and then the next one from "C:" shell, you may get a bunch of webpack warnings
+ * because it expects module paths to be case-sensitive.
+ */
+module.exports = function normalizeWindowsCwd() {
```
Comment (wardpeet) [inline packages/gatsby-cli/src/util/normalize-windows-cwd.js]: maybe rename the function to something that explicitly tells us what it does.
```suggestion
module.exports = function ensureWindowsDriveLetterIsUppercase() {
```

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+  if (platform() !== `win32`) {
```
Comment (wardpeet) [inline packages/gatsby-cli/src/util/normalize-windows-cwd.js]: should we move this check to index.ts instead so it shows that we only run this on windows?

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js (hunk 3 above)
Comment (vladar) [reply packages/gatsby-cli/src/util/normalize-windows-cwd.js]: I did it this way at first but felt like it made the readability worse? Do you think it is more readable this way?

Comment (wardpeet) [reply packages/gatsby-cli/src/util/normalize-windows-cwd.js]: i don't have an opinion TBH 😂

File: packages/gatsby-cli/src/util/normalize-windows-cwd.js (hunk 4 above)
Comment (vladar) [reply packages/gatsby-cli/src/util/normalize-windows-cwd.js]: Was something like this at first but then the filename for it got sooo long %) Anyways, it makes sense to do

**Comment by vladar** [comment]
Published in `gatsby-cli@2.8.27`

**Comment by joshdrumz** [comment]
Hi, I hate to comment on a PR that already fixed this issue #19863 but I'm still getting that error.
I previously had the latest version of `gatsby-cli` installed and I downgraded to `gatsby-cli@2.8.27`  and I still get this error.

If there's anything I'm missing here please let me know and thank you in advance.
