### PR TITLE
fix(gatsby-plugin-sitemap): add meaningful error when siteUrl is missing

### LINKED ISSUE #12912: gatsby-plugin-sitemap NoURLProtocolError: Protocol is required
While building the site with gatsby-plugin-sitemap I get the 
```NoURLProtocolError: Protocol is required```
error.

Why?

### PR DESCRIPTION
**Pull request by sbardian**
## Description
Throw a more descriptive error when users do not supply a `siteUrl` property when using `gatsby-plugin-sitemap`

## Related Issues
Fixes #12912

### CODE REVIEW

File: packages/gatsby-plugin-sitemap/src/internals.js [hunk 1]
```diff
@@ -29,6 +29,10 @@ export const runQuery = (handler, query, excludes, pathPrefix) =>
       return page
     })
 
+    if (!r.data.site.siteMetadata.siteUrl) {
+      throw new Error(`SiteMetaData 'siteUrl' property is required`)
+    }
+
     if (r.data.site.siteMetadata.siteUrl) {
```
Comment (sbardian) [inline packages/gatsby-plugin-sitemap/src/internals.js]: I guess we could remove this `if` around `r.data.site.siteMetadata.siteUrl` for removing trailing slashes as well?   Happy to do it if you would like?

Comment (pieh) [reply packages/gatsby-plugin-sitemap/src/internals.js]: it makes sense if we do throw earlier

File: packages/gatsby-plugin-sitemap/src/internals.js [hunk 2]
```diff
@@ -29,6 +29,10 @@ export const runQuery = (handler, query, excludes, pathPrefix) =>
       return page
     })
 
+    if (!r.data.site.siteMetadata.siteUrl) {
+      throw new Error(`SiteMetaData 'siteUrl' property is required`)
```
Comment (pieh) [inline packages/gatsby-plugin-sitemap/src/internals.js]: What do you think about linking to https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/#how-to-use to see example configuration (to provide more context to error)

Comment (sbardian) [reply packages/gatsby-plugin-sitemap/src/internals.js]: Looked around for errors that reference links to docs, but didn't see any (swear have before though)?  If there is a standard format for this please let me know and I'll update it.

File: packages/gatsby-plugin-sitemap/src/internals.js [hunk 3]
```diff
@@ -29,13 +29,17 @@ export const runQuery = (handler, query, excludes, pathPrefix) =>
       return page
     })
 
-    if (r.data.site.siteMetadata.siteUrl) {
-      // remove trailing slash of siteUrl
-      r.data.site.siteMetadata.siteUrl = withoutTrailingSlash(
-        r.data.site.siteMetadata.siteUrl
+    if (!r.data.site.siteMetadata.siteUrl) {
+      throw new Error(
+        `SiteMetaData 'siteUrl' property is required. (https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/#how-to-use)`
```
Comment (LekoArts) [inline packages/gatsby-plugin-sitemap/src/internals.js]: I'd give some more context to this link, something like:

```suggestion
        `SiteMetaData 'siteUrl' property is required. Check out the documentation to see a working example: https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/#how-to-use`
```

**Comment by sbardian** [comment]
Ha! Was going to push a test for this this morning, thanks @wardpeet !

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-plugin-sitemap@2.0.12`
