### PR TITLE
fix(gatsby-recipes): renable e2e test for npm package resource & fix dev/prod resource bug

### LINKED ISSUE #26480: gatsby recipes storybook-ts not working
## Description
The `storybook-ts` Gatsby recipe doesn't seem to be working. I am getting an error and a neverending installation phase.

It also seems to be messing up when writing to `package.json` (see image)

Screenshot 2020-08-15 at 17 58 04

Screenshot 2020-08-15 at 17 58 00

image

### Steps to reproduce

```sh
npx gatsby new gatsby-storybook-test
cd gatsby-storybook-test
npx gatsby recipes storybook-ts --install
```

### Expected result

No error. The recipe installs and configures correctly

### Actual result

Error and neverending installation

### Environment

```sh

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41 
    gatsby-image: ^2.4.15 => 2.4.15 
    gatsby-plugin-manifest: ^2.4.22 => 2.4.22 
    gatsby-plugin-offline: ^3.2.23 => 3.2.23 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.26 => 2.6.26 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12 
```

### PR DESCRIPTION
**Pull request by KyleAMathews**
fixes #26480

### CODE REVIEW

File: packages/gatsby-recipes/src/providers/npm/package.js [hunk 1]
```diff
@@ -48,7 +61,7 @@ const executeInstalls = async root => {
   const depType = installs[0].resource.dependencyType
   const packagesToInstall = types[depType]
   installs = installs.filter(
-    i => !_.some(packagesToInstall, p => i.resource.id === p.resource.id)
+    i => !_.some(packagesToInstall, p => i.resource.name === p.resource.name)
```
Comment (KyleAMathews) [inline packages/gatsby-recipes/src/providers/npm/package.js:64]: this was the main bug — it was filtering out all of the packages so the dev or production packages wouldn't get installed afterwards

File: packages/gatsby-recipes/src/providers/npm/package.js [hunk 2]
```diff
@@ -118,22 +150,19 @@ const create = async ({ root }, resource) => {
 }
 
 const read = async ({ root }, id) => {
-  let packageJSON
-  try {
-    packageJSON = JSON.parse(
-      await fs.readFile(resolveCwd(path.join(id, `package.json`)))
```
Comment (KyleAMathews) [inline packages/gatsby-recipes/src/providers/npm/package.js:124]: this wasn't respecting root before

File: packages/gatsby-recipes/src/providers/npm/package.js [hunk 3]
```diff
@@ -60,34 +74,59 @@ const executeInstalls = async root => {
...
-    })
-  } catch (e) {
-    // A package failed so call the rejects
-    return packagesToInstall.forEach(p => {
-      p.outsideReject(
-        JSON.stringify({
-          message: e.shortMessage,
-          installationError: `Could not install package`,
+  const release = await lock(`package.json`)
+  if (isJest) {
```
Comment (laurieontech) [inline packages/gatsby-recipes/src/providers/npm/package.js:78]: This isn't a great pattern for testing. For one, we should test production code, not a separate path. And two, any test-specific logic should live in testing files rather than the main codebase.

File: packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap [hunk 4]
```diff
@@ -4,7 +4,7 @@ exports[`gatsby-plugin resource all returns plugins as array 1`] = `
 Array [
   Object {
     "_message": "Installed gatsby-source-filesystem in gatsby-config.js",
-    "description": "Gatsby plugin which parses files within a directory for further parsing by other plugins",
+    "description": null,
```
Comment (laurieontech) [inline packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap:7]: Why are all these being set to null?

**Review by laurieontech — COMMENTED** [review]
Left a few comments. Good to know the id vs. name solution for the bug. However, there are some anti-patterns for tests in here.

To get the bug fix in I'd recommend we split this PR. The bug fix (and new test) vs. the testing framework proposed changes.

File: packages/gatsby-recipes/src/providers/npm/package.js (hunk 3 above)
Comment (wardpeet) [reply packages/gatsby-recipes/src/providers/npm/package.js:78]: 👍 We should mock execa and execute the jestCode that you wrote here so the flow inside this file isn't interrupted by an environment check.

File: packages/gatsby-recipes/src/providers/npm/package.js [hunk 5]
```diff
@@ -159,9 +195,23 @@ const destroy = async ({ root }, resource) => {
...
+        isDev: resource.dependencyType === `development`,
+      })
+      // Make mock async
+      setTimeout(() => resolve(), Math.random() * 100)
+    })
+  } else {
+    await execa(`yarn`, [`remove`, resource.name, `-W`], {
+      cwd: root,
+    })
+  }
```
Comment (wardpeet) [inline packages/gatsby-recipes/src/providers/npm/package.js:214]: Same applies here, mock execa. Does this mean this recipe only works in yarn land?

File: packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap (hunk 4 above)
[the remark this answers is not in the document]
Comment (KyleAMathews) [reply packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap:7]: The plugin test apparently relies on the plugin packages being installed to generate the snapshots. So not intentional.

File: packages/gatsby-recipes/src/providers/npm/package.js (hunk 5 above)
Comment (KyleAMathews) [reply packages/gatsby-recipes/src/providers/npm/package.js:214]: `destroy` isn't supported in general for recipes yet as we need a state file which tracks what things are created in order to be sure we know how to destroy all connected resources. `destroy` is only used for tests essentially atm which is why NPM doesn't have a code path yet.

File: packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap (hunk 4 above)
[the remark this answers is not in the document]
Comment (KyleAMathews) [reply packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap:7]: Not sure what I need to install to update them so just reverting

File: packages/gatsby-recipes/src/providers/npm/package-json.js [hunk 6]
```diff
@@ -20,7 +20,7 @@ const writePackageJson = async (root, obj) => {
 }
 
 const create = async ({ root }, { name, value }) => {
-  const release = await lock(`package.json`)
+  const release = await lock(root + `package.json`)
```
Comment (wardpeet) [inline packages/gatsby-recipes/src/providers/npm/package-json.js:23]: Are we sure root ends with a /? `path.join` gives us a bit more certainty.
```suggestion
  const release = await lock(path.join(root, `package.json`))
```

File: packages/gatsby-recipes/src/providers/npm/package.js [hunk 7]
```diff
@@ -60,6 +73,7 @@ const executeInstalls = async root => {
     packageManager: PACKAGE_MANGER,
   })
 
+  const release = await lock(root + `package.json`)
```
Comment (wardpeet) [inline packages/gatsby-recipes/src/providers/npm/package.js:76]:
```suggestion
  const release = await lock(path.join(root, `package.json`))
```

File: packages/gatsby-recipes/src/providers/npm/package.test.js [hunk 8]
```diff
@@ -8,15 +8,15 @@ const resourceTestHelper = require(`../resource-test-helper`)
...
 const root = path.join(os.tmpdir(), uuid.v4())
 fs.mkdirSync(root)
-const pkgResource = { name: `glob` }
+const pkgResource = { name: `bar` }
 
 test(`plan returns a description`, async () => {
   const result = await pkg.plan({ root }, pkgResource)
 
-  expect(result.describe).toEqual(expect.stringContaining(`Install glob`))
+  expect(result.describe).toEqual(expect.stringContaining(`Install bar`))
```
Comment (wardpeet) [inline packages/gatsby-recipes/src/providers/npm/package.test.js:16]: maybe we should go for a small package like https://github.com/developit/dlv. A zero dependency and small module. Feel free to pick anything else, maybe we should publish a noop package to @gatsbyjs

File: packages/gatsby-recipes/src/providers/npm/package.test.js [hunk 9]
```diff
@@ -26,6 +26,18 @@ describe.skip(`npm package resource`, () => {
...
+      pkg.create({ root }, { name: `foo` }),
+      pkg.create({ root }, { name: `bar`, dependencyType: `development` }),
+    ])
+
+    const fooResource = await pkg.read({ root }, `foo`)
+    const barResource = await pkg.read({ root }, `bar`)
+
+    expect(fooResource).toMatchSnapshot()
+    expect(barResource).toMatchSnapshot()
+  }, 20000)
```
Comment (wardpeet) [inline packages/gatsby-recipes/src/providers/npm/package.test.js:40]: Same here, small and real packages :)

File: packages/gatsby-recipes/src/providers/npm/script.js [hunk 10]
```diff
@@ -19,7 +19,7 @@ const writePackageJson = async (root, obj) => {
 }
 
 const create = async ({ root }, { name, command }) => {
-  const release = await lock(`package.json`)
+  const release = await lock(root + `package.json`)
```
Comment (wardpeet) [inline packages/gatsby-recipes/src/providers/npm/script.js:22]:
```suggestion
  const release = await lock(path.join(root, `package.json`))
```

**Review by wardpeet — COMMENTED** [review]
I've added some small comments. I don't really understand the snapshot changes

File: packages/gatsby-recipes/src/providers/npm/package.test.js (hunk 8 above)
Comment (KyleAMathews) [reply packages/gatsby-recipes/src/providers/npm/package.test.js]: haha yeah — I enjoyed the names mostly. Switched.

File: packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap [hunk 11]
```diff
@@ -3291,7 +3291,7 @@ exports[`gatsby-plugin resource e2e plugin resource test with hello world starte
 exports[`gatsby-plugin resource e2e plugin resource test with hello world starter: GatsbyPlugin update 1`] = `
 Object {
   "_message": "Installed gatsby-source-filesystem in gatsby-config.js",
-  "description": "Gatsby plugin which parses files within a directory for further parsing by other plugins",
+  "description": null,
```
Comment (KyleAMathews) [inline packages/gatsby-recipes/src/providers/gatsby/__snapshots__/plugin.test.js.snap:3294]: I investigated this more & this is correct. We don't installed the packages for these & it never should have worked. The only reason we got descriptions before was due to a bug in npm/package.js where it wasn't using the `root` value https://github.com/gatsbyjs/gatsby/pull/26699/files#r479681061

File: packages/gatsby-recipes/src/providers/npm/package.js (hunk 1 above)
Comment (ascorbic) [inline packages/gatsby-recipes/src/providers/npm/package.js:64]:
```suggestion
    i => !packagesToInstall.some(p => i.resource.name === p.resource.name)
```
Any reason to not use `Array.prototype.some`?

Comment (KyleAMathews) [reply packages/gatsby-recipes/src/providers/npm/package.js:64]: nope!

File: packages/gatsby-recipes/src/providers/gatsby/plugin.js [hunk 12]
```diff
@@ -99,8 +99,8 @@ const getNameForPlugin = node => {
   return null
 }
 
-const getDescriptionForPlugin = async name => {
-  const pkg = await readPackageJSON({}, name)
+const getDescriptionForPlugin = async (root, name) => {
+  const pkg = await readPackageJSON({ root }, name)
```
Comment (wardpeet) [inline packages/gatsby-recipes/src/providers/gatsby/plugin.js:103]: I might be reading it wrong but https://github.com/gatsbyjs/gatsby/pull/26699/files#diff-e78f1094a9c69cf340ad7054949c39dcR15 seems to be a string and not an object or do I miss something?
```suggestion
  const pkg = await readPackageJSON(root, name)
```

Comment (KyleAMathews) [reply packages/gatsby-recipes/src/providers/gatsby/plugin.js]: yeah good catch

**Review by ascorbic — APPROVED** [review]
