### PR TITLE
fix(gatsby-plugin-sharp): sort nested options

### LINKED ISSUE #14551: Add DuoTone options to cache key
## Description

On the gatsby-starter (and others) when I set a duotone on an image query...

````
<StaticQuery
    query={graphql`
      query {
        placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
          childImageSharp {
            fluid(
              maxWidth: 200
              duotone: { shadow: "#10c5f8", highlight: "#32CD32" }
            ) {
              ...GatsbyImageSharpFluid
            }
          }
        }
      }
    `}

````

 all works well. However when I change the highlight and shadow colours it still renders the old colour choices.

I have emptied all caches etc to no avail

### Steps to reproduce

Change highlight and shadow colours and rebuild

### Expected result

New colourset should render

### Actual result

Old duotone colurs render

### Environment

System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.3
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.8.3 => 2.8.3
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.5.12

### PR DESCRIPTION
**Pull request by Annnnnieee**
## Description

updated sharp plugin to sort nested options

## Related Issues
Fixes #14551

### CODE REVIEW

File: packages/gatsby-plugin-sharp/src/__tests__/process-file.js [hunk 1]
```diff
@@ -94,5 +94,28 @@ describe(`createArgsDigest`, () => {
...
       testHashEqual(`base64`, { base64: true })
     })
+
+    describe(`argument sorting`, () => {
+      it(`sorts nested arguments`, () => {
+        // take the defaultargsbaseline, add a duotone argument (out of order)
+        const args = {
+          duotone: {
+            highlight: `#32CD32`,
+            shadow: `#10c5f8`,
```
Comment (pieh) [inline packages/gatsby-plugin-sharp/src/__tests__/process-file.js]: For sake of more coverage - could we maybe swap order of `shadow` and `highlight` to make sure nested objects have sorted keys as well?

**Comment by pieh** [comment]
Published `gatsby-plugin-sharp@2.2.3`
