### PR TITLE
fix(gatsby-source-filesystem): fix add/change text

### LINKED ISSUE #17885: Hot reloading not working
## Description

In my Gatsby project with Gatsby `2.15.21` hot reloading is not working when editing existing Markdown files (managed with `gatsby-plugin-mdx`).

### Steps to reproduce

You can reproduce the issue at the specified commit in this project: https://github.com/UNDataForum/main-website/commit/a0ccd162288aa7b945e790b6c6e5aaa7015036e8.  See https://github.com/UNDataForum/main-website/issues/72 for more info on which Gatsby versions at which commit behaved normal and which commit introduced the bug.

When checking out a specific commit, I ran `yarn run clean` (purge cache) and `yarn run purge` (purge dependencies) and then installed dependencies with `yarn` before testing.

### Expected result

Hot reloading should work when editing Markdown files, but it does not work. I would expect to see

```
info changed file at /Users/thilo/Projects/undataforum/main-website/content/posts/connecting-the-dots.md
```
in the log.

### Actual result

Gatsby does not detect the change, but thinks a new file has been added. In the log I see

```
info added file at /Users/thilo/Projects/undataforum/main-website/content/posts/connecting-the-dots.md
```

Hot reloading does not work.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.13.71 => 2.15.21 
    gatsby-source-filesystem: ^2.0.37 => 2.1.26

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
Fixes info messages when filesystem detects changes. When a new file is created we use the `add` word, when updating we use the `changed` verb.

This might lead to confusion

## Related Issues
Fixes #17885

### CODE REVIEW

File: packages/gatsby-source-filesystem/src/gatsby-node.js [hunk 1]
```diff
@@ -171,6 +181,7 @@ See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
   })
 
   watcher.on(`change`, path => {
+    console.log(path)
```
Comment (pvdz) [inline packages/gatsby-source-filesystem/src/gatsby-node.js]: Intentional?

Comment (pieh) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: This does look like debugging helper, which should be removed

File: packages/gatsby-source-filesystem/src/gatsby-node.js [hunk 2]
```diff
@@ -102,6 +103,12 @@ const createFSMachine = (
           }
           createAndProcessNode(path).catch(err => reporter.error(err))
         },
+        updateAndProcessNode(_, { pathType, path }, { state }) {
```
Comment (pieh) [inline packages/gatsby-source-filesystem/src/gatsby-node.js]: Second param to xstate actions should also have `type`. Given that only thing that changes between `createAndProcessNode` and `updateAndProcessNode` is log (added / changed) - maybe we could have single action that changes that part based on action type to not repeat pretty much same action? Similarly with `queueNodeCreation` and `queueNodeUpdating` we could conditionally figure out which `op` to use

Comment (wardpeet) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: Using the proper xstate way by creating another side-effect.

File: packages/gatsby-source-filesystem/src/gatsby-node.js [hunk 3]
```diff
@@ -96,23 +131,17 @@ const createFSMachine = (
...
-            reporter.info(`${pathType} deleted at ${path}`)
-          }
           deletePathNode(path)
         },
         flushPathQueue(_, { resolve, reject }) {
           flushPathQueue().then(resolve, reject)
         },
         queueNodeDeleting(_, { path }) {
-          pathQueue.push({ op: `delete`, path })
+          pathQueue.push({ op: `delete `, path })
```
Comment (pieh) [inline packages/gatsby-source-filesystem/src/gatsby-node.js]: Something weird happened to formatting in latest commit - also check lines 159-166 and L186 (using new line numbers)
```suggestion
          pathQueue.push({ op: `delete`, path })
```

Comment (pieh) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: oh, almost outdated ;)

Comment (wardpeet) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: yeah I was checking my changes and saw something weird

File: packages/gatsby-source-filesystem/src/gatsby-node.js [hunk 4]
```diff
@@ -85,9 +91,32 @@ const createFSMachine = (
...
+                        `changed ${pathType} at ${path}`
+                    ),
+                  ],
+                },
+                CHOKIDAR_UNLINK: {
+                  actions: [
+                    `deletePathNode`,
+                    log(
+                      (_, { pathType, path }) =>
+                        `${pathType} deleted at ${path}`
```
Comment (muescha) [inline packages/gatsby-source-filesystem/src/gatsby-node.js]: why not same style as others `{action} ${pathType} at ${path}`
```suggestion
                        deleted `${pathType} at ${path}`
```

Comment (pieh) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: This just moved what we currently log, but I do think this suggestions makes sense (nicer to read)

Comment (wardpeet) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: Great suggestion @muescha

Comment (pvdz) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: Ehhh, no. You should probably test this before merging. I promise you it does not what you think it does :joy:

**Comment by pvdz** [comment]
Requesting changes to make sure this doesn't get merged as is, just in case the tests don't cover it. The last change was invalid. Not a syntax error but only because of a fluke. It'll be a runtime error for sure.
Feel free to ignore my request besides that.

**Comment by wardpeet** [comment]
I'll do a manual test before I merge, just to be sure

File: packages/gatsby-source-filesystem/src/gatsby-node.js (hunk 4 above)
Comment (muescha) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: @pvdz did you mean my wrong backtick? or other problems?

Comment (muescha) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: .

Comment (pvdz) [reply packages/gatsby-source-filesystem/src/gatsby-node.js]: Yeah the `deleted` was put before the backtick, causing it to become a tagged template. Syntactically valid, but runtime error because `deleted` is not a variable :)
