### PR TITLE
fix(gatsby-plugin-mdx): display better error message for MDX `html` field in development

### LINKED ISSUE #17210: Better error message for MDX `html` field in development
## Summary

Currently, if you query the `html` field of gatsby-plugin-mdx GraphQL nodes in development, you get the following errors in the console and the GraphQL output.

```
ReferenceError: window is not defined
    at evalmachine.<anonymous>:5:41
    at evalmachine.<anonymous>:794:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at module.exports (/Users/fin/Source/my-themed-blog/node_modules/eval/eval.js:73:12)
    at afterEmit (/Users/fin/Source/my-themed-blog/node_modules/gatsby-plugin-mdx/utils/render-html.js:81:22)
…
```

and:

```
gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.
>> This is a bug.
```

This can be confusing, whether you’re mistakenly using `html` in a web page (it should be `body`), or when you’re testing out in development a query for the RSS feed or some place where you _mean_ to use `body`.

The plugin should either throw a more explicit error, or instead return an obviously incorrect, but helpful value for `html`.

### Basic example

For example, the query: 

```graphql
query MyQuery {
  allMdx {
    nodes {
      html
    }
  }
}
```

could return:

```
{
  "allMdx": {
    "nodes": [{
       "html": "<strong>WARNING:</strong> The <code>html</code> field cannot be used in development. Did you mean <code>body</code>? (If you need this node’s HTML content for a non-browser output, such as an RSS feed, you can this query in production mode.)"
    }]
  }
```

This message is not a GraphQL error, which means you can still see the rest of any query you’re working on work. It also contains some HTML, so you can use dev mode to check any encoding or escaping/unescaping you need to do.

### Motivation

This is a confusing error message both for people who tried `html` when they should have used `body` (#16706) and for people who knew they wanted `html` but were confused why the query they were testing errored out (#17175).

### PR DESCRIPTION
**Pull request by vladar**
## Description

This fixes a cryptic error message when a user requests MDX `html` field. There were several issues about it and I also faced it while playing with md files. 

We already have a proper message in the `catch` block, all we need is to throw vs reporting directly to console. Should improve DX a bit.

Fixes #17210 

## Related Issues
Also reported in:
#16706
#17592
#17592
#17175

### CODE REVIEW

File: packages/gatsby-plugin-mdx/gatsby/source-nodes.js [hunk 1]
```diff
@@ -184,7 +184,8 @@ module.exports = (
             return html
           } catch (e) {
             reporter.error(
-              `Error querying the \`html\` field. This field is intended for use with RSS feed generation.
+              `gatsby-plugin-mdx: Error querying the \`html\` field.
```
Comment (sidharthachatterjee) [inline packages/gatsby-plugin-mdx/gatsby/source-nodes.js]: @pieh Shouldn't `reporter.error` already mention the plugin it was called in?

Comment (sidharthachatterjee) [reply packages/gatsby-plugin-mdx/gatsby/source-nodes.js]: Never mind. It will only after https://github.com/gatsbyjs/gatsby/issues/19024 is resolved 

This is okay for now
