### PR TITLE
fix(gatsby-plugin-manifest): generate icons sequentially

### LINKED ISSUE #25216: Gatsby develop stuck on Windows 10
Hello guys. I used Solus OS (linux) and gatsby worked just fine without any problem. Now I'm using Windows 10 (x64). Everything I type "gatsby develop" the first time after turning on my computer, it stucks right here:
```
success write out requires - 0.116s
success write out redirect data - 0.016s
⠋ onPostBootstrap
⠋ Build manifest and related icons
```
And I have to Ctrl+C and then "gatsby develop" again and it works. Always stucks at the first time.

### PR DESCRIPTION
**Pull request by wardpeet**
## Description

On windows icon generation sometimes get stuck and hangs forever, moving to processing images sequentially fixes it. Probalby an issue with open handlers in sharp or how we do the resize.

## Related Issues

Fixes #25216

### CODE REVIEW

File: packages/gatsby-plugin-manifest/src/gatsby-node.js [hunk 1]
```diff
@@ -220,11 +220,9 @@ const makeManifest = async ({
     async function processIconSet(iconSet) {
       // if cacheBusting is being done via url query icons must be generated before cache busting runs
       if (cacheMode === `query`) {
```
Comment (AnilSeervi) [inline packages/gatsby-plugin-manifest/src/gatsby-node.js:222]:
```suggestion
      if (cacheMode === `query` || cacheMode !== `query`) {
```

Comment (AnilSeervi) [reply packages/gatsby-plugin-manifest/src/gatsby-node.js:222]: The other ```if(cacheMode !== `query`)``` statement can be removed by changing the condition as above, because both of them are doing the same thing right?

**Review by AnilSeervi — COMMENTED** [review]
Is this a possible change here!

File: packages/gatsby-plugin-manifest/src/gatsby-node.js (hunk 1 above)
Comment (AnilSeervi) [reply packages/gatsby-plugin-manifest/src/gatsby-node.js:222]: but then this will run always :/

File: packages/gatsby-plugin-manifest/src/gatsby-node.js [hunk 2]
```diff
@@ -237,11 +235,9 @@ const makeManifest = async ({
 
       // if file names are being modified by cacheBusting icons must be generated after cache busting runs
       if (cacheMode !== `query`) {
```
Comment (AnilSeervi) [inline packages/gatsby-plugin-manifest/src/gatsby-node.js:237]:
```suggestion
      if (cacheMode === `name`) {
```

If icons are to be generated when the file names are modified, then isn't it best to `generateIcon` when cacheMode is equal to `name` cuz that's when the filenames do get changed!

**Review by AnilSeervi — CHANGES_REQUESTED** [review]
file names are modified if ```(cacheMode ===`name`)``` https://github.com/gatsbyjs/gatsby/blob/6b56e2b841e70a693bea9ae0b8e2f8089b1de06c/packages/gatsby-plugin-manifest/src/common.js#L63

File: packages/gatsby-plugin-manifest/src/gatsby-node.js (hunk 2 above)
Comment (wardpeet) [reply packages/gatsby-plugin-manifest/src/gatsby-node.js:237]: Thanks for the suggestion but it's a change that's not relevant to this PR. Also, the code above is fine as it will catch anything not matching the above

Comment (AnilSeervi) [reply packages/gatsby-plugin-manifest/src/gatsby-node.js:237]: > Also, the code above is fine as it will catch anything not matching the above.

Makes sense!

**Review by LekoArts — APPROVED** [review]
