### PR TITLE
fix(gatsby): Correct config for svgo plugins whitelist

### LINKED ISSUE #31619: Using sass with svgs as data uris, build reports Css Minimizer Plugin errors
## Description

Using sass with svgs as data uris, e.g. with Bootstrap, running build reports errors in the Css Minimizer Plugin config, related to postcss-svgo.

e.g.
```
Css Minimizer Plugin: postcss-svgo: [SCSS FILE PATH, LIINE NO]: Error: Plugin name should be specified
warn undefined
```

### Steps to reproduce

Install a basic gatsby starter with scss enabled, including gatsby-plugin-sass.
Add bootstrap and import bootstrap.scss in gatsby-browser.js.
Run `npm build`

### Expected result

No errors. Sass built with svgs.

### Actual result

Errors.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 14.1
  npmPackages:
    gatsby: ^3.6.1 => 3.6.1 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0 
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0 
    gatsby-plugin-sass: ^4.6.0 => 4.6.0 
    gatsby-plugin-sitemap: ^4.2.0 => 4.2.0 
```

### PR DESCRIPTION
**Pull request by spikyjt**
## Description

Fix the svgo config as the format for its plugins was not implemented correctly in webpack utils.

## Related Issues

Fixes #31619

### CODE REVIEW

File: packages/gatsby/src/utils/webpack-utils.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ import ReactRefreshWebpackPlugin from "@pmmmwh/react-refresh-webpack-plugin"
 import { getBrowsersList } from "./browserslist"
 import ESLintPlugin from "eslint-webpack-plugin"
 import { cpuCoreCount } from "gatsby-core-utils"
+import { extendDefaultPlugins as svgoExtendDefaultPlugins } from "svgo"
```
Comment (pieh) [inline packages/gatsby/src/utils/webpack-utils.ts:13]: `gatsby` doesn't depend on `svgo` directly - we would need to either explicitely add it to deps ( https://github.com/gatsbyjs/gatsby/blob/2e1f7e325adfe055f828336c247d71404f461be5/packages/gatsby/package.json#L12-L166 ) or maybe figure out some other way to access that function, I just can't find example of that for `minimizerOptions` :(

Comment (spikyjt) [reply packages/gatsby/src/utils/webpack-utils.ts:13]: Fair point. I guess we wouldn't want to introduce that dependency, even though it's implied?
I have a list of the current defaults, so could add that and not use this handy method, it's just more brittle.

**Comment by spikyjt** [comment]
I've refactored to remove the dependency on svgo and use a full plugins list, with the simpler format, so the diff is minimal. This includes removing the extraneous plugins that need additional config, that was never provided.

**Comment by spikyjt** [comment]
@pieh can you help me with why tests are failing? I've rebased, but when running tests locally, it seems to fail on stuff not changed by me. I can't see CircleCI of course.

**Comment by pieh** [comment]
> @pieh can you help me with why tests are failing? I've rebased, but when running tests locally, it seems to fail on stuff not changed by me. I can't see CircleCI of course.

Those for sure are unrelated to your changes, so you don't have to worry about those 2 failing (sorry for confusion, those 2 seem to be recently borked from upstream changes or something like that)

**Comment by spikyjt** [comment]
@pieh ok great, can you merge?

I guess I won't see this in a release any time soon if master is failing build?

**Comment by pieh** [comment]
So i tried running those changes and now istead of
```
Css Minimizer Plugin: postcss-svgo: [SCSS FILE PATH, LIINE NO]: Error: Plugin name should be specified
warn undefined
```

I get
```
Css Minimizer Plugin: postcss-svgo: [SCSS FILE PATH, LIINE NO]: TypeError: Cannot read property
'length' of undefined
warn undefined
```

It looks to me that this setup is also not quite correct?

File: packages/gatsby/src/utils/webpack-utils.ts [hunk 2]
```diff
@@ -675,56 +675,50 @@ export const createWebpackUtils = (
...
+                `convertPathData`,
+                `convertStyleToAttrs`,
+                `convertTransform`,
+                `inlineStyles`,
+                `mergePaths`,
+                `minifyStyles`,
+                `moveElemsAttrsToGroup`,
+                `moveGroupAttrsToElems`,
+                `prefixIds`,
+                `removeAttributesBySelector`,
```
Comment (pieh) [inline packages/gatsby/src/utils/webpack-utils.ts:697]: This is plugin that seems to require additional configuration and which causes `TypeError: Cannot read property
'length' of undefined` error as no selector is defined it seems (actual crash is later down in stack, but here just showing it get some selector which is empty object and cause problems later).
 
Screenshot 2021-05-31 at 14 44 20

Given that this require configuration - it might also need removing or figuring out default config and using object notation with proper params set?

**Comment by spikyjt** [comment]
OK that means there's another plugin requiring additional config that I haven't disabled. I thought I had got rid of all of those! I'll investigate further tonight.

**Comment by pieh** [comment]
> OK that means there's another plugin requiring additional config that I haven't disabled. I thought I had got rid of all of those! I'll investigate further tonight.

Check https://github.com/gatsbyjs/gatsby/pull/31620#discussion_r642462541 - it seems to be `removeAttributesBySelector` - after I removed that one, I did get warning-less build

**Comment by spikyjt** [comment]
That makes sense. It doesn't make any sense to have these `bySelector` or `byAttribute` plugins enabled without additional params. I'm not sure how it was working in the past with those in there!

**Comment by spikyjt** [comment]
I've rebased and removed that plugin. Let's see how this build goes...

**Comment by spikyjt** [comment]
Any idea why the ci stuff isn't building? I know it can take a while, but it's been 5 hours!

**Comment by pieh** [comment]
CircleCI had some troubles today ( https://status.circleci.com/incidents/4phwxjmdfs08 ), seems like some "jobs" during troublesome time period were just lost, will see if I can manually trigger this (otherwise some empty commit or something like that could possibly "nudge" circle ci to actually start working)

**Comment by spikyjt** [comment]
OK! easiest if I just edit the commit message?

**Review by pieh — APPROVED** [review]
Thanks @spikyjt!

**Comment by pieh** [comment]
@spikyjt while not published in stable I just did publish `@next` version containing your change (`gatsby@3.7.0-next.1`).
