### PR TITLE
fix(gatsby-plugin-catch-links): fix pluginOptions

### LINKED ISSUE #17324: [gatsby-plugin-catch-links] documentation for plugin options is not correct
## Description

The example that is given for Plugin Options for gatsby-plugin-catch-links shows 'excludePattern' the expected value is 'excludeRegex'

### Steps to reproduce

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-catch-links

### PR DESCRIPTION
**Pull request by universse**
## Description

I edited source instead of doc since users are already following current doc.

## Related Issues

Fixes #17324

### CODE REVIEW

File: packages/gatsby-plugin-catch-links/src/catch-links.js [hunk 1]
```diff
@@ -146,12 +146,12 @@ export const routeThroughBrowserOrApp = (
 
   if (hashShouldBeFollowed(origin, destination)) return true
 
-  if (pluginOptions.excludeRegex) {
+  if (pluginOptions.excludePattern) {
```
Comment (wardpeet) [inline packages/gatsby-plugin-catch-links/src/catch-links.js]: Let's make sure we support both cases, just in case.

```suggestion
  if (pluginOptions.excludeRegex && !pluginOptions.excludePattern) {
    pluginOptions.excludePattern = pluginOptions.excludeRegex
  }

  if (pluginOptions.excludePattern) {
```

**Comment by wardpeet** [comment]
Seems like we never used the regex as json.stringify removes all types of a regex so I've added a small change to this PR to make it work.

**Comment by universse** [comment]
Thanks for reviewing and fixing!
