### PR TITLE
fix(gatsby-source-contentful): Allow proxy to be passed in to contentful client

### LINKED ISSUE #4744: Proxy Setting | gatsby-source-contentful
Contentful latest version provide proxy settings as below, but gatsby-source-contentful doesn't give option to provide the proxy. 
I am using "gatsby-source-contentful": "1.3.44"

https://www.npmjs.com/package/contentful 
var contentful = require(`contentful`);
var client = contentful.createClient({
    space: `XXX`,
    accessToken:`XXX`  ,
    host: `XXX`,
    proxy: {
        host: 'XXX',
        port: 8085,
    }
});

I am expecting some configuration like below
gatsby-config.js
 {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `xxx`,
        accessToken: `xxxx`,
        proxy: {
          host: 'XXX',
          port: 8085,
        }
      }

### PR DESCRIPTION
**Pull request by mikekono**
## Description

Allows the proxy option to be passed into the contentful client. This was enabled in #5950 but seems to have gone away in later versions

## Related Issues

Fixes #4744

### CODE REVIEW

File: packages/gatsby-source-contentful/src/plugin-options.js [hunk 1]
```diff
@@ -32,6 +32,7 @@ const optionsSchema = Joi.object().keys({
   downloadLocal: Joi.boolean(),
   localeFilter: Joi.func(),
   forceFullSync: Joi.boolean(),
+  proxy: Joi.object(),
```
Comment (wardpeet) [inline packages/gatsby-source-contentful/src/plugin-options.js]: This should be more strict
Support for proxy are the following fields:
```
 proxy: {
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
  },
```
```suggestion
  proxy: Joi.object().keys({
    host: Joi.string().required(),
    port:  Joi.number().required(),
    auth:  Joi.object().keys({
      username: Joi.string(),
      password: Joi.string(),
    }),
  }),
```

**Comment by mikekono** [comment]
@wardpeet updated the README. thanks for taking a look!
