### PR TITLE
[www/starters] filter out invalid entries and set max number to show

### LINKED ISSUE #8757: [starter library] Gatsby starter page crashes on site
## Description

Loading everything on the Gatsby starter page listing (https://www.gatsbyjs.org/starters/) crashes, ends up with a white screen.

load more and crash

### Steps to reproduce

1. Open https://www.gatsbyjs.org/starters/
2. Scroll to bottom, click "Load More"
3. Repeat Step 2 until crash (~4 times)

### Expected result

All content to be loaded (and no more ability to load more content). At the very least though, an error boundary implemented at the page level that would make reporting this easier.

### Actual result

screen shot 2018-10-03 at 7 11 13 am

### PR DESCRIPTION
**Pull request by amberleyromo**
Closes #8757

### CODE REVIEW

File: www/src/views/starter-library/filtered-starters.js [hunk 1]
```diff
@@ -66,7 +66,10 @@ export default class FilteredStarterLibrary extends Component {
       )
     )
 
-    let starters = data.allStartersYaml.edges
+    // filter out starters missing github information
+    let starters = data.allStartersYaml.edges.filter(({ node: starter }) => {
```
Comment (DSchau) [inline www/src/views/starter-library/filtered-starters.js]: Could we add the filtering at the [GraphQL layer](https://github.com/gatsbyjs/gatsby/blob/d77d4eeeabdd8f695c3aa8628273ff8fcb486297/www/src/pages/starters.js#L19)? Then we don't have to worry about ever getting "bad" data?

File: www/src/views/starter-library/filtered-starters.js [hunk 2]
```diff
@@ -241,7 +244,13 @@ export default class FilteredStarterLibrary extends Component {
               tag="button"
               overrideCSS={styles.loadMoreButton}
               onClick={() => {
-                this.setState({ sitesToShow: this.state.sitesToShow + 15 })
+                let showAll =
```
Comment (DSchau) [inline www/src/views/starter-library/filtered-starters.js]: Since there's a little more logic here now, maybe it makes sense to refactor to a class method? e.g.

File: www/src/views/starter-library/filtered-starters.js (hunk 1 above)
Comment (amberleyromo) [reply www/src/views/starter-library/filtered-starters.js]: So this is part of the problem. There are like 1-2 starters that have data at the GraphQL layer, that somehow gets stripped in the view. I'm going to account for that in a new issue, but this is to get the view to not break in the meantime.

Comment (amberleyromo) [reply www/src/views/starter-library/filtered-starters.js]: Yeah now I'm not even seeing it on prod or local. This is a decent stopgap i think.

Comment (DSchau) [reply www/src/views/starter-library/filtered-starters.js]: With this approach or the GraphQL filtering?

Comment (amberleyromo) [reply www/src/views/starter-library/filtered-starters.js]: Either. This hasn't been merged, so prod is just prod, as it was when this was originally reported -- which makes me really not understand the inconsistent recurrence of this bug. I also don't see it reflected on my local branch. Also the starters missing data (sometimes) vary.

**Comment by amberleyromo** [comment]
@pieh review?
- `panicOnBuild` used appropriately?
- Also checking for the github key using `process.env.gatsby_executing_command === "build"`

File: www/src/views/starter-library/filtered-starters.js (hunk 1 above)
Comment (amberleyromo) [reply www/src/views/starter-library/filtered-starters.js]: I'm fine with leaving this stopgap here, and i'm going to make a hacktoberfest issue to investigate the disparity
