### PR TITLE
fix(gatsby-remark-images): allow tracedSVG to accept object with settings

### LINKED ISSUE #28217: Plugin options error for `gatsby-remark-images`
## Description

```
error Invalid plugin options for "gatsby-remark-images":

- "tracedSVG" must be a boolean
```

### Steps to reproduce

Having this issue when trying to run npm run develop

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

It should run the development server
### Actual result

Its crashing unexpectedly 

### Environment

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.2 - C:\Users\Anmol\AppData\Local\Programs\Python\Python38-32\python.EXE
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.41)
  npmPackages:
    gatsby: ^2.18.7 => 2.27.0
    gatsby-image: ^2.6.0 => 2.6.0
    gatsby-plugin-google-analytics: ^2.1.29 => 2.6.0
    gatsby-plugin-manifest: 2.6.1 => 2.6.1
    gatsby-plugin-netlify: ^2.1.27 => 2.6.0
    gatsby-plugin-offline: ^3.0.27 => 3.5.0
    gatsby-plugin-react-helmet: ^3.1.16 => 3.5.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.3
    gatsby-plugin-sharp: ^2.3.5 => 2.9.0
    gatsby-plugin-sitemap: ^2.2.22 => 2.7.0
    gatsby-plugin-styled-components: ^3.1.14 => 3.5.0
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: 3.5.1 => 3.5.1
    gatsby-remark-prismjs: ^3.3.25 => 3.8.0
    gatsby-source-filesystem: ^2.1.40 => 2.6.0
    gatsby-transformer-remark: ^2.6.39 => 2.11.0
    gatsby-transformer-sharp: ^2.3.7 => 2.7.0

### PR DESCRIPTION
**Pull request by pieh**
## Description

Currently plugin validation schema only supports `true/false`, but plugin does support setting detailed settings with object notation too - https://github.com/gatsbyjs/gatsby/blob/70b81a6e825c583387728c02d83a70e0d4e16072/packages/gatsby-remark-images/src/index.js#L262

## Related Issues

Fixes #28217

### CODE REVIEW

File: packages/gatsby-remark-images/src/gatsby-node.js [hunk 1]
```diff
@@ -52,7 +54,43 @@ exports.pluginOptionsSchema = function ({ Joi }) {
...
+              `TURNPOLICY_RIGHT`,
+              `TURNPOLICY_MINORITY`,
+              `TURNPOLICY_MAJORITY`,
+              // it also allow using actual policy values
+              Potrace.TURNPOLICY_BLACK,
+              Potrace.TURNPOLICY_WHITE,
+              Potrace.TURNPOLICY_LEFT,
+              Potrace.TURNPOLICY_RIGHT,
+              Potrace.TURNPOLICY_MINORITY,
+              Potrace.TURNPOLICY_MAJORITY
```
Comment (pieh) [inline packages/gatsby-remark-images/src/gatsby-node.js:76]: 2 ways of setting it is covered by https://github.com/gatsbyjs/gatsby/blob/70b81a6e825c583387728c02d83a70e0d4e16072/packages/gatsby-remark-images/src/index.js#L264-L271

File: packages/gatsby-remark-images/src/gatsby-node.js [hunk 2]
```diff
@@ -52,7 +54,43 @@ exports.pluginOptionsSchema = function ({ Joi }) {
...
+            .try(
+              Joi.number().min(0).max(255),
+              Joi.number().valid(Potrace.THRESHOLD_AUTO)
+            )
+            .default(Potrace.THRESHOLD_AUTO),
+          blackOnWhite: Joi.boolean().default(true),
+          color: Joi.string().default(`lightgray`),
+          background: Joi.string().default(`transparent`),
+        })
+      )
```
[the remark this answers is not in the document]
Comment (pieh) [reply packages/gatsby-remark-images/src/gatsby-node.js:93]: Also - maybe it's safer to remove defaults, because it's not this plugin that set them. My main motivation to add those defaults is that maybe they are (or will be) displayed in some form - if they are not, then better remove them as they can get out of sync

File: packages/gatsby-remark-images/src/__tests__/gatsby-node.js [hunk 3]
```diff
@@ -102,4 +103,210 @@ describe(`pluginOptionsSchema`, () => {
...
+          `TURNPOLICY_WHITE`,
+          `TURNPOLICY_LEFT`,
+          `TURNPOLICY_RIGHT`,
+          `TURNPOLICY_MINORITY`,
+          `TURNPOLICY_MAJORITY`,
+        ])(`supports "%s" by policy name`, async name => {
+          const { isValid } = await testPluginOptionsSchema(
+            pluginOptionsSchema,
+            {
+              tracedSVG: { turnPolicy: Potrace[name] },
```
Comment (pieh) [inline packages/gatsby-remark-images/src/__tests__/gatsby-node.js:188]: Ops, this is actually wrong - I need to edit this

Comment (pieh) [reply packages/gatsby-remark-images/src/__tests__/gatsby-node.js]: Just for clarification - this test should pass. The wrong part is that this `it.each` and following it.each` were both passing value (and it should pass policy name in one block and value in another)

Comment (pieh) [reply packages/gatsby-remark-images/src/__tests__/gatsby-node.js]: was addressed https://github.com/gatsbyjs/gatsby/pull/28242/commits/6990d080bb4f5f17396ab0adcfcd8ad4538f401f

**Review by mfrachet — APPROVED** [review]
This looks reasonable to me :). What do you think of that @mxstbr ?

**Comment by pieh** [comment]
Published in `gatsby-remark-images@3.7.1`
