### PR TITLE
fix(gatsby-link): Do not crash in unit tests when globals are undefined

### LINKED ISSUE #24789: Instantiating an instance of Link in unit tests triggers an error in withPrefix
## Description

Running unit tests in my project (jest and react testing library) triggers a failure in the Link component in the withPrefix function. 

The specific issue is the following line (which was recently changed):
```
export function withPrefix(path, prefix = __BASE_PATH__) {
```
If `__BASE_PATH__` is not defined, this triggers an error. The previous version of this file guarded against this case by checking that `typeof __BASE_PATH__` is defined.

I will be submitting a PR shortly with a fix.

### Steps to reproduce

Run a unit test using Jest with RTL for any component that uses the Gatsby Link component.

### Expected result

No reference error.

### Actual result

The specific error is: 
```
ReferenceError: __BASE_PATH__ is not defined
```

### Environment
```
  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - /var/folders/82/v_28mld95zqd97n81x_c2kb00000gn/T/yarn--1591305860413-0.03955211442214068/node
    Yarn: 1.22.4 - /var/folders/82/v_28mld95zqd97n81x_c2kb00000gn/T/yarn--1591305860413-0.03955211442214068/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Edge: 83.0.478.44
    Firefox: 77.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.23.0 => 2.23.0
    gatsby-background-image: ^1.0.1 => 1.1.1
    gatsby-cli: ^2.12.43 => 2.12.43
    gatsby-image: ^2.4.6 => 2.4.6
    gatsby-plugin-google-analytics: ^2.3.3 => 2.3.3
    gatsby-plugin-google-tagmanager: ^2.3.4 => 2.3.4
    gatsby-plugin-lodash: ^3.3.3 => 3.3.3
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.3 => 3.3.3
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-generator: ^1.0.5 => 1.0.5
    gatsby-plugin-remove-trailing-slashes: ^2.3.4 => 2.3.4
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sass: ^2.3.3 => 2.3.3
    gatsby-plugin-schema-snapshot: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^2.6.10 => 2.6.10
    gatsby-plugin-sitemap: ./plugins/gatsby-plugin-sitemap/ => 2.2.4
    gatsby-plugin-styled-components: ^3.3.3 => 3.3.3
    gatsby-plugin-typescript: ^2.4.4 => 2.4.4
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.10 => 1.1.10
    gatsby-source-contentful: 2.3.14 => 2.3.14
    gatsby-source-filesystem: ^2.3.10 => 2.3.10
    gatsby-transformer-json: ^2.4.4 => 2.4.4
    gatsby-transformer-sharp: ^2.5.4 => 2.5.4
    gatsby-transformer-sqip: ^2.3.10 => 2.3.10
```

### PR DESCRIPTION
**Pull request by blainekasten**
## Description

This allows `gatsby-link` to be used in unit tests where `__BASE_PATH_` and `__PREFIX_PATH_` do not exist. 

## Related Issues

Fixes #24789

### CODE REVIEW

**Comment by blainekasten** [comment]
@wardpeet totally understand your thought here. Maybe I should wrap those checks in NODE_ENV for tests. That way it gets stripped out in prod builds since our prod builds are guaranteed to have those values.

I personally don't think that having docs is enough. From a consumers perspective this would be super frustrating to deal with. The Link might be deep within the tree, and all you get as an obtuse error about an undefined variable you've never heard of. Seeking this down to write a unit test would be quite encumbering. I think we should make this easier. 

Does wrapping in a NODE_ENV for tests satisfy you?

File: packages/gatsby-link/src/index.js [hunk 1]
```diff
@@ -9,29 +9,44 @@ export { parsePath }
...
 }
 
+// These global values are wrapped in typeof clauses to ensure the values exist.
+// This is especially problematic in unit testing of this component.
+const getGlobalPathPrefix = () =>
+  process.env.NODE_ENV !== `production`
+    ? typeof __PATH_PREFIX__ !== `undefined`
+      ? __PATH_PREFIX__
+      : undefined
+    : __PATH_PREFIX__
```
Comment (ascorbic) [inline packages/gatsby-link/src/index.js:34]: Nested ternaries are really hard to read. How about

```suggestion
const getGlobalPathPrefix = () => {
    if( process.env.NODE_ENV === `production` ) {
        return undefined
    }
    return __PATH_PREFIX__ ?? undefined
}
```

Comment (ascorbic) [reply packages/gatsby-link/src/index.js:34]: Ironically, the ternary confused me so I misunderstood what was happening! I see what you're doing, but I'd still rather replafe the ternary with an early return.

**Comment by pieh** [comment]
> Are we sure we want this? Adding more code just to support tests..

Not just tests, but other 3rd party tools like storybook also need similar treatment (as evidenced by https://github.com/gatsbyjs/gatsby/pull/25643)

File: packages/gatsby-link/src/index.js (hunk 1 above)
Comment (pvdz) [reply packages/gatsby-link/src/index.js:34]: In the context of this discussion; I prefer to use `===` over `!==` if there is an `else` branch unless there's a clear reason to show the `!==` branch first. I think it reads better as inverting adds to the mental overhead of parsing code. I agree with Matt that this one is a little hairy. Sometimes it is what it is.

I would consider to ignore the production check (what purpose does that serve?) since it currently assumes the var exists in production anyways, so `typeof __PATH_PREFIX__ === 'undefined'` should be false regardless. So I'd suggest this instead.

```suggestion
const getGlobalPathPrefix = () =>
    // Prevent reference error; the `__PATH_PREFIX__` binding may not exist in tests
    typeof __PATH_PREFIX__ === `undefined` ? undefined : __PATH_PREFIX__
```
