### PR TITLE
[v2] [cache-dir] fix: rendering pages with missing data

### LINKED ISSUE #8193: [v2] [www] Featured site links cause errors and a blank page
## Description

Clicking a featured site on next.gatsbyjs.org causes an error and a white page

### Steps to reproduce

1. Visit https://next.gatsbyjs.org/showcase/
2. Click a site

### Expected result

It should load the page

### Actual result

The page goes blank and an error is shown in the console

### PR DESCRIPTION
**Pull request by davidbailey00**
Changes:

- Change `getResourcesForPathname` to `getResourcesForPathnameSync` in `public-page-renderer-prod.js`
- In `public-page-renderer-prod.js`, pass the JSON data into the component props - like in `production-app.js`:
   image
  - Previously, some pages e.g. https://next.gatsbyjs.org/showcase/ (after clicking a site), would error due to missing `props.data`
- In `loader.js`, check if `component` or `json` don't exist and return null
  - This is usually when we're offline - before this change, a blank page would be displayed and a console error would appear, due to undefined `component`, but after, the native offline page is displayed.

Fixes #8193

### CODE REVIEW

File: packages/gatsby/cache-dir/loader.js [hunk 1]
```diff
@@ -346,6 +346,11 @@ const queue = {
           getResourceModule(page.componentChunkName),
           getResourceModule(page.jsonName),
         ]).then(([component, json]) => {
+          if (!(component && json)) {
```
Comment (pieh) [inline packages/gatsby/cache-dir/loader.js]: does this ever happen?

Comment (davidbailey00) [reply packages/gatsby/cache-dir/loader.js]: yes, sometimes when offline, which causes the "white page of death" error

Comment (davidbailey00) [reply packages/gatsby/cache-dir/loader.js]: e.g. go to https://next.gatsbyjs.org/, clear storage (dev tools Application tab), reload, go offline (Network tab), click on plugins

Comment (pieh) [reply packages/gatsby/cache-dir/loader.js]: shouldn't `getResourceModule` reject/throw when it can't find stuff instead of returning null? It might be nicer to read
