### PR TITLE
[v2] Upgrade Babel from 7.0.0-beta.52 to 7.0.0 stable (fixing Windows tests)

### LINKED ISSUE #7652: Tests on Windows fail - reasons and ways to fix
cc @calcsam re: https://github.com/orgs/gatsbyjs/teams/maintainers/discussions/30/comments/7

Tests on Windows are broken due to two specific issues, which only affect a single package (gatsby-codemods). Both of these are technically upstream issues, rather than issues with Gatsby itself.

TL;DR we need to update @babel/core to at least 7.0.0-rc.3 (the hard part) and change one line in a single file.

---

Global GraphQL transforms (generated by `gatsby-codemods/global-graphql-calls`) output with the native system line-endings, rather than always using `\n`. This causes its jscodeshift tests to fail, since unlike Jest's built-in snapshot testing, jscodeshift's fixture tests don't normalise line endings.

To fix this, change the following line in `gatsby-codemods/src/global-graphql-calls.js` from:

```js
return root.toSource({ quote: `single` })
```

to:

```js
return root.toSource({ quote: `single`, lineTerminator: `\n` })
```

...so that the generated files match the snapshots, which use `\n` endings, rather than `\r\n` on Windows. Alternatively, to fix the root cause of the issue, a PR could be sent to jscodeshift so that it normalises line endings when performing fixture tests.

---

Babel's `--ignore **/__tests__` option is buggy on Windows with version 7.0.0-beta.52. Basically Babel converts globs to a regex, and then matches all files against this regex - internally this works a bit differently between Babel 7.0.0-beta.52 (which Gatsby is currently using) and 7.0.0-rc.3 (the latest version) - previously Babel used minimatch to do the conversion, but with the latest RC, it's been rewritten so that [it does the conversion itself](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/pattern-to-regex.js). So basically, to fix this issue we just need to update Babel to at least 7.0.0-rc.3.

*Sidenote: the following line in `.babel-preset.js` needs to be changed to upgrade to Babel 7 rc3:*

image

*Various other problems occur but these are package-specific, whereas ALL builds will fail without this change.*

### PR DESCRIPTION
**Pull request by vtenfys**
Changelog:

- Upgrade all @babel/... packages from 7.0.0-beta.52 to 7.0.0-rc.3
  - Until RC3, Babel had a bug where `--ignore XYZ` wasn't always working properly on Windows so extra failing tests were being generated
- Update polyfill options in `gatsby/cache-dir/__tests__/.babelrc` to match API changes
- Remove unnecessary polyfill from `.babel-preset.js`
- Update preset options in `babel-plugin-remove-graphql-queries/src/__tests__/index.js` to match API changes
- Update plugin options in `gatsby/src/utils/babel-parse-to-ast.js` to match API changes
- Always output with `\n` line endings in `gatsby-codemods/src/transforms/global-graphql-calls.js` to fix the remaining Windows tests failing

Fixes #7652

### CODE REVIEW

**Comment by pieh** [comment]
Looking good, right now we would probably want 7.0.0 as stable was released yesterday.

Other question is - should `@babel/runtime-corejs2` be added to all packages that target browser? (i.e. `gatsby-image`)?

**Comment by davidbailey00** [comment]
@pieh I've just upgraded to v7 stable - tests seem to be running fine still :)

Re: corejs, Babel's options say that we need to change the dependency for packages which use the corejs option, so yes, we should replace the deps in packages which specify `browser: true` in their `.babelrc`. I'll see if I can work on this

---

image

**Comment by davidbailey00** [comment]
@pieh I've just done all the dependency replacements, all tests passing locally (and hopefully on CI!) Please could you have a look and let me know if there's anything else which needs fixing?

**Comment by jquense** [comment]
I don't think we need to handle the core-js bits in packages since we polyfill the environments anyway.

I'd love to see this merged and get a release? this is not blocking a bunch of updates for me :)

File: packages/gatsby/src/utils/babel-parse-to-ast.js [hunk 1]
```diff
@@ -12,7 +12,12 @@ const PARSER_OPTIONS = {
     `flow`,
     `doExpressions`,
     `objectRestSpread`,
-    `decorators`,
+    [
+      `decorators`,
+      {
+        decoratorsBeforeExport: false,
```
Comment (jquense) [inline packages/gatsby/src/utils/babel-parse-to-ast.js]: maybe this should be true?

File: .babel-preset.js [hunk 2]
```diff
@@ -47,7 +47,7 @@ function preset(context, options = {}) {
         {
           // we are only polyfilling the node environment
           // so we need to enable the runtime replacements for the browser preset
-          polyfill: !!browser,
+          corejs: browser ? 2 : false,
```
Comment (jquense) [inline .babel-preset.js]: present env should handle this i believe since it's got the selective polyfilling on already?

File: packages/gatsby/src/utils/babel-parse-to-ast.js (hunk 1 above)
Comment (davidbailey00) [reply packages/gatsby/src/utils/babel-parse-to-ast.js]: ok, I'll change this

File: .babel-preset.js (hunk 2 above)
Comment (davidbailey00) [reply .babel-preset.js]: This might be the case but I was matching the previous behaviour - shall I remove this? And should I keep the changes in the last commit with the Babel runtime dependencies, or can these be left as just @babel/runtime?

Comment (jquense) [reply .babel-preset.js]: I'd say we want to remove it if it doesn't break anything. The reason they added this was exactly to enable less unnecessary polyfilling so it'd be a win to change, even if it's not the same as previous behavior

Comment (davidbailey00) [reply .babel-preset.js]: Okay, I'll remove it and run through the tests. And shall I undo [this commit](https://github.com/gatsbyjs/gatsby/pull/7655/commits/f3c86df8f8d756bf899695ee5bde5f1d5830900e) too? (Tests were passing before I added this)

**Comment by davidbailey00** [comment]
@jquense I've now removed the corejs option from `.babel-preset.js` and undone the unnecessary dependency changes - please let me know if this looks okay!

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit c7858fe95f0f1759840b7127ed1fbcffec8b7c2c

https://app.netlify.com/sites/using-contentful/deploys/5b859a5ab13fb16c4f811804

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit c7858fe95f0f1759840b7127ed1fbcffec8b7c2c

https://app.netlify.com/sites/image-processing/deploys/5b859a59b13fb16c4f8117fb

**Comment by davidbailey00** [comment]
ouch, Travis had a segfault

**Comment by davidbailey00** [comment]
AppVeyor failed because `gatsby-dev-cli` doesn't update dependencies - Gatsby built the site with the latest version of Babel, but the plugins resolve to packages inside Gatsbygram's own `node_modules` folder which has the old version of Babel, leading to incompatibilities.

File: package.json [hunk 3]
```diff
@@ -1,14 +1,14 @@
...
-    "@babel/core": "7.0.0-beta.52",
-    "@babel/node": "7.0.0-beta.52",
-    "@babel/plugin-proposal-class-properties": "7.0.0-beta.52",
-    "@babel/plugin-proposal-optional-chaining": "7.0.0-beta.52",
-    "@babel/plugin-transform-runtime": "7.0.0-beta.52",
-    "@babel/preset-env": "7.0.0-beta.52",
-    "@babel/preset-flow": "7.0.0-beta.52",
-    "@babel/preset-react": "7.0.0-beta.52",
-    "@babel/runtime": "7.0.0-beta.52",
+    "@babel/core": "7.0.0",
```
Comment (jquense) [inline package.json]: we should add back the `^` on the versions here since we are out of beta's and there will be no breaking changes between v7 versions

File: packages/babel-plugin-remove-graphql-queries/package.json [hunk 4]
```diff
@@ -3,8 +3,8 @@
   "version": "2.0.2-rc.0",
   "author": "Jason Quense <monastic.panic@gmail.com>",
   "devDependencies": {
-    "@babel/cli": "7.0.0-beta.52",
-    "@babel/core": "7.0.0-beta.52"
+    "@babel/cli": "7.0.0",
```
Comment (jquense) [inline packages/babel-plugin-remove-graphql-queries/package.json]: ditto for all the babel deps actually

File: package.json (hunk 3 above)
Comment (KyleAMathews) [reply package.json]: 👍

File: packages/gatsby/src/utils/babel-parse-to-ast.js [hunk 5]
```diff
@@ -12,7 +12,12 @@ const PARSER_OPTIONS = {
     `flow`,
     `doExpressions`,
     `objectRestSpread`,
-    `decorators`,
+    [
+      `decorators`,
+      {
+        decoratorsBeforeExport: true,
```
Comment (KyleAMathews) [inline packages/gatsby/src/utils/babel-parse-to-ast.js]: are these required options now?

**Comment by davidbailey00** [comment]
@KyleAMathews yep, those are required now. @jquense I'll add the ranged versions back later today and then hopefully this can be merged!

**Comment by davidbailey00** [comment]
I've now added the caret ranges!

File: packages/gatsby-link/package.json [hunk 6]
```diff
@@ -7,15 +7,16 @@
     "url": "https://github.com/gatsbyjs/gatsby/issues"
   },
   "dependencies": {
-    "@babel/runtime": "7.0.0-beta.52",
+    "@babel/runtime": "^7.0.0",
+    "@babel/runtime-corejs2": "^7.0.0",
```
Comment (pieh) [inline packages/gatsby-link/package.json]: This is not needed anymore, right?

Comment (davidbailey00) [reply packages/gatsby-link/package.json]: Ah yep, I'll just remove that line
