### PR TITLE
Fix the onClick override logic

### LINKED ISSUE #1417: Navigation on GatsbyJS.org
Hey all,

Not sure if this is the right place for this, but I was reading about Gatsby 1.0 today and pretty excited to try it, so I'm going through the [Getting started](https://www.gatsbyjs.org/docs/) page, and was a little confused (to put it mildly) when holding command (on OSX / Chrome) and clicking "Go to the tutorial" didn't open it in a new tab. At first I even thought my button was buggin', so I clicked the header links (which of course didn't work that way either). Fortunately I could at least right click it into a new tab, but for a moment it felt like an old-school flash application.

Now, I know this is sort of the point, that it's really fast and single-page, but this should really work. It might not be the end of the world, but as a power user, I certainly expect that to work.

### PR DESCRIPTION
**Pull request by jakedeichert**
I took @KyleAMathews suggestion and looked into  [react-router's Link component](https://github.com/ReactTraining/react-router/blob/676e8ac14da780e9fbd327576971fe549f3d0b8c/packages/react-router-dom/modules/Link.js#L40-L43) handleClick logic. This solution is almost a direct copy/paste of the important parts that gatsby-link needs in order for the click logic to behave more as expected.

Now, cmd/ctrl-clicking opens links in a new tab, as expected! Also, target="_blank" now works too.

Fixes #1417

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 980d09896552c21b4bd910870b7deddd42c76084

https://app.netlify.com/sites/using-styled-components/deploys/5966c94a6f4c5074d8a1ddd3

**Comment by jakedeichert** [comment]
The gatsby-link package currently doesn't have a test setup. Should I add a test for this change?

Also, let me know if the code doesn't pass your desired style guide 👍

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 980d09896552c21b4bd910870b7deddd42c76084

https://app.netlify.com/sites/image-processing/deploys/5966c94a6f4c5074d8a1ddcd

**Comment by KyleAMathews** [comment]
Thanks for the fix! Looks like it's working now 🎉 

Could you *not* break out the new code though into separate functions? There's very little code in the new functions so I think it makes things harder to follow.

**Comment by jakedeichert** [comment]
Sure thing! I'll adjust it 👍

**Comment by KyleAMathews** [comment]
Oh also the checks for production and if we should handle the click or not don't have anything to do with each other. Put the checks on handling the clicks at the top of the function.

**Comment by jakedeichert** [comment]
Right, this whole onClick handler should be wrapped inside an if statement. I'll adjust

File: packages/gatsby-link/src/index.js [hunk 1]
```diff
@@ -73,8 +55,27 @@ class GatsbyLink extends React.Component {
             !e.ctrlKey &&
             !e.shiftKey
           ) {
```
Comment (jakedeichert) [inline packages/gatsby-link/src/index.js]: How's this looking to you now? :)

If I misunderstood your instructions, let me know and I can adjust further.

Note that I kept `onClick && onClick(e)` outside the if statement so that it still can be overridden if need be.

Comment (KyleAMathews) [inline packages/gatsby-link/src/index.js]: Nope, looks great! Just been traveling recently. Merging now and will be prepping new release soon, thanks!

**Comment by jakedeichert** [comment]
Yay! Thanks for merging @KyleAMathews 😄

**Comment by jlengstorf** [comment]
Hiya @jakedeichert! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by jlengstorf** [comment]
Hiya @jakedeichert! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by jakedeichert** [comment]
@jlengstorf wow, this is so nice! Thank you! 😄
