### PR TITLE
fix(gatsby): fix materialization edge case

### LINKED ISSUE #28047: Sorting dates seems to be broken!
## Description

In my Gatsby project, I am displaying a list of items that I intent to sort by date. Sorting seems to be working as intended in GraphiQL, however the items are not correctly sorted in my Gatsby site. I consulted with @wardpeet over Discord, and he confirmed that this is indeed a Gatsby bug.

### Steps to reproduce

If you clone my repo and checkout this PR, you will be able to see the issue clearly: https://github.com/teddywilson/clothesline-recordings/pull/8/files

Sorry it's messy, I'm not really a web developer and am doing some refactoring. If you navigate to the "releases" tab in the site, you will notice the items are not sorted correctly. Each release has a `date` property, which also corresponds to a `catalogue` property (which you will see is out of order). By chance, the items may appear in order, so if that's the case, please run `gatsby clean && gatsby develop` once more to reproduce. You will notice in the Gatsby cache, the dates are not sorted properly.

For context the page with the query in question is location at `src/pages/releases.js` (in the linked PR).

I tried various things to mitigate the issue – upgrading/downgrading Gatsby and related dependencies, using different date formats, using a different property to sort entirely (hence the sloppy "index" property that is introduced here), etc. Nothing appears to work.

### Expected result

The items are sorted properly.

### Actual result

The items are out of order.

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 57.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.20.35 => 2.26.0
    gatsby-image: ^2.3.5 => 2.5.0
    gatsby-plugin-feed: ^2.5.0 => 2.7.0
    gatsby-plugin-google-analytics: ^2.2.5 => 2.5.0
    gatsby-plugin-manifest: ^2.3.7 => 2.6.0
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.10
    gatsby-plugin-offline: ^3.1.5 => 3.4.0
    gatsby-plugin-react-helmet: ^3.2.5 => 3.4.0
    gatsby-plugin-sharp: ^2.5.7 => 2.8.0
    gatsby-plugin-typography: ^2.4.4 => 2.6.0
    gatsby-remark-copy-linked-files: ^2.2.4 => 2.4.0
    gatsby-remark-images: ^3.2.6 => 3.5.0
    gatsby-remark-prismjs: ^3.4.5 => 3.7.0
    gatsby-remark-responsive-iframe: ^2.3.4 => 2.5.0
    gatsby-remark-smartypants: ^2.2.4 => 2.4.0
    gatsby-source-filesystem: ^2.2.5 => 2.5.0
    gatsby-transformer-remark: ^2.10.0 => 2.10.0
    gatsby-transformer-sharp: ^2.4.7 => 2.6.0
  npmGlobalPackages:
    gatsby-cli: 2.13.0
```

### PR DESCRIPTION
**Pull request by vladar**
## Description

There is a pretty complex set of conditions that causes Gatsby sorting to be skipped. Those are:

1. Run one query with `regex` filter without sorting
2. This filter must be run against a field **without a custom resolver**
3. Run the second query with the same `regex` filter but now also with sorting
4. The sorting must run against a field **with custom resolver**

(this situation is demonstrated in the added test)

The first query adds nodes to the fast filters cache. The second query fetches results from this cache. But when we get results from the cache we bypass `__gatsby_resolved` assignment (assuming it was set when we originally added nodes to cache).

But it was not set because of this line:

https://github.com/gatsbyjs/gatsby/blob/70b81a6e825c583387728c02d83a70e0d4e16072/packages/gatsby/src/schema/node-model.js#L386-L390

On the first call of this code, the `node.__gatsby_resolved` is not set and so any new materialized fields are not added to the cache until the next `__gatsby_resolved` assignment that never happens when results are returned from the fast filters cache.

P.S. this piece of Gatsby is so complicated, that it's even hard to explain 😕 

## Related Issues

Fixes #28047

### CODE REVIEW

File: packages/gatsby/src/schema/__tests__/node-model.js [hunk 1]
```diff
@@ -884,6 +923,44 @@ describe(`NodeModel`, () => {
...
+      // See https://github.com/gatsbyjs/gatsby/issues/28047
+      nodeModel.replaceFiltersCache()
+
+      // This is required to setup a state after which the error reveals itself
+      const result1 = await nodeModel.runQuery(
+        {
+          query: {
+            filter: { id: { regex: `/non-existing/` } },
+          },
+          firstOnly: true,
```
Comment (pvdz) [inline packages/gatsby/src/schema/__tests__/node-model.js:936]: Isn't `firstOnly` the bigger problem here? Does the problem still happen when it's not `firstOnly`? It's been a few months since I looked at this but I thought `firstOnly` would shortcut some steps. Maybe another test case, where `firstOnly` is `false` for both cases (and maybe one where it is `true` in both cases) is useful here.

File: packages/gatsby/src/schema/node-model.js [hunk 2]
```diff
@@ -383,11 +383,10 @@ class LocalNodeModel {
           queryFields,
           actualFieldsToResolve
         )
-        const mergedResolved = _.merge(
-          node.__gatsby_resolved || {},
-          resolvedFields
-        )
-        return mergedResolved
+        if (!node.__gatsby_resolved) {
+          node.__gatsby_resolved = {}
```
Comment (pvdz) [inline packages/gatsby/src/schema/node-model.js:387]: Should this not actually run the resolvers? The other part (in redux/nodes.ts) does something like this:

```js
        if (!node.__gatsby_resolved) {
          const typeName = node.internal.type
          const resolvedNodes = resolvedNodesCache.get(typeName)
          const resolved = resolvedNodes?.get(node.id)
          if (resolved !== undefined) {
            node.__gatsby_resolved = resolved
          }
        }
```

Why would we not want to do that here?

**Review by pvdz — COMMENTED** [review]
Not sure this is ready but perhaps I'm wrong.

File: packages/gatsby/src/schema/node-model.js (hunk 2 above)
Comment (vladar) [reply packages/gatsby/src/schema/node-model.js:387]: We actually want. But the problem is that this happens as a part of this call:

https://github.com/gatsbyjs/gatsby/blob/b34680487cff802ed36f7c328da8542e16cbda9d/packages/gatsby/src/redux/run-fast-filters.ts#L232-L240

It will populate the cache for the filter AND will set `__gatsby_resolved`. But in our case first query with this filter has no materialized fields, hence `const resolved = resolvedNodes?.get(node.id)` returns undefined.

Now the second query bypasses this codepath (because we have `filterCacheKey` now) but hits this codepath:

https://github.com/gatsbyjs/gatsby/blob/b34680487cff802ed36f7c328da8542e16cbda9d/packages/gatsby/src/redux/run-fast-filters.ts#L242-L247

And in this codepath we **don't** set `__gatsby_resolved` anywhere. It kinda works in most cases only because we re-assign `__gatsby_resolved` here:

https://github.com/gatsbyjs/gatsby/blob/b34680487cff802ed36f7c328da8542e16cbda9d/packages/gatsby/src/schema/node-model.js#L386-L389

`merge` mutates the first argument with the result of the merge. But on the first run this first argument of `merge` is just a detached object, so it is not mutated and cached results do not get their `__gatsby_resolved` values.

Probably the correct fix would be to add the piece you've highlighted somewhere inside `getNodesFromCacheByValue` but that will be a much bigger change and also will likely require an additional loop over all found nodes.

I went with an `easy` route because it is also consistent - we already mutate `node.__gatsby_resolved` in all cases but the very first one.

Comment (vladar) [reply packages/gatsby/src/schema/node-model.js:387]: So the `tldr;` is that when `filtersCache` is populated we bypass this codepath:

```js
        if (!node.__gatsby_resolved) {
          const typeName = node.internal.type
          const resolvedNodes = resolvedNodesCache.get(typeName)
          const resolved = resolvedNodes?.get(node.id)
          if (resolved !== undefined) {
            node.__gatsby_resolved = resolved
          }
        }
```

File: packages/gatsby/src/schema/__tests__/node-model.js (hunk 1 above)
Comment (vladar) [reply packages/gatsby/src/schema/__tests__/node-model.js:936]: I've checked with `firstOnly: false` and there is no difference. I picked `firstOnly` just to mimic the reproduction from the original issue.

The critical thing required to reproduce this is to populate `filtersCache` and keep `__gatsby_resolved` equal to `undefined` at the same time (so first query must have no filters/sorts by fields with custom resolvers)

File: packages/gatsby/src/schema/node-model.js (hunk 2 above)
Comment (vladar) [reply packages/gatsby/src/schema/node-model.js:387]: A fun fact: if I change this:

https://github.com/gatsbyjs/gatsby/blob/b34680487cff802ed36f7c328da8542e16cbda9d/packages/gatsby/src/schema/node-model.js#L386-L389

to this:

```js
const mergedResolved = _.merge({}, node.__gatsby_resolved ?? {}, resolvedFields)
```

a bunch of tests fails. So we kinda already rely on this mutation for materialization to function properly.

Comment (pvdz) [reply packages/gatsby/src/schema/node-model.js:387]: ok :shrug:  :)

**Review by pvdz — APPROVED** [review]
ok :)

I've restarted the e2e tests because I think it failed for unrelated reasons

**Comment by vladar** [comment]
Yeah, `pnp` tests fail because of this: https://github.com/gatsbyjs/gatsby/pull/28218#issuecomment-732422940 (so unrelated to this PR)

**Comment by vladar** [comment]
Published in `gatsby@2.27.2`
