### PR TITLE
fix(webpack-theme-component-shadowing): Support shadowing in yarn-style workspaces with Webpack 5

### LINKED ISSUE #30335: Theme shadowing in monorepo not working after upgrade to Gatsby 3
## Description

I have a monorepo project containing a Gatsby theme and an associated Gatsby site. The site shadows some files from the theme, as described in [Shadowing in Gatsby Theme](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/#extending-shadowed-files).

In Gatsby 2, the replacement component is indeed being displayed. However, after upgrading to Gastby 3, the original component is instead being rendered (that is, shadowing is not happening there).

### Steps to reproduce

See minimal example here: https://github.com/mjameswh/issue-gatsby3-monorepo-themeshadowing.

In that repo's history, the first commit is linked to Gatsby 2.23.12. Running from that commit, we can see that the replacement component is being rendered (in green); note that the original component is also being rendered (in red), since the replacement component imports and invoke the original component (this is expected).

In the second commit of that repo's history, Gatsby has been upgraded to 3.2.0-next-0 (note that result is the same with Gatsby 3.0.0). Running from that commit, we can see that only the original component is being rendered (in red).

I also tried using a pnpm workspace instead of yarn workspace (third commit in repo), but shadowing still doesn't work.

### Expected result

In Gatsby 2, the index page of the previous repo gives the following result:

Result in Gatsby 2

### Actual result

In Gatsby 3, the result is instead:

Result in Gatsby 3

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.2.0-next.0 => 3.2.0-next.0 
    gatsby-legacy-polyfills: ^1.1.0 => 1.1.0 
    gatsby-link: ^3.1.0 => 3.1.0 
    gatsby-react-router-scroll: ^4.1.0 => 4.1.0 
    gatsby-theme-example: ^1.0.0 => 1.0.0 
```

### PR DESCRIPTION
**Pull request by mjameswh**
## Description

Fix support of theme shadowing in monorepo (yarn/lerna-style workspaces), which was broken after migration to Gatsby 3/Webpack 5.

The webpack plugin has been modified to tap right before the `resolved` hook of Webpack's resolve pipeline. This was required because this is now the only point in the resolve pipeline at which symlinks in the path have been resolved to their absolute and canonical form. The theme shadowing algorithm itself relies on canonical paths in order to determine to which theme a file belongs. See #30335 for more details.

Note that in Webpack 4, symlink resolution would cause the pipeline to jump back to an earlier step, which is why tapping on the `relative` hook was then sufficient. This is no longer the case in Webpack 5, and from Webpack's point of view, the former behavior was not optimal and not justified, so there is no justification to call it a regression in Webpack itself.

One issue that consequence of intercepting an event that late in the pipeline is that the path provided to the plugin includes the file extension to which Webpack's default algorithm has resolved, based on the original theme. For example, let's assume that user code requires a file named `gatsby-theme-tomato/src/button/heading`. The theme shadowing plugin will instead receive a request path that will looks something like `/some/path/my-site/packages/gatsby-theme-tomato/src/button/heading.js`. In order to allow a theme file being shadowed by a file of a distinct extension, the plugin would previously simply try a list of potential file extensions and return the first match.

This strategy can no longer be applied, because assuming a requested file named `heading.js`, we would look for a shadow file named `heading.js.ts`. Removing existing extensions would also not be acceptable, because then, requesting a file named `heading.css` could result in a shadow file named `heading.ts` being returned (that is obviously not desirable).

Instead, this patch introduces a new mechanism to determine acceptable shadow extensions based on the original file extension. By default, this process recognize as equivalent file with extensions `js`, `jsx`, `ts` and `tsx`. This mapping can be extended, though doing so might be somewhat difficult.

I also included tests covering use of theme shadowing in a lerna/yarn-style workspace. Note that this requires a test fixture project containing symlinks. Unfortunately, restoration of symlinks in git repo is not reliable on Windows. Therefore, that specific test has been constructed such that the required symlinks are created by the test's code, at runtime, rather that as regular git objects, which would have been much simpler.

### Documentation

I included an updated version of the _How theme shadowing works?_ documentation page (according to changes up to this point).

## Related Issues

Fixes #30335

[ch28642]

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi!
Sorry for the slow reply on this. We very much appreciate you putting up this PR and we'll see to review it next week.

Thanks!

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js [hunk 1]
```diff
@@ -3,9 +3,17 @@ const debug = require(`debug`)(`gatsby:component-shadowing`)
...
-const pathWithoutExtension = fullPath => {
-  const parsed = path.parse(fullPath)
-  return path.join(parsed.dir, parsed.name)
+// By default, a file can only be shadowed by a file of the same extension.
+// However, the following table determine additionnal shadowing extensions that
+// will be looked for, given the extension of the file being shadowed.
+// This list maybe extended by user (by customizing webpack's configuration), in
+// order to allow less common use cases (ie. allow css files being shadowed by
+// a scss file, or jpg files being shadowed by png...)
+const DEFAULT_ADDITIONNAL_SHADOW_EXTENSIONS = {
```
Comment (LekoArts) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:12]: While we like the idea of having an explicit map of shadow extensions, people rely on `extensions: getConfig().resolve.extensions` to exist, e.g. for shadowing MDX files or in (probably) some rare cases even different image formats.

Was this something that was required to make shadowing in yarn workspaces work or was this thought of an improvement from you?

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js [hunk 2]
```diff
@@ -15,147 +23,165 @@ const pathWithoutExtension = fullPath => {
...
+        .map(({ themeDir }) => path.join(themeDir, `src`, theme.themeName))
+    )
+
+    const acceptableShadowFileNames = this.getAcceptableShadowFileNames(
+      path.basename(component)
     )
 
     for (const theme of themesArray) {
-      const possibleComponentPath = path.join(theme, component)
+      const possibleComponentPath = path.dirname(path.join(theme, component))
```
Comment (LekoArts) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:130]: Adding `path.dirname` here makes the variable name non-descriptive

**Review by LekoArts — DISMISSED** [review]
Thanks for the PR again! We went through it and have a couple of questions :)
@mjameswh

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js (hunk 1 above)
Comment (mjameswh) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:12]: I absolutely understand what you are saying and I would have prefered not to introduce a breaking change here. This was not designed as a deliberate improvement (though it might indeed be one, if can make it easier to work with). I'm open to discussion if someone sees alternatives, but I haven't found any way yet that do not introduces even worst consequences. So let me explain the situation, in case someone gets an idea.

It is expected that theme shadowing allows a shadow file to be of a different file extension that the file being shadowed... But in Gatsby 2, this relied on the fact that an importer file would import the file without specifying the file extension. For example, importer.js would import `gatsby-theme-example/Component` (without file extension).

Note however that if importer.js actually imported a file using a specific file extension, then the theme shadowing plugin would never try to _remove_ that file extension (though it would still look up for that file name with every entries in `extensions` appended). For example, importing `gatsby-theme-example/Component.css` would look for shadow files named `Component.css`, `Component.css.js`, `Component.css.ts`... But not for `Component.js`, which would be unexpected and certainly inappropriate. Therefore, _this is certainly the behavior that we want to preserve._ As we will see, this is the difficult point.

Now, In Gatsby 2 / Webpack 4, this was possible because the Webpack's resolver plugin would get invoked at some point where `request.path` is `/full/and/canonical/path/to/gatsby-theme-example/src/Component`. Note that at this point, the name of the package has been replaced by the absolute and canonical path (i.e. no symlink) to the source directory of the theme, but the file itself still has no extension.

In Webpack 5, there is never such a moment where the package's path has been fully resolved, but the file extension is still left to its original value. Indeed, symlinks are now canonicalized at the very last step of resolution, leaving very opportunity for interception of the resolution process by the shadowing plugin. At this point, Webpack's resolution process has already determined the file extension, based on the content of the original package (i.e. files in the unshadowed theme's source directory). For example, if importer.js requested `gatsby-theme-example/Component`, the plugin will get called with something like `/full/and/canonical/path/to/gatsby-theme-example/src/Component.js`, and the plugin gets no cue that the file that was originally requested is `Component`, without extension.

So the question is: how can the plugin determine at that point that `Component.ts` (that is an example) is an acceptable substitution file for the file specified in `request.path` (i.e. `Component.js`)? I initially thought of removing the provided file extension from `request.path` and then lookup for all files matching that name + one of the extension listed in `extensions`.  So a requested path of `.../Component.js` would get back to `Component`, and then would look for shadow files such as `Component.js`, `Component.jsx`, `Component.ts` and `Component.tsx`.

But then, what if importer request a file that is not code, such as `Component.css` or `Component.jpeg`? Assuming the previous strategy, both gets trimmed down to `Component`, and the shadowing plugin would then happily return the content of `Component.js` instead of `Component.css` or `Component.jpeg`.

I thought of trimming only "known" extensions (that is, extensions listed in `extensions`), but this still is insufficient as it is sometime useful to have `css`, `jpeg` or other non-code file extensions defined in `extensions`.

So I came up with this. The idea is that a code file should only be shadowed by another code file, an image by an image, and so on. From the algorithm point of view, I think the current strategy makes things simple, strong and predictable.

From the user's point of view, however, the "additional shadow extensions" table is difficult to customize and it introduces a breaking change. I think it is that specific point that needs to be improved.

Comment (mjameswh) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:12]: One thing that might be worth considering is that it would be relatively easy to automatically construct this mapping table based on the content of `extensions` array if we had some type of "file extension dictionary". Such "dictionary" would for example contains:

```
js => code
jsx => code
ts => code
tsx => code
jpeg => image
png => image
css => stylesheet
sass => stylesheet
```

Then, based on the content of `extensions`, it is now a simple algorithm exercise to rebuild the mapping table described previously. Note that it would be acceptable for the dictionary to contains extensions that are not actually used in a project, making it possible for the plugin to provide a default dictionary containing a reasonable list of known common extensions. Only extensions specified in Webpack's `extensions` array would actually get included in the mapping table.

I can easily provide the algorithm to build up the mapping table, but I would need some guidance on where to store the dictionary so that it is customizable (and possibly how to propagate that information up to the webpack's plugin).

Comment (pieh) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:12]: > Now, In Gatsby 2 / Webpack 4, this was possible because the Webpack's resolver plugin would get invoked at some point where `request.path` is `/full/and/canonical/path/to/gatsby-theme-example/src/Component`. Note that at this point, the name of the package has been replaced by the absolute and canonical path (i.e. no symlink) to the source directory of the theme, but the file itself still has no extension.

Can we still use same hook we used (or even any earlier ones) and store that `request.path` without added extension (if this was how it was imported of course in source code) so that `before-resolved` hook (one that does actual work) have access to it? I don't exactly know if passing information between hooks is "forbidden" or not but this:
```
    resolver.hooks.relative.tapAsync(`wat`, (request, stack, callback) => {
      console.log(`relative`, request.path)
      request.hack = request.path
      return callback()
    })

    resolver
      .getHook(`before-resolved`)
      .tapAsync(
        `GatsbyThemeComponentShadowingResolverPlugin`,
        (request, stack, callback) => {
          console.log(`before-resolved`, {
            path: request.path,
            hack: request.hack,
          })
```
Resulted in
```
console.log packages/gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index.js:51
    relative /Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/index.js

  console.log packages/gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index.js:61
    before-resolved {
      path: '/Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/index.js',
      hack: '/Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/index.js'
    }

  console.log packages/gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index.js:51
    relative /Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/node_modules/theme-a/src/components

  console.log packages/gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index.js:61
    before-resolved {
      path: '/Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/node_modules/theme-a/src/components.js',
      hack: '/Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/node_modules/theme-a/src/components'
    }

  console.log packages/gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index.js:61
    before-resolved {
      path: '/Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/src/theme-a/components.js',
      hack: '/Users/misiek/dev/gatsby/packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/__tests__/fixtures/test-sites/basic-shadowing/node_modules/theme-a/src/components'
    }
```
Which made it seem possible to pass some meta information between hooks (tho I definitely don't like mutating `request` to achieve this - as name in my code snippet suggest - it seems very hacky and also relies on `request` being same object between hook invocations that seems like implementaion detail that shouldn't be relied upon).

> From the user's point of view, however, the "additional shadow extensions" table is difficult to customize and it introduces a breaking change. I think it is that specific point that needs to be improved.

I think for gatsby@3 we will need to maintain behaviour, but the shadow extensions matrix is definitely something we like (we just can't completely switch to it). I do think there is a way to introduce usage of such matrix without creating breaking changes by following something like this:
 - highest priority - same extension
 - if above doesn't exist - try to use extension matrix to prioritize known compatible (swappable) extensions
 - if match still not found - fallback to just list of resolvable extensions (to not introduce breaking change) - to me only problem with doing this fallback is the issue you outlined above that we currently in `before-resolved` don't know if file was imported with explicit extension or extension was inferred at some point by webpack - if we would have access to metadata what the import looked like we could use it to decide wether we use that fallback or not

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js [hunk 3]
```diff
@@ -15,147 +23,165 @@ const pathWithoutExtension = fullPath => {
...
-          { ...request, path: builtComponentPath || request.path },
-          null,
-          {},
-          callback
-        )
-      }
-    )
+          if (builtComponentPath) {
+            return resolver.doResolve(
+              resolver.hooks.describedRelative,
```
Comment (pieh) [inline packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:97]: is this correct to use same hook as argument despite tapping into different one?

Comment (mjameswh) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:97]: Well... This is indeed _legal_ and this is done extensively in Webpack's default resolve pipeline.

Now, if your question is either this is the most appropriate hook to jump back to, that I have to admit I am not certain of it. Given that we are providing a fully resolved path to the shadowing file, I don't think there is anything left that ought to be done by the default resolve pipeline.

But it is hard to be sure here, because Webpack provides no official documentation of these hooks and which work is performed at which step, aside from the source code itself (mostly https://github.com/webpack/enhanced-resolve/blob/main/lib/ResolverFactory.js and implementations of the various plugins named there), which may change in the future.

Still, `describedRelative` appears to be a reasonably safe and stable point to reintroduce altered paths in the middle of the resolve pipeline, making it more future-proof. That is why I kept that one specifically.

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js (hunk 1 above)
Comment (mjameswh) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:12]: > Can we still use same hook we used (or even any earlier ones) and store that `request.path` without added extension (if this was how it was imported of course in source code) so that `before-resolved` hook (one that does actual work) have access to it? I don't exactly know if passing information between hooks is "forbidden" or not but this:

> Which made it seem possible to pass some meta information between hooks (tho I definitely don't like mutating request to achieve this - as name in my code snippet suggest - it seems very hacky and also relies on request being same object between hook invocations that seems like implementaion detail that shouldn't be relied upon).

I had initially thought of this option but had rejected it as too hacky... However, now that you bring it back on the table, I think it might be workable. I have examined a few default Webpack plugins, and this actually appears to be a strategy used internally. And though request objects themselves are never _reused_, new request objects always extends previous ones, so custom properties set early should still be available in later plugins.

I will implement something that integrate this as a fallback strategy, and come back with a new commit.

File: packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js (hunk 3 above)
Comment (pieh) [reply packages/gatsby/src/internal-plugins/webpack-theme-component-shadowing/index.js:97]: > But it is hard to be sure here, because Webpack provides no official documentation of these hooks and which work is performed at which step

Yeah, this part is what I find most difficult when working with webpack plugins/loaders etc. Unless you are very familiar with how webpack does things internally (by doing deep dives in sourcecode and trying to "reverse engineer" what and how is meant to work). 

I just wasn't sure here if what we had previously (using `describedRelative` in `relative` hook) was intentionally "the same" or using `describedRelative` just make sense in more scenarios than that. I'm completely fine with keeping it as-is if it make sense.

**Comment by pieh** [comment]
To not mess with your branch I opened https://github.com/mjameswh/gatsby/pull/1 with minor adjustments (fix unit tests and fix minor typo). https://github.com/gatsbyjs/gatsby/pull/31056 is draft PR on `gatsbyjs/gatsby` repo with same changes to just run CI tests and verify them

**Comment by pieh** [comment]
I think last set of changes added in https://github.com/mjameswh/gatsby/pull/2

**Review by pieh — APPROVED** [review]
Thanks so much for your work on this @mjameswh!

**Comment by pieh** [comment]
I will release `@next` with those changes today so users can use it with this asap. They will land in stable (`@latest`) in the next minor (in ~12 days)

**Comment by axe312ger** [comment]
Thank you!

**Comment by pieh** [comment]
`@next` published (`gatsby@3.5.0-next.2`)

**Comment by axe312ger** [comment]
Superb. Will try to check it out on the weekend with my huge theme(s) :)

**Comment by laurenskling** [comment]
Can confirm `gatsby@3.5.0-next.2` runs yarn workspace shadows again. Was a major yikes when I upgraded to gatsby 3 to see shadows being broken. Thanks so much for working on fixing it <3

**Comment by axe312ger** [comment]
Yes can confirm, it works now :)
