### PR TITLE
fix(gatsby-remark-prismjs): Use gatsby-highlight class to calculate line numbers

### LINKED ISSUE #22962: [gatsby-remark-prism]: Additional line numbers kept after line removal
## Description
This issue occurs when using the [gatsby-remark-prism](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-prismjs) plugin to process code-fences in markdown.

When enabling both line numbers and commented directives (ie. //highlight-start) within code-fences, the plugin's [line number generator](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/add-line-numbers.js) does not compensate for lines removed by the commented directives.

This leads to a discrepancy between the commented lines removed by the directive handler and the line number spans added beforehand, resulting in scrollable overflow of empty lines in the output code-fence.

This obviously does not occur when either the code-fence is not selected to use line numbers in the header (\`\`\`js{numberLines: true}) or the showLineNumbers: false option is passed to `gatsby-remark-prismjs` in `gatsby-config.js`. Rather, when both line numbers and comment directives are used in conjunction with one another.

#### Example 
Input:
```js
1: function test() {
2:   // highlight-start
3:  return "This is a test"
4:   // highlight-end
5: }
```

Output (* indicating line highlighting):
```js
1: function test() {
2:  *return "This is a test"*
3: }
4:  
5: 

```

I've tested this for both highlighting and hiding directives. To get a better understanding of what's happening in the directive handler, check out [this part of my proposed solution](https://github.com/gatsbyjs/gatsby/compare/master...miles-crighton:remark-prism-highlighting#diff-5fd2ab3304a334d4977bdcb27e492e3e), described later in this issue.

### Steps to reproduce

I've generated a minimised test case on [Github](https://github.com/miles-crighton/gatsby-prism-issue)

This includes 3 test cases, each using different directives. One for highlighting, one for hiding and a final for a combination of multiple.

**Code sandbox**

[Online sandbox](https://codesandbox.io/s/github/miles-crighton/gatsby-prism-issue)

**Run it locally**

`git clone https://github.com/miles-crighton/gatsby-prism-issue.git` to a local folder
then run `gatsby develop` find the test cases at `localhost:8000`

### Expected result

Screenshot 2020-04-09 at 12 06 11

### Actual result
gatsby-prism-issue

### Environment
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 66.0.4
    Safari: 13.0.5
  npmGlobalPackages:
    gatsby-cli: 2.11.5

# Proposed solution
I've developed a naive solution [in this branch](https://github.com/gatsbyjs/gatsby/compare/master...miles-crighton:remark-prism-highlighting).

This involves adding an additional action to the directives handler ([`directives.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/directives.js)) that keeps track of lines removed during processing. The count of `linesRemoved` is then passed back through [`highlight-code.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/highlight-code.js) and then once again to [`index.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/index.js). This value can then be fed into the line number generator to compensate for the lines removed during directive processing. Essentially this solution tries to allow feedback from the code-highlighter to be provided to the line number generator as currently, they run independently from one another. On the one hand, the independent modularity is good, but with the addition of comment directives outside of prismjs there needs to be some connection between components so that the additional features are being recognised at each part of the plugin. 

The alternative solution I initially considered involved performing an additional round of directive handling independently within `add-line-numbers.js` but ultimately the solution described above sounded more robust and required less unneccesary duplication.

Due to the fact that I'm changing the main return of `directives.js` and `highlight-code.js` to an object composed of both the highlighted code and total lines removed, **this will cause the currently implemented tests to fail, [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/__tests__/directives.js) and [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js)**. Ideally, I'd love to hear a better solution for passing `linesRemoved` to [`add-line-numbers.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/add-line-numbers.js) Also I'd like to know if this will have any unintended side-effects that I haven't seen.

If any maintainers have suggestions or comments on how to move forward with this issue or how to modify/create the solution feel free.

Thanks for taking the time to check this out.

### PR DESCRIPTION
**Pull request by miles-crighton**
## Description

The output of the [line highlighting parser](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/highlight-code.js) is now passed to the [line number generator]() to calculate the required line number spans to be created. Before, these two procedures were being run independently from one another. This change results in the line number generation now being dependent on the line highlighting parser apposed to the raw code-block markdown.

The line number generator now uses the newline (`\n`) delimiter in combination with matches of the HTML class `gatsby-highlight-code-line` to calculate the required line number count. 

This solution was generated with the help of @pieh's suggestion on #22962.

### Documentation

Shouldn't affect documentation as this attempts to fix a bug preventing expected behaviour.

## Related Issues

Fixes #22962

### CODE REVIEW

**Comment by pieh** [comment]
This looks nice!

Can we add some test cases to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/__tests__/index.js that would use both line numbers and some additional directives and make sure there are no empty lines produced?

File: packages/gatsby-remark-prismjs/src/add-line-numbers.js [hunk 1]
```diff
@@ -8,7 +10,11 @@ module.exports = (code = []) => {
     return spans
   }
 
-  const numberOfLines = code.length === 0 ? 0 : code.split(`\n`).length
+  const numberOfLines =
+    code.length === 0
+      ? 0
+      : code.split(`\n`).length +
```
Comment (pieh) [inline packages/gatsby-remark-prismjs/src/add-line-numbers.js:16]: now that we operate on html - does splitting on `\n` is actually what we want? Don't remember right now if we use `white-space: pre` on code blocks to have line breaks in rendered content or we use blocks (i.e. `<div>`) or explicit line breaks (`<br/>`) for it

Comment (miles-crighton) [reply packages/gatsby-remark-prismjs/src/add-line-numbers.js:16]: I just tested this locally and it seems [`highlightCode.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/highlight-code.js) (near the bottom) uses `\n` to line break everything including the line breaks specified within the input content.

This was what I was initially working off when making the changes that piped the output to this new line calculation. 

Is this what you meant or is there another scenario where this would not be the case?

Input:
```js
function highlightTest() {


  // highlight-start
  return "this is a highlight test"
  // highlight-end
}
```
Code splits (before output of `highlightCode.js`):
```
[
  {
    code: '<span class="token keyword">function</span> <span class="token function">highlightTest</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>',
    highlight: false,
    hide: false,
    flagSources: []
  },
  { code: '', highlight: false, hide: false, flagSources: [] },
  { code: '', highlight: false, hide: false, flagSources: [] },
  {
    code: '<span class="gatsby-highlight-code-line">  <span class="token keyword">return</span> <span class="token string">"this is a highlight test"</span></span>',
    highlight: true,
    hide: false,
    flagSources: [ [Object] ]
  },
  {
    code: '<span class="token punctuation">}</span>',
    highlight: false,
    hide: false,
    flagSources: []
  }
]
```
Output of `highlightCode.js`
```
<span class="token keyword">function</span> <span class="token function">highlightTest</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>


<span class="gatsby-highlight-code-line">  <span class="token keyword">return</span> <span class="token string">"this is a highlight test"</span></span><span class="token punctuation">}</span>
```

**Comment by miles-crighton** [comment]
Sure I'll work on a few test cases.

**Comment by miles-crighton** [comment]
@pieh I've pushed a snapshot + unit test for the new functionality, check them out and let me know if that's what you're looking for. (They pass for me on my local environment) If they look good, I can create a few larger tests with multiple directives.

**Comment by pieh** [comment]
Ah, I missed the fact how exactly line numbers are implemented - the empty `<span></span>` is pretty unfortunate (in terms of testing it in nice way). I will experiment a bit to see it's feasible to write nicer assertions, because I feel like checking just html output is confusing here - as in - if there are any changes that will happen in the future to that html markup - it will pretty hard to unpack what that means.

For now I have no further actionable comments for you, and this is waiting on me

**Comment by pieh** [comment]
@miles-crighton Take a look at https://github.com/miles-crighton/gatsby/pull/1 (PR against this PR :) ) as attempt at making nicer assertions

**Comment by miles-crighton** [comment]
That looks great - much more explicit and understandable :) Where do you want to go from here?

**Comment by pieh** [comment]
I think we are good for now. Given that line numbering and using directives was completely broken and this fixes this (at least for cases we tested) I'd say this is good to go in. If there will be further problems discovered we can iterate (and we have structure/assertion for line numbers tests so we can add problematic cases to tests as we discover them to make sure we don't regress in the future).

One thing that I'll do right now is to update branch to sync with master (we very recently upgraded prettier, so need to make sure that PR branch is on the same version of prettier as master)

**Comment by miles-crighton** [comment]
Pleasure working with you @pieh :)!
