### PR TITLE
fix(gatsby): workaround webpack terser plugin hanging on WSL

### LINKED ISSUE #6540: [v2] gatsby build hangs on WSL Ubuntu
## Description

Build hangs on "Building production Javascript and CSS bundles," after "bootstrap finished." This doesn't happen on Gatsby v1, or with `gatsby develop`.

### Steps to reproduce

1. Make a new gatsby site using command: `gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world#v2`. 
2. Run `gatsby build`.

### Expected result

Gatsby should build the production site.

### Actual result

Gatsby hangs on "Building production Javascript and CSS bundles." I let it run for 10 minutes and then quit. This occurs on both the gatsby-cli 

### Environment

- System:
  - OS: Linux 4.4 Ubuntu 16.04.4 LTS (Xenial Xerus) (wsl on Windows build 17692)
  - CPU: x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  - Shell: 5.1.1 - /usr/bin/zsh
- Binaries:
  - Node: 8.11.3 - /usr/local/bin/node
  - npm: 6.2.0 - /usr/local/bin/npm
- npmPackages:
  - gatsby: next => 2.0.0-beta.46
  - gatsby-plugin-react-helmet: next => 3.0.0-beta.3
- npmGlobalPackages:
  - gatsby-cli: 2.0.0-beta6
  - also occurs on -gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### PR DESCRIPTION
**Pull request by LubomirGeorgiev**
### What is the issue?
I am running Gatsby on WSL and I have this problem #6540.
[Right here](https://github.com/gatsbyjs/gatsby/issues/6540#issuecomment-438524817) someone said that if you change `parallel:true` to `parallel:false` in node_modules/gatsby/dist/utils/webpack-utils.js that solves the problem.

### Why do I submit this pull request?
I decided to make a pull request so that this issue is resolved permanently for everyone using WSL (Windows Subsystem for Linux).

### How did I test it?
I followed [this guide](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/) and tested it locally and I can confirm that it works.
After that I ran `yarn test` to make sure that I didn't break anything in the repository.

### Why do I want it merged?
I hope this gets merged so all of us using WSL can stop editing node_modules/gatsby/dist/utils/webpack-utils.js every time we do `npm install` or `yarn install`

## Related Issues

If this pull request gets merged it will solve #6540 and #7013

### CODE REVIEW

**Comment by wardpeet** [comment]
there is an upstream issue https://github.com/webpack-contrib/terser-webpack-plugin/issues/21

@LubomirGeorgiev it would be handy to have a repro for this and some env info.
Could you post the details of `gatsby info`.

I don't have an issue on our default starter `gatsby new starter`

**Comment by LubomirGeorgiev** [comment]
@wardpeet 

Did you test it on a Linux Subsystem for Windows specifically?
I can confirm that this pull request fixes the hanging on WSL.
Maybe someone using WSL for development can also test it and confirm.

**Comment by wardpeet** [comment]
I've tested it on WSL with the default-starter and with some other websites but I can't reproduce it. I'm on the latest windows version, are you?

File: packages/gatsby/src/utils/webpack-utils.js [hunk 1]
```diff
@@ -444,7 +445,7 @@ module.exports = async ({
   plugins.minifyJs = ({ terserOptions, ...options } = {}) =>
     new TerserPlugin({
       cache: true,
-      parallel: true,
+      parallel: !os.release().includes(`Microsoft`),
```
Comment (sidharthachatterjee) [inline packages/gatsby/src/utils/webpack-utils.js]: Maybe we can use https://github.com/sindresorhus/is-wsl for the check?

Comment (LubomirGeorgiev) [reply packages/gatsby/src/utils/webpack-utils.js]: Thanks for the suggestion. I just added it [right here.](https://github.com/gatsbyjs/gatsby/pull/12636/commits/d29877db36be75d6f1cf73e41b0886d8ed1905a7)

**Comment by LubomirGeorgiev** [comment]
> I've tested it on WSL with the default-starter and with some other websites but I can't reproduce it. I'm on the latest windows version, are you?

Yes I am running on the latest version of Windows
```
cmd.exe -> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.17763 N/A Build 17763
```

I've also updated my Ubuntu WSL with `sudo apt update && sudo apt upgrade`

File: packages/gatsby/src/utils/webpack-utils.js [hunk 2]
```diff
@@ -444,7 +445,7 @@ module.exports = async ({
   plugins.minifyJs = ({ terserOptions, ...options } = {}) =>
     new TerserPlugin({
       cache: true,
-      parallel: true,
+      parallel: !isWsl,
```
Comment (pieh) [inline packages/gatsby/src/utils/webpack-utils.js]: Just adding some context

```suggestion
      // can't use parallel on WSL because of issue in terser
      // see https://github.com/webpack-contrib/terser-webpack-plugin/issues/21
      parallel: !isWsl,
```

Comment (LubomirGeorgiev) [reply packages/gatsby/src/utils/webpack-utils.js]: Good suggestion. I just [added it here](https://github.com/gatsbyjs/gatsby/pull/12636/commits/b43746ed6d7308891a869277f76d7e4e64e2fa69)
