### PR TITLE
fix(docs): Update documentation for createPages

### LINKED ISSUE #25805: Document createPages formally
## Summary

The documentation for [createPages](https://www.gatsbyjs.org/docs/node-apis/#createPages) does not specify the parameters that `createPages` receives. Some of those parameters are glossed over in the example (`actions`), and some are omitted (`reporter`). 

Since this is an API reference page (rather than the corresponding [guide](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/)), I think the parameters should be comprehensively listed and documented.

### Motivation

My particular motivation was to drill into the documentation for the `graphql` parameter and see if there was any way I could pass a context, in order to make authenticated GraphQL queries from `gatsby-node`. I couldn't figure out where the documentation for the `graphql` instance lives.

On the same page, [`createResolvers`](https://www.gatsbyjs.org/docs/node-apis/#createResolvers) has a proper list of parameters.

### PR DESCRIPTION
**Pull request by davad**
Update parameters documentation in createPages

## Description

Add API parameter documentation for createPages

## Related Issues

Fixes #25805

### CODE REVIEW

File: packages/gatsby/src/utils/api-node-docs.ts [hunk 1]
```diff
@@ -11,6 +11,14 @@ export const resolvableExtensions = true
...
  *
  * See also [the documentation for the action `createPage`](/docs/actions/#createPage).
+ *
+ * @gatsbyVersion 2.2.0
+ * @param {object} $0 See the [documentation for `Node API Helpers` for more details](/docs/node-api-helpers)
+ * @param {Actions} $0.actions See the [list of documented actions](/docs/actions)
+ * @param {function} $0.actions.createPages [Documentation for this action](/docs/actions/#createPage)
+ * @param {function} $0.graphql: Query GraphQL API. See [examples here](/docs/creating-and-modifying-pages/#creating-pages-in-gatsby-nodejs)
+ * @param {GatsbyReporter} $0.reporter Log issues. See [GatsbyReporter documentation](/docs/node-api-helpers/#GatsbyReporter) for more details
+ *
```
Comment (pvdz) [inline packages/gatsby/src/utils/api-node-docs.ts:21]: Can you also describe the return value?

**Review by pvdz — CHANGES_REQUESTED** [review]

File: packages/gatsby/src/utils/api-node-docs.ts (hunk 1 above)
Comment (davad) [reply packages/gatsby/src/utils/api-node-docs.ts:21]: The caller discards any return value (`packages/gatsby/src/utils/api-runner-node.js`, Line 425). The implementer can return nothing, or optionally they can return a Promise in a sync function.

I'll add a @return annotation for that.

**Review by pvdz — APPROVED** [review]
Thanks! :purple_heart:
