### PR TITLE
fix(gatsby-plugin-offline): versioned import of idb-keyval

### LINKED ISSUE #24936: [gatsby-plugin-offline]: Potential for caching problems with idb-keyval
## Description

I observed, that the plugin has an npm dependency to `idb-keyval` and copies `idb-keyval-iife.min.js` from the node_modules folder into the public folder in `onPostBuild`:

https://github.com/gatsbyjs/gatsby/blob/f8b7317c435fa9573c1265ba7911f9a785615553/packages/gatsby-plugin-offline/src/gatsby-node.js#L163-L166  

The [official caching recommendations](https://www.gatsbyjs.org/docs/caching/) are oblivious of that file and it would be cached with `cache-control: public, max-age=31536000, immutable`.

Furthermore, the plugin itself will cache the file with the `CacheFirst` strategy by default:

https://github.com/gatsbyjs/gatsby/blob/f8b7317c435fa9573c1265ba7911f9a785615553/packages/gatsby-plugin-offline/src/gatsby-node.js#L135-L140

This is based on the assumption that all `.css` and `.js` files are fingerprinted, yet `idb-keyval-iife.min.js`  is not.

If a future version of the plugin decides to use another version of `idb-keyval` this will become a problem since clients will not receive the update of the new version of `idb-keyval` because it is cached as immutable.

### Idea for a fix

Read the version of `idb-keyval` from `package.json` in `node_modules/idb-keyval` and include it in the filename. Instead of calling `importScripts` with a literal file name in `sw-append.js`, it could be prepended here with the filename that includes the version:

https://github.com/gatsbyjs/gatsby/blob/f8b7317c435fa9573c1265ba7911f9a785615553/packages/gatsby-plugin-offline/src/gatsby-node.js#L184-L187

This solves the problem without the need to alter any existing caching configurations. I can send a PR if this is wanted.

### Environment
<details>
  <summary>gatsby info --clipboard</summary>

 ```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.20.1 - /tmp/yarn--1591893009228-0.6481271662017773/node
    Yarn: 1.22.4 - /tmp/yarn--1591893009228-0.6481271662017773/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 68.8.0esr
```

</details>

<details>
  <summary>yarn list | grep -E "(gatsby-plugin-offline|idb-keyval)" | grep -v deduped</summary>

```
│  ├─ gatsby-plugin-offline@^3.0.35
├─ gatsby-plugin-offline@3.2.1
│  ├─ idb-keyval@^3.2.0
├─ idb-keyval@3.2.0
```

</details>

### PR DESCRIPTION
**Pull request by nibtime**
Fixes #24936

### CODE REVIEW

**Comment by ascorbic** [comment]
Hi. Thanks for the PR. This is failing tests at the moment. Looks like something wrong with imports. Could you check and see if you can get them to pass. Thanks.

File: packages/gatsby-plugin-offline/src/sw-append.js [hunk 1]
```diff
@@ -1,7 +1,3 @@
-/* global importScripts, workbox, idbKeyval */
-
-importScripts(`idb-keyval-iife.min.js`)
```
Comment (pvdz) [inline packages/gatsby-plugin-offline/src/sw-append.js:3]: Rather than prepending the whole `importScripts` line, perhaps you could only replace the url, like is being done for `%pathPrefix%` and `%appFile%`?

File: packages/gatsby-plugin-offline/src/gatsby-node.js [hunk 2]
```diff
@@ -162,7 +162,10 @@ exports.onPostBuild = (
 
   const idbKeyvalFile = `idb-keyval-iife.min.js`
   const idbKeyvalSource = require.resolve(`idb-keyval/dist/${idbKeyvalFile}`)
-  const idbKeyvalDest = `public/${idbKeyvalFile}`
+  const idbKeyValVersioned = `idb-keyval-${
+    require(`idb-keyval/package.json`).version
+  }-iife.min.js`
```
Comment (pvdz) [inline packages/gatsby-plugin-offline/src/gatsby-node.js:167]: Please put this on a separate line, above it.
```suggestion
  const idbKeyvalPackageJson = require(`idb-keyval/package.json`)
  const idbKeyValVersioned = `idb-keyval-${idbKeyvalPackageJson.version}-iife.min.js`
```

File: packages/gatsby-plugin-offline/src/sw-append.js (hunk 1 above)
Comment (nibtime) [reply packages/gatsby-plugin-offline/src/sw-append.js:3]: Yeah, that's better. `importScripts` must be in `sw-append.js`, otherwise the build fails.

File: packages/gatsby-plugin-offline/src/gatsby-node.js (hunk 2 above)
Comment (nibtime) [reply packages/gatsby-plugin-offline/src/gatsby-node.js]: I applied that in https://github.com/gatsbyjs/gatsby/pull/24938/commits/0cc3df6a49e3761332fa01cc85ecd501f6249c05
