### PR TITLE
fix(gatsby): fix onCreatePage typings

### LINKED ISSUE #20870: typing for onCreatePage incorrectly says page arg is Node
## Description

I'm using TypeScript for my `gatsby-node` file so that I can use `GatsbyNode` type definitions. When following the example in https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/#configuring-pages-with-matchpath, I get TS errors such as:

> Property 'match' does not exist on type 'unknown'. ts(2339)

image

The [Gatsby typings](https://github.com/gatsbyjs/gatsby/blob/2a1508e3175082ec559a5405ba464bf3c9156128/packages/gatsby/index.d.ts#L211) have `page` typed as `Node & TNode` which does not have a `path` property. Injecting a `console.log` into the function and building the site shows that `page` does indeed have a `path` property, thus the args are incorrectly typed.

### Steps to reproduce

1. Convert `gatsby-node` to TypeScript.
2. Attempt to follow any `onCreatePage` example with the `GatsbyNode["onCreatePage"]` typing.

### Expected result

`page.path.match` should have a valid type.

### Actual result

`page.path` is `unknown` because `page` is declared as a `Node & TNode`.

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.19.5 => 2.19.5 
    gatsby-image: 2.2.29 => 2.2.29 
    gatsby-plugin-extract-schema: 0.0.5 => 0.0.5 
    gatsby-plugin-manifest: 2.2.23 => 2.2.23 
    gatsby-plugin-offline: 3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: 3.1.13 => 3.1.13 
    gatsby-plugin-sharp: ^2.3.10 => 2.3.10 
    gatsby-plugin-styled-components: ^3.1.14 => 3.1.14 
    gatsby-plugin-typescript: 2.1.15 => 2.1.15 
    gatsby-source-filesystem: 2.1.33 => 2.1.33 
    gatsby-source-graphql: ^2.1.31 => 2.1.31 
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9 

## Workaround

Replace `onCreatePage: GatsbyNode["onCreatePage"]` with `onCreatePage: any`.

### PR DESCRIPTION
**Pull request by cainlevy**
I'm unsure if the TypeScript declarations have test coverage like with the DefinitelyTyped project, but I tried the changes in my own project and noted that my `onCreatePage` handler both types and runs properly.

## Description

Improve types for `onCreatePage` handler.

## Related Issues

Fixes #20870

### CODE REVIEW

File: packages/gatsby/index.d.ts [hunk 1]
```diff
@@ -208,8 +208,8 @@ export interface GatsbyNode {
    * See the guide [Creating and Modifying Pages](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/)
    * for more on this API.
    */
-  onCreatePage?<TNode extends object = {}>(
-    args: CreatePageArgs<TNode>,
+  onCreatePage?(
+    args: {page: Page, actions: Actions},
```
Comment (ascorbic) [inline packages/gatsby/index.d.ts]: Rather than change this, could you change `CreatePageArgs` to change the type for `page`. I'd suggest you make onCreatePage generic again, but rather than the Node type argument, make the type argument the context type, which you would pass to your new Page type.

Comment (cainlevy) [reply packages/gatsby/index.d.ts]: Thanks! My mistake. I wasn't clear on the naming convention used here.
