### PR TITLE
[www] Make iPhone X compatible

### LINKED ISSUE #9448: [www] Not optimised for iPhone X
## Description

The iPhone X's indicator for accessing the Home screen is blocking the bottom navigation. 

### Steps to reproduce

Visit https://gatsbyjs.org on an iPhone X and scroll down
### Expected result

What should happen?

Bottom navigation should have some kind of padding to make sure it's above the indicator for accessing the Home Screen.

What happened.

The indicator for accessing the Home Screen is blocking the menu

img_0217

### PR DESCRIPTION
**Pull request by gurtjun**
This should fix #9448. 
Also added padding to the banner, layout and desktop navigation to make sure it also works in landscape mode on the iPhone X
img_0218

### CODE REVIEW

File: packages/gatsby/cache-dir/default-html.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ export default class HTML extends React.Component {
           <meta httpEquiv="x-ua-compatible" content="ie=edge" />
           <meta
             name="viewport"
-            content="width=device-width, initial-scale=1, shrink-to-fit=no"
+            content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover"
```
Comment (DSchau) [inline packages/gatsby/cache-dir/default-html.js]: I'm not sure we want to make this the default. This would presume that _every_ website using Gatsby will make the necessary changes for iPhone X compatibility, correct?

Comment (DSchau) [reply packages/gatsby/cache-dir/default-html.js]: Maybe pass this in with react-helmet instead? I'd think the _last_ one will win out, so that should be a good solution here.

Comment (gurtjun) [reply packages/gatsby/cache-dir/default-html.js]: Correct, this will affect every website using Gatsby! That would be a bit overkill. 
I added it to the react-helmet tags in `layout.js`.

**Comment by gurtjun** [comment]
@DSchau I moved the meta to react-helmet in `layout.js` to make sure it only affects the GatsbyJS website.

**Comment by gurtjun** [comment]
Not sure why the AppVeyor build failed though, possible to re-run this?

**Comment by thorn0** [comment]
@gurtjun You can close and reopen the PR to rerun the checks.

**Comment by gurtjun** [comment]
> @gurtjun You can close and reopen the PR to rerun the checks.

I reworded my commit message to rerun the checks, but it's still failing.
Seems that it goes wrong when running `yarn run build` in `/examples/gatsbygram` in AppVeyor, but it's working on my machine. Can someone confirm that it's also working at their end?

**Comment by gurtjun** [comment]
@DSchau @thorn0 Seems that now all checks are passed without changing anything. Strange but cool 👍

**Comment by DSchau** [comment]
@gurtjun the Windows PRs (Appveyor) tend to be a little flaky. We're working on improving them from a consistency basis! Taking a look at this PR now.

**Comment by gurtjun** [comment]
I checked this out on a real device.
