### PR TITLE
Run typescript sources through full babel transpiling pipeline

### LINKED ISSUE #3356: gatsby build fails to minify js if typescript is used, doesn't show the error
## Description

Note: this issue was reported elsewhere at least once (#1887). It's still broken in the current gatsby version.

`gatsby build` leaves the `component---src-pages-index-tsx-***.js` file unminified, because of the `SyntaxError: Unexpected token: operator (>)` in a `=>`.

### Environment

Gatsby version: 1.9.149
Node.js version: v8.1.3
Operating System: OSX

### File contents (if changed):

`gatsby-config.js`: 
```
process.setMaxListeners(0);

const plugin = (resolve, opts=null) => {
  const d = {resolve};
  if (opts) {
    d.options = opts;
  }
  return d;
}

module.exports = {
  plugins: [
    'gatsby-plugin-typescript',
    
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sharp',
    plugin('gatsby-plugin-typography', {
      pathToConfigModule: 'src/utils/typography.ts',
    }),
    plugin('gatsby-plugin-google-fonts', {
      fonts: ['source sans pro', 'overlock'],
    }),
    plugin('gatsby-plugin-nprogress', {
      color: '#FF4F00',
      showSpinner: true,
    }),
    'gatsby-plugin-manifest',
    'gatsby-plugin-offline',

    'gatsby-transformer-sharp',
    
    plugin('gatsby-source-filesystem', {
      name: 'images',
      path: `${__dirname}/src/img/`,
    }),
  ],
}
```

### Actual result

`gatsby build` **silently** fails to minify a js file.

### Expected behavior

`gatsby build` properly minifies the file. If it fails to do so it at the very least must show lots of red bold alerts.

### Steps to reproduce

Given the following index.tsx:

```
export default (props: any) => {
  return <h1>hello world</h1>;
}
```

Run gatsby build.

Result: `component---src-pages-index-tsx-***.js` file isn't minified.

If I instrument node_modules/webpack/lib/optimize/UglifyJsPlugin.js (around line 122), I can see the following error:

```
⠐ Building production JavaScript bundlesopt chunk file  component---src-pages-index-tsx-95dadac712787e4124a7.js JS_Parse_Error {
  message: 'SyntaxError: Unexpected token: operator (>)',
  filename: 'component---src-pages-index-tsx-95dadac712787e4124a7.js',
  line: 1931,
  col: 26,
  pos: 71372,
  stack: 
    Error
        at new JS_Parse_Error (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)
        at js_error (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)
        at croak (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)
        at token_error (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)
        at unexpected (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)
        at expr_atom (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)
        at maybe_unary (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)
        at expr_ops (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)
        at maybe_conditional (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)
        at maybe_assign (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)
        at maybe_assign (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2869:32)
        at maybe_assign (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2869:32)
        at expression (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2880:20)
        at simple_statement (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2319:55)
        at eval (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2188:19)
        at eval (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)
        at block_ (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2434:20)
        at eval (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2406:25)
        at function_ (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2412:15)
        at expr_atom (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2627:24)
        at maybe_unary (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)
        at expr_ops (eval at <anonymous> (./node_modules/webpack/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)
```

### PR DESCRIPTION
**Pull request by farcaller**
This partially fixes #3356, maybe #3274 (#3274 fails to be minified).

Open issues:
- [x] tests fail. I have no idea how to mock `program` for tests, as it comes from gatsby-cli and I'm not familiar enough with the test framework to try mocking that out.
- [x] async/await syntax works now (as it goes through babel as expected), but fails to be minified.
- [x] `UglifyJsPlugin.js` still fails to bubble up the error / break the build with an error.
- [x] `transpileOnly` seems to be broken badly and is only used in tests.

### CODE REVIEW

**Comment by jquense** [comment]
Thanks for the PR! I think we'd really like to avoid full Babel processing in addition to running through the typescript compiler, since it's a lot of potentially extra work. In the case of async/await that should work with just the TS compiler I think we'd want to figure out why that isn't working before adding an additional solution

**Comment by farcaller** [comment]
@jquense I don't think that's possible. To make TS emit safe code you need to target `es5`, which would do things like turning arrow functions into "old-style" functions. But that also wipes away the tagged templates (which are es6) and `babel-plugin-extract-graphql` can no longer visit them as they are not tagged template expressions but are rendered into function calls (as confirmed by `WebpackError: graphql is not defined`).

**Comment by farcaller** [comment]
I'll hijack this PR to list (and hopefully fix) everything that's broken in gatsby in re. typescript support if you don't mind?

Re. #3274,

@wedelgaard I've figured what's wrong with async/await and this PR won't fix them completely. Apparently babel transpiles async/await syntax into generators (that's es6 too) and uglify chokes up on those then. One way to fix it would be by using `transform-regenerator` in the babel pipeline and adding the regenerator runtime, but I'm not sure how polyfills work with all these webpack-generated modules.

Re #3356,

I've found the place in gatsby that mutes webpack errors and propagated them properly, so all the issues raised in #3356 are fixed now.

Re `transpileOnly`,

I've misread the docs, apparently what it does is that it disables everything in typescript that compiles and verifies the code. So as of now the default version of `gatsby-plugin-typescript` is totally useless as it will ignore any ts errors. I guess the idea was that VSCode or any other ts-capable editor would do the magic?  That's not the right way to do typescript though...

As for switching `transpileOnly` to `true`, that causes a whole storm of errors within react. Insofar I found https://github.com/yarnpkg/yarn/issues/1334 that might explain the problems within yarn. Indeed, npm install doesn't break TS right there (it breaks it in other places). I've searched down to a random comment here: https://github.com/aspnet/JavaScriptServices/issues/1132#issuecomment-316526354, reverted the types to versions noted and finally make ts compile the code, but this solution is kinda subpar.

**Comment by farcaller** [comment]
After poking around yarn more I figured that the version issue is covered by https://github.com/yarnpkg/rfcs/pull/68, thus the typescript starter can be fixed with:

```js
  "dependencies": {
    "@types/react": "^15.6.2", // existing dependency
    ...
  },
  "resolutions": {
    "**/@types/react": "^15.6.2"
  },
```

by forcing all the types to the same version.

**Comment by farcaller** [comment]
It seems that `transform-regenerator` doesn't have any negative side-effects on the build overall, but I'm hesitant to include it into this PR as it requires runtime support. I'd suggest the following as a workaround to fix #3274:

Add .babelrc having 
```js
{
  "plugins": ["transform-regenerator"]
}
```

Import polyfill that implements generators in `index.jsx`:
```js
import 'babel-polyfill';
```

I've verified that it's enough to make async/await functional in runtime

**Comment by farcaller** [comment]
@jquense, @KyleAMathews anything else you want me to do so this could land? Typescript support is still broken.

I can work on moving the pipeline over to `awesome-typescript-loader` that has a native support for babel (and caching), but I'd prefer to make the current code functional first.

**Comment by jquense** [comment]
> To make TS emit safe code you need to target es5, which would do things like turning arrow functions into "old-style" functions. But that also wipes away the tagged templates (which are es6) and babel-plugin-extract-graphql can no longer visit them 

yes bable with JUST this transform should be run before typescript, which is waht is happening now. then TS compiler is left to compile whatever is left

**Comment by farcaller** [comment]
@jquense webpack loaders are applied right-to-left, so in the current code the code is first transpiled by TS, then babel runs it's pass.

**Comment by farcaller** [comment]
... and if I swap the order to run babel first and then the ts pass, then babel (expectedly) chokes up on the typescript code.

**Comment by jquense** [comment]
I didn't notice the direction of the loaders sorry :P 

I still not sure though how this addresses the problem. Either you run the source through babel first and it will choke on the TS or after TS and it will fail because the tagged templates are gone. It seems like the "correct" way to to fix this is to build a TS equivalent to the babel plugin here (using the ts compiler). This should be feasible? you don't need real code generation, just the location of the tags and a string replace after they are extracted. The other potential option is babel 7 which _does_ have TS parsing support

**Comment by farcaller** [comment]
I think the best route is to use something akin to the `awesome-typescript-loader` that is specifically tailored for TS+Babel pipelines and let it do the caching.

Rationale: let TS emit the richest possible output (`esnext` in this case) and then run it through exactly the same pipeline that exists now. Yes, it might be marginally slower, but it's [the most stable approach](https://www.reddit.com/r/ProgrammingJokes/comments/520sn0/how_does_a_programmer_boil_a_kettle/) that's not going to break randomly and will be flexible to support any changes in the global babel pipeline that's managed by gatsby.

This has an added benefit of having to deal only with babel polyfills as TS won't generate any library code in this case.

File: packages/gatsby-plugin-typescript/src/gatsby-node.js [hunk 1]
```diff
@@ -23,16 +22,10 @@ module.exports.modifyWebpackConfig = (
...
-  const extractQueryPlugin = path.resolve(
-    __dirname,
-    `../gatsby/dist/utils/babel-plugin-extract-graphql.js`
-  )
-
   config.loader(`typescript`, {
     test,
     loaders: [
-      `babel?${JSON.stringify({ plugins: [extractQueryPlugin] })}`,
+      `babel?${JSON.stringify(babelConfig)}`,
```
Comment (jquense) [inline packages/gatsby-plugin-typescript/src/gatsby-node.js]: rather then passing through the babel config can you stick the ts loader in front of the existing js loader in the chain. You can also "override" the `js` loader and pass a function the gets the current one and alters it.

its not clean, but this will be much easier to do neatly in v2, and i don't think we want to add more surface area if we can avoid it, since its much harder to deprecate later

**Comment by KyleAMathews** [comment]
@farcaller can you profile this change a bit to see roughly how much slower this PR makes things? If it's not too much, I think it'd be fine. We're moving to Babel 7 with Gatsby v2 which will give us more options.

File: packages/gatsby-plugin-typescript/src/gatsby-node.js (hunk 1 above)
Comment (farcaller) [reply packages/gatsby-plugin-typescript/src/gatsby-node.js]: If I do that then typescript becomes a hard dependency. I don't think that makes sense for most people using gatsby.

**Comment by farcaller** [comment]
> @farcaller can you profile this change a bit to see roughly how much slower this PR makes things

@KyleAMathews it is marginally slower, but don't forget that I'm comparing a fast and totally broken config with a slower and actually functional one. I don't think this should be a case where a faster option wins—the current plugin doesn't do what it advertises **and** breaks the prod builds.

**Comment by KyleAMathews** [comment]
>I'm comparing a fast and totally broken config with a slower and actually functional one.

Ok, sold :-)

Better working than fast. Make it work, make it correct, make it fast. Let's revisit this in Gatsby v2 once we're on webpack 3.

**Comment by jurosh** [comment]
Thanks a lot guys! Those TypeScript issues were pretty serious and just now I updated Gatsby and looks like minification works fine..
ps. I would be also fan of removing babel when doing compilation with TypeScript (to reduce build complexity) - already tried to do it, but that extraction of queries is blocker here as `tsc` compiler doesn't allow usage of plugins like we can use in babel...

**Comment by jlengstorf** [comment]
Hiya @farcaller! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs
