### PR TITLE
fix(gatsby-plugin-netlify-cms): dynamically import netlify-identity-widget

### LINKED ISSUE #9209: Netlify CMS always includes Netlify Identity Widget in JS
## Description

Netlify identity widget can be disabled for `gatsby-plugin-netlify-cms` by specifying `enableIdentityWidget: false` in configuration. I would expect that this would also ensure that the netlify identity widget would not be included in the built application JS files through WebPack. However, by using `source-map-explorer` that there is 161 kB of `netlify-identity-widget` present in the build.

### Steps to reproduce

1. Add netlify CMS plugin:
```
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        enableIdentityWidget: false,
        modulePath: `${__dirname}/src/cms/cms.js`
      }
    },
```
2. Build site `npm run build`
3. Check if the resulting app has widget included: `npx source-map-explorer public/app-*.js`

### Expected result

Netlify-identity-widget should be excluded if disabled.

### Actual result

Netlify-identity-widget is included in JS bundle.

### Environment

Cannot get info due to #8502

### PR DESCRIPTION
**Pull request by alexandernanberg**
Closes #9209

Also had to add `plugin-syntax-dynamic-import` to the `babel-preset-gatsby-package` config

### CODE REVIEW

**Comment by alexandernanberg** [comment]
Not sure about the circleci errors, seems like the registry went down?

**Comment by DSchau** [comment]
@alexandernanberg seems to be the case 😩 May need to re-run these in a few minutes, but don't worry about them failing for now!

File: packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js [hunk 1]
```diff
@@ -1,15 +1,33 @@
...
-    netlifyIdentityWidget.on(`init`, user => {
-      if (!user) {
-        netlifyIdentityWidget.on(`login`, () => {
-          document.location.href = `${__PATH_PREFIX__}/${publicPath}/`
+// Taken from https://github.com/netlify/netlify-identity-widget
+const routes = /(confirmation|invite|recovery|email_change)_token=([^&]+)/
+const errorRoute = /error=access_denied&error_description=403/
+const accessTokenRoute = /access_token=/
+
+exports.onInitialClientRender = (
```
Comment (DSchau) [inline packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js]: Is this whole block anything we want to test for? I'd think adding some tests would be really valuable here, even if "just" unit tests!

Comment (alexandernanberg) [reply packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js]: Yeah, that would be nice. Not sure how tho, since it's a dynamic import things become a bit more tricky. Are there any similar tests a can look at to get going?

**Comment by alexandernanberg** [comment]
@DSchau I've given this some more thought and AFAK there is no good way to unit test this – without changing the source 🤔 Do you have any ideas?

**Comment by DSchau** [comment]
@alexandernanberg it's probably OK, don't worry about it!

One thing I missed the first time... shouldn't `@babel/plugin-syntax-dynamic-import` be added as a dependency of `babel-preset-gatsby-package`?

**Comment by alexandernanberg** [comment]
@DSchau Good catch, I've added it now!

**Comment by shannonbux** [comment]
Anyone know why @gatsbyjs/docs got assigned to review this PR? Though I'm happy to help, I'm not the one you want for reviewing `.js` files :). `.md`, on the other hand...I'm all about that

**Comment by alexandernanberg** [comment]
@shannonbux Sorry about that – I had a newer version of prettier installed locally that formatted some files automatically, but I removed them from this PR when I realized that

**Comment by alexandernanberg** [comment]
@DSchau Is there anything else that you want me to fix or is this ready to get merged? Would be nice to shave off ~50kb of the bundlesize for the current site I'm working on 😄

**Comment by pieh** [comment]
@alexandernanberg I think this should reviewd by @erquhart - I don't have enough context on `netlify-identity-widget` :/

File: packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js (hunk 1 above)
Comment (erquhart) [reply packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js]: Instant bug if the source this was copied from changes. Perhaps Netlify Identity links should include a flag query like `netlify_identity_redirect=true`. Opened an issue to discuss: https://github.com/netlify/netlify-identity-widget/issues/157

File: packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js [hunk 2]
```diff
@@ -1,18 +1,33 @@
 /* global __PATH_PREFIX__ */
-import netlifyIdentityWidget from "netlify-identity-widget"
+
+// Taken from https://github.com/netlify/netlify-identity-widget
+const routes = /(confirmation|invite|recovery|email_change)_token=([^&]+)/
+const errorRoute = /error=access_denied&error_description=403/
+const accessTokenRoute = /access_token=/
```
Comment (erquhart) [inline packages/gatsby-plugin-netlify-cms/src/gatsby-browser.js]: Instant bug if the source this was copied from changes. Perhaps Netlify Identity links should include a flag query like `netlify_identity_redirect=true`. Opened an issue to discuss: https://github.com/netlify/netlify-identity-widget/issues/157

**Comment by jedrichards** [comment]
Wahoo, my bundle size will halve with this. Thanks guys.
