### PR TITLE
fix(gatsby): Fix filtering on resolvable children

### LINKED ISSUE #19357: Can't filter on childMdx fields
## Description

Queries that filter on childMdx fields return no nodes.

### Steps to reproduce

Execute a query for file nodes that includes a filter on some childMdx field.

```
query {
  allFile(
    filter: {childMdx: {frontmatter: {title: {eq: "First Post"}}}}
  ) {
    edges {
      node {
        id
      }
    }
  }
}
```

### Expected result

The query should return file nodes that match the filter.

### Actual result

The query returns nothing.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 3.7.5 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.13.50 => 2.17.10 
    gatsby-image: ^2.2.8 => 2.2.30 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.26 
    gatsby-plugin-mdx: ^1.0.0 => 1.0.55 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.13 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.36 
    gatsby-source-filesystem: ^2.1.8 => 2.1.35 
    gatsby-transformer-sharp: ^2.2.5 => 2.3.2 
  npmGlobalPackages:
    gatsby-cli: 2.8.8
    gatsby-dev-cli: 2.5.36

### PR DESCRIPTION
**Pull request by freiksenet**
Fixes #19357

### CODE REVIEW

**Comment by vladar** [comment]
LGTM. And now I know what this `determineSearchableFields` method is responsible for

File: packages/gatsby/src/schema/schema.js [hunk 1]
```diff
@@ -197,6 +193,14 @@ const processTypeComposer = async ({
         nodeStore,
         parentSpan,
       })
+    }
+    await determineSearchableFields({
+      schemaComposer,
+      typeComposer,
+      parentSpan,
```
Comment (muescha) [inline packages/gatsby/src/schema/schema.js]: `parentSpan` is not used in function call?
