### PR TITLE
fix(gatsby-transformer-remark): Activate footnotes by default & remove included options with remark v13

### LINKED ISSUE #30964: gatsby-transformer-remark lost footnotes with #29678
## Description

#29678 broke footnotes. They were extracted from remark in v 12.0.0 (https://github.com/remarkjs/remark/releases/tag/remark-stringify%408.0.0) to remark-footnotes https://github.com/remarkjs/remark-footnotes. Similar to `gfm` we need to import and load that module in `extend-node-type.js` (https://github.com/gatsbyjs/gatsby/blob/da503c6aeba9e4ea631ae83fb160442353f2cffc/packages/gatsby-transformer-remark/src/extend-node-type.js#L120)

Also, the `commonmark` and `pedantic` options can be removed as remark no longer supports them (https://github.com/remarkjs/remark/releases/tag/13.0.0)

Downgrading to `gatsby-transformer-remark@3.3.0-next.1` restores footnote support.

### Steps to reproduce

See starter blog with remark. Add a footnote. See it does not process.

### Expected result

Footnotes should be supported.

### Actual result

Footnotes are not transformed.

### Environment
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /Users/fshowalt/.pyenv/shims/python
  Browsers:
    Chrome: 89.0.4389.128
    Firefox: 57.0.4
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.3.0 => 3.3.0
    gatsby-cli: ^3.3.0 => 3.3.0
    gatsby-plugin-catch-links: ^3.3.0 => 3.3.0
    gatsby-plugin-feed: ^3.3.0 => 3.3.0
    gatsby-plugin-image: ^1.3.0 => 1.3.0
    gatsby-plugin-manifest: ^3.3.0 => 3.3.0
    gatsby-plugin-preact: ^5.3.0 => 5.3.0
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0
    gatsby-plugin-sass: ^4.3.0 => 4.3.0
    gatsby-plugin-sharp: ^3.3.0 => 3.3.0
    gatsby-plugin-sitemap: ^3.3.0 => 3.3.0
    gatsby-remark-smartypants: ^4.0.0 => 4.0.0
    gatsby-source-filesystem: ^3.3.0 => 3.3.0
    gatsby-transformer-json: ^3.3.0 => 3.3.0
    gatsby-transformer-remark: ^4.0.0 => 4.0.0
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0
  npmGlobalPackages:
    gatsby-cli: 2.12.62
```

### PR DESCRIPTION
**Pull request by fshowalter**
## Description

Re-enables footnotes in gatsby-transformer-remark and removes options removed from Remark in 13.0.0.

### Documentation

https://github.com/fshowalter/gatsby/blob/topics/fix-footnotes-in-gatsby-transformer-remark/packages/gatsby-transformer-remark/README.md

## Related Issues

Fixes #30964.

### CODE REVIEW

**Comment by fshowalter** [comment]
I don't believe the CI errors are related to this PR as they seem inconsistent, but if a maintainer feels otherwise, please let me know.

File: packages/gatsby-transformer-remark/src/gatsby-node.js [hunk 1]
```diff
@@ -9,15 +9,9 @@ exports.setFieldsOnGraphQLNodeType = require(`./extend-node-type`)
 
 exports.pluginOptionsSchema = function ({ Joi }) {
   return Joi.object({
-    commonmark: Joi.boolean().description(
-      `Activates CommonMark mode (default: true)`
-    ),
```
Comment (vladar) [inline packages/gatsby-transformer-remark/src/gatsby-node.js:14]: We shouldn't remove those options in a minor/patch version. Let's allow any value for now and schedule removal in the next major:

```
    // Options `commonmark` and pedantic have no effect since gatsby-transformer-remark@4.0.0
    // TODO: remove in v5
    commonmark: Joi.any(),
    pedantic: Joi.any(),
```

**Review by vladar — CHANGES_REQUESTED** [review]
Thank you for this PR! 💜 Please ignore CI errors - they are unrelated. I've added a minor request for changes to avoid another breaking change in minor/patch. Otherwise, it looks good to me and we can definitely merge it.

File: packages/gatsby-transformer-remark/src/gatsby-node.js (hunk 1 above)
Comment (fshowalter) [reply packages/gatsby-transformer-remark/src/gatsby-node.js:14]: Fixed.

**Review by vladar — APPROVED** [review]
Thank you 🙏
