### PR TITLE
[cli] Fix unhandled rejection when no browser found

### LINKED ISSUE #8470: yarn develop -o fails when not able to open a browser
## Description

Running `gatsby develop -o` on a machine without a web browser fails with
```
error UNHANDLED REJECTION
  Error: Exited with code 3
  - index.js:84 ChildProcess.cp.once.code
    [sandbox]/[opn]/index.js:84:13
  - child_process.js:925 maybeClose
    internal/child_process.js:925:16
  - child_process.js:346 Socket.stream.socket.on
    internal/child_process.js:346:11
```

Note: Ran into this while trying to run https://github.com/LeKoArts/gatsby-starter-minimal-blog in Codesandbox, because it defines the `dev` script as `gatsby develop -o`.

### Steps to reproduce

Run `gatsby develop -o` on a machine without a web browser.

### Expected result

`gatsby develop -o` ignores that there's no browser and continues working (and maybe shows a warning).

### Actual result

`gatsby develop -o` failes with above error.

### Environment

```
$ /sandbox/node_modules/.bin/gatsby info --clipboard

  System:
    OS: Linux 4.17 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: x64 Intel Xeon Processor (Skylake, IBRS)
    Shell: Unknown - /bin/sh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^2.0.0 => 2.0.0
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.2
    gatsby-plugin-lodash: ^3.0.1 => 3.0.1
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-remark-autolink-headers: ^2.0.5 => 2.0.5
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-prismjs: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^2.0.1 => 2.0.1
    gatsby-transformer-remark: ^2.1.1 => 2.1.1

Done in 1.90s.
```

### PR DESCRIPTION
**Pull request by lbogdan**
Fixes #8470 .

### CODE REVIEW

File: packages/gatsby/src/commands/serve.js [hunk 1]
```diff
@@ -36,6 +36,7 @@ module.exports = async program => {
     if (open) {
       console.log(`Opening browser...`)
       openurl(openUrlString)
+        .catch(err => console.log(`warn browser not opened`))
```
Comment (pieh) [inline packages/gatsby/src/commands/serve.js]: just for consistency - can this follow same format as one in `develop` command?

Comment (lbogdan) [reply packages/gatsby/src/commands/serve.js]: Sure, I didn't do it because `chalk` was not already imported. Should I go ahead and import it?

Comment (pieh) [reply packages/gatsby/src/commands/serve.js]: so let's do it other way around and drop `chalk` in the other one?

Comment (lbogdan) [reply packages/gatsby/src/commands/serve.js]: I could do that, but then it will not be consistent will all other messages in `develop`, which are using `chalk`. 🙂

Comment (pieh) [reply packages/gatsby/src/commands/serve.js]: hah, then import it in `serve` too ;) it's no big deal

Comment (lbogdan) [reply packages/gatsby/src/commands/serve.js]: Ok, I also beautified the `serve` output a bit in the process, if that's all right:
image

File: packages/gatsby/src/commands/develop.js [hunk 2]
```diff
@@ -426,6 +426,7 @@ module.exports = async (program: any) => {
       printDeprecationWarnings()
       if (program.open) {
         require(`opn`)(urls.localUrlForBrowser)
+          .catch(err => console.log(`${chalk.yellow(`warn`)} browser not opened`))
```
Comment (jquense) [inline packages/gatsby/src/commands/develop.js]: i'd change this to something more descriptive. This sounds like it just decided not to open the browser

Comment (lbogdan) [reply packages/gatsby/src/commands/develop.js]: I've also thought about that, but couldn't find a good wording - maybe "No web browser found, not opening" ?
