### PR TITLE
fix(gatsby-transformer-documentationjs): handle free floating jsdocs

### LINKED ISSUE #13052: gatsby-transformer-documentationjs creates non-unique ids
`gatsby-transformer-documentationjs` creates nodes that can have non-unique ids, for example for comments like these:

```js
/**
 * This is a free-floating comment
 */

/**
 * This is a function
 */
const fn = () => {}
```

When trying to build such a site with `GATSBY_DB_NODES=loki` this will throw:
```
error Error processing Markdown in node 27c286f3-9f32-5454-9d77-a9265e600a7d:
Trying to update unsynced document. Please save the document first by using insert() or addMany()
```

See repo: https://github.com/stefanprobst/gatsby-bug-docjs

### PR DESCRIPTION
**Pull request by pieh**
This is not great fix, but it is fix for issue described in #13052 . This is happening because `documention` package creates 2 jsdocs for same object. I'm not sure if "free floating" jsdoc is valid or not (in scenarios other than defining type definition / callback), but because this is problematic quick fix is to not create multiple nodes with same `id`

Fixes #13052

### CODE REVIEW

File: packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js [hunk 1]
```diff
@@ -113,9 +115,19 @@ describe(`transformer-react-doc-gen: onCreateNode`, () => {
         })
       )
     })
+
+    it(`doesn't create multiple nodes with same id`, () => {
+      Object.values(groupBy(createdNodes, `id`)).forEach(nodes =>
```
Comment (pieh) [inline packages/gatsby-transformer-documentationjs/src/__tests__/gatsby-node.js]: keep forgetting `Object.values` is not supported in node 6 - will fix

**Comment by stefanprobst** [comment]
Confirmed that www builds with Loki with this.
