### PR TITLE
[transformer-remark] Fix hardcoded field used in table of contents

### LINKED ISSUE #4038: [gatsby-transformer-remark] Improve opaque need for slug field
## Description

The gatsby-transformer-remark has an [opaque dependency](https://github.com/gatsbyjs/gatsby/blob/ee5aa897d60e024a25108b69b4fca943768d3063/packages/gatsby-transformer-remark/src/extend-node-type.js#L219-L227) on having a `slug` field. It's needed if the `tableOfContents` property is requested as part of a GraphQL query. You have to use the `createNodeField` action on markdown nodes to add a field called `'slug'`, or else the query fails and it's not clear why.

### Environment

Gatsby version: 1.9.197

### Actual result

Given this query

```graphql
query AllPostsQuery {
  allMarkdownRemark {
    edges {
      node {
        tableOfContents
        frontmatter {
          title
        }
      }
    }
  }
}
```

It will have an error for the `tableOfContents` field

```
{
  "errors": [
    {
      "message": "Cannot read property 'slug' of undefined",
      "locations": [
        {
          "line": 13,
          "column": 6
        }
      ],
      "path": [
        "markdownRemark",
        "tableOfContents"
      ]
    }
  ],
  "data" : ...
}
```

### Expected behavior

The error should at least describe the need for a `slug` field and a link to where the person can read more about how to add it.

### PR DESCRIPTION
**Pull request by oorestisime**
Fixes #4038

[plugin-transformer-remark] Add an optional field for, untill now a hardcoded field used in the table of contents urls generation.

### CODE REVIEW

File: packages/gatsby-transformer-remark/src/extend-node-type.js [hunk 1]
```diff
@@ -408,8 +412,14 @@ module.exports = (
       },
       tableOfContents: {
         type: GraphQLString,
-        resolve(markdownNode) {
-          return getTableOfContents(markdownNode)
+        args: {
+          field: {
+            type: GraphQLString,
+            defaultValue: `slug`,
```
Comment (pieh) [inline packages/gatsby-transformer-remark/src/extend-node-type.js]: How about:
- renaming `field` to `pathToSlugField`
- changing `defaultValue` to `fields.slug`
- changing `markdownNode.fields[field]` to `_.get(markdownNode, pathToSlugField)`
?

This would allow more flexibility - if someone define slugs in frontmatter - he could set path to field as `frontmatter.slug` or `frontmatter.path` and don't require to create node field duplicate

Comment (oorestisime) [reply packages/gatsby-transformer-remark/src/extend-node-type.js]: yeah definitely i haven't thought about using frontmatter, thanks!

Comment (oorestisime) [reply packages/gatsby-transformer-remark/src/extend-node-type.js]: i dont know what process you follow, let me know if i have to squash commits or fixup or.. :)

**Comment by oorestisime** [comment]
@m-allanson i understood that i was supposed to return null if the field does not exist. I still send some `console.warn`ings. Or do you mean it actually returned the correct table of contents in which case it is weird (cache?). 
what do you suggest to check? like the actual expected result from table of contents or handling default values and the path field?
