### PR TITLE
fix(gatsby-source-contentful): fix crash when downloading asset with a file that doesn't have a url

### LINKED ISSUE #19217: gatsby-source-contentful Gatsby build cannot call slice() on undefined
## Description

When building a project with the gatsby source it fails if some asset nodes have a `file` but the `file` doesn't have a `url` property. 

> error Plugin gatsby-source-contentful returned an error
>  TypeError: Cannot read property 'slice' of undefined
>   - download-contentful-assets.js:56 Promise.all.contentfulAssetNodes.map
>   [gatsby-source-contentful]/download-contentful-assets.js:56:41

I think this happens if an asset was 'created' but not ['processed'](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/asset-processing).

### Steps to reproduce

1. Create an asset in the Contentful universe, like this (replace CONTENTFUL_SPACE_ID and CONTENTFUL_API_KEY). This will create an asset.

```
curl --request POST \
  --url https://api.contentful.com/spaces/${CONTENTFUL_SPACE_ID}/environments/master/assets \
  --header 'authorization: Bearer ${CONTENTFUL_API_KEY}' \
  --header 'content-type: application/json' \
  --data '{
	"fields": {
		"title": {
			"en-US": "Example png"
		},
		"file": {
			"en-US": {
				"contentType": "image/jpeg",
				"fileName": "example.jpeg",
				"upload": "https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png"
			}
		}
	}
}'
```

2. Run `gatsby develop` with the following `gatsby-config.js` for `gatsby-source-contentful`. The important bit here is to use the `preview.contentful.com` host so that 'Draft' content is queried.

```
{
  resolve: 'gatsby-source-contentful',
  options: {
    spaceId:  process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
    downloadLocal: true,
    host: 'preview.contentful.com'
  }
}
```

### Expected result

The build process should complete.

### Actual result

What happened. Build process errored:

```
error Plugin gatsby-source-contentful returned an error


  TypeError: Cannot read property 'slice' of undefined

  - download-contentful-assets.js:56 Promise.all.contentfulAssetNodes.map
    [gatsby-source-contentful]/download-contentful-assets.js:56:41
```

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - /var/folders/4n/nd5y3s7x00gbr3mk4fq0jv4c0000gn/T/fnm-shell-4520279/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.1 - /var/folders/4n/nd5y3s7x00gbr3mk4fq0jv4c0000gn/T/fnm-shell-4520279/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 69.0.3
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.1.14 => 2.1.14 
    gatsby-cli: ^2.4.11 => 2.4.11 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-link: ^2.0.11 => 2.0.11 
    gatsby-mdx: ^0.4.3 => 0.4.5 
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.0.12 
    gatsby-plugin-catch-links: ^2.0.11 => 2.0.11 
    gatsby-plugin-google-tagmanager: ^2.0.9 => 2.0.9 
    gatsby-plugin-intercom-spa: ^0.1.0 => 0.1.0 
    gatsby-plugin-layout: ^1.0.12 => 1.0.12 
    gatsby-plugin-netlify: ^2.0.11 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.21 => 2.0.21 
    gatsby-plugin-sitemap: ^2.0.5 => 2.0.5 
    gatsby-plugin-styled-components: ^3.0.6 => 3.0.6 
    gatsby-remark-autolink-headers: ^2.0.14 => 2.0.14 
    gatsby-remark-prismjs: ^3.2.4 => 3.2.4 
    gatsby-source-airtable: ^2.0.8 => 2.0.8 
    gatsby-source-contentful: ^2.1.52 => 2.1.54 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-remark: ^2.2.5 => 2.2.5 
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14 
  npmGlobalPackages:
    gatsby-cli: 2.7.30

```

### PR DESCRIPTION
**Pull request by dylanjha**
## Description

Prevents build process error when a gatsby asset has a file but not a url

## Related Issues

Fixes #19217

### CODE REVIEW

File: packages/gatsby-source-contentful/src/download-contentful-assets.js [hunk 1]
```diff
@@ -49,6 +49,12 @@ const downloadContentfulAssets = async gatsbyFunctions => {
         reporter.warn(`The asset with id: ${id}, contains no file.`)
         return Promise.resolve()
       }
+      if (!node.file.url) {
+        reporter.warn(
+          `The asset with id: ${id} has a file but the file contains no url.`
+        )
```
Comment (pieh) [inline packages/gatsby-source-contentful/src/download-contentful-assets.js]: This has potential to spam terminal output if we do it for every asset missing file. But maybe that's fine 🤔 

How can you end up in scenario where there is asset without file attached to it in Contentful?

Comment (pieh) [reply packages/gatsby-source-contentful/src/download-contentful-assets.js]: Oh I see, you mentioned this in the issue

**Comment by dylanjha** [comment]
Thanks @pieh !
