### PR TITLE
fix(gatsby-cli): enable inspect-brk & inspect options

### LINKED ISSUE #24573: Enable --inspect & --inspect-brk arguments on the build/develop args
## Summary

Add gatsby --inspect & and gatsby --inspect-brk commands to gatsby to enable easier debugging.

Now with node 10 we can use the https://nodejs.org/docs/latest-v10.x/api/inspector.html API to enable debugging programmatically, especially with the new gatsby develop changes.

For develop we could just enable it when we spawn the command.

### Basic example

When gatsby --inspect is ran, in gatsby we do:
```js
const inspector = require('inspector');

inspector.open()
```

### Motivation

Fixes https://github.com/gatsbyjs/gatsby/issues/24349#issuecomment-635384602

### PR DESCRIPTION
**Pull request by herecydev**
Fixes #24573

### CODE REVIEW

File: packages/gatsby/src/commands/develop.ts [hunk 1]
```diff
@@ -106,20 +112,25 @@ module.exports = async (program: IProgram): Promise<void> => {
   // Run the actual develop server on a random port, and the proxy on the program port
   // which users will access
   const proxyPort = program.port
-  const [statusServerPort, developPort] = await Promise.all([
+  const [statusServerPort, developPort, debugPort] = await Promise.all([
     getRandomPort(),
     getRandomPort(),
+    program.inspectBrk ? getRandomPort() : Promise.resolve(null),
```
Comment (pieh) [inline packages/gatsby/src/commands/develop.ts:118]: When using `node --inspect(-brk)` port by default is 9229 (not random). 

It would also be great if we could follow `node --inspect-brk` semantics - which allow us to specify port `--inspect-brk=9230` or skip specyfying port and then fallback to default

Comment (herecydev) [reply packages/gatsby/src/commands/develop.ts:118]: @pieh have you seen my motivation for this in the linked issue. There's some complication around doing what you suggested. I think this could only be acheived if we forgo trying to debug the "parent process" and focus only on the "child process"

Comment (pieh) [reply packages/gatsby/src/commands/develop.ts:118]: Thanks for the nudge to go look into the issue discussion! I'll take this discussion there ;)

File: packages/gatsby/src/commands/develop-process.ts [hunk 2]
```diff
@@ -379,9 +380,24 @@ async function startServer(program: IDevelopArgs): Promise<IServer> {
...
 interface IDevelopArgs extends IProgram {
   graphqlTracing: boolean
+  debugInfo: IDebugInfo | null
+}
+
+const openDebuggerPort = (debugInfo: IDebugInfo): void => {
+  if (debugInfo.break) {
+    inspector.open(debugInfo.port, undefined, true)
+    // eslint-disable-next-line no-debugger
+    debugger
```
Comment (pieh) [inline packages/gatsby/src/commands/develop-process.ts:390]: Is this actually needed? wouldn't 3rd argument to `inspector.open` do what `inspect-brk` does?

Comment (herecydev) [reply packages/gatsby/src/commands/develop-process.ts:390]: Yep, else it doesn't actually stop at the next line.

Found some others that are following the same pattern as well: https://github.com/avajs/ava/blob/master/lib/worker/subprocess.js#L206-L211

**Comment by herecydev** [comment]
@pieh any further comments? Otherwise, should be good to go with this PR

**Comment by pieh** [comment]
@herecydev I updated your PR (resolved some merge conflicted) and also added few things from myself:
 1. Adjust CLI description / default value ( https://github.com/gatsbyjs/gatsby/pull/24693/commits/e380e559e6ffc0d6a754fb8824690fec70d452d6 ) - it was mentioning random port, which I guess was initial implementation and wasn't adjusted later on?
 2. Made some changes to debugging doc ( https://github.com/gatsbyjs/gatsby/pull/24693/commits/0a292f56902d7ae9aae9a750608d49c9055bf2f8 ):
   - `build` doesn't have `--inspect(-brk)` (just `develop` has it), so reverted args changes in launch configuration for build 
   -  added `autoAttachChildProcesses: true` for `develop` launch configuration - it appears like if auto-attach is toggled off, it wasn't attaching to child process on its own (might be something on my end?)
   - adjusted all shell commands 

From my perspective this is good to go in now, but would like input on changes that I made, before I merge this in

**Comment by herecydev** [comment]
Yep both changes look good, appreciate your input . Some docs will have to be updated when the vscode debugger gets updated: https://github.com/microsoft/vscode-js-debug

But let's deal with that closer to the time. Let's get that merged!

**Comment by aaronadamsCA** [comment]
Note that you might want to note in the doc the minimum Gatsby version to use this new launch config. I was caught off guard when `"args": ["develop", "--inspect-brk"]` failed on me; I had to check the blame on the Markdown doc to find that it had just been changed.

**Comment by herecydev** [comment]
I think that's part of a wider discussion, every feature that Gatsby adds would have to be labelled with what version it was introduced in. I think if you went back to Gatsby 2.0.0 then a fair amount of the docs wouldn't reflect that version.
