### PR TITLE
Don't persist state so often & use cheaper method for generating api run ids

### LINKED ISSUE #6611: [v2] out-of-memory error with large amount of nodes
With sufficently large amount of data heavy nodes Gatsby v2 will fail with `JavaScript heap out of memory` (without increasing heap size).

<details><summary>Terminal output</summary>

```
⢀ source and transform nodescontentTypes fetched 42
Updated entries  6908
Deleted entries  0
Updated assets  2800
Deleted assets  0
Fetch Contentful data: 108808.495ms
success source and transform nodes — 116.323 s

<--- Last few GCs --->

[60520:0x103800000]   132309 ms: Mark-sweep 1422.2 (1564.9) -> 1421.8 (1564.9) MB, 138.1 / 0.0 ms  allocation failure GC in old space requested
[60520:0x103800000]   132557 ms: Mark-sweep 1421.8 (1564.9) -> 1421.8 (1523.9) MB, 247.6 / 0.7 ms  last resort GC in old space requested
[60520:0x103800000]   132726 ms: Mark-sweep 1421.8 (1523.9) -> 1421.8 (1519.4) MB, 168.9 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xf62d8aa57c1 <JSObject>
    1: mapToObject(aka mapToObject) [/Users/mike/dev/gatsbyinc/project/node_modules/gatsby/dist/redux/index.js:~32] [pc=0xb78e9d0547a](this=0xf625f7822d1 <undefined>,map=0xf622b48d6c1 <Map map = 0xf62f42048d9>)
    2: /* anonymous */ [/Users/mike/dev/gatsbyinc/project/node_modules/gatsby/dist/redux/index.js:103] [bytecode=0xf6295584df1 offset=79](this=0xf62dea0c211 <JSGlobal Object>,state...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/mike/.nvm/versions/node/v8.11.1/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/mike/.nvm/versions/node/v8.11.1/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/mike/.nvm/versions/node/v8.11.1/bin/node]
```
</details>

This seems to be cause by serializing huge nodes array to JSON string:

Here we pass all nodes and nodes of given type as args for `setFieldsOnGraphQLNodeType` API hook:
https://github.com/gatsbyjs/gatsby/blob/917ca71bb9e4c2d0d62bb644978de1a94a18e0e8/packages/gatsby/src/schema/build-node-types.js#L145-L153

This later get's serialized (`JSON.stringify(args)`):
https://github.com/gatsbyjs/gatsby/blob/1194951c0f75a3707aed560d7cee669b463ab16b/packages/gatsby/src/utils/api-runner-node.js#L171-L173

Resulting string itself wouldn't cause to cause out of memory, it seems like process of serializing it does:
memory

What I think is that `JSON.stringify` concatenate array items one by one and those intermediate strings are kept and we run out of memory before they are garbage collected (not sure about this, maybe someone with deeper v8 knowledge can correct me if I'm wrong).

This is change that fixes this problem (or maybe I should say workaround it) - https://github.com/pieh/gatsby/commit/b32ae20d35763a5941e4212bc3d8504159a2651c (just don't pass nodes as-is to API hook) - but if we would have 2x more nodes - we would hit same problem when we serialize reducer state to save it to file - right now it seems we get out-of-memory crash because we serialize nodes array twice independently (in API runner tracing and redux state saving)

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fixes #6611

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit e844756d4c0a1bd77999b7bd4fb40827501ae4bc

https://app.netlify.com/sites/using-postcss-sass/deploys/5b52a3a5e39e7c1a4404c062

**Comment by KyleAMathews** [comment]
Seems most of the OOM problems in #6611 were that we were persisting state multiple times during bootstrap (every second or so) and persisting state takes _just_ longer than a second which means you’d have overlapping persistings which would cause lots of contention which meant that there could soon be multiple persistings all going at once. I timed them and one got to 13 seconds. This PR changes persisting to now only happen once at the end of bootstrap which seems to have solved the OOM problem (just did a build w/o increasing heap size w/ no problems)

File: packages/gatsby-transformer-remark/src/extend-node-type.js [hunk 1]
```diff
@@ -104,7 +105,9 @@ module.exports = (
         return await ASTPromiseMap.get(cacheKey)
       } else {
         const ASTGenerationPromise = new Promise(async resolve => {
-          const files = getNodes().filter(n => n.internal.type === `File`)
+          if (process.env.NODE_ENV === `production` && !fileNodes) {
+            fileNodes = getNodes().filter(n => n.internal.type === `File`)
```
Comment (KyleAMathews) [inline packages/gatsby-transformer-remark/src/extend-node-type.js]: Not filtering on every query tripled graphql query rate for markdown 😱
