### PR TITLE
fix: Restore CLI port in use prompt feature

### LINKED ISSUE #24854: develop command crashing when default 8000 port in use,
I've bumped into a bug only in the last day or two and I'm not sure what update might have caused the change. When running `npx gatsby develop` and I already have something running on port 8000, I'd get the standard  response: `Would you like to run the app at another port instead?` but now the command crashes.

I can still run my server on another port with `npx gatsby develop -p 8001` and I so far assume this issue won't interfere with anything else.
I've not found this specific bug reported but there does appear to be recent activity around other yoga-layout-prebuilt bugs..
Here's the error:

```
/Users/Antonio/code/gatsby-starter-blog/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at startDevelopProxy (/Users/Antonio/code/gatsby-starter-blog/node_modules/gatsby/dist/utils/develop-proxy.js:79:10)
    at module.exports (/Users/Antonio/code/gatsby-starter-blog/node_modules/gatsby/dist/commands/develop.js:133:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 8000
}
```

### PR DESCRIPTION
**Pull request by polarathene**
## Description

Seems like it got accidentally removed during a big PR? DX with the `gatsby develop` command regressed as a result, if you had an existing process using port 8000, you would get the following:

```
$ gatsby develop

/.asdf/installs/nodejs/14.4.0/.npm/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8000
}
```

The above was also the output when run on the same project, where an appropriate error message should have been output. With this PR you'd now experience this:

```
$ gatsby develop

Something is already running at port 8000
✔ Would you like to run the app at another port instead? … yes

 ERROR 

Looks like develop for this site is already running. Try visiting http://localhost:8000/ maybe?
```

Now the correct error at the bottom is output to the terminal. Might be able to trigger that before the one this PR provides? Unclear as it wasn't triggering if the port was already in use (I assume it does if you specify a different port like this PR handles instead of crashing).

Unlike the same project error message, this PR prompt would still be useful if running multiple `develop` processes for different projects.

## Related Issues

Fixes #24854 

## Note

The `develop.ts` file has a comment in the first line:

> NOTE(@mxstbr): Do not use the reporter in this file, as that has side-effects on import which break structured logging 

The PR that removed this feature, kept the utility file active in the src, despite it not being used anymore, I'm not sure if that was intentional or just missed from the size of that PR. The above comment by @mxstbr may be relevant though as the utility does import the reporter, I'm not sure what the impact to users doing development is regarding breaking structured logging?

https://github.com/gatsbyjs/gatsby/blob/f1ace29f71bb2b9c25a2538f4fe2d8c8ebc89f9a/packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts#L2

### CODE REVIEW

**Comment by polarathene** [comment]
Forgot to test the command without the option/ENV var, the ports were always considered a mismatch as despite the TypeScript typing of the argument `port` gatsby-cli has that typed to `string`(presumably to support service names in addition to port numbers? Unclear as it's been a string type since the file was created), while the utility only works with a number.

This line used to exist within `develop.ts`:

https://github.com/gatsbyjs/gatsby/blob/0c0880999c0294748f6815ba63c5e06f14d1c0f7/packages/gatsby/src/commands/develop.ts#L392

If the CLI option type was changed to a `number`, that should remove the need for such, as I don't know if since that lines removal, `string` type for the port is intentional to support, I've restored that logic into the utility instead.

---

If it makes sense to instead change the CLI option type to a number like other port options, I can make that change instead?

File: packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts [hunk 1]
```diff
@@ -5,11 +5,11 @@ import prompts from "prompts"
 export const detectPortInUseAndPrompt = async (
   port: number
 ): Promise<number> => {
-  let foundPort = port
-  const detectedPort = await detectPort(port).catch((err: Error) =>
+  let foundPort = typeof port === `string` ? parseInt(port, 10) : port
```
Comment (blainekasten) [inline packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts:8]: why did you have to add this code? TS states that the port has to be a number.

File: packages/gatsby/src/commands/develop.ts [hunk 2]
```diff
@@ -163,6 +164,17 @@ const REGEX_IP = /^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(?:25
...
+  try {
+    program.port = await detectPortInUseAndPrompt(program.port)
+  } catch (e) {
+    if (e.message === `USER_REJECTED`) {
+      process.exit(0)
+    }
+
+    throw e
+  }
+
```
Comment (blainekasten) [inline packages/gatsby/src/commands/develop.ts:177]: 👍 looks like the same code from [before](https://github.com/gatsbyjs/gatsby/blob/4fd8f8e463402bff2944d98d83f2920dc0792755/packages/gatsby/src/commands/develop.ts#L390-L398)

File: packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts (hunk 1 above)
Comment (polarathene) [reply packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts:8]: See [last message](https://github.com/gatsbyjs/gatsby/pull/25863#issuecomment-660823247) I left in this PR. `gatsby-cli` types the port to string, it's unclear if it that's intentional(it's possible to use ports that aren't numbers, though I doubt anyone is doing that). TS isn't doing any enforcement or conversion despite the typing.

File: packages/gatsby/src/commands/develop.ts (hunk 2 above)
Comment (polarathene) [reply packages/gatsby/src/commands/develop.ts:177]: Yes, it is. This PR is restoring that, as pointed out seems like it was accidentally removed.

File: packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts (hunk 1 above)
Comment (blainekasten) [reply packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts:8]: ah oof. Seems like a mistake on the TS side then.. Wonder if we should fix this more globally. to make port always be a number.

Comment (blainekasten) [reply packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts:8]: I pushed up a change to handle the case early. Glad we found this discrepancy!

Comment (polarathene) [reply packages/gatsby/src/utils/detect-port-in-use-and-prompt.ts:8]: Should be fine, do you want that change added to this PR?

**Comment by blainekasten** [comment]
lol crap. gatsbybot merged the PR before my commit went through. Either way this was working great, my fix is just semantic. I'll put it through in a new PR
