### PR TITLE
fix: ignore dot files in page creator plugin.

### LINKED ISSUE #8474: 2.0 Regression - `gatsby build` fails on "dot" files in pages folder
## Description

This appears to be a regression, or at least difference in the handling of "dot" files within the `pages` folder during the `gatsby build` command. 

This was working in 1.x, but now in 2.0 it fails. I believe the intended behavior should be that dot files are ignored during the `gatsby build` command. 

### Steps to reproduce

In the `src/pages` folder, create a "dot" file, such as `.markdownlint.json` which does not export a react component. 
ie: 
```
{
  "first-heading-h1": false,
  "MD013": false,
  "first-line-h1": false
}
```

Run `gatsby build` and observe the build error. Notice though that `gatsby develop` **does** work correctly. 

### Expected result

The command should build successfully.

### Actual result

```
1:34:06 PM: success Building production JavaScript and CSS bundles — 11.416 s
1:34:07 PM: error Building static HTML for pages failed
1:34:07 PM: See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
1:34:07 PM: 
1:34:07 PM:   WebpackError: Invariant Violation: Minified React error #130; visit https://re  actjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the   full message or use the non-minified dev environment for full errors and addit  ional helpful warnings.
1:34:07 PM:   
1:34:07 PM:   
1:34:07 PM:   
1:34:07 PM:   - bootstrap:24 a.render
1:34:07 PM:     lib/webpack/bootstrap:24:1
1:34:07 PM:   
1:34:07 PM:   - bootstrap:21 a.read
1:34:07 PM:     lib/webpack/bootstrap:21:1
1:34:07 PM:   
1:34:07 PM:   - bootstrap:32 renderToString
1:34:07 PM:     lib/webpack/bootstrap:32:1
1:34:07 PM:   
1:34:07 PM:   - static-entry.js:188 Module../.cache/static-entry.js.__webpack_exports__.defa    ult.React.Component [as default]
1:34:07 PM:     lib/.cache/static-entry.js:188:18
1:34:07 PM:   
1:34:07 PM:   - bootstrap:24 Promise
1:34:07 PM:     lib/webpack/bootstrap:24:1
```

### Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.7 => 2.0.7 
    gatsby-plugin-catch-links: 2.0.2 => 2.0.2 
    gatsby-plugin-google-analytics: 2.0.6 => 2.0.6 
    gatsby-plugin-mailchimp: https://github.com/benjaminhoffman/gatsby-plugin-mailchimp.git#gatsby-v2 => 3.3.0 
    gatsby-plugin-manifest: 2.0.2 => 2.0.2 
    gatsby-plugin-offline: 2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: 3.0.0 => 3.0.0 
    gatsby-plugin-sass: 2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-sitemap: 2.0.1 => 2.0.1 
    gatsby-remark-autolink-headers: 2.0.6 => 2.0.6 
    gatsby-remark-copy-images: 0.2.1 => 0.2.1 
    gatsby-remark-copy-linked-files: 2.0.5 => 2.0.5 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: 2.0.1 => 2.0.1 
    gatsby-remark-prismjs: 3.0.0 => 3.0.0 
    gatsby-remark-responsive-image: ^1.0.0-alpha13-alpha.435e0178 => 1.0.0-beta.5-alpha.fb30fcd6 
    gatsby-source-filesystem: 2.0.1 => 2.0.1 
    gatsby-transformer-remark: 2.1.3 => 2.1.3 
    gatsby-transformer-sharp: 2.1.1 => 2.1.1 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### PR DESCRIPTION
**Pull request by mikelax**
Closes #8474 

Refactor the page creator plugin to ignore "dot" files.

### CODE REVIEW

**Comment by pieh** [comment]
I'm not sure about files starting with dot but it does sound reasonable. Could you also add ignoring `.json` files as well (same way `.d.ts` files are ignored)?

File: packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 const validatePath = require(`../validate-path`)
 const createPath = require(`../create-path`)
 
-describe(`JavaScript page creator`, () => {
+describe.only(`JavaScript page creator`, () => {
```
Comment (pieh) [inline packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js]: was this intentional to leave this here? or just for testing tests during dev?

Comment (mikelax) [reply packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js]: Oh fail, I forgot to remove after testing.  All tests ran anyway so it didn’t do anything. I will remove this.

File: packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js [hunk 2]
```diff
@@ -18,6 +18,59 @@ describe(`JavaScript page creator`, () => {
...
+      },
+      {
+        path: `.markdownlint.json`,
+      },
+      {
+        path: `something/.markdownlint.json`,
+      },
+    ]
+
+    expect(files.filter(file => validatePath(file.path)).length).toEqual(1)
```
Comment (DSchau) [inline packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js]: nit: but I'd probably just remove the `something/blah.js` and validate that the array length is `0`. _Then_ test the explicit .js inclusion in a separate test?

File: packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js [hunk 3]
```diff
@@ -18,6 +18,59 @@ describe(`JavaScript page creator`, () => {
...
+      },
+      {
+        path: `dir1/file.json`,
+      },
+      {
+        path: `dir1/dir2/file.json`,
+      },
+    ]
+
+    expect(files.filter(file => validatePath(file.path)).length).toEqual(2)
```
Comment (DSchau) [inline packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js]: Another way you could write this would be something like this

```js
const expected = [
  { path: `something/blah.js` },
  { path: `somefile.js` }
]

const files = expected.concat([]) // other files

expect(files.filter(file => validatePath(file.path)).length).toEqual(expected.length)
```

Comment (mikelax) [reply packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js]: hey @DSchau, I was just sticking with the format of the tests that were already there. If there is a new pattern for these types or tests, or you want me to update this and the other nit happy to do so.

Comment (DSchau) [reply packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js]: Should've looked! Up to you :) I'm all for improvements, and this is probably a good time to do them! What do you think?

File: packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js (hunk 1 above)
Comment (pieh) [reply packages/gatsby-plugin-page-creator/src/__tests__/gatsby-node.js]: Ha, don't worry - that's why we have those reviews ;)

**Comment by pieh** [comment]
> Also, I was wondering if in the `package.json` file we should update the peerDependencies to remove the alpha tag?

It looks a bit weird, but `2.0.0` does satisfy `>2.0.0-alpha` semver constraint. This probably would need to be selectively updated to see what's the actual need of packages and not just universally update it everywhere?

**Comment by mikelax** [comment]
>It looks a bit weird, but 2.0.0 does satisfy >2.0.0-alpha semver constraint. This probably would need to be selectively updated to see what's the actual need of packages and not just universally update it everywhere?

gotcha, I was just asking to remove the alpha, so leave `>2.0.0` to try and get any users that may still have the alpha, beta, or rc versions upgraded.

**Comment by mikelax** [comment]
@dschau I am 99% done with the changes. Will push in 5 min.

**Comment by DSchau** [comment]
@mikelax you're the best; it's appreciated :)
