### PR TITLE
fix(gatsby-telemetry): Don't display analytics notification if opted out

### LINKED ISSUE #16254: Don't display the opt-out text after opting out of telemetry
## Description

The telemetry 'opt-out' instructions can display after opting out of telemetry. The text should not display after opting out.

### Steps to reproduce

See https://twitter.com/code_punkt/status/1156597414486298624

### Expected result

'opt-out' text should not display

### Actual result

'opt-out' text is displayed

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### PR DESCRIPTION
**Pull request by alexluong**
Fixes #16254

### CODE REVIEW

File: packages/gatsby-telemetry/src/postinstall.js [hunk 1]
```diff
@@ -1,12 +1,14 @@
...
+const isTruthy = require(`./is-truthy`)
 
 let enabled = false
 try {
   const ci = require(`ci-info`)
   const Configstore = require(`configstore`)
   const config = new Configstore(`gatsby`, {}, { globalConfigPath: true })
   enabled = config.get(`telemetry.enabled`)
-  if (enabled === undefined && !ci.isCI) {
+  const disabled = isTruthy(process.env.GATSBY_TELEMETRY_DISABLED)
```
Comment (jamo) [inline packages/gatsby-telemetry/src/postinstall.js]: It would be cool to have this check live in only a single place. 
One option would be to expose the disabled field from the event store instead.

Comment (sidharthachatterjee) [reply packages/gatsby-telemetry/src/postinstall.js]: I went ahead and did this

**Comment by alexluong** [comment]
Thank you @sidharthachatterjee and @jamo for the review. It was fun.
