### PR TITLE
Always add leading slash to Gatsby Links, prevent double render during hydration

### LINKED ISSUE #1883: Duplicate render when `gatsby-link` is missing a leading slash
Hi again! I'm hitting double renders when omitting leading slashes in `gatsby-link` components.

**Reproduction:**

1. Visit http://gatsby-slash-append.surge.sh/
2. Open the networking panel
3. Throttle to 3G Slow

You should see the animation play for the static HTML, and then play again when React blows away the element and triggers the CSS animation once more.

**What I think is wrong:**

I think this is because the SSR markup includes a leading slash, however the client-side markup does not. At least, that seems to be the case when I diff the markup.

**Check out the code here:**

https://github.com/nhunzaker/gatsby-double-render/blob/master/src/pages/index.js

### PR DESCRIPTION
**Pull request by nhunzaker**
Good evening! 

This commit normalizes `to` on Gatsby Link to avoid leading double slashes, allowing a leading slash to consistently be inserted at the beginning of anchor tag hrefs.

This prevents a mismatch between server and client rendering, causing
a double render.

**Reproduction:**
http://gatsby-slash-append.surge.sh/

**The fix:**

http://gatsby-slash-append-fix.surge.sh/

---

Fixes #1883 

double-render

### CODE REVIEW

File: packages/gatsby/src/redux/__tests__/__snapshots__/pages.js.snap [hunk 1]
```diff
@@ -114,6 +120,7 @@ Array [
     "path": "/hi/",
     "pluginCreatorId": "test",
     "pluginCreator___NODE": "test",
+    "updatedAt": "2017-08-23T02:25:12.557Z",
   },
 ]
 `;
```
Comment (nhunzaker) [inline packages/gatsby/src/redux/__tests__/__snapshots__/pages.js.snap]: I'm not 100% sure why these needed updating.

**Comment by nhunzaker** [comment]
Also, sorry for the mess. Apparently I am not a master of copy/paste

File: packages/gatsby/src/redux/__tests__/__snapshots__/pages.js.snap (hunk 1 above)
Comment (KyleAMathews) [inline packages/gatsby/src/redux/__tests__/__snapshots__/pages.js.snap]: Ugh, those were from a PR of mine and I guess I didn't see Travis failing. Sorry about that.

**Comment by nhunzaker** [comment]
@KyleAMathews you're welcome! Thank you for all of your work on Gatsby!
