### PR TITLE
fix(gatsby-remark-images): captions do not show fallback based on filename

### LINKED ISSUE #14188: [gatsby-remark-images]: bug: uses filename as alt text when showCaptions is true
## Description

Since https://github.com/gatsbyjs/gatsby/pull/13489, when using `showCaptions:true` `gatsby-remark-images` inserts the file name, when using the standard img snippet:

```
![](./img.jpg)
```

### Steps to reproduce
1. Enable showCaptions:true with latest version of plugin
2. Add `` to a markdown

### Expected result
Shouldn't be any caption shown

### Actual result
The file name is inserted as caption

### Temporary workaround
You can insert a space between [ ], and then a space is shown instead, at least not visible.

### Environment

```

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.15.1 - ~/n/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/n/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.5
    Safari: 12.1
  npmPackages:
    gatsby: 2.5.x => 2.5.6 
    gatsby-image: ^2.1.0 => 2.1.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-images: 3.x => 3.0.11 
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.36 => 2.0.36 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.5.15
```

### PR DESCRIPTION
**Pull request by FrederikBolding**
## Description

Fixed an issue where captions would show the image filename if no caption/alt was given.

## Related Issues

Fixes #14188

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Had a chance to fix the linting issues. Will do a test a bit later!

**Comment by FrederikBolding** [comment]
@DSchau Added a test!

**Comment by FrederikBolding** [comment]
@DSchau I just reverted the change to the snapshot - Seems to be working fine now!

File: packages/gatsby-remark-images/src/__tests__/index.js [hunk 1]
```diff
@@ -369,4 +369,19 @@ describe(`showCaptions`, () => {
...
+
+    const nodes = await plugin(createPluginOptions(content, imagePath), {
+      showCaptions: true,
+    })
+    expect(nodes.length).toBe(1)
+
+    const node = nodes.pop()
+    const $ = cheerio.load(node.value)
+    expect($(`figcaption`).length).toBe(0)
+    expect(node.value).toMatchSnapshot()
```
Comment (DSchau) [inline packages/gatsby-remark-images/src/__tests__/index.js]: I'd just remove this! We're already testing what we want with the figcaption.length line 👍

Comment (DSchau) [reply packages/gatsby-remark-images/src/__tests__/index.js]: (Also great unit test 🚀 Nicely done!)

Comment (FrederikBolding) [reply packages/gatsby-remark-images/src/__tests__/index.js]: @DSchau I assume you mean line 385? It's all marked 😆

Comment (DSchau) [reply packages/gatsby-remark-images/src/__tests__/index.js]: Not sure what "it's all marked" means--but yeah, line 385!

```suggestion
```

Comment (FrederikBolding) [reply packages/gatsby-remark-images/src/__tests__/index.js]: @DSchau Great! I just mean that it's a comment for the whole block of code, but you're saying "I'd remove this" :-P

**Comment by FrederikBolding** [comment]
There you go!

**Comment by DSchau** [comment]
Successfully published:
 - gatsby-remark-images@3.0.12
