### PR TITLE
fix(www): fix background on gatsby version indicator in showcase

### LINKED ISSUE #20686: Gatsby starters version indicator is the wrong size on some starters
## Description

On the starters page, the Gatsby version indicator background is too large on those whose names are too long.

### Steps to reproduce

1. Head to this search query: https://www.gatsbyjs.org/starters/?c=Firebase&v=2
2. Example shown with first starter

### PR DESCRIPTION
**Pull request by keevan**
Resolves #20686

Also ensures the version and stars are always pinned to the top most
corner instead of sometimes floating based on the length of the author's
name

### CODE REVIEW

File: www/src/views/starter-library/starter-list.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ const StartersList = ({ urlState, starters, count, sortRecent }) => {
                     >
                       {owner} /
                     </span>
-                    <span css={{ display: `flex` }}>
+                    <span css={{ display: `flex`, maxHeight: '1rem' }}>
```
Comment (wardpeet) [inline www/src/views/starter-library/starter-list.js]: We should remove this one as it's more a hack than a fix.
```suggestion
                    <span css={{ display: `flex` }}>
```

Comment (keevan) [reply www/src/views/starter-library/starter-list.js]: Thank you for taking the time to review and suggest edits for my commit. Yes your proposed changes is definitely less hacky.
