### PR TITLE
fix(gatsby-transformer-sharp): define required image fields as non-null in schema

### LINKED ISSUE #17003: [gatsby-image] Bad schema typing for gatsby-images ?
Hi,

The TS defs for a fluid image is:

```tsx
export interface FluidObject {
  aspectRatio: number
  src: string
  srcSet: string
  sizes: string
  base64?: string
  tracedSVG?: string
  srcWebp?: string
  srcSetWebp?: string
  media?: string
}
```

Yet if we look at a graphql image fragment like this one, we can notice they are actually incompatible:

image

The GraphQL schema says that all those attributes can be undefined (which does not really make sense to me, is it possible to have an image without at least an src?)

The problem is that if you try to generate typedefs from generic queries, you'll end up with incompatible typings and will have to find workarounds (like using "any").

Otherwise you'll get typescript errors like this:

```
[0] src/page/home/queries/Images.tsx(54,3): error TS2322: Type 'Pick<ImageSharpFluid, "src" | "sizes" | "srcSet" | "aspectRatio" | "tracedSVG" | "srcWebp" | "srcSetWebp">[]' is not assignable to type 'Pick<FluidObject, "media" | "src" | "base64" | "sizes" | "srcSet" | "tracedSVG" | "srcWebp" | "srcSetWebp">[]'.
[0]   Type 'Pick<ImageSharpFluid, "src" | "sizes" | "srcSet" | "aspectRatio" | "tracedSVG" | "srcWebp" | "srcSetWebp">' is not assignable to type 'Pick<FluidObject, "media" | "src" | "base64" | "sizes" | "srcSet" | "tracedSVG" | "srcWebp" | "srcSetWebp">'.
```

I suggest to make those types compatible so that people using tools like graphql-codegen can easily use gatsby images

### PR DESCRIPTION
**Pull request by daugsbi**
## Description
The generated graphql schema have a lot of nullable fields which are required for images (i.e. the src of an image). This makes it incompatible to use it with type generators and TypeScript. 

This PR changes the gatsby-source-contentful and the gatsby-transformer-sharp to be at least compatible with the gatsby-image type definitions. 

### Documentation
Docs should exist already. I don't expect that they include such details. 

## Related Issues
This PR should close #17003.

### CODE REVIEW

File: packages/gatsby-transformer-sharp/src/customize-schema.js [hunk 1]
```diff
@@ -73,10 +74,10 @@ const fixedNodeType = ({
...
         },
         aspectRatio: { type: GraphQLFloat },
-        width: { type: GraphQLFloat },
-        height: { type: GraphQLFloat },
-        src: { type: GraphQLString },
-        srcSet: { type: GraphQLString },
+        width: { type: new GraphQLNonNull(GraphQLFloat) },
+        height: { type: GraphQLNonNull(GraphQLFloat) },
+        src: { type: GraphQLNonNull(GraphQLString) },
+        srcSet: { type: GraphQLNonNull(GraphQLString) },
```
Comment (vladar) [inline packages/gatsby-transformer-sharp/src/customize-schema.js]: Can you change it to `new GraphQLNonNull` everywhere for consistency (height, src, srcSet)?

Comment (daugsbi) [reply packages/gatsby-transformer-sharp/src/customize-schema.js]: Yes, sure. Just changed it with my last commit.
