### PR TITLE
fix(gatsby): persist pages between runs

### LINKED ISSUE #26520: createPages uses stale cached data for "previous" and "next" pages
## Description

I noticed this on my own blog's "previous post" and "next post" links, and it's reproducible on `gatsby-starter-blog`. It may have broader implications beyond my use case as well.

If you have links to "previous" and "next" posts on each blog post's page, then those are not updated on each build. As you add posts, they remember their cached "previous" link, but are never updated with the "next." If a post is removed, then existing "previous/next" links are preserved. (And its page will still exist in the build.)

### Steps to reproduce

I made a sample repo (almost identical to `gatsby-starter-blog`): https://github.com/johnridesabike/gatsby-prev-next

```
git clone https://github.com/johnridesabike/gatsby-prev-next.git
cd gatsby-prev-next
gatsby build
```

If you serve the built site, everything should be normal. The next part is where the problem happens:

```
mv test-post content/blog/test-post # add a new post
gatsby build
gatsby serve
```

### Expected result

The build should use up-to-date data in regards to "previous" and "next" links.

### Actual result

If you open the new built site, the new post ("Test Post") should be present. The previous post ("New Beginnings") does _not_ link to it. Clearing the cache fixes the problem:

```
gatsby clean
gatsby build
gatsby serve
```

The site should build as expected.

But now, if you remove the `content/blog/test-post` directory, and run `gatsby build`, "Test Post" won't appear on the index page but the "New Beginnings" post will still link to it (and the "Test Post" page will still exist in the build.)

### Additional information

I played around a bit trying to figure out how to bust the stale data, but with no luck. One thing I noticed is that the `createPages` function uses this logic to generate the `previous` and `next` data:

```js
const previous = index === posts.length - 1 ? null : posts[index + 1].node
const next = index === 0 ? null : posts[index - 1].node
```

I tried to update it to use a GraphQL query instead:

```diff
{
  allMarkdownRemark(sort: {fields: [frontmatter___date], order: DESC}, limit: 1000) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
        }
      }
+      previous {
+        fields {
+          slug
+        }
+        frontmatter {
+          title
+        }
+      }
+      next {
+        fields {
+          slug
+        }
+        frontmatter {
+          title
+        }
+      }
    }
  }
}
```

This had no effect. The stale cache was still used.

If it's not feasible to make the caching "smart" enough for this scenario, it would be also good if `createPages` had the ability to manually use or override the cache, as well as delete cached pages after their source data has been deleted.

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41 
    gatsby-image: ^2.4.15 => 2.4.15 
    gatsby-plugin-feed: ^2.5.11 => 2.5.11 
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13 
    gatsby-plugin-manifest: ^2.4.22 => 2.4.22 
    gatsby-plugin-offline: ^3.2.23 => 3.2.23 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.26 => 2.6.26 
    gatsby-plugin-typography: ^2.5.10 => 2.5.10 
    gatsby-remark-copy-linked-files: ^2.3.12 => 2.3.12 
    gatsby-remark-images: ^3.3.25 => 3.3.25 
    gatsby-remark-prismjs: ^3.5.10 => 3.5.10 
    gatsby-remark-responsive-iframe: ^2.4.12 => 2.4.12 
    gatsby-remark-smartypants: ^2.3.10 => 2.3.10 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-remark: ^2.8.28 => 2.8.28 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12 
  npmGlobalPackages:
    gatsby-cli: 2.12.66
```

### LINKED ISSUE #28281: Cache is not invalidated when programatically build pages and the data is changed
## Description

I am using Netlify CMS with markdown files and generating pages from certain collections. When the data for an entry in the collection changes the page is not updated with new data after the build. The site is deployed in Netlify and a caching plugin is used to persist cache between builds for faster builds.

### Steps to reproduce

Use Netlify CMS with markdown files and build pages in gatsby-node using a certain collection.

### Expected result

Page data should be updated with the changes.

### Actual result

The page is displaying old data.

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Languages:
    Python: 3.8.5 - /Users/macintoshhd/.pyenv/shims/python
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 72.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.27.1 => 2.27.1 
    gatsby-image: ^2.3.1 => 2.6.0 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^2.3.3 => 2.7.0 
    gatsby-plugin-netlify: ^2.6.0 => 2.6.0 
    gatsby-plugin-netlify-cms: ^4.5.0 => 4.5.0 
    gatsby-plugin-offline: ^3.1.2 => 3.5.0 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.5.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.3 
    gatsby-plugin-sass: ^2.2.1 => 2.6.0 
    gatsby-plugin-sharp: ^2.5.3 => 2.9.0 
    gatsby-plugin-sitemap: ^2.3.2 => 2.7.0 
    gatsby-remark-images: ^3.2.2 => 3.6.0 
    gatsby-source-filesystem: ^2.2.2 => 2.6.1 
    gatsby-transformer-remark: ^2.7.1 => 2.11.0 
    gatsby-transformer-sharp: ^2.4.3 => 2.7.0

### PR DESCRIPTION
**Pull request by pieh**
## Description

Approach in https://github.com/gatsbyjs/gatsby/pull/28351 turned out to be unfeasble - we do need entire page object actually to preserve backward compatiblity for `DELETE_PAGE` action.

To handle potential OOM issues when persisting state, I expanded state sharding during persistance from just `nodes` to both `nodes` and now persisted `pages`. Right now it's copied & pasted sharding done for nodes - I could have DRY it (I still can if reviewers will request it :) ), but didn't think DRYing it is worth adding mental overhead for added abstractions - thoughts?

This PR build on work already done by @redabacha (in https://github.com/gatsbyjs/gatsby/pull/28316) borrowing test change (unskip) already done (in https://github.com/gatsbyjs/gatsby/pull/28351).

TODO:
 - [x] garbage collect stateful pages during bootstrap ([see comment](https://github.com/gatsbyjs/gatsby/pull/28590#issuecomment-748583901))

## Related Issues

fixes #28281
fixes #26520
[ch19791]

### CODE REVIEW

File: packages/gatsby/src/redux/__tests__/index.js [hunk 1]
```diff
@@ -149,4 +173,178 @@ describe(`redux db`, () => {
...
+        numberOfPages: 50,
+        simulatedPageObjectSize: 10 * 1024 * 1024,
+        expectedNumberOfPageShards: 1,
+      },
+      {
+        numberOfPages: 5,
+        simulatedPageObjectSize: 0.9 * 1024 * 1024 * 1024,
+        expectedNumberOfPageShards: 5,
+      },
+    ]
```
Comment (pieh) [inline packages/gatsby/src/redux/__tests__/index.js:209]: This is to construct scenario matrix - and we check each combination. I didn't go over the board - primary purpose of this is that sharding for pages and nodes is separate and that one doesn't affect the other.

Something to think about is wether we want to add some edge cases here - like when number of nodes or pages is equal 0 - for now implementation for those is that we discard persisted state when either is 0 - it does make a whole lot of sense for nodes as core creates some nodes of their own even if user doesn't use any source plugins. It's a bit different for pages - gatsby doesn't create pages (well except for `gatsby develop` creating `dev-404-page` ...). I am not sure if it's worth handling this case more gracefully? Do we want to optimize for scenarios where there are 0 pages?

File: packages/gatsby/src/redux/persist.ts [hunk 2]
```diff
@@ -67,10 +70,29 @@ export function readFromCache(): ICachedReduxState {
...
   obj.nodes = new Map(nodes)
 
+  // Note: at 1M pages, this will be 1M/chunkSize chunks (ie. 1m/10k=100)
+  const pagesChunks = globSync(
+    reduxChunkedPagesFilePrefix(reduxCacheFolder) + `*`
+  ).map(file => v8.deserialize(readFileSync(file)))
+
+  const pages: Array<[string, IGatsbyPage]> = [].concat(...pagesChunks)
+
+  if (!pagesChunks.length) {
```
Comment (pieh) [inline packages/gatsby/src/redux/persist.ts:80]: Potentially problematic - this will discard state if there are 0 pages - do we want to optimize for those cases? (I don't even know if gatsby actually "works" if there are 0 pages TBH)

Comment (pieh) [reply packages/gatsby/src/redux/persist.ts:80]: When way to go about this is to add `pagesCount` to `redux.rest` part and compare it I guess? Cache will get invalidated anyway after upgrade due to `pagesChunk.length` being 0 so I think cache shape "version" could be handled gracefully

Comment (pvdz) [reply packages/gatsby/src/redux/persist.ts:80]: If there were no pages then it's probably no big deal to bust the cache anyways.

File: packages/gatsby/src/redux/persist.ts [hunk 3]
```diff
@@ -125,6 +151,20 @@ function prepareCacheFolder(
       )
     }
   }
+
+  if (pagesMap) {
```
Comment (pvdz) [inline packages/gatsby/src/redux/persist.ts:155]: Is it possible for `pagesMap` to be nullable here? I understand the property is nullable from the typing pov, but at this point in the code I think the pages ought to exist, right?

File: packages/gatsby/src/redux/persist.ts (hunk 2 above)
Comment (pvdz) [reply packages/gatsby/src/redux/persist.ts:80]: As per off-thread discussion. I think you can merge this PR in a patch without this check, if you wanted to and then add the check in a minor bump later.

File: packages/gatsby/src/redux/persist.ts (hunk 3 above)
Comment (pieh) [reply packages/gatsby/src/redux/persist.ts:155]: I think it should be at least empty Map, yes. To be fair - this is just copied part from https://github.com/gatsbyjs/gatsby/blob/f24a23d5b1f24ab33aec7a8ac882dbbccdf7d01e/packages/gatsby/src/redux/persist.ts#L113-L127 which also use same check. I guess this is mostly to apease TS gods. And nullable part is also copied from how `nodes` is typed in ICachedReduxState and reason I guess is that we set it to `undefined` temporaritly while we save `rest` part of the sate

**Comment by pieh** [comment]
Additional note on this - this needs additional handling done for `createPagesStatefully`: `createPages` does "garbage collect" and it works as-is with this code, but `createPagesStatefully` doesn't have garbage collection so we will never clean those pages up. This means that if user do `gatsby build` -> remove page from `src/pages/` -> `gatsby build`, with this code as-is we will crash with (currently):
```
 ERROR #85913  GRAPHQL

There was a problem reading the file: /Users/misiek/dev/gatsby-starter-blog/src/pages/multiple-exports.js

File: src/pages/multiple-exports.js



  Error: ENOENT: no such file or directory, open '/Users/misiek/dev/gatsby-starter-blog/src/pages/multiple-exports.js'

failed extract queries from components - 0.324s
```

TODO item: garbage collect stateful pages in bootstrap

**Comment by pieh** [comment]
If merged, we should revert https://github.com/gatsbyjs/gatsby/pull/29431

File: packages/gatsby/src/redux/persist.ts [hunk 4]
```diff
@@ -74,7 +89,7 @@ function guessSafeChunkSize(values: Array<[string, IGatsbyNode]>): number {
   }
 
   // Sends a warning once if any of the chunkSizes exceeds approx 500kb limit
-  if (maxSize > 500000) {
+  if (showMaxSizeWarning && maxSize > 500000) {
     report.warn(
       `The size of at least one page context chunk exceeded 500kb, which could lead to degraded performance. Consider putting less data in the page context.`
```
Comment (LekoArts) [inline packages/gatsby/src/redux/persist.ts:94]: We've talked about adding information about _what_ page exceeds this limit, but that's for a follow-up (not in this PR)

**Review by LekoArts — DISMISSED** [review]
LGTM

**Review by LekoArts — APPROVED** [review]
🌮

File: packages/gatsby/src/utils/changed-pages.ts [hunk 5]
```diff
@@ -7,14 +7,16 @@ import { IGatsbyPage } from "../redux/types"
...
+  timeBeforeApisRan: number,
+  shouldRunCreatePagesStatefully: boolean
 ): Array<string> {
   const deletedPages: Array<string> = []
 
   // Delete pages that weren't updated when running createPages.
   currentPages.forEach(page => {
     if (
-      !page.isCreatedByStatefulCreatePages &&
+      (shouldRunCreatePagesStatefully ||
```
Comment (pierluigizagaria) [inline packages/gatsby/src/utils/changed-pages.ts:18]: shouldRunCreatePagesStatefully is always true in "gatsby build" so pages are always deleted if not updated.
