### PR TITLE
fix(gatsby): Do not add field `id` to the query when `id` alias exists

### LINKED ISSUE #20943: Upgrading to Gatsby 2.19.x breaks existing queries
## Description

I'm trying to test out Gatsby Builds which requires updating to the latest Gatsby and Sharp, and it also seem we need a more current gatsby-source-contentful. 

When I do this all our queries have an additional id added to the query, at each level. This breaks the queries, as an example:

> Fields "items" conflict because subfields "id" conflict because they return conflicting types ID! and String. Use different aliases on the fields to fetch both if this was intentional.

Screenshot 2020-01-28 at 11 06 35

However, when I look at the source code for we don't set these IDs in our queries so they are being added automatically and then clashing. 

Screenshot 2020-01-28 at 11 10 54

### Environment

 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 69.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: 2.19.7 => 2.19.7 
    gatsby-image: ^2.2.7 => 2.2.39 
    gatsby-link: ^2.2.22 => 2.2.22 
    gatsby-plugin-eslint: ^2.0.4 => 2.0.5 
    gatsby-plugin-google-tagmanager: ^2.1.3 => 2.1.4 
    gatsby-plugin-i18next: ^1.1.7 => 1.1.7 
    gatsby-plugin-react-helmet: ^3.1.1 => 3.1.2 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.4.0 => 2.4.3 
    gatsby-plugin-styled-components: ^3.1.1 => 3.1.2 
    gatsby-source-contentful: 2.1.82 => 2.1.82 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-remark: ^2.6.3 => 2.6.9 
    gatsby-transformer-sharp: ^2.3.0 => 2.3.13

### PR DESCRIPTION
**Pull request by vladar**
## Description

A follow up for #20849 That PR doesn't take into account aliases. So when alias for `id` exists, we shouldn't auto-add `id` field to the query

## Related Issues

#20943

### CODE REVIEW

File: packages/gatsby/src/query/query-compiler.js [hunk 1]
```diff
@@ -503,7 +503,7 @@ const addExtraFields = (document, schema) => {
         if (node.name.value === `__typename`) {
```
Comment (freiksenet) [inline packages/gatsby/src/query/query-compiler.js]: In theory this can also be aliased.

Comment (vladar) [reply packages/gatsby/src/query/query-compiler.js]: I was pretty sure that field names starting with `__` are not allowed in GraphQL but apparently aliases are. Good catch, will add a check here as well.

**Comment by vladar** [comment]
Published in `gatsby@2.19.9`
