### PR TITLE
fix(gatsby-source-drupal): allow specifying disallowed link types

### LINKED ISSUE #19921: Provide disallowed links setting for the Drupal source plugin
The Drupal source package retrieves data from the JSON:API module. The default module has links that are `self`, `next`, `first`, `prev`, and `last`. The source plugin only cares for and processes `next`. 

However, it's currently a hardcoded logic skip if we encounter `self` and only process `next`. 

`jsonapi_hypermedia` and core improvements allow misc links (like actions to take) and we should add an `allowed_links` option which defaults to `next` and maybe allows others.

For instance, the jsonapi_schema module adds a `describedby` link that provides the document schema and isn't an actual JSON:API document.

_Originally posted by @mglaman in https://github.com/gatsbyjs/gatsby/pull/19879#issuecomment-560534067_

### PR DESCRIPTION
**Pull request by mglaman**
## Description

Adds a `disallowedLinkTypes` setting that allows you to exclude specific link types.

By default it excludes `self` and `describedby`, meeting the current state. This allows skipping link types on `/jsonapi`. This way someone could exclude certain resource links from being crawled, so it actually allows someone to add performance enhancements when building.

I've added a test fixture and test.

## Related Issues

Fixes #19921
Relates  #19867
Relates #19879

### CODE REVIEW

File: packages/gatsby-source-drupal/src/gatsby-node.js [hunk 1]
```diff
@@ -57,7 +61,7 @@ exports.sourceNodes = async (
   })
   const allData = await Promise.all(
     _.map(data.data.links, async (url, type) => {
-      if (type === `self` || type === `describedby`) return
+      if (_.includes(disallowedLinkTypes, type)) return
```
Comment (larowlan) [inline packages/gatsby-source-drupal/src/gatsby-node.js]: for my benefit: why do we use lodash here instead of the native [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) method?
this never runs in a browser right?

Comment (pvdz) [reply packages/gatsby-source-drupal/src/gatsby-node.js]: Thank you, @larowlan :)

Comment (pieh) [reply packages/gatsby-source-drupal/src/gatsby-node.js]: @larowlan lot of this code was originally written when Gatsby supported node version that didn't have `Array.prototype.includes` (node 4), but now we support Node 8+ (And soon when Node 8 reaches end of support life we will be Node 10+). You are free to use `includes` method in newly written code

Comment (mglaman) [reply packages/gatsby-source-drupal/src/gatsby-node.js]: For what it's worth, I reused lodash here since the file did not know what node supported. I can update to use the native method. That way new code slowly move away from lodash

**Comment by larowlan** [comment]
Thanks folks, newcomer here but all that makes sense - thanks for confirming

File: packages/gatsby-source-drupal/src/gatsby-node.js (hunk 1 above)
Comment (mglaman) [reply packages/gatsby-source-drupal/src/gatsby-node.js]: This has been updated to use `Array.prototype.includes`

**Comment by muescha** [comment]
I miss a documentation in the plugin readme

**Comment by mglaman** [comment]
Added information to the README

File: packages/gatsby-source-drupal/README.md [hunk 2]
```diff
@@ -162,6 +162,26 @@ module.exports = {
 }
 ```
 
+## Disallowed Link Types
+
+You can use the `disallowedLinkTypes` option to skip link types found in JSON:API documents. By default it skips the `self` and `describedby` links, which do not provide data that can be sourced. You may override the setting to add additional link types to be skipped.
+
+```javascript
```
Comment (pvdz) [inline packages/gatsby-source-drupal/README.md]: Tip: you can use ` ```js ` here ;) But ` ```javascript ` also works so it's fine either way.

File: packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json [hunk 3]
```diff
@@ -6,6 +6,9 @@
     "node--article": "http://fixture/jsonapi/node/article",
     "taxonomy_term--tags": {
       "href": "http://fixture/jsonapi/taxonomy_term/tags"
+    },
+    "describedby": {
+      "href":"http://fixture/jsonapi/schema"
```
Comment (pvdz) [inline packages/gatsby-source-drupal/src/__tests__/fixtures/jsonapi.json]: Formatting: Missing a space. Did this get Prettiered?

File: packages/gatsby-source-drupal/src/__tests__/fixtures/schema.json [hunk 4]
```diff
@@ -0,0 +1,40 @@
+{
```
Comment (pvdz) [inline packages/gatsby-source-drupal/src/__tests__/fixtures/schema.json]: Tihs file seems to be indented by 4 spaces. The other json file has 2 spaces. I actually don't know what we set json files to but the inconsistency here makes me wonder whether Prettier ran at all :)
