### PR TITLE
fix(www): make DebounceInput value externally controlled

### LINKED ISSUE #9244: [starter-library] Empty search field on "Reset all filters"
## Summary

When clicking the "Reset all Filters" button the starter showcase, the "Search starters" input should be emptied.

### Basic example

* Go to the starter showcase https://www.gatsbyjs.org/starters/
* Enter `lumen` into the "Search filters" input (top right, left of "Submit a Starter")
* Click the "Reset all Filters" button (top left, grey)

Expected result:

* The "Search filters" input should be cleared

Actual result:

* The search query is no longer applied
* But the text remains in the box

### Motivation

Minor UI bug.

### PR DESCRIPTION
**Pull request by Wattenberger**
Fixes #9244 
Makes `DebounceInput`'s value externally controlled, which allows the parent component to change its value - eg. now we're clearing it on reset.

### CODE REVIEW

File: www/src/components/debounce-input.js [hunk 1]
```diff
@@ -5,35 +5,52 @@ import PropTypes from "prop-types"
...
+    inputValue: ``,
   }
 
-  onChangeText = e => {
-    this.setState({ value: e.target.value })
+  componentDidMount() {
+    this.setInputValue(this.props.value)
+  }
+
+  componentDidUpdate(prevProps, prevState, shouldFireRouteUpdate) {
```
Comment (pieh) [inline www/src/components/debounce-input.js]: `prevState` and `shouldFireRouteUpdate` are unused - can we remove them?

Comment (Wattenberger) [reply www/src/components/debounce-input.js]: sure thing!
