### PR TITLE
fix: pretty print syntax error in gatsby api files

### LINKED ISSUE #8147: Make errors more specific
## Description

Compile error not specific enough

### Steps to reproduce

- Put a syntax error inside `gatsby-node.js`
- Execute `gatsby develop`

### Expected result

Syntax error in the `gatsby-node.js` file is pointed out.

### Actual result

Syntax error in the "gatsby config" pointed out, while there's no error in `gatsby-config.js`.
bildschirmfoto 2018-09-14 um 13 41 52

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.5.0/bin/npm
  Browsers:
    Chrome: 69.0.3497.92
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.15 => 2.0.0-rc.15 
    gatsby-image: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-plugin-flow: ^1.0.1-rc.1 => 1.0.1-rc.1 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-plugin-sharp: ^2.0.0-rc.7 => 2.0.0-rc.7 
    gatsby-plugin-styled-components: ^3.0.0-rc.5 => 3.0.0-rc.5 
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.1-rc.6 
    gatsby-transformer-json: ^2.1.1-rc.6 => 2.1.1-rc.6 
    gatsby-transformer-sharp: ^2.1.1-rc.3 => 2.1.1-rc.3 
```

### PR DESCRIPTION
**Pull request by pieh**
Display more useful warning message when there is syntax error in gatsby-x api files. Right now babel parser exceptions are not handled - this add handling at least for syntax errors (not sure about other types that can be expected there, so I just rethrow them)

It changes output from:
```bash
success open and validate gatsby-config — 0.010 s
error Unexpected token, expected ";" (8:4)


  SyntaxError: Unexpected token, expected ";" (8:4)

  - index.js:3939 _class.raise
    [gatsby-i8147]/[@babel]/parser/lib/index.js:3939:15

  - index.js:5248 _class.unexpected
    [gatsby-i8147]/[@babel]/parser/lib/index.js:5248:16

  - index.js:5232 _class.semicolon
    [gatsby-i8147]/[@babel]/parser/lib/index.js:5232:40
[...]
```
to
```bash
success open and validate gatsby-config — 0.010 s
error Syntax error in "/Users/misiek/issues/gatsby-i8147/gatsby-node.js":
Unexpected token, expected ";" (8:4)
  6 |
  7 | // You can delete this file if you're not using it
> 8 | foo bar baz
    |    ^
```

closes #8147

### CODE REVIEW

**Comment by pieh** [comment]
Heh, I didn't realize you commented :) seems like I read your mind about tests

File: packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js [hunk 1]
```diff
@@ -106,6 +111,7 @@ describe(`Resolve module exports`, () => {
   beforeEach(() => {
     resolver = jest.fn(arg => arg)
     require(`fs`).__setMockFiles(MOCK_FILE_INFO)
+    require(`gatsby-cli/lib/reporter`).panic.mockClear()
```
Comment (DSchau) [inline packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js]: May as well require it above?

```js
const reporter = require(`gatsby-cli/lib/reporter`)

beforeEach(() => {
  // other stuff
  reporter.panic.mockClear))
})
```
