### PR TITLE
fix(gatsby-theme-blog): fix functions that are interpolated in css

### LINKED ISSUE #20326: gatsby-starter-blog-theme  printing "Functions that are interpolated in css calls will be stringified" error in console
## Description
Fresh Gatsby instance created  using the command `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme-core` is printing a "Functions that are interpolated in css calls will be stringified" error in browser console

Screen Shot 2019-12-28 at 10 42 29 PM

### Steps to reproduce
1. On a machine with gatsby and yarn installed globally run `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme-core`
2. go into newly created folder and run `gatsby develop`
3. view the site in chrome and open the developer tools -> console. You should be able to see the error

Minimal Reproduction 
https://github.com/seetdev-opensource/interpolated-in-css-calls-error

### Expected result
No "Functions that are interpolated in css calls will be stringified" error in browser console should be printed

### Actual result
"Functions that are interpolated in css calls will be stringified" was printed twice

### Environment
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v13.3.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v13.3.0/bin/npm
  Languages:
    Python: 3.7.3 - /Users/darrens/miniconda3/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 69.0.3
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-theme-blog: ^1.2.7 => 1.2.7
  npmGlobalPackages:
    gatsby-cli: 2.8.22

Additional Information
The error messages appear to be caused by the following block of code around lines 57-62 of packages/gatsby-theme-blog/src/components/header.js

```
const iconCss = [
  css({
    pointerEvents: `none`,
  }),
  { margin: 4 }, // Explicitly leave margin out of theme-ui, this positioning should not change based on theme
]
```
I can make the error go away if I change the same block of in node_modules to the following:
```
const iconCss = [
  {
    pointerEvents: "none",
  },
  { margin: 4 }, // Explicitly leave margin out of theme-ui, this positioning should not change based on theme
]
```

Not sure if it might be related but issue 997 in emotion-js/emotion mention something about not being able to compose themed css in emotion 10. The same issue mentioned that it might be fixed in version 11.

### PR DESCRIPTION
**Pull request by seetdev**
## Description
Remove call to css call from theme-ui for iconCss in header file of gatsby-theme-blog

### Documentation

No updates required

## Related Issues

Fixes #20326

### CODE REVIEW

File: packages/gatsby-theme-blog/src/components/header.js [hunk 1]
```diff
@@ -55,9 +55,9 @@ const Title = ({ children, location }) => {
 }
 
 const iconCss = [
-  css({
+  {
     pointerEvents: `none`,
-  }),
+  },
   { margin: 4 }, // Explicitly leave margin out of theme-ui, this positioning should not change based on theme
```
Comment (blainekasten) [inline packages/gatsby-theme-blog/src/components/header.js]: we could combine these into a single object if you want to make the change

**Comment by seetdev** [comment]
I would make the change

**Comment by seetdev** [comment]
Completed the page to make the configuration a single object
