### PR TITLE
fix(gatsby): don't remount matchPath pages

### LINKED ISSUE #10227: gatsby-plugin-create-client-paths remounts the root on every page transition
## Description

`gatsby-plugin-create-client-paths`  is remounting the root component on every single page transition for the client-only path. This means that if you have auth check in your top-level root, your authentication check will run on each new page instead of just once like it would with a normal React SPA (e.g. one built with create-react-app)

### Expected result

The root component should only mount once.

### Actual result

The root (with routes) is remounted on every single transition.

### PR DESCRIPTION
**Pull request by pieh**
Actual fix is one line change - most of this PR is cypress testing to catch any behaviour changes in future PRs

fixes #10227

### CODE REVIEW

File: packages/gatsby/cache-dir/page-renderer.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ class PageRenderer extends React.Component {
       replacementElement ||
       createElement(this.props.pageResources.component, {
         ...props,
-        key: this.props.location.pathname,
+        key: this.props.pageResources.page.path,
```
Comment (pieh) [inline packages/gatsby/cache-dir/page-renderer.js]: actual fix

File: e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
+describe(`Production build tests`, () => {
+  it(`should remount when navigating to different template`, () => {
+    cy.visit(`/`).waitForAPI(`onRouteUpdate`)
+
+    cy.getTestElement(`page2`)
+      .click()
+      .waitForAPI(`onRouteUpdate`)
+
+    cy.window().then(win => {
+      cy.wrap(win.___PageComponentLifecycleCallsLog).snapshot()
```
Comment (pieh) [inline e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js]: using snapshot testing, which is quite verbose and might be hard to read - it might make sense to not use snapshots here and use more programmatic assertions

Comment (KyleAMathews) [reply e2e-tests/production-runtime/cypress/integration/lifecycle-methods.js]: One way to test this would be count renders in local state and add that to the DOM and assert against it

File: packages/gatsby/cache-dir/page-renderer.js (hunk 1 above)
Comment (KyleAMathews) [reply packages/gatsby/cache-dir/page-renderer.js]: 🎉

File: e2e-tests/production-runtime/src/pages/index.js [hunk 3]
```diff
@@ -2,22 +2,40 @@ import React from 'react'
...
-    <Link to="/page-2/">
-      <span data-testid="page2">Go to page 2</span>
-    </Link>
-    <Link to="/page-3/" data-testid="404">
-      To non-existent page
-    </Link>
-    <Link to="/long-page/" data-testid="long-page">
-      To long page
-    </Link>
+    <pre data-testid="dom-marker">{pageContext.DOMMarker || `index`}</pre>
```
Comment (DSchau) [inline e2e-tests/production-runtime/src/pages/index.js]: This is pretty slick. Nice work!

**Comment by jaredpalmer** [comment]
Thanks for the turnaround on this one! Was pulling my hair out on the undefined.fm's upcoming job board on this. You all rock!
