### PR TITLE
[v2] [gatsby-plugin-offline] Migrate to Workbox from sw-precache

### LINKED ISSUE #7547: [v2] [gatsby-plugin-offline] Service worker install fails on non-Blink browsers
Thanks to @dbrookes for finding this - I used a negative lookbehind in a regex in `gatsby-plugin-offline/gatsby-node.js`, which isn't compatible with Firefox or older versions of Node. I'll submit a PR shortly - just creating this issue to keep track

### PR DESCRIPTION
**Pull request by davidbailey00**
Changelog:

- Packages `sw-precache` and `replace-in-file` are removed, and `workbox-build` is installed
- `getAssetsForChunks` is modified:
  - To return a dense array (i.e. no `undefined` items, which was happening previously)
  - To not return items as `public/...` since this is now handled by `globDirectory`
- Workbox is more strict about invalid globs (it precaches **nothing**, if **any** glob doesn't match a file) so we check if each manifest exists before adding it
- Options updated to match the different names in Workbox
- Changes from #7569 are applied (using `navigateFallbackBlacklist` instead of all-in-one) to prevent needing lookbehinds in regexes (which aren't supported in many JS engines yet)
- `pluginOptions.plugins` is deleted since this is added by default (with the value `[]`), without options specified in the user's `gatsby-config.js` - Workbox throws an error given invalid options so we need to do this
- The function call to generate the service worker is updated, and a then-block added to display information
  - This info was displayed automatically by `sw-precache` but now we need to explicitly output it
- `get-resources-from-html.js` is updated to only return local files (since the SW can't precache external files) and output without the `public` prefix (again, now handled by `globDirectory`)
- The README is updated to match the latest config

Closes #7569, closes #7547.
I've left #7569 open because it might take less time to review than this PR, in case #7547 needs to be fixed urgently - I thought it's quite a nasty bug since SWs fail to install entirely on most non-Chromium-based browsers.

<details>
<summary>Manual tests (dropdown)</summary>

```
configurations:

- 1) online without gatsby-plugin-offline
- 2) online with gatsby-plugin-offline
- 3) offline with gatsby-plugin-offline
- 4) online in develop

- x.1) with a custom 404 page
- x.2) without a custom 404 page


tests:

- 1) 404s are handled correctly from internal links - custom 404 or server 404
  if custom is unavailable, or offline error, but no blank pages

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 2) 404s are handled correctly when entering a URL directly - as above

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 3) back button works properly after 404 (navigates to the expected page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 4) pages which fail to load display a native offline error (no blank pages)

  requires: [3.1, 3.2]
  passed:   [3.1, 3.2]

- 5) the service worker remains installed after a 404/offline error

  requires: [3.1, 3.2]
  passed:   [3.1, 3.2]

- 6) Netlify CMS /admin/ loads or displays an offline error (no 404/blank page)

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]

- 7) going to a page by entering the URL directly works

  requires: [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2]
  passed:   [1.1, 1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.1]
```

Note: I've only retested configurations 2.x and 3.x since #7355, since gatsby-plugin-offline doesn't affect configurations 1 and 4.
</details>

### CODE REVIEW

**Comment by davidbailey00** [comment]
cc @kkemple - Kyle said you'd previously tried to update to Workbox, so I was wondering if you could have a look at this and let me know your thoughts? No pressure if you're working on more important stuff at the moment :)

**Comment by davidbailey00** [comment]
I just need to update the "it extracts resources correctly" test, since I've changed the behaviour of `get-resources-from-html.js`. Will edit comment when done

**Comment by davidbailey00** [comment]
Going to find out if this delay is still necessary with Workbox (`packages/gatsby/cache-dir/register-service-worker.js`)

```js
// Post to service worker that install is complete.
// Delay to allow time for the event listener to be added --
// otherwise fetch is called too soon and resources aren't cached.
window.setTimeout(() => {
  apiRunner(`onServiceWorkerInstalled`, {
    serviceWorker: reg,
  })
}, 100)
```

File: packages/gatsby-plugin-offline/src/gatsby-node.js [hunk 1]
```diff
@@ -80,35 +84,35 @@ exports.onPostBuild = (args, pluginOptions) => {
...
+    navigateFallbackBlacklist: [/\?(.+&)?no-cache=1$/],
     cacheId: `gatsby-plugin-offline`,
     // Don't cache-bust JS files and anything in the static directory
     dontCacheBustUrlsMatching: /(.*js$|\/static\/)/,
     runtimeCaching: [
       {
         // Add runtime caching of various page resources.
         urlPattern: /\.(?:png|jpg|jpeg|webp|svg|gif|tiff|js|woff|woff2|json|css)$/,
-        handler: `fastest`,
+        handler: `staleWhileRevalidate`,
```
Comment (KyleAMathews) [inline packages/gatsby-plugin-offline/src/gatsby-node.js]: In the future, we can be smarter here e.g. our js/css files + anything in the static folder never needs to be revalidated.

File: packages/gatsby-plugin-offline/src/get-resources-from-html.js [hunk 2]
```diff
@@ -37,15 +37,12 @@ module.exports = htmlPath => {
...
       $elem.attr(`src`) || $elem.attr(`href`) || $elem.attr(`data-href`)
-    const blackListRegex = /\.xml$/
 
-    if (!blackListRegex.test(url)) {
-      let path = url
-      if (url.substr(0, 4) !== `http`) {
-        path = `public${url}`
-      }
+    // Don't cache XML files, or external resources (beginning with // or http)
+    const blackListRegex = /(\.xml$|^\/\/|^http)/
```
[the remark this answers is not in the document]
Comment (davidbailey00) [reply packages/gatsby-plugin-offline/src/get-resources-from-html.js]: I think we can runtime-cache secure external files, but we can't precache them - IIRC I was getting errors without ignoring these with Workbox, and definitely with sw-precache.

File: packages/gatsby-plugin-offline/src/gatsby-node.js (hunk 1 above)
Comment (davidbailey00) [reply packages/gatsby-plugin-offline/src/gatsby-node.js]: Maybe we could just add `.*\.css` to the `dontCacheBustUrlsMatching` regex? (Also I just noticed there should be a `\.` before `js` in that regex to prevent edge cases)

Comment (KyleAMathews) [reply packages/gatsby-plugin-offline/src/gatsby-node.js]: Yeah that'd be good.

But we could also do a cache only option for those. Though perhaps doesn't matter as the browser cache should take care of the requests I believe.

File: packages/gatsby-plugin-offline/src/get-resources-from-html.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (davidbailey00) [reply packages/gatsby-plugin-offline/src/get-resources-from-html.js]: Actually on second thoughts I was only testing with localhost (http) so I think my last comment was wrong; I'll add this back in another PR
