### PR TITLE
fix(gatsby): support union types for one-to-one ___NODE relations

### LINKED ISSUE #10090: Single reference fields that accept multiple content types don't work in GraphQL
## Description

Revisiting: https://github.com/gatsbyjs/gatsby/issues/3535

As stated in the previous issue (closed), single reference fields that accept multiple content types cause GraphQL to error out: "Expected value of type \"ContentfulPage\" but got: [object Object]."

The workaround is to create a multiple reference field, but this shouldn't be a permanent fix.

### Steps to reproduce

Write a query for a content type with a single reference field which accepts multiple types.

GraphQL errors out.

### Expected result

The field should support fragments for each content type.

### Actual result

GraphQL errors out: "Expected value of type \"ContentfulPage\" but got: [object Object]."

### PR DESCRIPTION
**Pull request by vladar**
## Description

This PR should make the processing of `___NODE` convenience fields consistent for `one-to-one` and `one-to-many` relations (currently `one-to-many` works as expected while `one-to-one` doesn't). 

Take this example with `one-to-one` relation:
```
createNode({
  internal: { type: `MyType` },
  related___NODE: `FooTypeNode1`,
})
createNode({
  internal: { type: `MyType` },
  related___NODE: `BarTypeNode1`,
})
```

The expected inference result is a union type:
```
type MyType {
  related: FooBar
}

union FooBar = Foo | Bar
```

The actual result is a first registered object type:
```
type MyType {
  related: Foo
}
```

The same example for `one-to-many` relation produces an expected result:
```
createNode({
  internal: { type: `MyType` },
  related___NODE: [`FooTypeNode1`],
})
createNode({
  internal: { type: `MyType` },
  related___NODE: [`BarTypeNode1`],
})
```

Results in:
```
type MyType {
  related: [FooBar]
}

union FooBar = Foo | Bar
```

## Related Issues
Fixes #10090

### CODE REVIEW

File: packages/gatsby/src/schema/infer/inference-metadata.js [hunk 1]
```diff
@@ -115,7 +119,7 @@ const getType = (value, key) => {
 }
 
 const updateValueDescriptor = (
-  { nodeId, key, value, operation = `add` /*: add | del*/, descriptor = {} },
```
Comment (pvdz) [inline packages/gatsby/src/schema/infer/inference-metadata.js]: Fwiw, the colon in `/*: add | del */` was a workaround for Flow which would support it as if it weren't a comment. This way you could add types to a js document without having to worry about post processing / scrubbing types. Best of both worlds.

So the colon here (I think I've added it myself) is not a typo...

File: packages/gatsby/src/schema/infer/inference-metadata.js [hunk 2]
```diff
@@ -216,15 +220,20 @@ const _updateValueDescriptor = (
       })
       break
     }
-    case `listOfUnion`: {
+    case `relatedNode`:
+    case `relatedNodeList`: {
       const { nodes = {} } = typeInfo
```
Comment (pvdz) [inline packages/gatsby/src/schema/infer/inference-metadata.js]: Wouldn't this process be faster with a `Map`? Seems like it's doing pseudo arbitrary property setting and getting. And presumably the number of nodes can grow at scale?

File: packages/gatsby/src/schema/infer/inference-metadata.js [hunk 3]
```diff
@@ -216,15 +220,20 @@ const _updateValueDescriptor = (
...
-      value.forEach(nodeId => {
+      const listOfNodeIds = Array.isArray(value) ? value : [value]
+      listOfNodeIds.forEach(nodeId => {
         nodes[nodeId] = (nodes[nodeId] || 0) + delta
```
Comment (pvdz) [inline packages/gatsby/src/schema/infer/inference-metadata.js]: Is there value to setting this after `dirty === true`? Otherwise we can use a `some` for this loop so it can short circuit the loop on the first dirty.

(I kind of doubt it since this seems to be a lot of work for just tracking dirty, but who knows)

File: packages/gatsby/src/schema/infer/inference-metadata.js (hunk 1 above)
Comment (vladar) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: Yeah but our eslint config complains about this syntax for me (in Webstorm)

Comment (pvdz) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: Oh hm, my webstorm did not. Alright well nevermind then :)

File: packages/gatsby/src/schema/infer/inference-metadata.js (hunk 2 above)
Comment (vladar) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: You tell me %) Any idea how much faster it will be? I used objects because they are easier to debug, also keys are always strings here, and insertion order doesn't matter.

Comment (pvdz) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: Kind of depends on the size. If each `nodes` object is limited to, say, five keys. Then it all doesn't matter much. If the size scales with the size of the site (whether it be queries, pages, or images), then we should just run this against such a site and check. But in that case I predict a map will be faster.

The advantage of a map is that the engine will optimize hashing, expecting an arbitrary set of keys. For regular objects it will continuously try ot optimize, and fail to do so, which is expensive. Additionally, gathering all keys of a map is cheaper versus doing that on an arbitrary object.

There's a little overhead (not sure if that's still true today, actually) to using Maps vs objects so for very small objects I'm not sweating it too much.

File: packages/gatsby/src/schema/infer/inference-metadata.js (hunk 3 above)
Comment (vladar) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: We use this information for incremental inference. Dirty tracking is orthogonal to type inference - it just helps us detect when structural changes occur but we still need to track all entries of all nodes.

File: packages/gatsby/src/schema/infer/inference-metadata.js (hunk 2 above)
Comment (pvdz) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: I suspect it will make a difference for govbook so lemme check that.

I think this step is separate from this PR so I don't see this PR blocked on it.

File: packages/gatsby/src/schema/infer/inference-metadata.js (hunk 1 above)
Comment (pvdz) [reply packages/gatsby/src/schema/infer/inference-metadata.js]: Randomly looking at a TS wip I realized the error is that the strings should have been quoted :p

I just don't have the flow package installed or enabled for my webstorm so I'm not getting the complaints, I guess.
