### PR TITLE
Persist search pane on plugin lib

### LINKED ISSUE #9084: Plugin detail page reloads / experience is not smooth
## Description

_Reported by [`@rchrdnsh` on Twitter](https://twitter.com/rchrdnsh/status/1050978923863887872):_
> I scroll down the plugin list and click on a plugin, the whole page reloads, including the plugin list, rather then just the plugin info, and the plugin list starts over from the beginning, rather then maintaining it's current list position, which is maddening, to say the least.

### Steps to reproduce

Scroll down the plugin list and select a plugin.

### Expected result

The plugin list maintains its position, and the plugin detail shows without reloading the whole page.

### Actual result

The plugin list resets, and the page reloads to show the plugin detail page.

### PR DESCRIPTION
**Pull request by amberleyromo**
Fixes #9084. Incorporate layout plugin for smoother browsing on plugin lib.

kapture 2018-12-20 at 16 19 09

### CODE REVIEW

**Comment by amberleyromo** [comment]
bump @gatsbyjs/website

File: www/src/layouts/index.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+export default props => {
+  if (props.pageContext.layout === `plugins`) {
+    return (
+      <PluginLibraryWrapper location={props.location}>
+        {props.children}
+      </PluginLibraryWrapper>
+    )
+  }
+  return <div>{props.children}</div>
```
Comment (LekoArts) [inline www/src/layouts/index.js]: Is a `<React.Fragment>` also possible here? I'm always for minimizing the `div`-ception

Comment (amberleyromo) [reply www/src/layouts/index.js]: Yeah, good idea.
