### PR TITLE
fix(gatsby): take into account possible invalid values in getValueAt

### LINKED ISSUE #26531: Missing onError handler for invocation 'rebuildSchemaWithSitePage'
## Description

```
Missing onError handler for invocation 'rebuildSchemaWithSitePage', error was 'TypeError: Cannot read property 'contents' of null'. Stacktrace was 'TypeError: Cannot read property 'contents' of null
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:10:20)
    at map (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:20:59)
    at Array.map (<anonymous>)
    at getArray (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:19:6)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:12:36)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:13:50)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:13:50)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:13:50)
    at getValueAt (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:4:10)
    at getFirstValueAt (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:14:15)
    at find (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:84:13)
    at Array.find (<anonymous>)
    at getFilePath (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:83:41)
    at isFile (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:91:20)
    at getSimpleFieldConfig (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:315:11)
    at getFieldConfig (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:174:19)'
```

### Steps to reproduce

Minimal reproduction: https://github.com/SimonSiefke/gatsby-bug

1. Run `gatsby develop`
2. Error occurs

### Expected result

No Error

### Actual result

Error

### Environment

```

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.3.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47 
  npmGlobalPackages:
    gatsby-cli: 2.12.87

```

### PR DESCRIPTION
**Pull request by vladar**
## Description

Fixes an edge case with file type inference (the bug is actually in a related utility function). 

## Related Issues

Fixes #26531

### CODE REVIEW

File: packages/gatsby/src/utils/get-value-at.ts [hunk 1]
```diff
@@ -5,6 +5,7 @@ export function getValueAt(obj: object, selector: string | string[]): any {
 }
 
 function get(obj: object, selectors: string[]): any {
+  if (obj === null) return undefined
```
Comment (pieh) [inline packages/gatsby/src/utils/get-value-at.ts:8]: Is targeting just `null` safe? Can `obj` ever be `undefined` for example? Just wondering if checking if loosening the condition to check `obj` is falsy would be correct here (and potentially safer). (I have not much context around inference anymore, so I will defer to your judgement)

Comment (vladar) [reply packages/gatsby/src/utils/get-value-at.ts:8]: Good question. We have it typed as `object` in function arguments. That's why I am only checking for `null` (as it is technically an object too).

If it can be something else - then our typings are incorrect. Let me check real quick.

Comment (vladar) [reply packages/gatsby/src/utils/get-value-at.ts:8]: Yeah, typings are incorrect indeed. I'll try to fix those too.

Comment (vladar) [reply packages/gatsby/src/utils/get-value-at.ts]: Fixed those, please re-check. And thanks for noticing this!

**Review by pieh — APPROVED** [review]
Looking good, thanks!

**Comment by pieh** [comment]
Published in `gatsby@2.24.49`
