### PR TITLE
fix(gatsby-dev-cli): increase debounce threshold in CI environments

### LINKED ISSUE #8381: [ci]: gatsby-dev-cli in CircleCI sometimes copies over 0 files
## Description

CircleCI sometimes copies over 0 files from the packages/ directory, which causes the e2e builds to (usually) fail 

### Steps to reproduce

Check out [this CircleCI build](https://circleci.com/gh/gatsbyjs/gatsby/1686?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). The failures are intermittent, sometimes files copy over, sometimes they don't 🤷‍♂️ Really weird error.

### Expected result

gatsby-dev-cli should deterministically copy over all the contents of packages/ with the --copy-all flag.

### Actual result

It didn't.

### Environment

N/A

### PR DESCRIPTION
**Pull request by DSchau**
I think this _might_ fix #8381.

I think the process was exiting too quickly in the CI environment, therefore the task was stopped before all the files could copy over.

Also note I tested the issue (not the fix) by `ssh`ing to the CircleCI container, and running the following commands

```bash
gatsby-dev --scan-once
```

it would occasionally copy the expected amount of files, and then sometimes 0, leading me to believe this fix may be the trick 🤞

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Huh weird. Who wrote that code 😅 

Can't we do a `Promise.all` on the copying or something to more directly know when the copying is done?

**Comment by DSchau** [comment]
@KyleAMathews I was refactoring it to go that way. I'll continue that here 😄

File: packages/gatsby-dev-cli/src/watch.js [hunk 1]
```diff
@@ -8,21 +8,23 @@ let numCopied = 0
 const debouncedQuit = _.debounce(() => {
```
Comment (KyleAMathews) [inline packages/gatsby-dev-cli/src/watch.js]: Do we still need to debounce?

Comment (DSchau) [reply packages/gatsby-dev-cli/src/watch.js]: I think so. I think the watcher gets triggered pretty often, and so the debounce is necessary so that we don't quit too soon.

That said, that's more of a guess than a firm guarantee 🤷‍♂️

Comment (KyleAMathews) [reply packages/gatsby-dev-cli/src/watch.js]: Oh I see... yeah, on `scan-once` we should only listen to the `ready` event then as that's only called once Chokidar has scanned all files https://github.com/paulmillr/chokidar

Comment (DSchau) [reply packages/gatsby-dev-cli/src/watch.js]: Neat :) I'll fix this in a sec. Deep in caching stuff 😅

File: packages/gatsby-dev-cli/src/watch.js [hunk 2]
```diff
@@ -5,10 +5,10 @@ const syspath = require(`path`)
 
 let numCopied = 0
 
-const debouncedQuit = _.debounce(() => {
+const quit = () => {
```
Comment (DSchau) [inline packages/gatsby-dev-cli/src/watch.js]: No need for `debounce` anymore. We _know_ it's done when `.on('ready')` fires.

File: packages/gatsby-dev-cli/src/watch.js [hunk 3]
```diff
@@ -27,53 +27,57 @@ const copyPath = (oldPath, newPath, quiet) =>
...
-  packages.forEach(p => {
-    const prefix = syspath.join(root, `/packages/`, p)
+  const ignored = [
+    /[/\\]node_modules[/\\]/i,
+    /\.git/i,
+    /\.DS_Store/,
+  ].concat(
+    packages.map(p => new RegExp(`${p}[\\/\\\\]src[\\/\\\\]`, `i`))
+  )
+  const watchers = packages.map(p => syspath.join(root, `/packages/`, p))
```
Comment (DSchau) [inline packages/gatsby-dev-cli/src/watch.js]: Set up an array of packages to watch, rather than iterating with a .forEach (which is kinda janky, and `.on('ready')` will fire for _every_ package.

File: packages/gatsby-dev-cli/src/watch.js [hunk 4]
```diff
@@ -27,53 +27,57 @@ const copyPath = (oldPath, newPath, quiet) =>
...
-      })
-      .on(`all`, (event, path) => {
-        if (event === `change` || event === `add`) {
-          // Copy it over local version.
+  chokidar.watch(watchers, {
+    ignored: [(path, stats) => _.some(ignored, reg => reg.test(path))],
+  })
+    .on(`all`, (event, path) => {
+      if (event === `change` || event === `add`) {
+        const name = syspath.basename(syspath.dirname(path.split(`packages/`).pop()))
```
Comment (DSchau) [inline packages/gatsby-dev-cli/src/watch.js]: A little janky, but we need to infer the name from the full watched file path.

**Comment by DSchau** [comment]
e2e tests are failing on `/bin/sh: 1: gatsby: Permission denied`, which is unrelated to this PR. I can merge upstream/master in to try again, one sec.
