### PR TITLE
fix(*): enable separate config for node_modules transpilation

### LINKED ISSUE #15183: Deploying  [build] to Netlify stuck
## Description
I'm new to Gatsby and Netlify. Haven't really changed anything in configuration. My deploy stop at some point and it's not moving forward. It can take ages. There is no cancel message after 15 minutes. I cannot see any error message. 
My local build is ok. 
Its working good after **'gatsby build & gatsby serve'**

### Steps to reproduce

commit to repository ( https://github.com/finewitch/clinicalspace ) then deploy from netlify website

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
 System:
    OS: macOS Sierra 10.12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.11.0 => 2.11.0
    gatsby-image: ^2.2.3 => 2.2.3
    gatsby-plugin-netlify: ^2.1.0 => 2.1.0
    gatsby-plugin-netlify-cms: ^3.0.18 => 3.0.18
    gatsby-plugin-purgecss: ^3.1.1 => 3.1.1
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sass: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.0
    gatsby-remark-images: ^3.1.2 => 3.1.2
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2
    gatsby-source-filesystem: ^2.1.1 => 2.1.1
    gatsby-transformer-remark: ^2.5.0 => 2.5.0
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0
```

NETLIFY:

```
4:42:48 PM: Build ready to start
4:42:50 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
4:42:50 PM: build-image tag: v3.3.2
4:42:50 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
4:42:51 PM: Fetching cached dependencies
4:42:51 PM: Starting to download cache of 255.0KB
4:42:51 PM: Finished downloading cache in 71.883466ms
4:42:51 PM: Starting to extract cache
4:42:51 PM: Failed to fetch cache, continuing with build
4:42:51 PM: Starting to prepare the repo for build
4:42:51 PM: No cached dependencies found. Cloning fresh repo
4:42:51 PM: git clone https://github.com/finewitch/clinicalspace
4:42:53 PM: Preparing Git Reference refs/heads/master
4:42:53 PM: Found netlify.toml. Overriding site configuration
4:42:53 PM: Different functions path detected, going to use the one specified in the toml file: 'lambda' versus '' in the site
4:42:53 PM: Creating functions prep folder
4:42:53 PM: Starting build script
4:42:53 PM: Installing dependencies
4:42:55 PM: Downloading and installing node v10.16.0...
4:42:55 PM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
4:42:56 PM: 
##
4:42:56 PM:        3.0%
4:42:56 PM: 
############################################
4:42:56 PM:                             62.4%
4:42:56 PM: 
##########################################################
4:42:56 PM: #########       94.2%
4:42:56 PM: 
######################################
4:42:56 PM: ################################## 100.0%
4:42:56 PM: Computing checksum with sha256sum
4:42:56 PM: Checksums matched!
4:42:59 PM: Now using node v10.16.0 (npm v6.9.0)
4:42:59 PM: Attempting ruby version 2.6.2, read from environment
4:43:01 PM: Using ruby version 2.6.2
4:43:02 PM: Using PHP version 5.6
4:43:02 PM: Started restoring cached node modules
4:43:02 PM: Finished restoring cached node modules
4:43:02 PM: Started restoring cached yarn cache
4:43:02 PM: Finished restoring cached yarn cache
4:43:02 PM: Installing yarn at version 1.9.4
4:43:02 PM: Installing Yarn!
4:43:02 PM: > Downloading tarball...
4:43:02 PM: [1/2]: https://yarnpkg.com/downloads/1.9.4/yarn-v1.9
4:43:02 PM: .4.tar.gz --> /tmp/yarn.tar.gz.CZ9eVJn7Sw
4:43:02 PM:   % Tot
4:43:02 PM: al    % Received % Xferd  Average Speed   Time    Time
4:43:02 PM:     Time  Current
4:43:02 PM:                      Dload  Upload   Total   Spent    Left  Speed
4:43:02 PM: 
  0     0    0     0    0     0      0
4:43:02 PM: 0 --:--:-- --:--:-- --:--:-
4:43:02 PM: -     0
4:43:02 PM: 
100    91  100    91    0     0    27
4:43:02 PM: 9      0 --:--:-- --:--:-- --:--:--   280
4:43:03 PM: 
100   608    0   608    0     0    722      0 --:--:-- --:--:-- --:--:--   722
4:43:03 PM: 
  0     0    0     0    0     0      0      0
4:43:03 PM: --:--:-- --:--:-- --:--:--     0
4:43:03 PM: 
100  915k  100  915k    0     0   721k      0  0
4:43:03 PM: :00:01  0:00:01 --:--:-- 3304k
4:43:03 PM: [2/2]: https://yarnpkg.com/downloads/1.
4:43:03 PM: 9.4/yarn-v1.9.4.tar.gz.asc --> /tmp/yarn.tar.gz.CZ9eVJn7Sw.asc
4:43:03 PM: 
100    95  100    95    0     0   2297      0 --:--:-- --:--:-- --:
4:43:03 PM: --:--  2297
4:43:03 PM: 
100   612    0   612    0     0   4267      0 --:--:-- --:--:-- --:--:--  4267
4:43:03 PM: 
100   832  100   832    0     0   4604      0 --:-
4:43:03 PM: -:-- --:--:-- --:--:--  4604
4:43:03 PM: > Verifying integrity...
4:43:03 PM: gpg: Signature made Fri 03 Aug 2018 07:53:36 PM UTC using RSA key ID B6FF4DE3
4:43:03 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
4:43:03 PM: gpg: Note: This key has expired!
4:43:03 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907
4:43:03 PM:   BBB7 1646 B01B 86E5 0310
4:43:03 PM:      Subkey fingerprint: E219 30C4 D0A4 AA46 1858  1F7A E074 D16E B6FF 4DE3
4:43:03 PM: > GPG signature looks good
4:43:03 PM: > Extracting to ~/.yarn...
4:43:03 PM: > Adding to $PATH...
4:43:03 PM: > We've added the following to your /opt/buildhome/.profile
4:43:03 PM: > If this isn't the profile of your current shell then please add the following to your correct profile:
4:43:03 PM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
4:43:03 PM: 
4:43:04 PM: > Successfully installed Yarn 1.9.4! Please open another terminal where the `yarn` command will now be available.
4:43:05 PM: Installing NPM modules using Yarn version 1.9.4
4:43:06 PM: yarn install v1.9.4
4:43:06 PM: [1/4] Resolving packages...
4:43:07 PM: warning gatsby > @hapi/joi@14.5.0: This version is no longer maintained
4:43:09 PM: [2/4] Fetching packages...
4:43:09 PM: (node:1371) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
4:43:36 PM: info fsevents@1.2.7: The platform "linux" is incompatible with this module.
4:43:36 PM: info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
4:43:36 PM: [3/4] Linking dependencies...
4:43:36 PM: warning "gatsby > pnp-webpack-plugin > ts-pnp@1.0.1" has unmet peer dependency "typescript@*".
4:43:36 PM: warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
4:43:36 PM: warning "gatsby-plugin-sass > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
4:43:36 PM: warning " > lodash-webpack-plugin@0.11.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
4:43:36 PM: warning "netlify-cms > netlify-cms-media-library-cloudinary@1.3.2" has unmet peer dependency "netlify-cms-lib-util@^2.1.3-beta.0".
4:43:36 PM: warning "netlify-cms > netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
4:43:36 PM: warning "netlify-cms > netlify-cms-app > netlify-cms-widget-markdown > slate-edit-list@0.11.3" has incorrect peer dependency "slate@^0.32.0".
4:43:36 PM: warning "netlify-cms > netlify-cms-app > netlify-cms-widget-markdown > slate-edit-table@0.15.2" has incorrect peer dependency "slate@^0.33.3".
4:43:36 PM: warning "netlify-cms > netlify-cms-app > netlify-cms-widget-markdown > slate-edit-table@0.15.2" has unmet peer dependency "slate-schema-violations@^0.1.7".
4:43:51 PM: [4/4] Building fresh packages...
4:44:02 PM: success Saved lockfile.
4:44:02 PM: Done in 56.45s.
4:44:02 PM: NPM modules installed using Yarn
4:44:03 PM: Installing Hugo 0.27
4:44:05 PM: Hugo Static Site Generator v0.27 linux/amd64 BuildDate: 2019-06-27T13:44:04Z
4:44:05 PM: Started restoring cached go cache
4:44:05 PM: Finished restoring cached go cache
4:44:05 PM: unset GOOS;
4:44:05 PM: unset GOARCH;
4:44:05 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
4:44:05 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
4:44:05 PM: go version >&2;
4:44:05 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
4:44:05 PM: go version go1.12 linux/amd64
4:44:05 PM: Installing missing commands
4:44:05 PM: Verify run directory
4:44:05 PM: Executing user command: npm run build
4:44:05 PM: > gatsby-starter-netlify-cms@1.1.3 build /opt/build/repo
4:44:05 PM: > run-p build:**
4:44:06 PM: > gatsby-starter-netlify-cms@1.1.3 build:lambda /opt/build/repo
4:44:06 PM: > netlify-lambda build src/lambda
4:44:06 PM: > gatsby-starter-netlify-cms@1.1.3 build:app /opt/build/repo
4:44:06 PM: > npm run clean && gatsby build
4:44:06 PM: > gatsby-starter-netlify-cms@1.1.3 clean /opt/build/repo
4:44:06 PM: > rimraf .cache public
4:44:07 PM: netlify-lambda: Building functions
4:44:08 PM: Hash: 2ef9d4d7556e24942a63
4:44:08 PM: Version: webpack 4.29.6
4:44:08 PM: Time: 1380ms
4:44:08 PM: Built at: 06/27/2019 1:44:08 PM
4:44:08 PM:    Asset      Size  Chunks             Chunk Names
4:44:08 PM: hello.js  1.19 KiB       0  [emitted]  hello
4:44:08 PM: Entrypoint hello = hello.js
4:44:08 PM: [0] ./hello.js 777 bytes {0} [built]
4:44:10 PM: success open and validate gatsby-configs — 0.025
4:44:11 PM: success load plugins — 1.121
4:44:11 PM: success onPreInit — 0.006
4:44:11 PM: success delete html and css files from previous builds — 0.006
4:44:11 PM: success initialize cache — 0.011
4:44:11 PM: success copy gatsby files — 0.038
4:44:11 PM: success onPreBootstrap — 0.017
4:44:11 PM: success source and transform nodes — 0.336
4:44:11 PM: success building schema — 0.399
4:44:12 PM: success createPages — 0.059
4:44:12 PM: success createPagesStatefully — 0.062
4:44:12 PM: success onPreExtractQueries — 0.003
4:44:12 PM: success update schema — 0.040
4:44:12 PM: success extract queries from components — 0.315
4:44:12 PM: success write out requires — 0.005
4:44:12 PM: success write out redirect data — 0.001
4:44:12 PM: success onPostBootstrap — 0.000
4:44:12 PM: info bootstrap finished - 5.656 s
4:44:12 PM: success run static queries — 0.298 — 2/2 6.73 queries/second
4:44:13 PM: success Generating image thumbnails — 5/5 - 0.550 s
4:44:21 PM: [BABEL] Note: The code generator has deoptimised the styling of /opt/build/repo/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
4:44:22 PM: gatsby-plugin-purgecss: Only processing  /opt/build/repo/src/components/styles.scss
4:44:39 PM: success Building production JavaScript and CSS bundles — 26.910
4:44:39 PM: success Rewriting compilation hashes — 0.001
4:44:41 PM: success run page queries — 1.204 — 20/20 16.62 queries/second
4:44:43 PM: success Generating image thumbnails — 38/38 - 2.976 s
4:44:43 PM: 
4:44:43 PM: gatsby-plugin-purgecss:
4:44:43 PM:  Previous CSS Size: 17.40 KB
4:44:43 PM:  New CSS Size: 16.51 KB (-5.13%)
4:44:43 PM:  Removed ~0.89 KB of CSS
4:44:43 PM: 
4:44:45 PM: success Building static HTML for pages — 2.446 — 20/20 54.28 pages/second
4:44:45 PM: info Done building in 38.687 sec
4:44:45 PM: Function Dir: /opt/build/repo/lambda
4:44:45 PM: TempDir: /tmp/zisi-711121018
4:44:46 PM: Prepping functions with zip-it-and-ship-it 0.3.1
4:44:50 PM: [ { path: '/tmp/zisi-711121018/hello.zip', runtime: 'js' },
4:44:50 PM:   { path: '/tmp/zisi-711121018/p5.zip', runtime: 'js' },
4:44:50 PM:   { path: '/tmp/zisi-711121018/p5.min.zip', runtime: 'js' } ]
4:44:51 PM: Prepping functions complete
4:44:51 PM: Caching artifacts
4:44:51 PM: Started saving node modules
4:44:51 PM: Finished saving node modules
4:44:51 PM: Started saving yarn cache
4:44:51 PM: Finished saving yarn cache
4:44:51 PM: Started saving pip cache
4:44:51 PM: Finished saving pip cache
4:44:51 PM: Started saving emacs cask dependencies
4:44:51 PM: Finished saving emacs cask dependencies
4:44:51 PM: Started saving maven dependencies
4:44:51 PM: Finished saving maven dependencies
4:44:51 PM: Started saving boot dependencies
4:44:51 PM: Finished saving boot dependencies
4:44:51 PM: Started saving go dependencies
4:44:51 PM: Finished saving go dependencies
4:44:54 PM: Build script success
4:44:54 PM: Starting to deploy site from 'public'
4:44:54 PM: Creating deploy tree 
4:44:54 PM: 0 new files to upload
4:44:54 PM: 3 new functions to upload
4:45:31 PM: Finished processing build request in 2m40.604997147s
```

PACKAGE.JSON
```json
{
  "name": "gatsby-starter-netlify-cms",
  "description": "Example Gatsby, and Netlify CMS project",
  "version": "1.1.3",
  "author": "Austin Green",
  "dependencies": {
    "bulma": "^0.7.5",
    "gatsby": "^2.11.0",
    "gatsby-image": "^2.2.3",
    "gatsby-plugin-netlify": "^2.1.0",
    "gatsby-plugin-netlify-cms": "^3.0.18",
    "gatsby-plugin-purgecss": "^3.1.1",
    "gatsby-plugin-react-helmet": "^3.1.0",
    "gatsby-plugin-sass": "^2.1.0",
    "gatsby-plugin-sharp": "^2.2.1",
    "gatsby-remark-copy-linked-files": "^2.1.0",
    "gatsby-remark-images": "^3.1.2",
    "gatsby-remark-relative-images": "^0.2.1",
    "gatsby-source-filesystem": "^2.1.1",
    "gatsby-transformer-remark": "^2.5.0",
    "gatsby-transformer-sharp": "^2.2.0",
    "lodash": "^4.17.5",
    "lodash-webpack-plugin": "^0.11.4",
    "netlify-cms": "^2.9.4",
    "node-sass": "^4.12.0",
    "parcel-bundler": "^1.12.3",
    "prop-types": "^15.6.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "uuid": "^3.2.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "clean": "rimraf .cache public",
    "start:app": "npm run develop",
    "start:lambda": "netlify-lambda serve src/lambda",
    "start": "run-p start:**",
    "build:app": "npm run clean && gatsby build",
    "build:lambda": "netlify-lambda build src/lambda",
    "build": "run-p build:**",
    "develop": "npm run clean && gatsby develop",
    "serve": "gatsby serve",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"{gatsby-*.js,src/**/*.js}\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "http-proxy-middleware": "^0.19.1",
    "netlify-lambda": "^1.4.13",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.18.2",
    "rimraf": "^2.6.2"
  }
}
```

and netlify.toml
```toml
[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
```

Screen Shot 2019-06-27 at 17 00 30

am I missing sth ?

### LINKED ISSUE #15190: Gatsby@2.11.0 Build failure (JavaScript heap out of memory)
## Description

Gatsby 2.11 breaks site build. I'm guessing it's the new functionality around building node_modules as well as the site (#14111). 

i was updating dependencies on [master](https://github.com/moonmeister/moonmeister.net/tree/master) when build started breaking. I've updated to 2.10.5 on an [update branch](https://github.com/moonmeister/moonmeister.net/tree/updatedeps) with no troubles but as soon as I move Gatsby to 2.11 the build breaks. 

### Steps to reproduce

1. Clone master or update branches from https://github.com/moonmeister/moonmeister.net
2. update gatsby dep to gatsby@2.11.0 
3. run build => see breakage.

### Expected result

build should be successful.

### Actual result
```
[BABEL] Note: The code generator has deoptimised the styling of /home/ajmoon/code/moonmeister/moonmeister.net/node_modules/netlify-cms-app/dist/netlify-cms-app.js as it
⠦ Building production JavaScript and CSS bundles

<--- Last few GCs --->

[19712:0x2dbca30]    45370 ms: Scavenge 1338.2 (1423.9) -> 1337.3 (1423.9) MB, 2.9 / 0.0 ms  (average mu = 0.163, current mu = 0.102) allocation failure 
[19712:0x2dbca30]    45374 ms: Scavenge 1338.4 (1423.9) -> 1337.5 (1423.9) MB, 2.8 / 0.0 ms  (average mu = 0.163, current mu = 0.102) allocation failure 
[19712:0x2dbca30]    45378 ms: Scavenge 1338.6 (1423.9) -> 1337.7 (1424.4) MB, 2.6 / 0.0 ms  (average mu = 0.163, current mu = 0.102) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x34eb54adbe1d]
    1: StubFrame [pc: 0x34eb54a875c2]
Security context: 0x2caa7a21e6e9 <JSObject>
    2: /* anonymous */(aka /* anonymous */) [0x23804dd52ac9] [/home/ajmoon/code/moonmeister/moonmeister.net/node_modules/@babel/core/lib/transformation/file/merge-map.js:~155] [pc=0x34eb5534b963](this=0x01389b5022b1 <null>,m=0x1c2e6adbae29 <Object map = 0x11c6eb590b11>)
    3: arguments adaptor frame: 3->1
    4: forEach...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 2: 0x8dc55c  [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 5: 0xec7bf2  [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
 9: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
10: 0xea07f4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
11: 0x114018e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/home/ajmoon/.nvm/versions/node/v10.15.3/bin/node]
12: 0x34eb54adbe1d 
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
  npmPackages:
    gatsby: 2.11.0 => 2.11.0 
    gatsby-image: ^2.0.34 => 2.2.3 
    gatsby-plugin-eslint: ^2.0.4 => 2.0.5 
    gatsby-plugin-manifest: ^2.0.24 => 2.2.0 
    gatsby-plugin-netlify: ^2.0.13 => 2.1.0 
    gatsby-plugin-netlify-cms: ^4.1.0 => 4.1.0 
    gatsby-plugin-offline: ^2.0.25 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.0.10 => 3.1.0 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0 
    gatsby-plugin-sass: ^2.0.11 => 2.1.0 
    gatsby-plugin-sharp: ^2.0.30 => 2.2.1 
    gatsby-plugin-sitemap: ^2.0.11 => 2.2.0 
    gatsby-remark-images: ^3.0.10 => 3.1.2 
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2 
    gatsby-source-filesystem: ^2.0.27 => 2.1.1 
    gatsby-transformer-remark: ^2.3.8 => 2.5.0 
    gatsby-transformer-sharp: ^2.1.17 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.7.2
    gatsby-dev-cli: 2.5.0
```

### LINKED ISSUE #15207: Javscript bundles are full of duplicate packages
## Description

I have noticed some fairly large Javascript files on my site. Most of them in the range 100-400KB. Examination with `source-map-explorer` showed that most of the size of them consists of duplicate libraries. I'm aware that Gatsby bundles packages that are used multiple times in the `commons-*.js `file. But for some reason, my build does not seem to make one. I know I've seen it be created before, but now my build only contains `component-*.js` files. I cannot place how or when the `commons-*.js` is created and would like some guidance in understanding when it happens? And will the bundling occur the same during `develop` and `build` commands?

### Steps to reproduce

Unfortunately I have not identified how to reproduce

### Expected result

There should always be a bundled `commons-*.js` file created

### Actual result

`commons-*.js` bundle is not always created, even when the build will greatly benefit from it

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.11.0 => 2.11.0
    gatsby-background-image: ^0.7.3 => 0.7.3
    gatsby-image: ^2.2.3 => 2.2.3
    gatsby-plugin-advanced-sitemap: ^1.1.1 => 1.1.1
    gatsby-plugin-google-gtag: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0
    gatsby-plugin-netlify: ^2.1.0 => 2.1.0
    gatsby-plugin-nprogress: ^2.1.0 => 2.1.0
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.0
    gatsby-source-filesystem: ^2.1.1 => 2.1.1
    gatsby-source-graphql: ^2.1.0 => 2.1.0
    gatsby-source-wordpress: ^3.1.2 => 3.1.2
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0
  npmGlobalPackages:
    gatsby-cli: 2.6.2
```

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
Implements point 1 & 2 from #15213. Mostly stolen from create-react-app.

We revert the changes done by https://github.com/gatsbyjs/gatsby/pull/14111 in the js loader and create a new loader called `dependencies` to do specific work on node_modules.

Inside the `dependencies` loader, we set every optimisation to false. We also disable sourcemap generation as this might fail on big files (ex #15190).

It's not really much faster.

| site | before node transpilation | after node transpilation | This PR |
|-----------------|---------------------------|--------------------------|---------|
| gatsbyjs.org | 88.907s | 110s | 91.936s |
| moonmeister.net | 55.749s | 82s | 57.216s |
| default-starter | 9.444s | 13s | 13s |

More PRs will follow to speedup webpack build time. Sadly most of these PRs will only work on next build.

## Related Issues
Fixes #15190
Fixes #15183
Fixes #15207

### CODE REVIEW

File: packages/gatsby/src/utils/webpack-utils.js [hunk 1]
```diff
@@ -309,6 +305,36 @@ module.exports = async ({
     rules.js = js
   }
 
+  /**
+   * Node_modules JavaScript loader via babel
```
Comment (wardpeet) [inline packages/gatsby/src/utils/webpack-utils.js]: add (exlucde core-js & babel-runtime to speedup babel transpilation)
