### PR TITLE
fix(optimize-hook-destructuring): handle skipped items

### LINKED ISSUE #23413: `optimize-hook-destructuring` throws when skipping some items
## Updated description:

Skipping some items when destructuring arrays returned by hooks result in following errors:
```
Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got null
```

To reproduce (and test) - add following test to https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/src/__tests__/optimize-hook-destructuring.js:
```
  it(`should handle skipped items`, () => {
    const input = trim`
      import { useState } from 'react';
      const [, setCount] = useState(0);
    `

    expect(() => babel(input)).not.toThrow()
    expect(babel(input)).toMatchInlineSnapshot()
  })
```

Right now it will fail and the `.not.toThrow()` assertion

Ref: https://github.com/gatsbyjs/gatsby/pull/22619

---
## Original description:

I receive this random error while running build remotely (pipeline): 

failed Building production JavaScript and CSS bundles - 101.981s
error Generating JavaScript bundles failed
`Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got null`

Building locally it's all okay though.
I think this may be related to [request being deprecated](https://github.com/request/request/issues/3142)

I'm using old versions though:    

    "gatsby": "^2.1.18",
    "gatsby-background-image": "^0.2.72",
    "gatsby-cli": "^2.8.27",
    "gatsby-image": "^2.0.30",
    "gatsby-plugin-create-client-paths": "^2.1.17",
    "gatsby-plugin-material-ui": "1.2.5",
    "gatsby-plugin-page-creator": "^2.0.10",
    "gatsby-plugin-react-helmet": "^3.0.7",
    "gatsby-plugin-sharp": "^2.0.28",
    "gatsby-plugin-styled-components": "^3.0.6",
    "gatsby-plugin-web-font-loader": "^1.0.4",
    "gatsby-plugin-webpack-bundle-analyzer": "^1.0.4",
    "gatsby-source-filesystem": "^2.0.26",
    "gatsby-transformer-sharp": "^2.1.17",

How shall I change this to put it all back together? Thank you!

### PR DESCRIPTION
**Pull request by pieh**
## Description

This fixes hook destructuring for cases when some elements are skipped - for example:
```
const [, setCount] = useState(0);
```

## Related Issues

Fixes #23413

### CODE REVIEW

File: packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts [hunk 1]
```diff
@@ -52,8 +52,14 @@ export default function ({
       if (!(onlyBuiltIns ? isBuiltInHook : isHook).test(hookName)) return
 
       path.parent.id = t.objectPattern(
-        path.parent.id.elements.map((element, i) =>
-          t.objectProperty(t.numericLiteral(i), element!)
+        path.parent.id.elements.reduce(
```
Comment (pieh) [inline packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts:55]: not very happy with using `.reduce` here ... but TS was not very happy with 
`.map().filter(Boolean)` trick or other similar ones (it still would still complain that I try to use array of `BabelTypes.ObjectProperty | null` as param of `t.objectPattern`

Comment (vladar) [reply packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts:55]: I think something like this could work:

```
.filter(<T>(n: T | null | undefined): n is T => Boolean(n))
```

But not sure if it is easier to read :)

Comment (pieh) [reply packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts:55]: Happy to try it, but honestly I'm not sure if it's actually more readable - especially for someone that isn't very "fluent" in typescript (so for example me :P)

Comment (pieh) [reply packages/babel-preset-gatsby/src/optimize-hook-destructuring.ts:55]: I'll skip this doing any changes - it doesn't seem that impactful one way or the other, and we can better spend our time :)
